### ISSUE TITLE
Wrong magic number. Aborting.. Error in readbina()

### ISSUE THREAD

**Issue by vkp3** [privefl/bigsnpr#101]
Hi,

I'm opening a new issue (as referenced in #94) that occurs when reading in a .bed file. In particular, after compiling the latest version (1.4.0) on macOS, and reading in a plink binary file set like so:

```
bedfile <-
     '...maf0.1.geno0.mind0.05.hwe10e-4.ld_pruned.bed'
tmpfile <- tempfile()
rds <- snp_readBed(bedfile, backingfile = tmpfile)

test <- snp_attach(paste0(tmpfile, ".rds"))
```

I encounter the following error when executing snp_readBed():
```
> rds <- snp_readBed(bedfile, backingfile = tmpfile)
Error in readbina(bedfile, bigGeno, getCode()) : 
  Wrong magic number. Aborting..
```

The .bed file does not have missing values, and the .bim and .fam are present in the same directory.

Looking at the source for snp_readBed(), it seems to me this line is where it fails:
```
function (bedfile, backingfile = sub_bed(bedfile)) 
{
    backingfile <- path.expand(backingfile)
    assert_noexist(paste0(backingfile, ".bk"))
    bimfile <- sub_bed(bedfile, ".bim")
    famfile <- sub_bed(bedfile, ".fam")
    sapply(c(bedfile, bimfile, famfile), assert_exist)
    fam <- bigreadr::fread2(famfile, col.names = NAMES.FAM)
    bim <- bigreadr::fread2(bimfile, col.names = NAMES.MAP)
    bigGeno <- FBM.code256(nrow = nrow(fam), ncol = nrow(bim), 
        code = CODE_012, backingfile = backingfile, init = NULL, 
        create_bk = TRUE)
    **reach.eof <- readbina(bedfile, bigGeno, getCode())**
    if (!reach.eof) 
        warning("EOF of bedfile has not been reached.")
    snp.list <- structure(list(genotypes = bigGeno, fam = fam, 
        map = bim), class = "bigSNP")
    rds <- sub_bk(bigGeno$backingfile, ".rds")
    saveRDS(snp.list, rds)
    rds
}
<bytecode: 0x7fe5b251b200>
<environment: namespace:bigsnpr>
```

I should note that the example.bed file as described in the tutorial does work, so I'm assuming there's something incorrect with the way my plink file set is constructed. Could you please let me know what diagnostics I should be looking at to make sure the plink file set is appropriate to be read in by snp_readBed()?

**Comment by privefl** [comment]
The binary PLINK file normally starts with 3 bytes, "the magic number".
I'm checking this number in the C++ code: https://github.com/privefl/bigsnpr/blob/master/src/read-plink.cpp#L33-L34.
You can try running `
readBin(bedfile, what = 1L, n = 3, size = 1)`. You should get `108 27 1`.

**Comment by vkp3** [comment]
The issue resolved itself. I'm not sure exactly why, unfortunately, but I suspect reloading the bigsnpr package has worked. And running `readBin(bedfile, what = 1L, n = 3, size = 1)` does indeed give me `108 27 1`. For reference, I was on macOS Catalina 10.15.5 and using R version 4.0.1.
