### ISSUE TITLE
Error in snp_ldsc2 in "(max(abs(..."

### ISSUE THREAD

**Issue by Sabor117** [privefl/bigsnpr#102]
Hi Florian,

I've been getting a repeated error with a number of different summary stats when trying to run LDpred-auto, at the stage where you are instructed to use snp_ldsc2(). It is not completely persistent with all of my data, so something funny is going on with some of the stats.

The error in question is:
```
Error in if (max(abs(pred - pred0)) < 1e-06) break : 
  missing value where TRUE/FALSE needed
```

I worked through the snp_ldsc2() and the internal snp_ldsc function and am coming across where I believe the problem lies.

Just prior to that command, there is the line:
```
pred <- step1_int + wlm_no_int(x, yp, w = WEIGHTS(pred0,  w_ld))$pred
```
And in the analyses going into error, this line produces a vector of repeated "NaN" (presumably one for each SNP in the analysis, as it is the same number).

Going into this: pred0, x, yp and w_ld are all vectors of numbers (although both w_ld and x have values of "Inf" within the vector). While step1_int = 1. The WEIGHTS() function also produces a similar vector of numbers.

As far as I can make out the issue here is in the wlm_no_int() function which is producing the vector of NaNs.

Could you please advise on how to fix this?

**Comment by Sabor117** [comment]
Just a small update: I'm working under the assumption that it is the presence of the "Inf" values that is causing the problem. I have currently traced this back to Inf values within
```
ld_score = Matrix::colSums(corr0^2)
```
And from that it seems like there may be Inf within corr0.

**Comment by privefl** [comment]
Thanks for making the effort to identify the issue.

You can try which(abs(corr0) > 1, arr.ind = TRUE) to see which values are weird.

**Comment by Sabor117** [comment]
```
which(abs(corr0) > 1, arr.ind = TRUE)```

Does not seem to work.

**Comment by privefl** [comment]
You might need to load package Matrix first.

I think snp_cor handles if you have a few missing values.

**Comment by Sabor117** [comment]
Ahhh, okay, loading Matrix helped. Provided me with a list of values, but I'm not sure exactly what to do with this information.

**Comment by Sabor117** [comment]
Ah, okay, apologies. Took me a few minutes to understand what I was looking at. I think I have found the issue then, it seems just one SNP might be responsible for the issues.

Do you think it makes the most sense to simply remove this?

**Comment by Sabor117** [comment]
Okay, another update:

I am beginning to suspect all of this is being caused by another issue with our own data as opposed to the bigsnpr/bigstatsr packages...

To investigate the SNP causing the issue I do want to confirm that when I cross-reference snp_info and G, I should be using _NUM_ID_ and _not_ _NUM_ID_.ss?

**Comment by privefl** [comment]
NUM_ID is for the bigSNP data, and SS for the sumstats.

If it is only one SNP causing the issue, you can remove it. If you can understand why it would be useful for me and other having the same issue.

**Comment by Sabor117** [comment]
I'm still investigating further so cannot say for certain, but there IS a very obvious difference in the way that particular SNP is displayed within G.

When I view another random SNP within G, the output on the terminal looks like this:
```
   [1] 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 2.00 0.00 0.00 2.00
  [15] 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00
  [29] 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00 0.00 2.00
```
For this problem SNP, the values are:
```
   [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  [38] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
```
While these seem to still be numeric values, I do not think it is coincidental that the SNP causing the problems also does not have decimals for the genotypes.

**Comment by privefl** [comment]
Might be the case for genotyped SNPs. Don't worry about that. I'm more worried about that it is all 2s. What is the frequency?

**Comment by Sabor117** [comment]
Allele frequency is 0.01612378

**Comment by privefl** [comment]
Any update on this?

**Comment by williambrandler** [comment]
I hit the same issue @Sabor117 using simulated data. 

How did you identify that this SNP was problematic?

And was it just this one SNP, and what exactly caused the issue with how the genotypes for that SNP were represented? 

I am testing ldpred2 on simulated data and so expect all the SNPs to be represented the same way (although the allele frequencies are different)

**Comment by Sabor117** [comment]
Apologies @williambrandler, it has now been so long that I have forgotten what exactly the problem I was having here was.

I will say that I somewhat suspect the output I was getting may have been a case of user error on my part (as I did make a few mistakes while learning how to use LDpred), so it is worth double checking that all the inputs are correct.
