### ISSUE TITLE
Is the new version of bigsnpr on CRAN? 

### ISSUE THREAD

**Issue by charlisech** [privefl/bigsnpr#103]
Hi Florian,

Will the newer version of the bigsnpr be available on CRAN? Installing bigsnpr using the code `remotes::install_github("privefl/bigsnpr") ` on MAC 10.15.3 with R 3.6.2 is giving me errors on clang: `clang: error: unsupported option '-fopenmp'`.

**Comment by privefl** [comment]
Have you looked at #94?

**Comment by privefl** [comment]
It is on CRAN now but I think you need to wait for them to build the Mac binaries.
Cf. https://cran.r-project.org/web/packages/bigsnpr/index.html.
