### ISSUE TITLE
Using snp_cor() on a subset of a BGEN-based bigSNP object?

### ISSUE THREAD

**Issue by cqgd** [privefl/bigsnpr#105]
Hi Florian,

Hope you're well.

Thanks for developing LDpred2, I've been following your tutorial at https://privefl.github.io/bigsnpr/articles/LDpred2.html.

I've found the step to calculate SNP correlations to take very long:

```
corr0 <- snp_cor(G, ind.col = ind.chr2, ncores = NCORES,
                 infos.pos = POS2[ind.chr2], size = 3 / 1000)
```

Because I'm calculating PRSes for individuals in the UK Biobank, and working with the entire chr22 bgen as an example, I should presumably subset G to a smaller number of individuals. 

It looks like `subset_snp()` [expects](https://privefl.github.io/bigsnpr/reference/snp_subset.html) some individual identifiers for the purpose of subsetting. As far as I can tell, my bigSNP objects from `snp_readBGEN()` do not have these attached: they just have `$genotype` and `$map`. For reference, I called `snp_readBGEN()` without supplying `ind.row`, so as to create an RDS containing chr22 data on all individuals, as per the [docs](https://privefl.github.io/bigsnpr/reference/snp_readBGEN.html).

Adding a fake `$fam` (perhaps there is a better BGEN equivalent that mirrors a sample file) to my bigSNP object works for the purpose of subsetting with `subset_snp()`, but ultimately causes `snp_cor()` to crash when working on the subset:
```
> system.time(corr0 <- snp_cor(G_LD_subset, ind.col = ind.chr3, ncores = 4, infos.pos = POS2[ind.chr2], size = 3 / 1000)) 
Error in seq_len(nrow(x)) : argument must be coercible to non-negative integer
```
Is there any way I can run `snp_cor()` for a subset of my bigSNP object, when that object comes from a complete BGEN read with `snp_readBGEN()`? 

You might find it clearer to see [my current code](https://gist.github.com/cqgd/85d7cf3471ceedc1f1b822d589d0fb54).

Any advice on using your software would be much appreciated.

Thanks in advance,

Chris

**Comment by privefl** [comment]
To subset individuals, you have 3 ways:
- either provide a subset of indices (corresponding to the .sample file) in `snp_readBGEN()` (cf. https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-genotypes.R)
- subset the bigSNP object using `snp_subset()` (I believe you get an .rds file and should use `snp_attach()` on it)
- use the `ind.row` parameter in `snp_cor()`, which I would recommend if the subsetting is just for computing the correlation matrix

PS1: we do not recommend to use all variants.
PS2: something is wrong with your matching (perhaps not the same build for positions); the latest version should appropriately give you an error about this.

**Comment by cqgd** [comment]
Hi Florian, 

Thanks for your reply. 

You may have noticed I have already tried both `snp_subset()` ([on line 104](https://gist.github.com/cqgd/85d7cf3471ceedc1f1b822d589d0fb54#file-ldpred2_for_bgen-r-L104)) and supplying `ind.row` to `snp_cor()` ([on line 99](https://gist.github.com/cqgd/85d7cf3471ceedc1f1b822d589d0fb54#file-ldpred2_for_bgen-r-L99)). Neither works in the absence of my bigSNP object's `$fam`, as described above. 

As I require multiple overlapping subsets of individuals from the UKB BGEN, subsetting that one multiple times with `snp_readBGEN()` (creating partially overlapping files on disk, with significant additional runtime for each read_BGEN` call is not ideal. Creating an RDS for the entire BGEN (i.e. not subsetting with `snp_readBGEN()`), but then subsetting after `snp_attach()` seems to be the logical choice for my use case.

Would it be possible to provide a MWE showing how to subset a BGEN after it has been read in with snp_readBGEN? Again, the crux is that it has no `$fam`, which your last two suggestions seem to rely on.

Many thanks for your help.

Chris

**Comment by cqgd** [comment]
P.S.: Regarding your PS1, are you referring to performing QC on the summary stats variants included in the analysis as per [your supplement](https://github.com/privefl/paper-ldpred2/blob/master/paper/paper-ldpred2-supp.pdf)?

**Comment by privefl** [comment]
My PS1 is referring to use only the HapMap3 variants that I talk about in the paper and at the end of the tutorial.

In the code of the paper, I'm using `ind.row` to compute the LD matrices using only 10K individuals from the whole 360K I read from the BGEN files: https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-corr-spmat.R#L19-L23.
There is no problem of not having any `$fam` with that.

**Comment by cqgd** [comment]
Thanks Florian, that's a useful snippet!  If using `ind.row` with `snp_cor()` doesn't rely on `$fam`, I'll give that another shot. Good to know it takes >2hrs on 10K. Will subset to the HapMap3 variants prior to QC and update after.

**Comment by privefl** [comment]
`ind.row` corresponds to the order in `G`.

**Comment by cqgd** [comment]
I see, so that would be `G` as derived from the obj.bigSNP? I have a map from my UKB eid's to their position in the BGENs (from which G is derived), so I know which individuals have passed QC and should be read with `snp_readBGEN`. After providing `ind.row` to `snp_readBGEN`, I suppose my ind.rows indices are reset to just be `1:N`, so whenever I subset any further I need to re-compute which individuals are which based on my UKB eid's. 

Is there any way to attach consistent identifiers to the individuals (like sample names or UKB eids), which don't change when subsetting `G`? That would be very useful, especially if these could then be provided instead of ind.rows.

**Comment by privefl** [comment]
Are you asking for rownames for `G`? I don't plan to implement that.
The ids are in the .sample file. You just need to use function `match()`.
