### ISSUE TITLE
Error in using LDpred2 in heritability values

### ISSUE THREAD

**Issue by PradoVarathan** [privefl/bigsnpr#108]
Hi!
I started using LDPred2 based on the tutorial mentioned, but with a larger dataset. When I tried for the infinitesimal model, it got stuck. So, I tried the other auto and grid seperately and got astronomical values for h2 values.

         p          h2 sparse
1   0.00010  7297946991  FALSE
2   0.00018  7297946991  FALSE
3   0.00032  7297946991  FALSE
4   0.00056  7297946991  FALSE
5   0.00100  7297946991  FALSE
6   0.00180  7297946991  FALSE
7   0.00320  7297946991  FALSE
8   0.00560  7297946991  FALSE
9   0.01000  7297946991  FALSE
10  0.01800  7297946991  FALSE
11  0.03200  7297946991  FALSE
12  0.05600  7297946991  FALSE
13  0.10000  7297946991  FALSE
14  0.18000  7297946991  FALSE
15  0.32000  7297946991  FALSE
16  0.56000  7297946991  FALSE
17  1.00000  7297946991  FALSE
18  0.00010 10425638559  FALSE
19  0.00018 10425638559  FALSE
20  0.00032 10425638559  FALSE

and so on..
I shall attach the whole output with this issue for reference.
Thank you!

[Output.txt](https://github.com/privefl/bigsnpr/files/4888211/Output.txt)

**Comment by privefl** [comment]
This estimates comes from LD score regression.
This is where it is weird:
```
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
        int          h2 
          1 10425638559 
```
Are you loading other packages before?

**Comment by PradoVarathan** [comment]
Hi!
I do not load any other packages prior to running the script.
I see that this h2 is being adapted into all the three steps. As suggested, i have printed the df_beta

 beta beta_se   n_eff
2994463  0.0241  0.0655  0.0494
2994464  0.0147  0.0901 -0.1476
2994465  0.0814  0.0362  0.0170
2994466 -0.9246  0.0338 -0.0250
2994467  0.4060  0.0155  0.0025
2994468  0.4099  0.0153 -0.0003

Thank you 
!

**Comment by privefl** [comment]
`n_eff` looks very weird, don't you think?

**Comment by PradoVarathan** [comment]
Is it fine to not have n_eff values in the input summary statistics since the example does not have either?

**Comment by PradoVarathan** [comment]
> `n_eff` looks very weird, don't you think?

I think it assumed another set of values as n_eff. I shall manually change the n_eff to a standard number in R and try them again!

**Comment by PradoVarathan** [comment]
Hi! my n_eff is pretty large because of the large sample size, to be accurate , it is 57148. Would that be an issue to cause this problem?

**Comment by privefl** [comment]
57148 would be fine but you currently have `0.0494 -0.1476 ...`.

**Comment by PradoVarathan** [comment]
Understood.Thank you!

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
