### ISSUE TITLE
log file empty, no bed file produced

### ISSUE THREAD

**Issue by Bec-D** [privefl/bigsnpr#11]
Hi Florian

I'm having trouble with snp_plinkQC. It runs, but it produces a log file that is empty, and it does not produce the bed file. 

The data is available at (http://dgrp2.gnets.ncsu.edu/data.html) "plink formatted genotype".  My code is pasted below. 
I realise I haven't given you much to go on but do you have a feeling where the issue may be? 
Thanks in advance!

```
library(bigsnpr)
bedfile <- "/home/mist/projects/dgrp2.bed"
print(bedfile)

prefix  <- sub("\\.bed$", "", bedfile)
plink <- download_plink()
print(prefix)
bigsnp <- snp_plinkQC(plink.path = plink,
                      prefix.in = prefix,
                      prefix.out = tempfile(),
                      file.type = "--bfile",
                      maf = 0.05, 
                      geno = 0,   
                      mind = 1,   
                      hwe = 0,    
                      autosome.only = FALSE) 
bigsnp <- snp_readBed(bigsnp)

Loading required package: bigstatsr
[1] "/home/mist/projects/dgrp2.bed"
trying URL 'https://www.cog-genomics.org/static/bin/plink180911/plink_linux_x86_64.zip'
Content type 'application/zip' length 2284660 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

[1] "/home/mist/projects/dgrp2"
[1] "/tmp/RtmpP40ZZj/file627364b519ff.bed"
Error: File '/tmp/RtmpP40ZZj/file627364b519ff.bed' doesn't exist.
```

**Comment by privefl** [comment]
Just a remark, `geno = 0` would mean that you don't allow any missing value in your data.

Second remark, you store the resulting `.bed` from QC in a temporary file.
This file should not be deleted as long as you don't restart your R session.
Do you have the problem when executing all this code at once?
Could you try without specifying `prefix.out`?

**Comment by Bec-D** [comment]
Thanks for your thoughts!

I tried geno = 0.05 and geno = 1, to allow missing values and make sure that wasn't the issue. 
I also removed the prefix.out command. It still didn't work.

When I run the snp_plinkQC code there are no error messages but it runs very quickly! When I run snp_readBed I get the error that the .bed file doesn't exist. But yes, I am running the code all at once (ie R doesn't restart).

Do you think its something to do with plink? It is using PLINK v1.90b6.4 64 bit (7 Aug 2018)

**Comment by privefl** [comment]
Just tested the code with the data you provided. 
It works fine for me, and it is fast because the data is small.

Which OS? Which version of R?  Version of {bigsnpr}?

**Comment by privefl** [comment]
I have R 3.4.4 and the same versions for the 2 packages. 
WEIRD

**Comment by privefl** [comment]
Just tested on Windows with R 3.5.0, and no problem.
Have you tried other computers?

I've no idea what your pb is.

**Comment by Bec-D** [comment]
I've now successfully run it on a mac! It seems to be that the PLINK binaries for Linux seg fault (tried a few versions). So it was nothing to do with bigsnpr! Thanks for all the time you put in to help me!

**Comment by privefl** [comment]
You're welcome
