### ISSUE TITLE
no snp_asGeneticPos()

### ISSUE THREAD

**Issue by jiehuang001** [privefl/bigsnpr#111]
hi, 

I installed bigsnpr library successfully and loaded it in R.

however, when I follow the ldpred2 tutorial, it says snp_asGeneticPos is not available. 

Don't know if I somehow missed some dependency package.

Best regards,
Jie

**Comment by privefl** [comment]
Which version did you install?
`packageVersion("bigsnpr")`

**Comment by jiehuang001** [comment]
Hi, 

I just found it is bigsnpr version 1.3.0.
I am using R 3.6.3. Recently I tried to upgrade to R 4.0, but found it messed with a lot of packages that I have been using. 

I followed the instruction on your website, used remotes::install_github("privefl/bigsnpr") to install. 
How could I upgrade to bigsnpr version 1.4.2 ?

Thanks!

Jie

**Comment by privefl** [comment]
Using `remotes::install_github("privefl/bigsnpr")` you should get version 1.4.5.

**Comment by jiehuang001** [comment]
Before I run this "remotes::install_github" command, I did try to do it through "install.packages()". 
Maybe somehow something was messed up.

How could I completely remove bigsnpr in a clean way, so that I try this remotes::install_github command again?

thanks!

jie

**Comment by privefl** [comment]
Just restart your R session before doing the install.
`install.packages()` should be fine as well (you would get v1.4.3).

**Comment by jiehuang001** [comment]
Ok. i now used install.packages() and now got version 1.4.4.

![捕获](https://user-images.githubusercontent.com/26947455/87555045-80456d00-c6e7-11ea-8c5b-3fd0ecca6a18.JPG)

Don't know why this time it is so quick and easy. I did that a couple of weeks ago, somehow it took a long time and i don't know why i got version 1.3 in the first place ...

best regards,
jie

**Comment by privefl** [comment]
The v1.4.4 was pushed to CRAN only a few days ago.

**Comment by jiehuang001** [comment]
Thanks!

I now got a new error. Please see below.

Best regards,
Jie

![捕获](https://user-images.githubusercontent.com/26947455/87562583-c4893b00-c6f0-11ea-86b3-591c4ad105ef.JPG)
