### ISSUE TITLE
Split snp_fastImpute() for parallel computing

### ISSUE THREAD

**Issue by doggy8088** [privefl/bigsnpr#114]
Is it possible to split `snp_fastImpute()` to multiple machines for parallel computing?

**Comment by privefl** [comment]
For now, the code (https://github.com/privefl/bigsnpr/blob/master/R/impute.R#L137-L159) is just looping over all chromosomes.
You could replace the loop to process the chromosomes on different machines. Or even chunk in the way you want.
You can call the internal function using `bigsnpr:::imputeChr()`.
