### ISSUE TITLE
Warning issue concerning xgboost process in snp_fastImpute()

### ISSUE THREAD

**Issue by domiden** [privefl/bigsnpr#115]
First at all, many thanks for your hard work!

Since I have changed to `R` version 4.0.x, a warning issue concerning the `xgboost` process shows while performing imputation using the `bigsnpr::snp_fastImpute()` function. 

```{r}
WARNING: amalgamation/../src/learner.cc:480: 
Parameters: { verbose } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.
```

- `bigsnpr` version 1.2.3
- `xgboost` version 1.1.1.1
- `R` version 4.0.2

It seems that isn't a big problem, however, it would be nice if you would look into it. If you need any further information, just let me know. Thanks!

**Comment by privefl** [comment]
This should be fixed in the latest version.
