### ISSUE TITLE
ldpred2 questions

### ISSUE THREAD

**Issue by namjoub2** [privefl/bigsnpr#116]
Hi there
I have several issues/questions with ldpred2. since I better understand I continue use ldpred1.

1) first I have a quantitative phenotype in my sumstat (as well as target genotype data) so I am not sure how to follow these lines:
sumstats$n_eff <- 4 / (1 / sumstats$n_case + 1 / sumstats$n_control)
sumstats$n_case <- sumstats$n_control <- NULL
2) my sumstate had about 30 million variants and I am getting memory error at this line:
info_snp <- snp_match(sumstats, map)
3) I downloaded HM3 plink file and separate African and European to be used as "temp"-public reference data. but  I don't see target genotype data in your lines. only "public-data" and "sumstat". does your program validate the results in "target" genotype data?
4) do I need to first separate each chromosome in my sumstat and target genotype data , or I can provide chr number to program
5) also downstream analyses  are not clear for me and how to add all chromosomes again back together and do AUC or R2 for performance in 3 different models. this will be very time consuming and ineffective ...can you provide one example for combining?
thank you

**Comment by privefl** [comment]
1. For quantitative phenotypes, just use the total sample size.

2. Do you still get a memory error with the latest version (>= 1.4.6)?

3. I'm separating the data in training/test for the tutorial.

4. I don't understand the question, please rephrase.

5. This question has already been answered in 3 other issues. And the code from the paper is available.

**Comment by namjoub2** [comment]
thank you. I have version 1.4.4. (if you have updated version I can not find it in install package R, path.
1) can you provide exact code here for quantitative phenotype: ( it will be useful for other s as well)
sumstats$n_eff <- 4 / (1 / sumstats$n_case + 1 / sumstats$n_control)
 sumstats$n_case <- sumstats$n_control <- NULL
4) you wrote that ldpred2 has to do one chromosome at a time. does it mean that the sumstat need to be first separated per chromosome? or there is command line to do --chr1 , --chr 2 etc?

**Comment by privefl** [comment]
1. Just assign `n_eff` to the column representing sample size (often called `N`, or some number from the GWAS paper).

2. Cf. both the code from tutorial and paper.

**Comment by namjoub2** [comment]
thanks...I am also getting this error...I think the first one you wrote that it is fine, since this is quantitative  and I just change the column name sample to n_eff.    
The second error  at the end of line is new and I can not find the NA in column name:

Error in merge.data.table(as.data.table(sumstats4), as.data.table(info_snp),  : 
  x has some duplicated column name(s): NA,NA. Please remove or rename the duplicate(s) and try again.

more detail:



> set.seed(1)
> ind.val <- sample(nrow(G), 200)
> ind.test <- setdiff(rows_along(G), ind.val)
> sumstats$n_eff <- 4 / (1 / sumstats$n_case + 1 / sumstats$n_control)
Error in `$<-.data.frame`(`*tmp*`, n_eff, value = numeric(0)) : 
  replacement has 0 rows, data has 34285070
> sumstats$n_case <- sumstats$n_control <- NULL
> names(sumstats) <- c("chr", "rsid", "pos", "a0", "a1", "beta", "beta_se", "p",> map <- obj.bigSNP$map[-(2:3)]
> names(map) <- c("chr", "pos", "a0", "a1")
> info_snp <- snp_match(sumstats, map)
34,285,070 variants to be matched.
4,863,641 ambiguous SNPs have been removed.
Error in merge.data.table(as.data.table(sumstats4), as.data.table(info_snp),  : 
  x has some duplicated column name(s): NA,NA. Please remove or rename the duplicate(s) and try again.
>

**Comment by privefl** [comment]
Check the (col)names of what you pass as `sumstats`.

**Comment by namjoub2** [comment]
I set up an HM3 reference and remove chr X with lower number of markers. Now I do not get error or memory issue
At Infinitesimal model for chr 1: I am getting this error

> pred_inf <- big_prodVec(G, beta_inf, ind.row = ind.test, ind.col = ind.chr1)
> AUCBoot(pred_inf, y[ind.test])
Error: 'target' should be composed of 0s and 1s.

My H2 was 0.02:

> (ldsc <- snp_ldsc2(corr0, df_beta))
       int         h2 
1.00000000 0.02024136

please note my HM3 plink file do not have phenotype. my sumstat phenotype is also a quantitative phenotype.

**Comment by privefl** [comment]
You don't even try to look at those issues by yourself, and are just waiting passively for me to help you.
Sorry, this is the last answer you'll get from me in the next 2-3 days. I need a break.

For the error, what do you think "'target' should be composed of 0s and 1s." means?
Look at `unique(y[ind.test])`; is it only 0 and 1?

**Comment by namjoub2** [comment]
that is fine.  thank you...I agree with you if i were a programmer...
 the confusion for me is the discovery- validation and test (target) set and i can see that others had the same questions. in my code, we divided the HM3 into two, but none of those indiv has phenotypes. so how we can test an independent  plink binary target file (with binary phenotype), while we are also using HM3 as reference and sumstats as model fitting or validation...

**Comment by bnj50** [comment]
so i see you close this but this is the error:

> POS2 <- snp_asGeneticPos(CHR, POS, dir = "tmp-data", ncores = 3)
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
> ind.chr <- which(info_snp$chr == 1)
> df_beta <- info_snp[ind.chr, c("beta", "beta_se", "n_eff")]
> 
> ind.chr1 <- info_snp$`_NUM_ID_`[ind.chr]
> corr0 <- snp_cor(G, ind.col = ind.chr1, ncores = NCORES,
+                  infos.pos = POS2[ind.chr1], size = 3 / 1000)
> corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))
> (ldsc <- snp_ldsc2(corr0, df_beta))
       int         h2 
1.00000000 0.02024136 
> h2_est <- ldsc[["h2"]]
> beta_inf <- snp_ldpred2_inf(corr, df_beta, h2 = h2_est)
> pred_inf <- big_prodVec(G, beta_inf, ind.row = ind.test, ind.col = ind.chr2)
Error in as.list.environment(parent.frame()) : 
  object 'ind.chr2' not found
> AUCBoot(pred_inf, y[ind.test])
Error in lengths(list(...)) : object 'pred_inf' not found
> unique(y[ind.test])
[1] -10
>

**Comment by bnj50** [comment]
> corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))
> (ldsc <- snp_ldsc2(corr0, df_beta))
       int         h2 
1.00000000 0.02024136 
> h2_est <- ldsc[["h2"]]
> beta_inf <- snp_ldpred2_inf(corr, df_beta, h2 = h2_est)
> pred_inf <- big_prodVec(G, beta_inf, ind.row = ind.test, ind.col = ind.chr1)
> AUCBoot(pred_inf, y[ind.test])
Error: 'target' should be composed of 0s and 1s.
> unique(y[ind.test])
[1] -10
>

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
