### ISSUE TITLE
Question about (de)coupling of methods and file format

### ISSUE THREAD

**Issue by CreRecombinase** [privefl/bigsnpr#119]
Hi this is a really great package.  I was wondering how open you would be to pull requests that decouple the algorithms from the specifics of the storage backend.  As an example, I've found that swapping out the `.rds` file for a [qs file](https://github.com/traversc/qs/) with `altrep` enabled yielded a 30x speedup for `snp_attach`. I wonder if additional performance(/maintainability/reliability) benefit could be gained by swapping out FBM for something like HDF5. HDF5 would be cool because it has libraries in every major programming language.   I haven't studied your C++ in depth; what I have seen makes me think this wouldn't be a huge amount of work. What do you think?

**Comment by privefl** [comment]
I am open to any pull request, but I can't guarantee I will merge them.

I've heard about {qs}, it looks promising. However, the time running `snp_attach()` is very small compared to the time taken doing the analysis afterwards, don't you think?

However, I'm against HDF5. I can't think it could be a better way to store matrix data.

**Comment by CreRecombinase** [comment]
making `snp_attach` as fast as it can be is nice because sometimes I just want to know what samples/what variants are in my file.  If I've run `snp_attach` on the wrong file, the analysis time afterwards is 0.  Even if I do have the right file, the runtime of `snp_attach` increases pretty much linearly with the number of variants, which isn't great if I know I only need a subset of the data (e.g I'm running chunked jobs in parallel jobs on a HPC cluster).
As for HDF5, it's your package so you obviously don't have to justify being opposed to it, but do you think you could say more about why you're against it?  If it's performance, do you think a benchmark might change your mind?

**Comment by privefl** [comment]
Yes, it is about performance. For storing a dense matrix format, I don't think there is more efficient than what I'm currently doing. But a benchmark might be interesting.

I do understand that it could be nice to be a bit faster. But it would also require introducing a breaking change, where people should rewrite their current files. Also introducing a new dependency. All this extra fuss, is it worth it?

**Comment by privefl** [comment]
Also, regarding your comment about chunking and applying to part on HPC cluster, I do that all the time.
What I'm doing is using `snp_attach()` before and then the chunking is done on `G`, which is very lightweight.

**Comment by CreRecombinase** [comment]
What do you think might make a good benchmark?  Rowsums and colsums of a matrix 1,000,000 by 1,000 (i.e something approximately the size of 1000 genomes at the Hapmap 3 SNPs). Rowsums and colsums of a random subset of rows and columns? Something fancier?  I don't think it would require a breaking change, or even added (mandatory) dependencies.  You could simply add `hdf5r` (or `rhdf5`) as a `Suggests` to `DESCRIPTION`, and  HDF5 would be another supported backend.

**Comment by CreRecombinase** [comment]
As for whether the extra fuss is worth it, with HDF5 you would get more or less "for free":
- ability to store multiple datasets/datatypes in one file (you wouldn't need the separate `bk` and `rds` files)
- a format with language bindings for every other major programming language
- a command line tool (`h5ls`) for querying metadata (e.g dimensions etc)
- a composable compression pipeline. There's even a built-in n-bit compression for handling datatypes that take on a small number of values (e.g dosage)
- control over chunking
- ability to create and store references to subsets of the data in the file (or outside the file)
- ability to create virtual datasets that combine datasets from multiple files. You can, for example, store each chromosome (or subset of individuals, or both) in its own file and create a virtual dataset that's a concatenation of all of them.

**Comment by privefl** [comment]
I agree that you mention some cool features (I really like the virtual dataset one), but I'm really not sure you could get all these changes for free. What about e.g. the C++ code?

**Comment by privefl** [comment]
For the benchmarks, I would recommend 10K x 100K (n < p) is closer to what we would get.

**Comment by privefl** [comment]
Closing this for now.
Feel free to reopen when you have more update on this.
