### ISSUE TITLE
big_randomSVD() hangup

### ISSUE THREAD

**Issue by biojiangke** [privefl/bigsnpr#12]
Ran the example here (https://privefl.github.io/bigsnpr/articles/demo.html) successfully and started trying my own data (started slow with 353 samples but only 17 variants in a small interval). Ran the following code:

library(bigsnpr)
library(ggplot2)
setwd("XXX/XXX")
tmpfile <- tempfile()
snp_readBed("test_region.bed", backingfile = tmpfile)
obj.bigSNP <- snp_attach(paste0(tmpfile, ".rds"))
str(obj.bigSNP, max.level = 2, strict.width = "cut")
G <- obj.bigSNP$genotypes
CHR <- obj.bigSNP$map$chromosome
POS <- obj.bigSNP$map$physical.pos
big_counts(G, ind.col = 1:10)

NCORES <- nb_cores()
ind.keep <- snp_clumping(G, infos.chr = CHR, ncores = NCORES)
obj.svd <- big_randomSVD(G, fun.scaling = snp_scaleBinom(), ind.col = ind.keep, ncores = NCORES)

Everything looked fine until the last step. The "big_randomSVD" hung up indefinitely without any error message. Based on the number of samples and variants this shouldn't take very long. Any advices? I could provide the "test_region.bed" data used here.

**Comment by privefl** [comment]
Can you share the data with me (if allowed to) so that I can try to determine what's the problem?

Anyway, if you have at least one dimension of your data that is not to big (say < 5000), 
you could/should use `big_SVD` instead of `big_randomSVD`.

**Comment by biojiangke** [comment]
I think I found out the problem: the input data cannot contain variants with multiple alleles (even they are split into multiple biallelic variant sites using bcftools/plink). If everything is biallelic, both big_SVD and big_randomSVD would work. If there are multi-allelic variant sites present, it would either hand up or throw the "TridiagEigen: eigen decomposition failed" error. This was stemmed from using WGS SNP data, instead of regular SNP chip data which only contain biallelic sites.

**Comment by privefl** [comment]
I'm not sure I understand.
If you have a binary PLINK file, everything should be considered biallelic, right?

Are you sure you don't have any misssing values in your data?

**Comment by biojiangke** [comment]
Plink doesn't like/accept multi-allelic sites. So I used bcftools to split those sites, such as from "20 31022441 AG AGG,A" into two separate sites "20 31022441 AG AGG" and "20 31022441 AG A". The presence of such split multi-allelic sites seems to affect the SVD calculation and cause "Eigen decomposition failed" error.

**Comment by privefl** [comment]
Not sure how you come to this conclusion.
What is the result of `sum(big_counts(G)[4, ])`?
Can you share the data with me?

**Comment by biojiangke** [comment]
Where could I upload the ".bed", ".fam" and ".bim" data? I'll prepare two small plink bed files with and without the multi-allelic sites, respectively.

**Comment by privefl** [comment]
Where you want, you could make a zip and put that on dropbox, google drive, etc.
Make sure you have the rights to do it.

**Comment by privefl** [comment]
Were you able to solve this problem?

**Comment by privefl** [comment]
Close for inactivity.
