### ISSUE TITLE
install bigsnpr package

### ISSUE THREAD

**Issue by jialiwang1211** [privefl/bigsnpr#121]
Hi Florian,

I was trying to install bigsnpr on R version 3.6.3, but got the following error message. It seems to fail installing 'isoband' package. Do you know how to fix it?

Thank you!

* installing *source* package ‘isoband’ ...

** package ‘isoband’ successfully unpacked and MD5 sums checked

** using staged installation

** libs

g++ -std=gnu++11 -I"/modules/EasyBuild/software/R/3.6.1/lib64/R/include" -DNDEBUG  -I"/gpfs/fs1/modules/EasyBuild/software/R/3.6.1/lib64/R/library/testthat/include" -I/usr/local/include  -fpic  -g -O2  -c clip-lines.cpp -o clip-lines.o

In file included from clip-lines.cpp:12:0:

utils.h:28:1: error: expected unqualified-id before ‘[’ token

make: *** [clip-lines.o] Error 1

ERROR: compilation failed for package ‘isoband’

* removing ‘/gpfs/fs1/home/jwang/R/x86_64-pc-linux-gnu-library/3.6/isoband’

Error: Failed to install 'bigsnpr' from GitHub:

  (converted from warning) installation of package ‘isoband’ had non-zero exit status

**Comment by privefl** [comment]
Try `install.packages("isoband")` first.

If it does not work, please open an issue at https://github.com/wilkelab/isoband/issues.

**Comment by privefl** [comment]
Were you able to solve this problem?

**Comment by jialiwang1211** [comment]
We are building a new R on our cluster, because the complier in the older version does not supports the C++11 standard, which is required to install isoband. It might take a few days and I will try to install bigsnpr again on new R version.

**Comment by privefl** [comment]
I see. It is also required by most of my packages anyway.
