### ISSUE TITLE
Error while performing snp_grid_prs()

### ISSUE THREAD

**Issue by glageosa** [privefl/bigsnpr#123]
Hi Florian, 

 Sometimes when I do a snp_grid_PRS(G, all_keep, betas = beta, lpS = lpval, ind.row = ind_train, n_thr_lpS = 50, backingfile = paste0(TMP_PATH, "prs_scores"), ncores = NBCORES) I have this error : 

> Error` in seq.default(from = log(from), to = log(to), length.out = length.out) :
  'to' must be a finite number
 Calls: snp_grid_PRS ... as.list.environment -> seq_log -> seq -> seq.default
 Exécution arrêtée

Do you know from where it may come from ? 

Thanks

**Comment by privefl** [comment]
You probably have missing values in `lpval`.
You'll need to define `grid.lpS.thr` yourself instead of relying on `n_thr_lpS`.
I probably could add `na.rm = TRUE` in my uses of `min()` and `max()` to make the grid.

**Comment by glageosa** [comment]
Oh ok I see, I'll look for missing values, thank you very much ! 

Amazing work with your packages by the way, really helped me a lot !
