### ISSUE TITLE
Error: You can't have missing values in 'X'

### ISSUE THREAD

**Issue by May-Ibrahim** [privefl/bigsnpr#124]
Hi,

I'm getting the following error when I run LDPRED2 on an imputed dataset (not UKB), although I'm running the analysis only on HAPMAP snps followed by cleaning the target data (G) using the following criteria:
- MAF>0.05
- SNPs CallRate>0.995
- rsq>0.6

**pred_inf <- big_prodVec(G, beta_inf, ind.row = ind.test, ind.col = ind.chr)
Error: You can't have missing values in 'X'.**

It looks like the function doesn't accept missing values in G which means that we need to clean by SNPs CallRate=1, but that leaves us with handful of snps!! 

How did you handle this issue when you run it on UKB data? Any suggestion/recommendation?

Many thanks,
Maysson

**Comment by privefl** [comment]
You can either use `snp_fastImputeSimple()` to e.g. impute by the mean,
or use PLINK to compute the scores (I don't remember what it does to handle missing values though).

**Comment by bnj50** [comment]
Hi
i have the same issue. many target plink files will have low degree of missingness and  reimputation of already imputed data is not recommended but any way, can you let us know how to make secondary plink file after reimputation.  i have these codes (can you continue it?)
snp_readBed("tmp-data/AA-hm3-binary.bed")
obj.bigSNP <- snp_attach("tmp-data/AA-hm3-binary.rds")
str(obj.bigSNP, max.level = 2, strict.width = "cut")
G   <- obj.bigSNP$genotypes
CHR <- obj.bigSNP$map$chromosome
POS <- obj.bigSNP$map$physical.pos
y   <- obj.bigSNP$fam$affection - 1
NCORES <- nb_cores()
bigsnp <- snp_attachExtdata("AA-hm3-median-binary.bed")
G <- bigsnp$genotypes
G[, 2]  
G2 <- snp_fastImputeSimple(G)
G2[, 2]
G$copy(code = CODE_IMPUTE_PRED)[, 2]
G$copy(code = c(0, 1, 2, rep(0, 253)))[, 2]

**Comment by privefl** [comment]
Why do you have missing values if your data is already imputed?

Is `G2` not okay? Do you still have missing values?

**Comment by bnj50** [comment]
we are merging many different arrays after individual imputation. that we cause in average about 5% missing rate and i suspect many will have the same issue. 
I am wondering if your bigsnpr program can make a plink binary file from G2...if not, i need to know how to use the G2 in downstream analyses...thank you!

**Comment by privefl** [comment]
I would recommend to use only variants in common between all your datasets.

You can use `snp_writeBed()` for making bed/bim/files out of a bigSNP.

**Comment by bnj50** [comment]
we had more than 95 arrays and so it is is impossible to have zero NA (it may end up to only 1000 markers)... considering that G2 doesnt have any NA, can you please continue the codes above using -->snp_writeBed()?

**Comment by privefl** [comment]
```r
obj.bigSNP$genotypes <- G2
snp_writeBed(obj.bigSNP, ...)
```
Is it what you want?

**Comment by bnj50** [comment]
thanks...i used line 1 and continue and it works. 
for missingness we also filter based on info score. (0.7)

**Comment by May-Ibrahim** [comment]
Thanks, the data is imputed by the Michigan server but there are still missing values!

Now,I'm trying to save it in bed format but It gives an error:

PRS_rds <- bigsnpr:: snp_readBGEN(
    bgenfiles = glue::glue("/bgen_v2/chr{chr}.bgen", chr = 1:22),
    list_snp_id = list_snp_id,
    backingfile = "/PRS_imp",  # name of .bk and .rds files
    bgi_dir = "/step3_bgen_v2/",
    ncores = NCORES
 )

PRS <- snp_attach("./PRS_imp.rds")

bigsnpr::snp_writeBed(PRS,bedfile="./PRS.bed")
**Error in data.table::fwrite(x, file, sep = "\t", quote = FALSE, row.names = FALSE,  :
  is.list(x) is not TRUE**

It is weird because I test it and it is a list 
 > is.list(PRS)
TRUE

PRS object contains two items, and there are missing values in the genotypes (NA)
 $ genotypes
 $ map

Thanks,
Maysson

**Comment by privefl** [comment]
You also need a `$fam`.
You should be able to get this information from e.g. a '.sample' file.
Or create a fake one using `bigsnpr::snp_fake(n, 1)$fam`, when `n` is the number of individuals.

**Comment by May-Ibrahim** [comment]
Thanks, it is working now.

Maysson

**Comment by mkelcb** [comment]
@privefl this issue is still causing problems...
`pred_auto <- big_prodMat( TestGenotype , beta_auto)`
 I get error: Error: You can't have missing values in 'X'.

I tried the suggested solution
`imputed = snp_fastImputeSimple(TestGenotype_hapmap3_matched_QC)`
- for which I get Error: 'Gna' is not of class 'FBM.code256'.

The only thing that worked was this:
```
TestGenotype_noNA = big_copy(TestGenotype, type = "raw")
pred_auto <- big_prodMat( TestGenotype_hapmap3_matched_QC_noNA , beta_auto)
```
- this gave me warnings that it coerced the NAs to 0s, which I guess (???) is the same snp_fastImputeSimple...

Is there a better way of doing this?

**Comment by privefl** [comment]
What is the class of `TestGenotype` if not 'FBM.code256'?

In `snp_fastImputeSimple()`, it is not imputing by 0, but by either mode, mean or randomly. You can use `method = "mean2"`, which is the one I usually prefer.

**Comment by mkelcb** [comment]
Thanks for the quick response @privefl ! It is a "double"  type FBM, here is what I would like to do:
```
testSet= snp_readBed("myTest.bed", tempfile(tmpdir = "myTempDir"))
testData <- snp_attach(testSet)
TestGenotype_hapmap3_matched = testData$genotypes[,SNPsKept_indices] # subset the genotype file to the HapMap3 matched SNPs
TestGenotype = as_FBM(TestGenotype_hapmap3_matched[,!is_bad], type = "double",tempfile(tmpdir = "myTempDir"))
imputed = snp_fastImputeSimple(TestGenotype)
# SNPsKept_indices and is_bad are vectors for including/excluding SNPs that failed QC
```
- what would I need to change above to make this work?

**Comment by privefl** [comment]
You can't use a double FBM with functions from {bigsnpr}.

Instead of using `TestGenotype = as_FBM(TestGenotype_hapmap3_matched[,!is_bad], type = "double",tempfile(tmpdir = "myTempDir"))`, you can either (in order of preference):
  - use `snp_readBed2()` to read the subset `ind.col = which(!is_bad)` that you want to use
  - use this subset in `big_prodMat()` instead
  - use `big_copy()` without specifying the type (will use the same as `TestGenotype_hapmap3_matched`).

**Comment by mkelcb** [comment]
Thanks @privefl. Could you please clarify your suggestions a bit further?

Your first suggestion:
> use snp_readBed2() to read the subset ind.col = which(!is_bad) that you want to use
- this does not reproduce my original results.  I first need to match the testset to the hapmap3 panel, and THEN exclude the bad SNPs. So I cannot just load them with  "**ind.col = which(!is_bad)**", as the "**!is_bad**" will refer to the wrong SNPs. I first need to obtain the matched subset first with "**SNPsKept_indices**", and then apply the "**!is_bad**" exclusion to those.

Your second suggestion:
> use this subset in big_prodMat() instead
- Sorry, did you mean to say something after this?

Your third suggestion:
> use big_copy() without specifying the type (will use the same as TestGenotype_hapmap3_matched).
- do you mean:
`TestGenotype = big_copy(TestGenotype_hapmap3_matched[,!is_bad])`

**Comment by privefl** [comment]
1. You can do the matching without reading the whole genotype matrix, right? Just read the .bim file.

2. No, just use `ind.col = which(!is_bad)` in this function.

3. Same, just use `ind.col = which(!is_bad)` in this function.

**Comment by pjordab** [comment]
Hi Florian!
I am having the same issue exposed here for the function big_prodMat( ).
Error: You can't have missing values in 'X'.
My target data has been filtered with geno --0.02. 
Following your recommendations I'm using snp_fastImputeSimple( ) function.
G <- obj.bigSNP$genotypes
genotype <- snp_fastImputeSimple(G)
obj.bigSNP$genotypes <- genotype
Should I use this new re-imputed genotype file for all the steps (so also for correlation, ld, ldsc and df_beta calculations) or only from big_prodMat ()?
Many thanks!

**Comment by privefl** [comment]
Normally, the LD computation handles missing values.
So, I guess it is useful to impute only to compute the polygenic scores.

**Comment by JNajar** [comment]
Hi!

I have used your script for LDPred2 several times with good results. However, now that i want to create a PRS for diabetes type 2, for some reason i get this warning during the LD calculations: "Warning message: NA or NaN values in the resulting correlation matrix."
I have already removed NAs in a previous step:

# a lot of NAs for hg38 variable 
sumstats <- na.omit(sumstats)

And when i check for NAs i dont find any. 

If i continue with the script i get this: 
> ## We assume the fam order is the same across different chromosomes
> fam.order <- as.data.table(obj.bigSNP$fam)
>
> ## Rename fam order
> setnames(fam.order,
+         c("family.ID", "sample.ID"),
+         c("FID", "IID"))
>
> # 6. Perform LD score regression
>   df_beta <- info_snp[,c("beta", "beta_se", "n_eff", "_NUM_ID_")]
>
>   ldsc <- snp_ldsc(   ld,
+                       length(ld),
+                       chi2 = (df_beta$beta / df_beta$beta_se)^2,
+                       sample_size = df_beta$n_eff,
+                       blocks = NULL)
Error in if (max(abs(pred - pred0)) < 1e-06) break :
  missing value where TRUE/FALSE needed
>
>   h2_est <- ldsc[["h2"]]
Error: object 'ldsc' not found
Do you know what might be the problem? Or how I can troubleshoot?

All the best,
Jenna

**Comment by privefl** [comment]
@JNajar that's a different issue. Please search for "Warning message: NA or NaN values in the resulting correlation matrix".
