### ISSUE TITLE
snp_match with multiple datasets

### ISSUE THREAD

**Issue by fsakhtari** [privefl/bigsnpr#125]
I'm using ldpred2 to compute PRS. I have following **distinct** datasets:

1. summary statistics (ss)

1.  LD reference panel (ldref)

1.  Validation data (validn)

1. Test data (test)

As shown in the tutorial, snp_match() needs to be run to (a) get common SNPs across all datasets, (b) remove ambiguous alleles, flip or reverse alleles / flip the sign on the beta values and (c) get the SNP column indices in the genotype matrices. We need to use the intersection of SNPs present in all datasets. 
**Q. What's the simplest way to do snp_match() across all datasets?**

I was going down this route:
'# Get the intersection of SNPs present in all datasets
common_snps <- intersection of rsids in ss, ldref, validn, test datasets
'# Only keep the common intersection of SNPs for the analysis
summstats <- summstats %>% filter(rsid %in% common_snps)

'# Match variants between summary statistics and ..
'# .. LDrefpanel
info_snp.ld <- snp_match(summstats, ldref.map)
'# .. validation genotype data
info_snp.validn <- snp_match(summstats, validn.map)
'# .. test genotype data
info_snp.test <- snp_match(summstats, test.map)

So far, this has solved (a) and (c).

Next, using code with similar notation as in the tutorial ...
... <skipping some steps> ....
df_beta <- info_snp.ld [ind.chr, c("beta", "beta_se", "n_eff")]
....
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
'# Using beta_grid on validation data 
pred_grid <- big_prodMat(**validn.G,** beta_grid, ind.col = ind.chr2)

The beta values in beta_grid have been potentially reversed for the genotypes/alleles in the LD reference panel. However, the genotypes/alleles in the validation data (and later in the test data) may be different than in the LD reference panel. That sign reversing for the validation data was done in info_snp.validn and for test data in info_snp.test. But how do I use information from that when computing PRS using the adjusted values in beta_grid ?
I was thinking that I could use this logic : If the sign of any beta value in info_snp.validn$beta is not equal to the sign of info_snp.ld$beta then reverse the sign for that beta in beta_grid when using it with validn.G (and similarly for test data)
i.e. multiply each column in beta_grid with :  sign(ss.ld$beta) * sign(ss.val$beta)

Would that work or am I convoluting this more than it needs to be?

**Comment by privefl** [comment]
That's a good point; `snp_match()` only works with 2 datasets.
I've already used in with 3 but it was simply because val and test were imputed in the same way, so that alleles seemed to be on the same strand and direction.

What I would probably try first if I were in your situation is to use e.g. PLINK to merge all your 3 individual-level datasets.

What I would try second is to use 3 `snp_match()` consecutively, but using the output from the one before. You might need to rename the fields giving the indices.

**Comment by fsakhtari** [comment]
Hi Florian,
Thanks for your reply.
How did you use snp_match with 3 datasets? Was your validation data also the LD reference panel?

Option 1) plink merge. This is a cleaner approach but is rather involved and long -
denote group for each dataset -> plink merge in diff mode -> get mismatched snps -> plink flip mismatched snps -> plink merge -> if errors, discard these snps -> plink merge

Q. What do you think about multiplying with the sign vector? Is it too hacky/dirty?

Option 2) I did think about that too. But that would still lead to the same output as before since the signs just get reversed and we'd have the same issue where the beta_grid from snp_ldpred2_grid would have the signs for the LD reference panel and not the validation data.
info_snp.validn2 <- snp_match(ss.ld %>% select(-c('_NUM_ID_.ss', '_NUM_ID_', 'id')), val.map)

df_beta <- info_snp.ld [ind.chr, c("beta", "beta_se", "n_eff")]
....
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
'# Using beta_grid on validation data
pred_grid <- big_prodMat(validn.G, beta_grid, ind.col = ind.chr2)

or should I be doing:
df_beta <- **info_snp.validn2**[ind.chr, c("beta", "beta_se", "n_eff")]    <- use the betas (signs) for validn genos instead of the LDref panel genos
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
'# Using beta_grid on validation data
pred_grid <- big_prodMat(validn.G, beta_grid, ind.col = ind.chr2)

Even if I do this, I'd still have the issue with the test data.

**Comment by privefl** [comment]
If you provide me your map/sumstats data (maybe subset for one chromosome), I can look at some strategy tomorrow.

**Comment by fsakhtari** [comment]
Thanks, Florian!!! You are a godsent!!
Attached are the subsets of the map file (LD reference panel) and summary statistics before & after doing snp_match() for chromosome 14.
BTW, close to 50% of the SNPs were reversed in snp_match(summstats, ldref.map). 
 - {From snp_match: 1,886,541 variants have been matched; 431 were flipped and 926,782 were reversed.}
Clearly, something weird is going on here with the data. I am investigating why this is so. I don't know if this will block you from working on this issue.

Here's what I'm using for the datasets:
1. Summary statistics - from this meta-analysis paper on T2D https://diabetes.diabetesjournals.org/content/diabetes/66/11/2888.full.pdf , downloaded from here: http://diagram-consortium.org/downloads.html 
2. LD reference panel - 1000 Genome Phase 1 dataset
3. Validation data - UK Biobank data
4. Test data - In-house data

Please let me know if you need other data from me or if there is anything else that I can do.

[map_ss.tar.gz](https://github.com/privefl/bigsnpr/files/5037863/map_ss.tar.gz)

**Comment by privefl** [comment]
Basically, I would like to have `summstats`, `ldref.map`, `validn.map` and `test.map`, possibly as RDS files.

**Comment by fsakhtari** [comment]
I will check if I can give you the validn.map and test.map. It might be ok since the .map doesn't have IDs, but I need to check.

**Comment by fsakhtari** [comment]
Hi Florian,
Here are the 4 datasets for chr 14. My code follows your tutorial and these data are extracted after executing the line of code from tutorial: "names(map) <- c("chr", "pos", "a0", "a1")" . snp_match has not been done, neither has filtering for common snps that I mentioned in my original question.
Also note that the LDref panel is from 1000 Genome Phase 1 and the SNP chromosome position may be different than that in other datasets, hence join_by_pos will need to be FALSE in snp_match().
Thanks again for your help. Please let me know if more information is required or if I can do anything.

[issue125_4datasets.tar.gz](https://github.com/privefl/bigsnpr/files/5042452/issue125_4datasets.tar.gz)

**Comment by privefl** [comment]
Thanks for the data.
I got this that should work but is a bit messy..
```r
library(bigsnpr)
library(dplyr)

summstats <- readRDS("summstats.rds")
summstats$pos <- NULL

# Match variants between summary statistics and LDrefpanel
ldref.map <- readRDS("ldref.map.rds")
info_snp.ld <- snp_match(summstats, ldref.map, join_by_pos = FALSE)
# rename fields because same will be created in next snp_match()
info_snp.ld <- rename(info_snp.ld, c("_NUM_ID_.summstats" = "_NUM_ID_.ss",
                                     "_NUM_ID_.ldref" = "_NUM_ID_",
                                     "beta.summstats" = "beta"))
info_snp.ld$beta <- 1
str(info_snp.ld)

# .. validation genotype data
validn.map <- readRDS("validn.map.rds")
info_snp.validn <- snp_match(info_snp.ld, validn.map, join_by_pos = FALSE, 
                             match.min.prop = 0)
str(info_snp.validn)
# .. test genotype data
test.map <- readRDS("test.map.rds")
info_snp.test <- snp_match(info_snp.ld, test.map, join_by_pos = FALSE)
str(info_snp.test)

final_info <- inner_join(info_snp.validn, info_snp.test, 
                         by = setdiff(c(names(info_snp.ld), "_NUM_ID_.ss"),
                                      c("beta", "_NUM_ID_", "pos")),
                         suffix = c(".validn", ".test"))
final_info$`_NUM_ID_.ss` <- NULL
str(final_info)
```

Basically, you need 
1. the first `snp_match()` to have the `beta` matching the LD ref to compute the polygenic scores
2. need to find the indices and signs when you'll need to project on both validation and test
3. find the variants both in first 2 + validation/test with final `inner_join()`.

Also, I don't think just multiplying by the sign for val/test is the appropriate way to do it. You just need to think that 0 <-> 2 (see the code of `bigsnpr:::prodVecRev`).

I've not think enough about this to make it easy to use. It might be easier to use PLINK for
- either merging the 3 datasets in one
- or computing the scores on the validation/test sets (I believe PLINK takes care of the allele matching?) -> then, the only thing you need to do is restrict LDref to the rsids present in both val/test.

**Comment by fsakhtari** [comment]
Hi Florian, 
Thanks so much for working on this. If I understand correctly, after getting final_info, I should continue along tutorial as follows:

## indices in final_info
ind.chr <- which(final_info$chr == 2)
df_beta <- final_info[ind.chr, c("beta.summstats", "beta_se", "n_eff")]

## indices in ldref.G
ind.chr.ldref <- final_info$`_NUM_ID_.ldref`[ind.chr]
corr0 <- snp_cor(ldref.G, ind.col =ind.chr.ldref, ncores = NCORES, infos.pos = POS2[ind.chr2], size = 3 / 1000)
corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))
...
beta_grid.ldref <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)

'# change signs for validation genotypes
beta_grid.validn <- beta_grid.ldref %*% final_info$beta.validn[ind.chr]
pred_grid <- big_prodMat(validn.G, beta_grid.validn, ind.col = final_info$_NUM_ID_.validn[ind.chr])
..
best_grid_sp <- params %>%
  mutate(id = row_number()) %>%
  filter(sparse) %>%
  arrange(desc(score)) %>%
  slice(1) %>%
  pull(id) %>%
  beta_grid[, .]
....
'# change signs for test genotypes
beta_vec.test <- best_grid_sp %*% final_info$beta.test[ind.chr]
pred_nosp <- big_prodVec(test.G, beta_vec.test, ind.row = ind.test, ind.col =final_info$_NUM_ID_.test[ind.chr])

So, the above workflow is multiplying by the sign for val/test as I had originally proposed, right? 
But, then I'm confused as to why you stated just multiplying by the sign for val/test is not the appropriate way to do it.  Maybe I'm not understanding correctly.

Also, I don't quite follow what prodVecRev is doing and why - 
I see that it does this:
prodVecRev <- function(G, betas.col, same.col, ind.row, ind.col) {
  betas.col.mod <- (2 * same.col - 1) * betas.col
  big_prodVec(G, betas.col.mod, ind.row, ind.col) +
    2 * sum(betas.col[!same.col])
}
so it is compensating for a -ve sum of some betas by adding 2x of them back in. When would same.col have 'FALSE' and where does this come in into the snp_ldpred2_grid workflow?

Apologies if I didn't understand something correctly.

**Comment by privefl** [comment]
Something like this could work. What is this `%\*%` operator though?

The thing with `prodVecRev` is just that it is adding some offset `2 * sum(betas.col[!same.col])` to all values. Don't worry about this if you check correlation or AUC afterwards (it is independent of any linear transfo). I'm using this function for some other thing, not in LDpred2.

**Comment by fsakhtari** [comment]
Ahh, I just meant %*% for matrix multiplication. The '\' was to remove formatting, looks like I didn't need it.
Ok, so if this will work then I'll follow the steps you mentioned for final_info and then change signs for validation and test as in my last post. Will keep you posted.

**Comment by fsakhtari** [comment]
Hello Florian,
Sorry for the delayed update, I've been caught up with other things. I've implemented this workflow in my pipeline and my results with the UK biobank data seem to agree overall with what has been published in existing literature for PRS for type 2 diabetes using UK biobank data. Also, as a test I used another sample from the UK biobank data as a test dataset and confirmed that results are similar to the sample from the UK biobank validation dataset. On my list of todos is to compare the PRS to plink's allele scoring.
Also, I made a small but important update to the workflow above.
Thank you so much for you help with this issue, it really helped me develop my PRS pipeline with LDpred2. You've been tremendous!

**Comment by privefl** [comment]
You're welcome.

Could I know which important update you made?

**Comment by fsakhtari** [comment]
I made the following change in the workflow that I had posted above:
 ....
  best_grid_sp <- params %>%
  mutate(id = row_number()) %>%
  filter(sparse) %>%
  arrange(desc(score)) %>%
  slice(1) %>%
  pull(id) %>%
  beta_grid.ldref [, .]          <<< This should be the LDref panel's beta grid and not the validation beta grid because the final_info$beta.test signs are based off of the LD ref panel. Originally, I wrote it as just "beta_grid" & it was unclear as to which one it was.

beta_vec.test <- best_grid_sp * final_info$beta.test[ind.chr]
