### ISSUE TITLE
distribution of prs

### ISSUE THREAD

**Issue by bnj50** [privefl/bigsnpr#126]
i am wondering whether ldpred2 can generate a file that shows distribution of prs (or adjusted prs) per individual (per chr)  of target population like ldpred1?
currently i only see one single mean score per chr with 95% CI and SD
thanks

**Comment by privefl** [comment]
I don't follow.

> currently i only see one single mean score per chr with 95% CI and SD

What are you referring to?

**Comment by bnj50** [comment]
so this is what i get for chr 1:
 AUCBoot(final_pred_auto, y[ind.test])
      Mean       2.5%      97.5%         Sd 
0.47147451 0.45075039 0.49213008 0.01060703 

however, i would like to see score for each individual of my target population for chr 1.  
as you know, ldpred1 generate a score file per individual for all chr. 
can we have those in this version? if yes, could you please describe it in wiki

**Comment by privefl** [comment]
Actually, I am not very familiar with LDpred1.

Are you talking about the polygenic score? That is `final_pred_auto`.

**Comment by bnj50** [comment]
yes...that is correct.  our goal for using this program is to get polygenic score for our patients in order to rank them. so we ultimately need polygenic score per individual (after combining all autosomal chr).  we then need to incorporate covariates to the model (from PC , gender to many environmental elements) and compare polygenic score with and without these covariates per individual.

**Comment by privefl** [comment]
You'll need to do a bit of R coding there.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
