### ISSUE TITLE
specify the effect and non-effect allele in map file

### ISSUE THREAD

**Issue by kaibios0101** [privefl/bigsnpr#129]
Hi privefl- LDpred2 is a powerful tool for PRS analysis. After perusing your paper on bioRxiv and tutorial, I have some confusion in specifying the effect allele in the map file. 

In your tutorial, you define the allele1 as the a0 (alternative allele) and allele2 as the a1 (effect allele) in the map file from genotype data, as follow:

$ map      :'data.frame':   130816 obs. of  6 variables:
..$ chromosome  : int [1:130816] 2 2 2 2 2 2 2 2 2 2 ...
..$ marker.ID   : chr [1:130816] "rs13400442" "rs7594567" "rs7597758" "..
..$ genetic.dist: int [1:130816] 0 0 0 0 0 0 0 0 0 0 ...
..$ physical.pos: int [1:130816] 18506 21833 22398 28228 32003 32005 36..
..$ allele1     : chr [1:130816] "C" "G" "T" "A" ...
..$ allele2     : chr [1:130816] "T" "C" "C" "G" ...
attr(*, "class")= chr "bigSNP"

map <- obj.bigSNP$map[-(2:3)]
names(map) <- c("chr", "pos", "a0", "a1")

However, in plink, the allele1 is considered as an effect allele by default and allele2 as an alternative allele. This inconsistent definition may change the orientation of beta estimation by the snp_match function. I'm not sure which is the right way or there may be some misunderstanding for me about the procedure. Can you give me some help?  Many thanks!

Kai

**Comment by privefl** [comment]
This is confusing for me too.
From what I (think I) understand, a1 is supposed to be the alternative allele while a0 (or a2) is the reference allele.
In UKBB, it seems that what they report in the mfi files and the bgi files is reversed.. and this is why I had to reverse them.

Honestly, my way to go is that if all are reversed for some sumstats (when I do `snp_match()`), then I just switch all a0 and a1.
Also, if you get some negative correlations for all of the derived PRS, it is a good sign that you need to reverse a0 and a1.

**Comment by kaibios0101** [comment]
Hi, privefl. Thanks for your answer. I will try your suggestion. Many thanks!

Kai
