### ISSUE TITLE
Problem with snp_fastImpute function

### ISSUE THREAD

**Issue by kassimbashir** [privefl/bigsnpr#13]
The error I'm getting is : " Error in trunc(x) : non-numeric argument to mathematical function "
The error occured after running the following code : 

```
##### convert vcf to bed ########
vcffile <- "Ha412_Jan2017.vcf"
prefix  <- sub("\\.vcf$", "", vcffile)
plink <- download_plink()
bedfile <- snp_plinkQC(plink.path = plink, prefix.in = prefix, prefix.out = tempfile(), file.type = "--vcf", extra.options =  "--aec --vcf-half-call m")
########## read the bed file ############
rds <- snp_readBed(bedfile, backingfile = tempfile())
########## get the BigSNP object #############
XX <- snp_attach(rds)
################## dealing with missing values : imputation ##########################
G <- XX$genotypes
CHR <- XX$map$chromosome
system.time(
 Z <- snp_fastImpute(G, CHR, ncores = nb_cores()) ### ERROR HERE!
)
```

Packages versions:
- bigstatsr : 0.7.0
- bigsnpr: 0.6.1

I'm afraid I am not allowed to provide the vcf file data.
Thanks

**Comment by privefl** [comment]
Can you also provide logs of PLINK QC please?

**Comment by kassimbashir** [comment]
sure. PLINK QC:

PLINK v1.90b6.5 64-bit (13 Sep 2018)           www.cog-genomics.org/plink/1.9/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /tmp/RtmpRdQwpj/file2c33c6e58db98.log.
Options in effect:
  --allow-extra-chr
  --geno 0.1
  --hwe 1e-50
  --maf 0.01
  --make-bed
  --mind 0.1
  --out /tmp/RtmpRdQwpj/file2c33c6e58db98
  --vcf Ha412_Jan2017.vcf
  --vcf-half-call m

1031980 MB RAM detected; reserving 515990 MB for main workspace.
--vcf: /tmp/RtmpRdQwpj/file2c33c6e58db98-temporary.bed +
/tmp/RtmpRdQwpj/file2c33c6e58db98-temporary.bim +
/tmp/RtmpRdQwpj/file2c33c6e58db98-temporary.fam written.
675291 variants loaded from .bim file.
239 people (0 males, 0 females, 239 ambiguous) loaded from .fam.
Ambiguous sex IDs written to /tmp/RtmpRdQwpj/file2c33c6e58db98.nosex .
2 people removed due to missing genotype data (--mind).
IDs written to /tmp/RtmpRdQwpj/file2c33c6e58db98.irem .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 237 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate in remaining samples is 0.966087.
62128 variants removed due to missing genotype data (--geno).
--hwe: 283914 variants removed due to Hardy-Weinberg exact test.
0 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
329249 variants and 237 people pass filters and QC.
Note: No phenotypes present.
--make-bed to /tmp/RtmpRdQwpj/file2c33c6e58db98.bed +
/tmp/RtmpRdQwpj/file2c33c6e58db98.bim + /tmp/RtmpRdQwpj/file2c33c6e58db98.fam
... done.

**Comment by privefl** [comment]
1. I check parameters for almost all functions of packages {bigstatsr} and {bigsnpr}. For example, I check if indices (`ind.row`, `ind.col`, etc.) are really integers, with [this function](https://github.com/privefl/bigstatsr/blob/master/R/utils-assert.R#L109-L112). This option disables all those checkings.

2. To disable those parameters in `snp_plinkQC`, use `maf = 0, geno = 1, mind = 1, hwe = 0`.

**Comment by kassimbashir** [comment]
Ok I get it.
So the `options(bigstatsr.check.args = FALSE)` function does not solve the error problem but it's helpful for testing until a solution is found.
I''ll see if I could arrange to attach a part of the data so you would able to see the problem I'm seeing.
I will probably contact you tomorrow.
thanks

**Comment by privefl** [comment]
Thanks to the data you provided, I was able to find the problem.
The problem is that the data you pass as `CHR` should be integers (chromosome numbers), not strings (names).
You just have to recode those.

In future versions, I'll catch this error so that the error message is more explicit.
Thanks for reporting.

**Comment by kassimbashir** [comment]
Wow that's great,
You helped me a lot.
Thanks,
Kassim

**Comment by kassimbashir** [comment]
Hi Florian,
I'm trying to figure out what's the best way to make an efficient
multivariate linear regression of my own formula on a bigSNP object using
the bigstatsr package.
I'd be glad to hear your suggestion.
thanks,
Kassim Bashir

**Comment by privefl** [comment]
Please open another issue or comment in https://github.com/privefl/bigstatsr/issues/6.

**Comment by privefl** [comment]
The error is now `'infos.chr' should be numeric.`
