### ISSUE TITLE
Error in snp_cor() function with large number of variants 

### ISSUE THREAD

**Issue by Zhe-JJ-Wang** [privefl/bigsnpr#130]
Hello,

I am trying to use ldpred2 following the detailed manual you provided on https://privefl.github.io/bigsnpr/articles/LDpred2.html. I would like to build a prs using about 400K variants from one chromosome. I'd encounter a error says "Error in validityMethod(as(object, superClass)) : long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519" if I run the line 
'corr0 <- snp_cor(G, ind.col = ind.chr2, ncores = NCORES,
                 infos.pos = sort(POS2[ind.chr2]), size = 3 / 1000)' with all 400K variants. The snp_cor() function works fine if I limited to 200K variants. But then the line 'corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))' will through an error message as "Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 92 "
None of these two error occurs if I use only 100K variants.
Is there a hard limit for how many variants that can be used to build PRS per chromosome? Any chance you plan to support PRS computation with larger number of variants?

Thanks,
JJ

**Comment by privefl** [comment]
Please see #89

**Comment by privefl** [comment]
In summary,
Please try the newest version with `remotes::install_github("privefl/bigsnpr")`.
You should be able to directly do `as_SFBM(corr0)` instead of `bigsparser::as_SFBM(as(corr0, "dgCMatrix"))` now.

**Comment by Zhe-JJ-Wang** [comment]
> In summary,
> Please try the newest version with `remotes::install_github("privefl/bigsnpr")`.
> You should be able to directly do `as_SFBM(corr0)` instead of `bigsparser::as_SFBM(as(corr0, "dgCMatrix"))` now.

Hi,

Thanks for pointing me to the previous issue. The discussion is really helpful. But I may already have the most recent version of bigsnpr (bigsnpr_1.4.4) as I installed it last Friday (Aug 14th). But it seems like I cannot find the function corr <- as_SFBM(corr0). Error in as_SFBM(corr0) : could not find function "as_SFBM".

**Comment by privefl** [comment]
The latest is 1.4.7 I think.
The 1.4.4 is the CRAN version, which is more than 1 month old.

**Comment by Zhe-JJ-Wang** [comment]
Hi Florian,

Thank you! I will contact our HPC team to update using the github version. Will report back if the issue is solved.

Many Thanks,
JJ

**Comment by Zhe-JJ-Wang** [comment]
Hi Florian,

With the latest version of bigsnpr, the new function as_SFBM() works well (using 250k variants). But I still encounter the same  error message when I try to use snp_cor() for 400K+ variants. "Error in validityMethod(as(object, superClass)) : long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519".

Thanks,
JJ

**Comment by privefl** [comment]
Could you run `snp_cor()` line by line? (if you use `debugonce(snp_cor)`, you'll be able to do so.
To tell me which line of the function is failing.

**Comment by Zhe-JJ-Wang** [comment]
I think it's the corMat() function that was written in C++, as I used to try the snp_cor() line by line. Unfortunately I am not familiar with C++ to be able to debug further. The full outcome from debugonce() is as below
------------------------------------------------------------
corr0 <- snp_cor(G, ind.col = ind.chr16, ncores = NCORES,
+                  infos.pos = sort(POS2[ind.chr16]), size = 3 / 1000)
debugging in: snp_cor(G, ind.col = ind.chr16, ncores = NCORES, infos.pos = sort(POS2[ind.chr16]),
    size = 3/1000)
debug: {
    check_args()
    if (is.null(infos.pos))
        infos.pos <- 1000 * seq_along(ind.col)
    assert_lengths(infos.pos, ind.col)
    assert_sorted(infos.pos)
    suppressWarnings(q.alpha <- stats::qt(p = alpha/2, df = seq_along(ind.row) -
        2, lower.tail = FALSE))
    THR <- q.alpha/sqrt(seq_along(ind.row) - 2 + q.alpha^2)
    ind_val <- corMat(BM = Gna, rowInd = ind.row, colInd = ind.col,
        size = size * 1000, thr = THR, pos = infos.pos, ncores = ncores)
    m <- length(ind.col)
    corr <- Matrix::sparseMatrix(i = unlist(lapply(ind_val, function(.) .$i)),
        j = rep(1:m, times = sapply(ind_val, function(.) length(.$i))),
        x = unlist(lapply(ind_val, function(.) .$x)), dims = c(m,
            m), symmetric = TRUE)
    if (fill.diag)
        diag(corr) <- 1
    corr
}
Browse[2]>
debug: check_args()
Browse[2]>
debug: if (is.null(infos.pos)) infos.pos <- 1000 * seq_along(ind.col)
Browse[2]>
debug: assert_lengths(infos.pos, ind.col)
Browse[2]>
debug: assert_sorted(infos.pos)
Browse[2]>
debug: suppressWarnings(q.alpha <- stats::qt(p = alpha/2, df = seq_along(ind.row) -
    2, lower.tail = FALSE))
Browse[2]>
debug: THR <- q.alpha/sqrt(seq_along(ind.row) - 2 + q.alpha^2)
Browse[2]>
debug: ind_val <- corMat(BM = Gna, rowInd = ind.row, colInd = ind.col,
    size = size * 1000, thr = THR, pos = infos.pos, ncores = ncores)
Browse[2]>
debug: m <- length(ind.col)
Browse[2]>
debug: corr <- Matrix::sparseMatrix(i = unlist(lapply(ind_val, function(.) .$i)),
    j = rep(1:m, times = sapply(ind_val, function(.) length(.$i))),
    x = unlist(lapply(ind_val, function(.) .$x)), dims = c(m,
        m), symmetric = TRUE)
Browse[2]>
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519

**Comment by privefl** [comment]
No, it seems the error comes from
```r
Matrix::sparseMatrix(i = unlist(lapply(ind_val, function(.) .$i)),
    j = rep(1:m, times = sapply(ind_val, function(.) length(.$i))),
    x = unlist(lapply(ind_val, function(.) .$x)), dims = c(m,
        m), symmetric = TRUE)
```

Before running this line, could you run each of 
- `unlist(lapply(ind_val, function(.) .$i))`
- `rep(1:m, times = sapply(ind_val, function(.) length(.$i)))`
- `unlist(lapply(ind_val, function(.) .$x))`

If all 3 run fine, could you try then
```r
corr <- Matrix::sparseMatrix(i = unlist(lapply(ind_val, function(.) .$i)),
    p = c(0, cumsum(sapply(ind_val, function(.) length(.$i)))), 
    x = unlist(lapply(ind_val, function(.) .$x)), symmetric = TRUE)
```

**Comment by Zhe-JJ-Wang** [comment]
I'm sorry I am not that good at debugging. I think last time I got stuck when trying to run snp_cor() line by line is because I cannot directly run corMat() function.  For example. I find out that to run assert_lengths(), I need to use bigassertr::assert_lengths(). Could you please let me know how I can get corMat()?

**Comment by privefl** [comment]
You could use `bigsnpr:::corMat()`.

**Comment by Zhe-JJ-Wang** [comment]
ind_val <- bigsnpr::corMat(
+   BM     = G,
+   rowInd = ind.row,
+   colInd = ind.col,
+   size   = size * 1000,
+   thr    = THR,
+   pos    = infos.pos,
+   ncores = 48
+ )
Error: 'corMat' is not an exported object from 'namespace:bigsnpr'

**Comment by Zhe-JJ-Wang** [comment]
Ahh, great! Thank you, I didn't know about triple column before. The function corMat() takes some time to run. Will get back to you once it's done.

**Comment by privefl** [comment]
LDpred runtime is quadratic with the number of variants used.
It takes approx 2 hours to run all models for 100K variants with 8 cores if I remember correctly.
It should therefore take ~32 hours with 400K variants.

**Comment by privefl** [comment]
Are you using parallelism?
Computing LD is proportional to N * M^2. 
It takes 15 min with N = 10K and M = 100K when using 16 cores.
It should therefore take 4 hours for M = 400K and same N.

**Comment by jianvhuang** [comment]
Hi Florian, 

I came across a similar problem as discussed in this issue. I also read the discussion in another [issue ](https://github.com/privefl/bigsnpr/issues/89), but I am already using the bigsnpr_1.8.1. 

Could you advise on this issue again? Thank you.

I am using packages of below versions
```
R version 4.0.4 (2021-02-15)
bigsnpr_1.8.1
bigstatsr_1.5.1
Matrix_1.3-2 
```

I am using HM3 SNPs, with 47285 on chr1. But snp_cor still failed.
I followed your above suggestions to run snp_cor line by line.

```
G=snp_fastImputeSimple(obj.bigSNP$genotypes, method = "random", ncores = NCORES) 
POS2 <- obj.bigSNP$map$genetic.dist

 ##############################################
  chr=1
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'G'
  ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
  
  Gna=G 
  ind.col=ind.chr2
  size = 3 / 1000
  infos.pos = POS2[ind.chr2]
  ncores = NCORES
  
  ind.row = rows_along(Gna)
  alpha=1
  thr_r2 = 0
  fill.diag = TRUE
  info = rep(1, length(ind.col))
  
  if (is.null(infos.pos)) infos.pos <- 1000 * seq_along(ind.col)
  bigassertr::assert_lengths(infos.pos, info, ind.col)
  bigassertr::assert_sorted(infos.pos)
  if (!all(0.1 <= info & info <= 1))
    stop2("All values of 'info' must be between 0.1 and 1.")
  
  # Get significance thresholds with type-I error `alpha`
  suppressWarnings(
    q.alpha <- stats::qt(p = alpha / 2,
                         df = seq_along(ind.row) - 2,
                         lower.tail = FALSE)
  )
  THR <- q.alpha / sqrt(seq_along(ind.row) - 2 + q.alpha^2)
  
  ind_val <- bigsnpr:::corMat(
    BM     = Gna,
    rowInd = ind.row,
    colInd = ind.col,
    size   = size * 1000,
    thr    = pmax(THR, sqrt(thr_r2)),
    pos    = infos.pos,
    info   = info,
    ncores = ncores
  )
  
  m <- length(ind.col)
  
###########
# I checked these line before running the sparseMatrix, and they run fine.
  unlist(lapply(ind_val, function(.) .$i))
  rep(1:m, times = sapply(ind_val, function(.) length(.$i)))
  unlist(lapply(ind_val, function(.) .$x))
 ###########

  corr0 <- Matrix::sparseMatrix(
    i = unlist(lapply(ind_val, function(.) .$i)),
    p = c(0, cumsum(sapply(ind_val, function(.) length(.$i)))),
    x = unlist(lapply(ind_val, function(.) .$x)), 
    symmetric = TRUE)
  
# the above function Matrix::sparseMatrix also run fine, but when I call the output by running "corr0" as below, it returned the below error
corr0
**47285 x 47285 sparse Matrix of class "dsCMatrix"
Error in subCsp_cols(x, j, drop = drop) :  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89**


 if (fill.diag) diag(corr0) <- 1
  ##############################################

```

**Comment by privefl** [comment]
With such a small number of variants, the only issue I can see is that you're computing correlations between ALL pairs of variants.
Are you really providing the genetic positions (in cM) in `POS2`? Maybe you have just a vector of 0s or something very small?

**Comment by jianvhuang** [comment]
Thank you. You are right. I should have used snp_asGeneticPos to convert position from bp to cM.
