### ISSUE TITLE
Genotype PCA

### ISSUE THREAD

**Issue by juanb001** [privefl/bigsnpr#131]
Hi,

I'm interested in running a GWAS analysis and in controlling for population structure by including genotype principal components as covariates in the model. Following the tutorial here (https://privefl.github.io/bigsnpr/articles/how-to-PCA.html) I get numerous PCs that seem to divide my different populations well (from the 1000 Genomes Project). What caught my attention is that the axes range on a scale of tens (-50 to 50 or -100 to 100, similar to the examples you provide) wheras other tools I'm seeing online (admittedly looking at completely different data) seem to range on a scale of 1/100s (-0.02 to 0.02, for example). I'm curious if there might be factors that explain this difference, aside from true, more variable genotypes in my data compared to what others might be looking at?

Separately, are there plans to output how much of the variance is explained by a given PC? I think it would be a useful feature.
EDIT: Just saw a previous post like this. Thanks!

Thanks for the software and support!

**Comment by privefl** [comment]
I think it is just a factor of 1 / sqrt(n - 1) or something like this.
I'm using UD as PC scores, where UDV^T is the (truncated) singular value decomposition.

This is the same behaviour as in R:
```r
pca <- prcomp(iris[-5], scale. = TRUE)
svd <- svd(scale(iris[-5]))
PC <- sweep(svd$u, 2,  svd$d, '*')
all.equal(PC, pca$x, check.attributes = FALSE)
```

I see that you found the answer to your other question, good.
