### ISSUE TITLE
Question about parallelization in bigsnpr

### ISSUE THREAD

**Issue by danny-wilson** [privefl/bigsnpr#133]
I've been trialling bigsnpr for PCA in biobank-scale data.

I wonder if you would help me understand the behaviour of the parallelization?

Although my version of R is built with working BLAS, as far as I can tell big_randomSVD does not make use of it. The only available parallelization seems to be through the argument ncores.

(To use ncores>1, I first execute the commands options(bigstatsr.check.parallel.blas = FALSE) and options(default.nproc.blas = NULL).)

However, when I use ncores>1, R forks child processes, each of which appears to duplicate the memory usage of the original process. I.e. they don't share memory. Please let me know if I misunderstand.

This is a problem for my compute cluster, where each core is allocated 16GB memory. Therefore to load the data, which requires 42GB memory, I must request 3 slots: equivalent to 3 cores. However, if I want to use two-fold parallelization (ncores=2), I must request 9 slots because I store 3 copies of the data: one for the parent and one for each child process. That is inefficient when I wish to submit ~60 analyses.

I would be happy to be corrected about any of the above, because I have put in the time to code up the analysis :)

**Comment by privefl** [comment]
Any update on this?

**Comment by danny-wilson** [comment]
Thanks for this Florian.

I have been away but will try your bed file suggestion, I think the 4-fold
memory reduction is just right to make this work with our local constraints
on memory per core.

In terms of the question about the memory problem. My impression (which
could be wrong) is that when R creates a fork for n-fold parallelization,
at that point it does appear to duplicate the memory once - only once, not
n times. Downstream of that, the way the Univa grid engine bookkeeps the
memory doesn't take into account shared memory between those n parallel
processes, and that appears to make it think there are n+1 copies, instead
of 2 copies. So the overall behaviour looks like an unfavourable
interaction between the method of parallelization, memory bookkeeping and
the per-core memory constraint on our system. My guess is that OpenMP
parallelization would play more nicely, but that would be a different
software design from what I understand.

best wishes
Danny
