### ISSUE TITLE
how to input gds file

### ISSUE THREAD

**Issue by 229668880** [privefl/bigsnpr#134]
A troublesome way is to convert gds file into bed file, then input bed file. Is there a easy way?

**Comment by privefl** [comment]
Sorry, what is a gds file?

**Comment by 229668880** [comment]
GDS format is a very common way to store GWAS data, like BED format for Plink.

**Comment by privefl** [comment]
Could you at least point me to somewhere describing the format.

**Comment by 229668880** [comment]
This is a short introduction.  http://si.biostat.washington.edu/sites/default/files/modules/GDS_intro.pdf
SNPRelate and GWASTools packages in R accept both BED and GDS as input format. This is very helpful, because many GWAS data are stored in GDS format to save disk space.

**Comment by privefl** [comment]
I see that {SNPRelate} has some converters, and it does not seem trivial (cf. https://github.com/zhengxwen/SNPRelate/blob/master/R/Conversion.R#L310-L425).

I currently does not have enough time to work on this. There are two solutions:
- as you mentioned, convert to bed using e.g. {SNPRelate} and then convert to my format.
- you adapt the code from {SNPRelate} and I can help you along the way if you have some questions. My format should be even easier to understand than the bed format.

**Comment by 229668880** [comment]
Thanks for reply. I will try.

**Comment by privefl** [comment]
Did you find a solution to this?

**Comment by 229668880** [comment]
I converted GDS into Bed file.  Hope bigsnpr can deal with GDS file in the future, as GDS file is used to save disk space.
Thanks for your followup.

**Comment by privefl** [comment]
Honestly, there is little chance bigsnpr will handle this format as I've never encountered it yet.
It would be good to get some PR on this from people actually using it, like you. 
Closing this for now until someone wants to look at it.
