### ISSUE TITLE
setting seed for lpred2 + QC questions

### ISSUE THREAD

**Issue by fsakhtari** [privefl/bigsnpr#136]
Q1. 
I'm using the workflow described in the LDpred2 tutorial to do the following:
snp_ldpred2_grid -> obtaining beta_grid -> computing PRS -> logistic regression -> use AUC to pick best beta_grid & param values (p, h2 values)
In different runs, I see that different param values give the best AUC. The overall end result does not change (i.e. auc, etc.), just which param values get chosen changes in different runs. I'm assuming that this is because of the randomness from the Gibbs Sampler (I see some code in ldpred2.cpp::ldpred2_gibbs_one()). Is it possible to use a seed for this and expose this seed to the front-end user ? I would like to have reproducibility to report the p and h2 values and the beta values.

Q2.
The QC suggested here - https://github.com/privefl/paper-ldpred2/blame/master/code/run-ldpred2.R#L101-L108 
```
 sc <- apply(pred_auto, 2, sd)
 final_beta_auto <- rowMeans(beta_auto[, abs(sc - median(sc)) < 3 * mad(sc)])
```
Instead of filtering based on the PRS standard deviations, I'm filtering based on the standard deviations of the beta values themselves. 
```
std_devs <- apply(beta_grid, 2, sd)
keep <- (1:ncol(beta_grid))[abs(std_devs - median(std_devs)) < 3 * mad(std_devs)]
```
I wanted to confirm that this is equivalent.  Since the PRS is the beta * genotype, I think that these should be equivalent, correct?

Q3.
I'm using 4 distinct datasets - Summary statistics, LD reference panel, Validation data and Test data.
In this case, I believe that the QC described here - https://github.com/privefl/paper-ldpred2/blob/master/paper/paper-ldpred2-supp.pdf would need to be done for both the Validation and Test data sets, correct?

**Comment by privefl** [comment]
Q1.
I guess I could try to do something about seeds.

Q2.
I'm not sure it is equivalent to this on the betas. Say everything has mean 0. Then variance of beta is beta^T beta / (m -1) while variance of PRS is beta^T G^T G beta / (n - 1). Basically your solution is not accounting for LD and over-counting effects for rare variants, I think.
But then, because you're comparing between them, it might not change much.
I'll think about it. 

Q3.
Probably a good idea, yes.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
