### ISSUE TITLE
snp_asGeneticPos step || can this be done in-house after downloading manually?

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#137]
hi there,

thanks for this. This is a great tool.
I'm interested to run the data through your pipeline. https://choishingwan.github.io/PRS-Tutorial/ldpred/

I pass and process data until snp_asGeneticPos  step. My cluster has certain integrated and modular quality measures in place that forbids to connect with data outside.

But I can download data manually, move around the cluster via winscp-filezilla.

How do I execute

https://privefl.github.io/bigsnpr/articles/LDpred2.html#computing-ldpred2-scores-for-one-chromosome-1

`POS2 <- snp_asGeneticPos(CHR, POS, dir = "tmp-data", ncores = 3)`

Where dir=`where data are already downloaded manually`

Data for the population in analyses aren't EUR.

Best,

**Comment by privefl** [comment]
The function expects the (uncompressed) files to have the form `paste0("chr", chr, ".OMNI.interpolated_genetic_map")`.

**Comment by sariya** [comment]
I see. If I download them, how do I tell function to look into so and so folder? Sorry I opened this in a different repo earlier. Thanks
~

**Comment by privefl** [comment]
You can specify the directory with parameter `dir`.

**Comment by sariya** [comment]
perfecto. Thanks much
