### ISSUE TITLE
question: dosage after loading bgen file v/s dosage from IMPUTE2 genotype probability

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#141]
Please see attached files:

1. genotype probability from the IMPUTE2 software (`impute2_outputCHR22.txt`) Rows are SNPs. More description provided below
2. dosage from bgen (`bgen_dosage.txt`) after loading in bigsnpr package. Rows are individuals and columns are SNPs. 
3. dosage for allele in 5th column (`dosage_for_allele_calculatedby_code.txt`) Rows are SNPs and Columns are for individuals from 4t columns.

File from IMPUTE2 has 5+10*3 columns. CHR, SNP, POS, Allele1, Allele2. Allele1 and Allele2 are not based on their frequency, but simply put. It is possible that the frequency of the Allele2 is 5% or 55%. 
Let us say, `Allele1` is `A` and `allele2` is `B`. The first 5 columns are then followed by the probability of `P(AA)`, `P(AB)` and `P(BB)`

When I calculate dosage (allele in 5th col (`Allele2` or `B`) from the IMPUTE2 s/w) using an in-house code the values are absolutely different than what I observe after reading an imputed-converted-bgen file. 

Dosage is calculated as
```
awk -v s=10 '{
printf $2 "," $4 "," $5;
for(i=1; i<=s; i++) printf "," $(i*3+5)*2+$(i*3+4); printf "\n"
}' impute2_file.txt

# where s is an input parameter. 10 is number of individuals in this case
```

I've following questions:

1. For which allele (4th column, 5th column) from the imput2 file format does bignpr calculates dosage?
2. How is the dosage calculated in the bigsnpr package? I am unable to understand how `NA` is dosage (attached lines)

May I please understand what is the bgen file format doing with the impute2 data and how is that transmitted within the bigsnpr while reading?

[impute2_outputCHR22.txt](https://github.com/privefl/bigsnpr/files/5203990/impute2_outputCHR22.txt)
[bgen_dosage.txt](https://github.com/privefl/bigsnpr/files/5203954/bgen_dosage.txt)
[dosage_for_allele_calculatedby_code.txt](https://github.com/privefl/bigsnpr/files/5203961/dosage_for_allele_calculatedby_code.txt)

Let me know if any other details are needed.
Sanjeev

**Comment by privefl** [comment]
Just so I understand, the `bgen_dosage.txt` you're showing is basically the output of `G[]`, where you have something like this before:
```r
rds <- snp_readBGEN(...)
obj.bigsnp <- snp_attach(rds)
G <- obj.bigsnp$genotypes
G[]
```
?
Could you share the real BGEN & BGI files as well? How do you get them?

**Comment by sariya** [comment]
Yes, the code shared is correct to get the dosage for `bgen_dosage.txt`.
How do I share files to you? I can put them on dropbox to take forward.

best,

**Comment by privefl** [comment]
If they are small, I think you can just drag and drop them here.
(You might need to add a .txt extension for it to work.)

**Comment by sariya** [comment]
The files (.bgen + .bgi) in total are ~32Mb

One more thing I'd like to add before data are shared. I mentioned in the original post `Allele2` may have a frequency of 5% of 55% from the imputed data off the IMPUTE2 s/w. The alleles are switched accordingly in the plink files when data are transformed. To elaborate, consider SNP on CHR22: SNP1 POS1 A T, let us say T has AF of 5%

In the plink format (.bim) it will appear as

`22      SNP1 0       POS1        T       A`

Now, consider SNP2 on CHR22, `SNP2 POS2 G C`, here C has AF of 55%; in the plink format it will appear as

`22      SNP2 0       POS2        G       C`

Allele1 is minor https://www.cog-genomics.org/plink/1.9/data#ax_allele

I hope I'm making sense and where this proceeds. Based on what I [understand](https://github.com/privefl/bigsnpr/issues/138#issuecomment-688629340) when bgen reads plink file it will make SNP names as `SNP1_POS1_T_A` and similarly, `SNP2_POS2_G_C`. 

When working with imputed data from such as IMPUTE2 s/w I set my allele (that is recoded allele) whose frequency can be 0-100%, create dosage and conduct GWAS. The AF user isn't known to the user until GWAS is conducted. 
In my case or several others data using imputed data from IMPUTE2 I format them as  `SNPNumber_POS_notRecodedallele_RecodedAllele` I take this to the end with GWAS, summary statistics so and so forth. Where `notRecodedallele` is allele not coded and `RecodedAllele` is coded allele

This is why probably simply [switching allele](https://github.com/privefl/bigsnpr/issues/138#issuecomment-688465566) may not be a good idea unless the genotype probabilities are also taken care of when alleles are flipped from IMPUTE2 s/w later on .bgen and read onto bigsnpr. My hunch is that this may cause _some_ raucous here or in the pipeline. 

For the data shared no switching took place as far as I can tell. :)

**Comment by privefl** [comment]
I'm not sure I follow everything.
Can you share the bgen data with me?
It should not be very large as you have only 10 individuals and 10 variants?

**Comment by sariya** [comment]
I initially processed data for 500+ individuals. I've tried to create for 10 individuals and 10 SNPs. It is excruciatingly painful from IMPUTE2 --> bgen --> bgi --> bigsnpR. There can be crack anywhere. The results don't match for the earlier post nonetheless, I'd like to understand how dosage values are calculated.

I'm attaching following files:

1) .gen used to create bgen and .bgi 
[test_input_bgen.gen.txt](https://github.com/privefl/bigsnpr/files/5210131/test_input_bgen.gen.txt)

2) .gen used to create plink file 
[plinktest_input.gen.txt](https://github.com/privefl/bigsnpr/files/5210135/plinktest_input.gen.txt)

3) .sample file used to create bgen file format 
[sample_qctool.sample.txt](https://github.com/privefl/bigsnpr/files/5210141/sample_qctool.sample.txt)

4) .sample file used to create plink file
[sample_CHR22.sample.txt](https://github.com/privefl/bigsnpr/files/5210151/sample_CHR22.sample.txt)

5) .bgen file 
[CHR22_sampledata.bgen.txt](https://github.com/privefl/bigsnpr/files/5210553/CHR22_sampledata.bgen.txt)

6) .bgil file 
[CHR22_sampledata.bgen.bgi.txt](https://github.com/privefl/bigsnpr/files/5210555/CHR22_sampledata.bgen.bgi.txt)

Code for working with the bigsnpR loading and other tasks
``` r
library(bigsnpr)
library(data.table)
library(magrittr)
options(bigstatsr.check.parallel.blas = FALSE)
options(default.nproc.blas = NULL)

bim_df=data.table::fread("CHR22_smalltest.bim")
SNP_list<-bim_df$V2
file_snpbed<-paste0("CHR22_smalltest.bed")

snp_readBed(file_snpbed)

rds <- bigsnpr::snp_readBGEN(
    bgenfiles="CHR22_sampledata.bgen",
    bgi_dir = "./",
	backingfile="CHR22_smalltest.rds",
    ncores = 8,list_snp_id=list(SNP_list)
)

passed.bigSNP <- snp_attach("CHR22_smalltest.rds.rds")
passed.bigSNP$genotypes[]

````

The difference between `test_input_bgen.gen.txt` and `plinktest_input.gen.txt` is allele swaps if and when needed. 

let me know if you need code for .impute2 ->plink-> part of the pipeline too.
best,

**Comment by privefl** [comment]
I am mostly interested in how you generate the BGEN file. With which tool and command?
Are you making sure it is BGEN v1.2 as specified in the documentation of `snp_readBGEN()`?

**Comment by sariya** [comment]
```
qctool -g test_input_bgen.gen -s sample_qctool.sample -assume-chromosome  22 -ofiletype bgen -og CHR22_sampledata.bgen

bgenix  -clobber -g CHR22_sampledata.bgen -index

```

qctool (version: 2.0.8, revision )
bgenix (version: 1.1.7, revision )

Platform details:
`$ uname -a`
`Linux hgrcgridlogin01 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux`

**Comment by privefl** [comment]
Thanks, that is very useful.

OK, I see at https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/genotype_file_formats.html that the default is to use 16 bits per probability, whereas I require to have only 8 bits per probability (cf. documentation).
Could you try adding `-bgen-bits 8` in the qctool command and tell me if it is now read appropriately?

**Comment by sariya** [comment]
If I run with specified output format (earlier I have been using bgen) dosage from bigsnpr::snp_readBGEN is still unconvincing to me. Now format as v1.2

`qctool -g test.gen -s sample_qctool.sample -assume-chromosome  22 -ofiletype bgen_v1.2 -og CHR22_sampledata.bgen`
Thank you

**Comment by sariya** [comment]
> Thanks, that is very useful.
> 
> OK, I see at https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/genotype_file_formats.html that the default is to use 16 bits per probability, whereas I require to have only 8 bits per probability (cf. documentation).
> Could you try adding `-bgen-bits 8` in the qctool command and tell me if it is now read appropriately?

Good lord this worked
`
qctool -g test.gen -s sample_qctool.sample -assume-chromosome  22 -ofiletype bgen_v1.2 -bgen-bits 8  -og CHR22_sampledata.bgen

`
The data now match for the dosage values per SNP per person.

**Comment by sariya** [comment]
In essence LD-Pred needs `dosage` values in the `genotype` of the **effect** allele. Am I understanding this correctly? 

https://choishingwan.github.io/PRS-Tutorial/ldpred/

**Comment by privefl** [comment]
I'm not sure I follow your comment on "needs `dosage` values in the `genotype` of the effect allele"?
LDpred2 does not need really dosage values, but most functions in the package don't handle missing values, so it is easier to work with imputed dosages.

PS: please use proper names "bigsnpr" and "LDpred".

**Comment by sariya** [comment]
Sorry for my poor scientific terminology.  

- Initially, with my data the LD-PRED2 pipeline with plink (`.bim/.fam/.bed`) formatted input files couldn't calculate h2, most likely I attribute it to the missing values. The plink files were generated after converting imputed data from IMPUTE2 s/w.  8 chromosomes failed due to the error related to h2. `Error: 'h2' should have only positive values.`

- That led me to explore other options that is why I am attempting to read/load imputed data which are shaped in the .bgen format (.bgil) files which is most widely supported and used by the UK Bio bank. In the issue here we discussed through various steps from loading, conversion (.bgi, bgen, qctools) and such. 

- I was running through errors and discrepancy in the dosage values calculated by the `bigsnpr::snp_readBGEN` function upon loading the bgen file, which were compared against in-house imputed dosage values calculated using `awk -v s=10 '{ printf $2 "," $4 "," $5; for(i=1; i<=s; i++) printf "," $(i*3+5)*2+$(i*3+4); printf "\n"}' impute2_file.txt` 

- In the LD-pred2 [pipeline](https://choishingwan.github.io/PRS-Tutorial/ldpred/#running-prs-analysis) it requires genotypes `genotype <- obj.bigSNP$genotypes` 
Here I'm plan to use the in-house imputed dosage values right off the bat to proceed to avoid all the bgen conversion. I'll calculate the imputed dosage values for the `effect` allele.
 
> I'm not sure I follow your comment on "needs dosage values in the genotype of the effect allele"?

Hence, I was confirming if I can pass dosage directly instead of tedious data conversion and transformation process of bgen and such.
Again sorry for a lengthy reply, confusing and poor phrasing.~
