### ISSUE TITLE
bigsnpr: memory errors

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#142]
I'm provided north of 100Gb where genotyped (dosage from imputed files) data were for 500 individuals. 

```
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535
Calls: snp_cor ... validObject -> anyStrings -> isTRUE -> validityMethod

```
Besides this I also run into error:

```
Error in asMethod(object) :
  Cholmod error 'out of memory' at file ../Core/cholmod_memory.c, line 147
Calls: snp_cor -> <Anonymous> -> as -> asMethod
```
I'm calculating SNP correlation for the LDpred-2 pipeline `    ldsc <- snp_ldsc2(corr0, df_beta)`

**Comment by privefl** [comment]
This issue has been reported already in other issues, e.g. #89 and #130.
Have you looked at them?

**Comment by sariya** [comment]
I looked at them before opening new issue. Sadly there were less helpful. Thank you.

**Comment by Qiaolan** [comment]
> I looked at them before opening new issue. Sadly there were less helpful. Thank you.

Sorry to reopen this. Hi @sariya, I had the same issue. Could you please tell me if you solved it at the end? Thank you!

**Comment by sariya** [comment]
@Qiaolan - hi, I was unable to get through this. I abandoned it due to memory and several other issues (format conversion and such).

**Comment by Qiaolan** [comment]
> @Qiaolan - hi, I was unable to get through this. I abandoned it due to memory and several other issues (format conversion and such).

Thank you!
