### ISSUE TITLE
How to perform threshold

### ISSUE THREAD

**Issue by biostat0903** [privefl/bigsnpr#143]
Hi, 
I would like to use the `bigsnpr` to do clumping and threshold, but not to do prediction. The function `snp_cluping` only clumps the genotype data. Could you tell me how can I do P threshold? Or use the `snp_subset` to select some snps? Thanks!

Best, 
Sheng

**Comment by privefl** [comment]
When you say "not to do prediction", you mean just outputting the indices of the remaining variants?

It is fairly easy to do this yourself.
Imagine you have the vector `pval` of p-values corresponding to all variants in `G`, and `ind.keep` is the indices you get from `snp_clumping(G, ...)`, then you can do:
```r
ind.keep[pval[ind.keep] < thr]
```
