### ISSUE TITLE
question: LDpred - difference between different models and LD clumping 

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#144]
hi privefl,

Sorry if this has been asked somewhere. I'm reading more tutorial with PRS and bigsnpr that left me few questions and some confusions.
There are few [models ](https://privefl.github.io/bigsnpr/articles/LDpred2.html)used: infinitesimal, grid, auto. In addition to these there are approaches that perform clumping and threshold (C+T) https://privefl.github.io/bigsnpr/articles/SCT.html

This makes me wonder when to use what (infinitesimal or clumping)  and why (infinitesimal v/s clumping) ? 
Thanks much for your exhaustive support.~ :)

**Comment by privefl** [comment]
This is a great question that is the topic of whole papers.

To answer you quickly, C+T and SCT seem to work best for traits that are not too polygenic, while LDpred2 (grid/auto) seems to work very well in most cases. The infinitesimal model works well only for very polygenic traits (or small sample sizes).

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
