### ISSUE TITLE
LDPred2 yields sensible betas but a confusing PRS. How do I double-check sample and SNP order in my genetic data?

### ISSUE THREAD

**Issue by cqgd** [privefl/bigsnpr#145]
Hi Florian,

Hope all is well. 

I have a strange issue where the beta's calculated by LDPred2 make sense, but they're not being applied to to the genetic data in such a way that my PRS correlates with true trait values, as it should.  I suspect either my samples or my loci are shuffled somewhere. 

When I extract the betas and use them with my UK Biobank bgens using [Plink 2's --score](https://www.cog-genomics.org/plink/2.0/score), all looks good.

I extract the betas as below, where `info_snp` comes from `snp_match()`:
```
multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est,
                               vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
                               ncores = NCORES)

beta_auto <- sapply(multi_auto, function(auto) auto$beta_est)

annotated_betas = cbind(data.table(info_snp)[,.(chr,pos,a0,a1,beta,markername,bgen_name)],
                        beta_auto)

fwrite(annotated_betas,"betas.csv")
```
Using these yields very good trait/PRS correlation, as expected.

If I use the same beta_auto's within LDPred2 to generate a final PRS, the PRS doesn't correlate with the trait:

```
multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est,
                               vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
                               ncores = NCORES)

beta_auto <- sapply(multi_auto, function(auto) auto$beta_est)

pred_auto <- big_prodMat(G, beta_auto, ind.col = ind.chr2)

```

The loci don't directly seem mixed up to me. If it helps, my ind.chr2 appears to simply run along G:

```
> dim(G)
[1] 263512  16160

> all(ind.chr2==1:ncol(G)) #no re-ordering in big_prodMat()
[1] TRUE

> as.data.table(info_snp)
       chr      pos a0 a1      markername  freq1    beta beta_se       p totalsamplesize  n_eff       bgen_name _NUM_ID_.ss _NUM_ID_
    1:  22 17057138  G  T 22:17057138:SNP 0.9476 -0.1195  0.1194 0.31670          214507 204942 22_17057138_T_G     3443466        1
    2:  22 17067504  G  T 22:17067504:SNP 0.6746  0.1044  0.0608 0.08569          228360 177553 22_17067504_T_G     3443469        2
    3:  22 17072483  A  G 22:17072483:SNP 0.0981  0.2224  0.0946 0.01871          250874 200655 22_17072483_A_G     3443475        3
    4:  22 17074622  A  C 22:17074622:SNP 0.0817  0.1926  0.0932 0.03880          287242 233753 22_17074622_A_C     3443480        4
    5:  22 17075353  C  A 22:17075353:SNP 0.8134  0.0923  0.0598 0.12280          276413 269760 22_17075353_A_C     3443481        5
   ---                                                                                                                              
16156:  22 51165664  G  A 22:51165664:SNP 0.3010 -0.0358  0.0510 0.48290          282004 266445 22_51165664_A_G     3540364    16156
16157:  22 51171497  G  A 22:51171497:SNP 0.1834 -0.0599  0.0702 0.39370          264747 204338 22_51171497_A_G     3540367    16157
16158:  22 51171693  G  A 22:51171693:SNP 0.2711  0.0138  0.0552 0.80250          267241 246898 22_51171693_A_G     3540369    16158
16159:  22 51175626  A  G 22:51175626:SNP 0.9383 -0.0232  0.0972 0.81110          280504 272854 22_51175626_A_G     3540374    16159
16160:  22 51178090  G  A 22:51178090:SNP 0.0558  0.0704  0.1048 0.50170          280502 263723 22_51178090_A_G     3540376    16160
> obj.bigSNP$map
# A tibble: 16,160 x 6
   chromosome marker.ID       rsid       physical.pos allele1 allele2
        <int> <chr>           <chr>             <int> <chr>   <chr>  
 1         22 rs5746647       rs5746647      17057138 G       T      
 2         22 22:17067504_G_T rs5747968      17067504 G       T      
 3         22 22:17072483_A_G rs2236639      17072483 A       G      
 4         22 22:17074622_A_C rs5746664      17074622 A       C      
 5         22 22:17075353_C_A rs5747999      17075353 C       A      
 6         22 22:17084609_A_G rs2070501      17084609 A       G      
 7         22 22:17087656_C_A rs11089263     17087656 C       A      
 8         22 22:17094749_A_C rs2096537      17094749 A       C      
 9         22 rs16984366      rs16984366     17096864 T       C      
10         22 22:17100497_C_T rs2154615      17100497 C       T      
# … with 16,150 more rows
```

The other problem I could imagine is re-ordering of the individuals. If I don't supply `ind.row` to `big_prodMat`, I suppose the ordering is just that of G, which I expect to be ordered following the indices I supplied to `snp_readBGEN`:

```
  rds_path <- bigsnpr::snp_readBGEN(
    bgenfiles = paste0("/gfs/archive/jostins/ukbb/v3/imputation/ukb_imp_chr",i,"_v3.bgen"),
    list_snp_id = list(snp_list),
    ind_row = E$index, #I would think this determines the order of G in the end
    backingfile = bk_file,
    bgi_dir = "/gfs/archive/jostins/ukbb/v3/imputation/",
    ncores = NCORES
  )
```
In the above `E` also holds true trait values, so I should just be able to `cbind()` my PRS `pred_auto` and `E` to compare these, I had thought. Alas...

Any debugging tips would be much appreciated. Please do let me know if more code is helpful -- I have kept the snippets above brief for clarity.

Thanks in advance,

Chris

**Comment by privefl** [comment]
Hum, I think you've already investigated the most probable causes.
Are you sure the indices in `E` matches the phenotypes in `E`?

Could you be more precise for two things:
- what do you mean by "the betas calculated by LDpred2 make sense"?
- how bad are the prediction using `big_prodMat()` compared to using PLINK to get the scores?

**Comment by cqgd** [comment]
Thanks Florian,

I think I've identified the culprit: it's the eid and bgen row index map. 

To answer your question, by "the betas make sense", I mean that they generate a valid PRS in conjunction with genetic data interpreted by Plink, a PRS that correlates well with true trait values (Pearson's R of 0.19, instead of <<0.01).

The reason why using Plink worked in this scenario, and equally why extracting data with qctool and doing the matrix multiplication between the betas and genetic data in R worked (i.e. lead to a predictive PRS), is that both these tools work based off of FID and IID, equivalent to UK Biobank eids, to extract data on specifici individuals. Users don't generate a map between row indices and FID/IID, as needed for LDpred2.

The fact that you're working with raw indices means it's crucial to remove the first row from the UK Biobank sample file (FID 0, IID 0) before generating a map, it seems.

My original implementation was:

```
E = fread("resource/group_eids.csv")

link_path = c("links/ukb1062_imp_chr1_v2_s12345.sample")
link = fread(link_path)

E[,index:=match(E$eid,link$ID_1)]
fwrite(E,"resource/group_eids_index.csv")
```

Instead, I believe the indices should be generated as follows:

```
E[,index.skip.row:=match(E$eid,link[-1,ID_1])]
```

While I don't immediately spot it in the [main tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html), I am 100% sure you show this correctly somewhere. Nonetheless, this type of user error may be preventable by extracting data by FID/IIDs. Added benefit would be that you could use a single file to define samples between LDPred2, qctool and Plink then. 

I'm re-running at the moment, and will confirm if re-generating the map worked!

Thanks again for your help.

Chris

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
