### ISSUE TITLE
Error in calculating LD

### ISSUE THREAD

**Issue by Qiaolan** [privefl/bigsnpr#146]
Hi!

I got the error below when it was calculating LD. I try to figure it out, but I can't even tell what the error message means. My R code:

`corr0 <- snp_cor( genotype, ind.col = ind.chr, ncores = NCORES, infos.pos = POS2[ind.chr], size = 3 / 1000 ) corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))`

I am sure that the error below came from the code above by debugging:

`Error in validityMethod(as(object, superClass)) : long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522 Calls: snp_cor ... validObject -> anyStrings -> isTRUE -> validityMethod Execution halted`

After I filtered the genotye by plink (--geno 0), the error disappeared but I got "'h2' should have only positive values". Does this mean that I have too many missing values in my genotype? But I ran `snp_fastImpute()` before calculating LD.

Thanks for your help!

best,

Qiaolan

**Comment by privefl** [comment]
The first error has been reported in other issues here, please have a look at them. It seems that you are not using HapMap3 variants as recommended?

The second error means that the heritability estimate that you input to LDpred2 is negative.

**Comment by Qiaolan** [comment]
> The first error has been reported in other issues here, please have a look at them. It seems that you are not using HapMap3 variants as recommended?
> 
> The second error means that the heritability estimate that you input to LDpred2 is negative.

Sorry, I am not very familiar with HapMap3 (I am from stats). What do you mean by HapMap3 variants? What I got were plink binary files.

Thanks!

**Comment by privefl** [comment]
At the end of the tutorial.

**Comment by Qiaolan** [comment]
> Also note that I've just released some precomputed LD reference here: https://doi.org/10.6084/m9.figshare.13034123.

Hi Florian! Thanks for your patience. I've read through #130 and it seems that the user still didn't solve the error about "long vector" at the end. Could you please tell me the possible reason for this error?

Thanks!

Qiaolan

**Comment by privefl** [comment]
You're using too many variants, which causes to produce too many non-zero pairwise correlations.

You can try to use `as_SFBM(corr0)` directly (if you have the newest version), but you should really consider using HapMap3 variants, as recommended.

**Comment by Qiaolan** [comment]
> You're using too many variants, which causes to produce too many non-zero pairwise correlations.
> 
> You can try to use `as_SFBM(corr0)` directly (if you have the newest version), but you should really consider using HapMap3 variants, as recommended.

Hi Florian,

Thanks for your reply. It looks like the error occurs at `snp_cor()` not `bigsparser::as_SFBM(as(corr0, "dgCMatrix"))`. I updated bigsnpr and replaced it with `as_SFBM(corr0)`. But the error still appeared.

But thanks for your information. Now I have a better understanding of this error. Because when I tried the code in a smaller chromosome, it worked fine. Thus, I'd better consider using HapMap3 variants instead of current large set of variants (I have 10 million snps).

Thanks!

best,

Qiaolan

**Comment by privefl** [comment]
You're welcome.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.

**Comment by Qiaolan** [comment]
> Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.



> You're welcome.

Hi Florian! I have a question about Hapmap3. Currently, we have lots of variants (10 million), but Hapmap3 has only 1 million snps. Using Hapmap3 will remove lots of snps and information. Is it possible to use LDpred2 with a large number of snps in the target sample?

Thanks!

best,

Qiaolan

**Comment by privefl** [comment]
The problem is that running time and memory requirements are quadratic with the number of variants.
And there is no evidence that using more variants would improve predictive performance.
If you have very high performance computers, you can always try.
You might also encounter some issue of having "long vector not supported".

**Comment by Qiaolan** [comment]
> The problem is that running time and memory requirements are quadratic with the number of variants.
> And there is no evidence that using more variants would improve predictive performance.
> If you have very high performance computers, you can always try.
> You might also encounter some issue of having "long vector not supported".

Hi Florian. There might be a typo in your new genome-wide analysis code (https://github.com/privefl/paper-ldpred2/blob/master/code/run-ldpred2-gwide.R#L39-L64). It seems that `line 49` should be related to genotype file instead of summary statistics. Correct me if I'm wrong.

best,

Qiaolan

**Comment by privefl** [comment]
I am not sure I follow? You would replace what by what?

I don't think there is any typo as this was used to produce the (good) results of the paper.

**Comment by bbitarello** [comment]
@Qiaolan  I believe you should filter the variants to include only those present in the summary statistics file since LD information beyond that won't be used downstream?

**Comment by bbitarello** [comment]
Florian, regarding the LD info you provided in figshare scripts, is it in hg19? Do you have them in hg38 by any chance?

**Comment by privefl** [comment]
This comes from UKBB data, but I don't remember.
I think I provide positions in other builds as well (in the map.rds file)
(see https://github.com/privefl/paper-ldpred2/blob/master/code/provide-ld-ref.R#L57-L62)

Please tell me if I messed up the names of the builds.
I have absolutely no time to look at this this week, I'm sorry, too many things are adding up.

**Comment by bbitarello** [comment]
So, apparently, [your map.rds](https://figshare.com/articles/dataset/European_LD_reference/13034123?file=24928055) contains hg16 as the 'POS' (probably because of hapmap in previous steps). Then you provide hg17 and hg19 in that object. I think it would be good to add hg38 perhaps. Thanks!

**Comment by privefl** [comment]
If you have linux or Mac, you can use liftover as shown in the code to do that.

**Comment by bbitarello** [comment]
Yeah, I will. Also, I am not sure that the original build is hg17. Your code says it's hg18 so maybe that's correct?

**Comment by privefl** [comment]
@bbitarello I have checked and seems I have messed up the builds. It seems UKBB is using hg19 (therefore what is in `$pos`). I have now updated the `map.rds` file adding hg17, hg18 and hg38.

Thanks for bringing up this issue!

**Comment by AlisaBIG** [comment]
Hi, @Qiaolan . I also encountered the same error as you did : ' h2' should have only positive values. Did you solved your problem in the end? Thanks in advanced if you could reply me your solution. 
And also  sorry to put forward this silly questions, @privefl  I failed to find out what mistakes caused this problem.
