### ISSUE TITLE
big_prodVec() returns NAs

### ISSUE THREAD

**Issue by Qiaolan** [privefl/bigsnpr#147]
Hi Florian,

After I run `pred_inf <- big_prodVec(G, beta_inf[ind.chr], ind.row = ind.test, ind.col = ind.chr)`, I find that `pred_inf` are all NAs.

I impute G by `snp_fastImputeSimple(obj.bigSNP$genotypes,method = "random")`, then check NAs by `big_counts()` and there is no NA in G.

Also, `beta_inf` has non-zero values.

The information about G is below:

`str(G)`

`Reference class 'FBM.code256' [package "bigstatsr"] with 15 fields
 $ extptr      :<externalptr> 
 $ extptr_rw   :<externalptr> 
 $ nrow        : int 2079
 $ ncol        : int 1117280
 $ type        : Named int 1
  ..- attr(*, "names")= chr "unsigned char"
 $ backingfile : chr "/fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/LDpred2/geno/rs_file/upitt/target_geno_hapmap3_upitt.bk"
 $ is_read_only: logi FALSE
 $ address     :<externalptr> 
 $ address_rw  :<externalptr> 
 $ bk          : chr "/fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/LDpred2/geno/rs_file/upitt/target_geno_hapmap3_upitt.bk"
 $ rds         : chr "/fs/ess/PAS1501/gaolab/qldeng/AD_Eden_PRS/LDpred2/geno/rs_file/upitt/target_geno_hapmap3_upitt.rds"
 $ is_saved    : logi TRUE
 $ type_chr    : chr "unsigned char"
 $ type_size   : int 1
 $ code256     : num [1:256] 0 1 2 NA 0 1 2 NA NA NA ...
 and 26 methods, of which 12 are  possibly relevant:
   add_columns, as.FBM, bm, bm.desc, check_dimensions, check_write_permissions,
   copy#envRefClass, initialize, initialize#FBM, save, show#envRefClass, show#FBM`

Thanks for your help!

Qiaolan

**Comment by Qiaolan** [comment]
I solve this by correctly match the index of beta coefficients and the index of snps.

**Comment by bbitarello** [comment]
Hi Qiaolan, can you explain how you correctly matched them? I'm having the same issue. Thanks!

**Comment by Qiaolan** [comment]
> Hi Qiaolan, can you explain how you correctly matched them? I'm having the same issue. Thanks!

Hi, you can check if beta_inf[ind.chr] and ind.chr match in length first.

**Comment by Janina24** [comment]
If they have the same length, what else could be the problem?
