### ISSUE TITLE
Map error when using big_prodVec()

### ISSUE THREAD

**Issue by Sabor117** [privefl/bigsnpr#148]
Having an occasional issue when running big_predVec() as part of LDpred2.

Essentially it returns the following error:

```
Error in getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type) : 
  Error when mapping file:
  No such file or directory.
Calls: big_prodVec ... [ -> [ -> extract_vector -> <Anonymous> -> getXPtrFBM
```

I think I saw a similar issue somewhere else that suggested that the issue could be in the creation of the tempfile used by snp_readBGEN(). Is this the case?

If it is the case, does the method by which you create the temp file make any difference? To clarify, I have previously done the following for this:
```
temp_file = tempfile()
snp_readBGEN(cohort_chr_bgen, # BGEN file location
			backingfile = temp_file, # tempfile()
			list_snp_id = snp_list) # bigsnpr SNP-list
```
But have subsequently also tried:
```
temp_file = tempfile(tmpdir = /specific/directory/chosen/)
```
and:
```
temp_file = tempfile(paste0(gene_name), tmpdir = /specific/directory/chosen/)
```
Do you know if doing these latter methods would make any difference?

**Comment by privefl** [comment]
If the latter is not the temp dir then it won't get removed unless you do it yourself.

**Comment by Sabor117** [comment]
> If the latter is not the temp dir then it won't get removed unless you do it yourself.

This was something I had taken into account and was doing myself, yes. But that would happen after having run big_prodVec().

Or are you saying that the temp file should be removed prior to that?

**Comment by privefl** [comment]
I don't know why the temp file get removed. But this happens with temp files. Try not to use them. It there as default for convenience only.

**Comment by Sabor117** [comment]
Sorry, I'm a tad uncertain what you mean by this now. Two points:

1. Does this mean that the above error is definitely caused by the temp file? And it would be potentially fixed by just using ```temp_file = tempfile()```?

2. You say that this is there as a default (and it is in your tutorial as well), but what is the alternative? If the ```backingfile``` argument is left blank, will the function still work? Or does it need some kind of file, but it doesn't necessarily need to be a tempfile? For example, creating some kind of Rdata file or something?

**Comment by privefl** [comment]
1. I'm not sure this would be enough.

2. The alternative is to write the file outside of the temp directory. I usually write these in "data" folder (if I want to keep it) or in "tmp-data" (if I don't care about keeping it). I actually have updated the LDpred2 tutorial to use `tmp <- tempfile(tmpdir = "tmp-data")` some time ago. You need to do the cleaning of the "tmp-data" folder yourself.

**Comment by Sabor117** [comment]
Hmm... So it is likely to do with the tempfile being deleted then that is causing the error.

Okay, I will continue to use the: ```temp_file = tempfile(tmpdir = "/specific/directory/chosen/")``` version of the code I was using before and hope for the best.

Thanks Florian.
