### ISSUE TITLE
How many variants/SNPs should we use in LDpred2?

### ISSUE THREAD

**Issue by Qiaolan** [privefl/bigsnpr#149]
Hi Florian,

Thanks for your time.

As mentioned, Hapmap3 variants are strongly recommended in LDpred2. Even if I have 10 million snps in the target sample, it will be cut down to about 1.5 million snps according to Hapmap3. It seems that both LDpred and LDpred2 claimed that more SNPs will not improve prediction accuracy. Does the paper of LDpred2 explicitly explain the reason (maybe I missed it)? I feel like removing millions of variants may lose much information.

As a result, when we collect the genotype of target sample, we only need to collect Hapmap3 variants and ignore the rest of variants? What if the variants of interest are not in Hapmap3?

Thank you!

best,

Qiaolan

**Comment by privefl** [comment]
HapMap3 variants have undertaken some quality control, are usually well imputed and offer a good coverage of the genome.

More work is needed to see if another set of variants could be used instead, but anything that I've tried so far ended up being worse than using HM3.

Also, the more variants you have, the more time and memory will be required, and the more chance you have that the Gibbs sampler can go crazy.

**Comment by Qiaolan** [comment]
> HapMap3 variants have undertaken some quality control, are usually well imputed and offer a good coverage of the genome.
> 
> More work is needed to see if another set of variants could be used instead, but anything that I've tried so far ended up being worse than using HM3.
> 
> Also, the more variants you have, the more time and memory will be required, and the more chance you have that the Gibbs sampler can go crazy.

Understand. I find that many published papers using LDpred followed Hapmap3 variants.

**Comment by privefl** [comment]
These variants are also used in PRS-CS and SBayesR. In the latter, I think they show that you don't gain anything by using more variants.
Until someone find a better set, I'll keep recommending HM3.
