### ISSUE TITLE
LDpred2 adjusts for covariates

### ISSUE THREAD

**Issue by Qiaolan** [privefl/bigsnpr#150]
Hi Florian,

Thanks for your time.

I am wondering how LDpred2 adjusts for covarites. When estimate betas, in `beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)`, there's no argument for covariates and I guess only `df_beta` from summary statistics contains estimated beta adjusting for covariates.

Moreover, when check prediction accuracy, is there a way to adjust for covariates? For continuous phenotypes, I applied `pheno ~ prs + covariates` to see R^2. But for binary phenotypes, is there a proper to add covariates in `AUCBoot()` function?

Thank you!

best,

Qiaolan

**Comment by privefl** [comment]
IIRC, no summary statistics based method is able to adjust for covariates.
Usually, covariates are used in the GWAS to make the summary statistics, and in the final evaluation of the model as you mentioned.
In the LDpred2 tutorial, you can also use covariates when computing the Z-Scores of each model to pick the best parameters for LDpred2-grid.

I don't think there is a way to adjust for covariates in the AUC. Alternatively, you can report the Z-Score in a glm() model or compute some pseudo-R as done in many studies.

**Comment by Qiaolan** [comment]
> IIRC, no summary statistics based method is able to adjust for covariates.
> Usually, covariates are used in the GWAS to make the summary statistics, and in the final evaluation of the model as you mentioned.
> In the LDpred2 tutorial, you can also use covariates when computing the Z-Scores of each model to pick the best parameters for LDpred2-grid.
> 
> I don't think there is a way to adjust for covariates in the AUC. Alternatively, you can report the Z-Score in a glm() model or compute some pseudo-R as done in many studies.

Thanks for your reply!

Therefore, is the AUC from `AUCBoot()` only based on prs? 

Also, to use covariates when computing Z-score, the tutorial just mentioned `It also enables adjusting for covariates in this step.`

`pred_grid <- big_prodMat(G, beta_grid, ind.col = ind.chr2)`
`params$score <- big_univLogReg(as_FBM(pred_grid[ind.val, ]), y[ind.val])$score`

I intend to add a matrix of covariates in the `big_univLogReg()` function. Is this the correct way?

Thanks!

best,

Qiaolan

**Comment by privefl** [comment]
The AUC is computed from whatever score and binary phenotype you provide. You can't really provide any more variables.

Yes, this is the correct way to add covariates (I think via the `covar.train` parameter).
