### ISSUE TITLE
Adding other columns to snp_match.

### ISSUE THREAD

**Issue by swvanderlaan** [privefl/bigsnpr#151]
Hi,

I was just using snp_match and wanted also the allele frequency and Z to be flipped. I added this manually. 

It would be nice to include this (perhaps as optional columns) to the function. 

Thanks

Sander

**Comment by privefl** [comment]
Thanks for the suggestion.

You're talking about the direction of the effect that is reversed, not the alleles that are flipped, right?

Are you thinking about something like:
"If columns 'freq' and 'Z' are also provided, their direction is also reversed when needed"?
The thing is that I'm not using these columns for anything in the package currently. 
And what if other variables are also required?

Alternatively, I could try to have a dplyr-like way of specifying which column to modify and what modification to apply to them.

How were you thinking this could be implemented?

**Comment by swvanderlaan** [comment]
> Are you thinking about something like:
> "If columns 'freq' and 'Z' are also provided, their direction is also reversed when needed"?

Yes, exactly like this ... Of course optionally, where Z and/or beta could be given. I know that you are not use it perse, But I was using

**Comment by swvanderlaan** [comment]
Again, great packages!

**Comment by privefl** [comment]
I could have a parameter to specify if the user wants to keep internal variables "\_FLIP\_" and "\_REV\_".
Then, the user could do the transformations you talk about.
Would it be okay to you?

**Comment by swvanderlaan** [comment]
That would be great. I noticed this issue was reopened and closed again. Did you add this feature?

**Comment by privefl** [comment]
No, I don't remember doing it. Don't know why I closed this. 

Do you want the flip and rev variables?
I can do it next week. Or someone could do a PR. This should not be hard to implement.

**Comment by swvanderlaan** [comment]
That would be great if this is added. And yes, flipping and reversing variables would be needed indeed.

**Comment by privefl** [comment]
This is now implemented in the latest GitHub version (see you param `return_flip_and_rev`).
