### ISSUE TITLE
Make use of allele frequency

### ISSUE THREAD

**Issue by swvanderlaan** [privefl/bigsnpr#152]
Hi,

The snp_match function ignores ATCG variants, which is pragmatic. It also is assuming that the data are derived from the same population and therefore allele frequencies are similar.  

I propose to add a check on allele frequency.

- Check for ATCG variants whether they are sufficiently different, e.g. +/- 0.15, and flip these. Else discard them. 
- Check for any variant whether the difference between the reference (info_snp) and the summary statistics (sumstats) is sufficiently small, for instance no more than 0.15. If it is more, than these variants should be discarded - or at least be flagged. 

Thanks

**Comment by privefl** [comment]
Thanks for the suggestion.

What do you mean by "ignores ATCG variants"?

For reversing the effect when frequencies are different, I don't this is good practice. 
You should probably just discard them. 
Or maybe you're talking specifically about strand-ambiguous variants?

For the quality control, this is something that can be performed after the matching, right? 
Why would it be needed to do this in the `snp_match()` function? 
I'm just trying to keep functions as simple as possible.

**Comment by swvanderlaan** [comment]
Some clarification. 

Suppose it's an A > T (or C > G) variant, with a frequency of say, 0.48. And the reference has T > A with a frequency of 0.48. It will be difficult to tell whether it's simply noting the variant as T > A instead of A > T or whether there is a difference in the frequency.

**Comment by swvanderlaan** [comment]
Other than that: great package!

**Comment by privefl** [comment]
Thanks for the suggestions.

Just to be clear, what would you like me to do about this?
