### ISSUE TITLE
snp_ldpred2_auto needs ssh?

### ISSUE THREAD

**Issue by Raketuv** [privefl/bigsnpr#154]
Hi, I encountered the following:
```
multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est, vec_p_init = seq_log(1e-4, 0.9, 30), ncores = NCORES)
sh: 1: ssh: not found
```
Seems like when using parallelism, this function requires ssh. This is easy to fix, however, I still wonder why this is needed here

**Comment by privefl** [comment]
Try if you can do
```r
library(parallel)
cl <- makeCluster(1)
clusterEvalQ(cl, 1)
```

**Comment by Raketuv** [comment]
Thanks for the quick reply.
```
> library(parallel)
> cl <- makeCluster(1)
> clusterEvalQ(cl, 1)
[[1]]
[1] 1
```
That's what I get.

**Comment by privefl** [comment]
Great.
Try this next:
```r
library(doParallel)
registerDoParallel(cl <- makeCluster(2))
foreach(i = 1:10, .combine = 'c') %dopar% { sqrt(i) }
```

**Comment by Raketuv** [comment]
```> registerDoParallel(cl <- makeCluster(2))
> foreach(i = 1:10, .combine = 'c') %dopar% { sqrt(i) }
 [1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278```

**Comment by privefl** [comment]
Then, I have no idea what is going on.
The code is not much different than this foreach loop (see https://github.com/privefl/bigsnpr/blob/master/R/LDpred2.R#L144-L179).

**Comment by Raketuv** [comment]
Thank you for your time. I will update if a solution comes up

**Comment by privefl** [comment]
Any update on this?

**Comment by privefl** [comment]
Closing for now. Feel free to reopen.

**Comment by Raketuv** [comment]
Fyi: this weird behaviour occurred when the function was mounted into a src folder on a docker image, and sourced in R from this folder. Once I moved the code from the function back into a directly executed heredoc in the container, it worked again.
Merry Christmas to France!
