### ISSUE TITLE
Selection of 'best PRS model' and its validation (testing) in another dataset

### ISSUE THREAD

**Issue by XcodeBio** [privefl/bigsnpr#155]
Hi Florian,

Thank you for the wonderful PRS package and the tutorial. I am trying to understand the tutorial (https://privefl.github.io/bigsnpr/articles/LDpred2.html) and have some question regarding PRS construction and validation (testing). Apologies if this has already been asked here. I am fairly new to PRS analysis and would truly appreciate your help.

Imagine that the phenotype of interest is a continuous trait, and I am following the sequence below for PRS construction and best model selection-

snp_ldpred2{model} -> obtaining beta_{model}-> compute PRS -> linear regression -> pick the best model based on the phenotypic variance explained by the PRS.

Imagine phenotypic variance explained by each models looks like this -

A. Infinitesimal = 0.0100
B. Grid Model = 0.00180
C. Auto Model = 0.171 

My questions are -

1. Because Auto model explains the highest phenotypic variance here, based on this would you say that Auto model is the 'best model'?

2. Let us just assume that the Auto model is the 'best model', how would you use parameters from Auto Model to perform validation (validation=testing in your tutorial) in another data set? Do you extract the number of snps used in Auto Model and then perfom validation in another set using these SNPs? How is the prediction part done? Do you have any tips?

3. How can I use the p and h2 parameters (from Grid model) for validation (testing)? 

 
Thank you for your time and help!

**Comment by privefl** [comment]
1. Your numbers look very weird. I guess the prediction for at least one grid model should be very close to the auto model.

2. Usually, "validation" refers to choosing the best-performing model, while "testing" refers to evaluating the accuracy of this final model chosen. The final model is nothing but the LDpred2 betas (effects) because then you can compute prediction by simply multiplying the genotypes/dosages G by the effects beta.

3. Not sure I understand the question, sorry.

**Comment by XcodeBio** [comment]
Hi Florian,

Thank you for the reply. 

1. The numbers are from a PRS tutorial (simulated dataset based on the 1000 Genomes (https://choishingwan.github.io/PRS-Tutorial/ldpred/). 

2. Imagine my 'best-performing model' is Infinitesimal model from "validation" stage. So the betas (effects) would be 
beta_inf <- snp_ldpred2_inf(corr, df_beta, h2 = h2_est). Is this right? I can then use beta_inf for out-of-sample prediction ("testing") using pred_inf <- big_prodVec(G, beta_inf, ind.row = {testing sample}, ind.col = ind.chr2)? Did I get it right?

3. Sorry, I could not frame the question properly. 

Thank you again for your help.

**Comment by privefl** [comment]
2. Yes

3. You can try to say it otherwise. It might be me being tired.

**Comment by XcodeBio** [comment]
Hi Florian,

Thank you very much for your help.

Cheers
