### ISSUE TITLE
Create bigSNP object from plink files for each chromosome

### ISSUE THREAD

**Issue by jialiwang1211** [privefl/bigsnpr#159]
Hi Florian,

My plink files are organized for each chromosome separately.  I can see you nicely provided an example for reading bgen files ([here](https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-genotypes.R#L1-L62)), but what would be the command to read the plink files and write to a bigSNP rds file?

I've tried 

rds <- bigsnpr::snp_readBed(
  bedfile   = glue::glue("chr{chr}.bed", chr = 1:22),
  backingfile = "UKBB_imp"
)

but it gives me the following error message:

Error in readbina(bedfile, bigGeno, getCode()) : 
  Expecting a single string value: [type=character; extent=22].
In addition: Warning messages:
1: In if (!grepl(pattern, path)) stop2("Path '%s' must have 'bed' extension.",  :
  the condition has length > 1 and only the first element will be used
2: In if (!grepl(pattern, path)) stop2("Path '%s' must have 'bed' extension.",  :
  the condition has length > 1 and only the first element will be used

Thanks for your kind help!

**Comment by privefl** [comment]
I do not provide an option to read multiple bed files at once, sorry.
What I usually do in this situation is combining PLINK files first and then read the combined file.
You can see some example code for the UK Biobank at https://github.com/privefl/paper4-bedpca/blob/master/code/download-UKBB.R#L12-L26.

**Comment by jialiwang1211** [comment]
Thanks for your example!

Is there a quick way to deal with the duplicated SNP id using bigsnpr? See the error message below. 

Warning: First fileset to be merged contains duplicate variant ID(s).  Variants
with matching IDs are all merged together; if this is not what you want (e.g.
you have a bunch of novel variants, all with ID "."), assign distinct IDs to
them (with e.g. --set-missing-var-ids) before rerunning this merge.
Error: 9778 variants with 3+ alleles present.
* If you believe this is due to strand inconsistency, try --flip with
  merged-merge.missnp.
  (Warning: if this seems to work, strand errors involving SNPs with A/T or C/G
  alleles probably remain in your data.  If LD between nearby SNPs is high,
  --flip-scan should detect them.)
* If you are dealing with genuine multiallelic variants, we recommend exporting
  that subset of the data to VCF (via e.g. '--recode vcf'), merging with
  another tool/script, and then importing the result; PLINK is not yet suited
  to handling them.
See https://www.cog-genomics.org/plink/1.9/data#merge3 for more discussion.

**Comment by privefl** [comment]
This is a PLINK issue. Because of some multiallelic variants.
You should try one of the two options I guess mentioned.

**Comment by jialiwang1211** [comment]
I merged the set of plink files by removing duplicated rsid. Now I've got ~200k samples and 10 million SNPs in the merged file. How much memory do you think it is required to run LDpred2? 

I understand that it is recommended to use HAPMAP3 variants (~1.2 million SNPs), but would like to test on the whole set first.

**Comment by privefl** [comment]
It is not possible to run LDpred2 with 10M variants, sorry. Please see other issues discussing this.
