### ISSUE TITLE
snp_ldpred2_auto

### ISSUE THREAD

**Issue by DM087** [privefl/bigsnpr#161]
Hi Florian,

I get the error below when running the step 
`multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est, vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES), ncores = NCORES)`

Error in { : task 1 failed - "object '_bigsnpr_ldpred2_gibbs_auto' not found"
Calls: snp_ldpred2_auto -> %dopar% -> <Anonymous>

My code works fine when I run inf and grid models but the auto model throws an error. Any idea what is going wrong here?

Thank you!

**Comment by DM087** [comment]
Thank you for the prompt reply!

bigsnpr_1.5.2

**Comment by privefl** [comment]
This is the CRAN version, that is weird.
Have you some trouble using other packages with compiled code?
Are you able to do `install.packages("bigsnpr", type = "source")`?

**Comment by DM087** [comment]
Thank you!

Yes, I am able to do `install.packages("bigsnpr", type = "source")`

Do you think the issue is because of the CRAN version?

**Comment by privefl** [comment]
You can try the latest GitHub version but I have little hope.
I'm not sure what is going on. 
What is your R version?
Do you have the same problem when using `ncores = 1`?

**Comment by DM087** [comment]
R --version
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

I will try `ncores = 1 ` and let you know the outcome.

Would `debugonce(snp_ldpred2_auto)` be of any help?

Have a great weekend!

**Comment by privefl** [comment]
No I don't think it would be helpful.
It just don't find the C++ function here: https://github.com/privefl/bigsnpr/blob/9d94272b552dbcb9fa47f118d420ff6d2024e5eb/R/RcppExports.R#L69
Which `packageVersion("Rcpp")` do you have?

**Comment by DM087** [comment]
packageVersion("Rcpp")
[1] ‘1.0.5’

**Comment by privefl** [comment]
Do you have a Mac with the latest version?

**Comment by DM087** [comment]
I am running the job on hpc cluster.

I do have a Mac but not with the latest version though! using mac high sierra 10.13. 

Thank you!

**Comment by DM087** [comment]
UPDATE

Hi Florian,

`ncores=1` in the code below works fine

```
multi_auto <- snp_ldpred2_auto(
   corr,
    df_beta,
    h2_init = h2_est,
    vec_p_init = seq_log(1e-4, 0.9, length.out = 4),
    ncores = 1
)

```

**Comment by privefl** [comment]
I guess there is something weird about the installation.
Can you try to clone the repo on your cluster, and use `devtools::document()` and `devtools::install()` within this repo?

**Comment by DM087** [comment]
I will try it.

Thank you!

**Comment by DM087** [comment]
Hi Florian,

Works fine when I use` devtools::install()` after repo clone. 

Thank you!

**Comment by privefl** [comment]
Good to hear.

Would be useful to know how you installed it before.

**Comment by DM087** [comment]
Can't remember exactly. I think I tried `install.packages()` before but did not log the installation.

Thank you again for this wonderful package!

**Comment by chrisraynerr** [comment]
I was experiencing this exact same error with bigsnpr version 1.12.2, so I followed your suggestion to use devtools installation (version 1.12.9) and the error persists -- but only for some functions (snp_ldsc, snp_ldpred2_auto.. i think snp_fastImpute as well).

I saw one suggestion that the error occurs when the functions/objects required aren't exported to the different nodes. I don't know how to test this. 

This is how I'm calling the function:

```
multi_auto <-
  snp_ldpred2_auto(
    corr=corr,
    df_beta=df_beta2, # %>% filter(chr==22),
    h2_init=h2_est,
    vec_p_init=seq_log(from=1e-4, to=0.9, length.out=30),
    allow_jump_sign=F,
    shrink_corr=0.95 #,
    # ncores=NCORES ## PARALLELIZATION NOT WORKING FOR SOME REASON??
    )
```
It only works if I run without parallelising...

I have tried the Rscript with and without:

```
cl <- makeCluster(NCORES, type="PSOCK", outfile="")}
registerDoParallel(cl)
on.exit(parallel::stopCluster(cl), add = TRUE)
```

and with and without:

```
options(bigstatsr.check.parallel.blas = FALSE)
options(default.nproc.blas = NULL)
options(max.print=100)
```

this is my bash wrapper

```
#!/bin/bash
#SBATCH --job-name=LdPred2_Auto
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=8GB

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

source /cluster/bin/jobsetup
cd /cluster/projects/

module purge
module load R/4.2.0-foss-2021b
GwaSs=${1}
Rscript --vanilla LdPred2Auto.R -s ${GwaSs}

```

Any ideas?

Thanks in advance!

**Comment by privefl** [comment]
This should just be an installation issue.
Close all R sessions, restart R, reinstall {bigsnpr}, and the error should disappear.
