### ISSUE TITLE
genotype value from the snp_readBed2() function

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#163]
Dear Devs,

I load plink data from the sample provided with the bigsnpr library. I select SNPs I am interested and fetch genotypes that provides me a matrix. Values are {0, 1, 2}. I use following code to perform task aformentioned.

```
     (bedfile <- system.file("extdata", "example.bed", package = "bigsnpr"))

     # Reading the bedfile and storing the data in temporary directory
     rds <- snp_readBed2(bedfile, backingfile = tempfile(), ind.col=(c(1:4)))

     test <- snp_attach(rds)

     str(test)
     dim(G <- test$genotypes)
     G[1:8, 1:4]

```
Does the genotype value represent minor allele or major; allele1 or allele2 ?

Thank you,

**Comment by privefl** [comment]
I'm not sure; I don't recall what is the convention in PLINK.
I would guess it is the number of allele1, which is often the alternative allele.
You can compare the allele frequency for a few SNP with the ones reported on [dbSNP](https://www.ncbi.nlm.nih.gov/snp/) to be sure.

**Comment by sariya** [comment]
Thank you.
