### ISSUE TITLE
question: snp_readBed2() - how do I convert genotype to data.table? 

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#165]
Hi Dev,

I am interested to extract genotype information from the snp_readBed2 obtained outcome after reading plink files. However, I get error for coerce "FBM.code256".

```

file_plink<-"data_c22_b0_v1.bed"

plink_rds <- bigsnpr::snp_readBed2(file_plink,backingfile = tempfile(), ind.col=c(1:4000) ) ## get 4000 SNPs
     data_plink <- snp_attach(plink_rds) ## attached

plink_genotype_dt<-  data_plink$genotypes  ## extract genotype value

plink_genotype_dt <- as.data.table(plink_genotype_dt) ## error below

```

I get error as:

```
Error in as.data.frame.default(x, ...) :
  cannot coerce class 'structure("FBM.code256", package = "bigstatsr")' to a data.frame
```

Any clue how to keep data intact without breaching data integrity and information?

**Comment by privefl** [comment]
You have to go through matrix format first, by accessing a subset with standard matrix accessors or accessing the full data as a matrix using `plink_genotype_dt[]`.

**Comment by sariya** [comment]
thank you.
