### ISSUE TITLE
question: bigsnpr::snp_readBed2 || is it possible to provide list of SNP ids?

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#166]
hi developer,

Thank you for this library.

I was wondering if it is possible to load SNP based on the IDs? `bigsnpr::snp_readBed2` can take SNP index. But getting SNPs index from plink `.bim` file would force loading complete `.bim` file.

Thank you.

**Comment by privefl** [comment]
No, you need to use either `match()` (vectors) or `vctrs::vec_match()` (data frames with several columns).
The .bim info should be stored in the `$map` of the `bigSNP` object.

**Comment by sariya** [comment]
Thanks. 
But in order to use `$map` from `bigSNP` I will have to load complete data set (N=>200K), which is something I would like to avoid. 
I don't want to provide SNP index either but SNP ids.

**Comment by privefl** [comment]
Ah yes it was stupid of me.
Then you can just read the bim file before, e.g. with `bigreadr::fread2`.

**Comment by sariya** [comment]
If possible I would like to suggest this as an enhancement (in future). 
I will read bim file and to match for the task meanwhile. 

Similarly, instead of index for individuals, list/vector of ids would be great.

**Comment by sariya** [comment]
@privefl If there's a test/development branch I can try and learn with this that would be interesting and learning for me. I would definitely require guidance with it (parent library and such). I do not have exp with C/C++.

**Comment by privefl** [comment]
You can always fork the repo (you get your own copy of the repo that you can modify as you want, and then make a pull request).
There is no need for C++ bg for this one.

I've already thought about using IDs to subset but there are so many small issues.
E.g. how would you handle when there are some unmatched ones? some duplicated ones? Would you match on both family.ID and sample.ID or just sample.ID?
This is two lines of R code needed by the user if I let them do it as they want, and it keeps my code as simple as possible, this is why I chose not to implement it yet.
