### ISSUE TITLE
LDpred2 QC for linear regression and LD ref panel questions

### ISSUE THREAD

**Issue by mkelcb** [privefl/bigsnpr#168]
Thanks @privefl  for developing LDpred2! I have two questions:

1. I have a continuous trait, and I have been trying to follow the tutorial here:
https://figshare.com/articles/dataset/European_LD_reference/13034123?file=24927089
However, the following QC measures don't work (all SNPs will fail):
```
sd_ldref <- with(info_snp, sqrt(2 * af_UKBB * (1 - af_UKBB)))
sd_ss <- with(info_snp, 2 / sqrt(n_eff * beta_se^2))
is_bad <-  sd_ss < (0.5 * sd_ldref) | sd_ss > (sd_ldref + 0.1) | sd_ss < 0.1 | sd_ldref < 0.05
#is_bad will include all SNPs!
```

In the LDpred2 paper, you recommended to use a different formula for sd_ss for continuous traits (page 12 under "Quality control of summary statistics"), however, this was not spelled out exactly. This is how I interpreted it:
```
sd_y_est = median( sd_ldref * info_snp$beta_se * sqrt(info_snp$n_eff))
sd_ss = with(info_snp, sd_y_est / sqrt(n_eff * beta_se^2))
```
Is the above correct?

2. Can I re-use the same LD ref panel for the same individuals but different summary stats?
The use-case scenario are multi-trait analyses or simulations. For example, I have 1000 repeats of different phenotypes on the same genotype data, so in theory, I should be able to re-use the same LDref panel as that does not depend on the phenotype.

The problem is that the current workflow is:
**(1)** match sumstats to hapmap3
**(2)** perform QC on sumstats (loose a few SNPs)
**(3)** match QCd sumstats to LD ref panel
**(4)** run LDpred2

Step **(3)** takes several hours and requires some very large files to be written to disk to produce the sparse matrix of SNP correlations. Ideally, I would produce this matrix just once, and then re-use it for different traits. The problem is that in Step **(2)** I may loose a slightly different set of SNPs due to QC, so they will no longer match the LD ref panel exactly (I get an "Error: Incompatibility between dimensions." if I try). As the LD ref panel is an SFBM object, I could also not use array notation to subset it (I tried corr[!is_bad, !is_bad]), so there is no obvious way around this, other than recalculating the entire ref panel every time.

My question is: if there is a way to re-use the same LDref panel for different runs by somehow sub setting the full hapmap3 LD ref panel to the SNPs that I am actually using? 

If this is not possible yet, then you may consider adding this as a feature.
This would also have an advantage that since the full hapmap3 LDref panel is only ~4Mbs as an .rbs file, you could include this data in the LDpred2 R package. This would make adoption a lot easier, as 99% of people would only need hapmap3 anyway, they would not need to download the full 10GB data from figshare.

Thanks,
Martin

**Comment by privefl** [comment]
1. Yes, you need to estimate sd(y), which you can do with the median() formula or the min() formula (whichever fit best your data).

2. Yes you can use the same LD ref as long as it's still European data (it is what I do in the paper).
Does (3) really take a long time (it shoudn't); which part exactly? 

The way I recommend doing it is the way I do it in the paper, i.e. 
- compute the LD ref once for all HapMap3 variants (per chromosome in R format -> output of snp_cor()) and store the 22 matrices in RDS format (or use the ones provided in the paper).
- subset the correlation matrices in R and build the SFBM (should be fast in recent versions of package bigsparser).
- run LDpred2
- delete the SFBM

**Comment by mkelcb** [comment]
Thanks @privefl  for the quick reply!

1. Can you be please  little bit more specific? What do you mean by the 'min() formula'? I am unable to find anything in your paper that matches this. I tried to adopt your notation from your tutorial for my interpretation of what I thought you meant in the LDpred2 paper:

```
sd_y_est = median( sd_ldref * info_snp$beta_se * sqrt(info_snp$n_eff))
sd_ss = with(info_snp, sd_y_est / sqrt(n_eff * beta_se^2))
```

I would most appreciate if you had a look to see if this is correct? Others who are interested in applying LDpred2 to continuous traits may benefit from knowing this too.


2. Sorry, maybe I don't understand you, but it seems that you are suggesting to follow the same steps that I am already following, IE going through each LD_chr*.rds file, subsetting them to the post-QC SNPs and then combining the result into an SFBM?

The computational burden originates from this loop starting:
`for (chr in 1:22) {`

This takes ~2 hours, and it also produces a ~30GB file, which may be temporary, however, if you do this a 1000 times for a simulation, it would still result in a 30TB IO burden on a cluster.
It would be great if instead of this, there would be a way to directly subset an SFBM file to the SNPs present in the data, without having to regenerate the entire thing for each run. Is this not possible?

The code for this could look something like this:
```
corrLoaded = readRDS("myHapmap3LDref.rds")) # this is the 'corr' object produced by the above loop, that could be saved to the disk and the loaded back in
corr_subset = corrLoaded[!is_bad, !is_bad] # ideally this should work...
```

**Comment by privefl** [comment]
1. End of section 3.4, just after the median() formula you present.

2. About subsetting the SFBM, please have a look at https://github.com/privefl/bigsparser/issues/4. Making the SFBM should not take 2 hours (with the newest versions). What you are asking for is basically an in-memory format.

**Comment by mkelcb** [comment]
1. I am really sorry to be a pain, but there is no section 3.4 in the LDpred2 paper, nor in the tutorial I linked. Can you please clarify?

2. My packageVersion('bigsparser') is ‘0.4.0’. The other thread mentioned it being slow too.

**Comment by privefl** [comment]
1. The LDpred2 paper: https://doi.org/10.1093/bioinformatics/btaa1029

2. The other thread does mention that it takes e.g. 10 min only.

**Comment by privefl** [comment]
Any update on this?
