### ISSUE TITLE
too many is_bad snps in prepare_sumstats.R

### ISSUE THREAD

**Issue by stat-yyang** [privefl/bigsnpr#169]
Hi Florian,

Good morning!
I am implementing your ldpred2 methods to our data but had some problems.
When I ran through prepare_sumstats.R, I got too many is_bad SNPs. So I didn't exclude any SNPs in the downstream analysis.
Do you know how to approach this problem or why it happened?

Best,
Yue

**Comment by privefl** [comment]
Any update on this?
