### ISSUE TITLE
Problem installing bigsnpr on MacOS High Sierra

### ISSUE THREAD

**Issue by Charlotte-Vrijen** [privefl/bigsnpr#170]
Hi,

I am trying to download bgsnpr on my macbook with OS High Sierra 10.13.6, R version 4.0.3. I used these commands:

```
install.packages("remotes")
library(remotes)
remotes::install_github("https://github.com/privefl/bigsnpr.git")
```

This resulted in the following errors:

```
ERROR: package installation failed
Error: Failed to install 'bigsnpr' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o bigsnpr.so RcppExports.o bed-acc-xptr.o bed-fun.o bed-prod-vec.o clumping-bed.o clumping-cached.o clumping.o colstats.o copy-subset.o corr.o impute-simple.o ldpred2-auto.o ldpred2-sampling.o ldpred2.o multLinReg.o read-bgen.o read-plink.o sp-colsumssq-sym.o write-plink.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -lz -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
E> ld: warning: directory not found for option '-L/usr/lo
```
Do you know how this can be solved? Many thanks!

Charlotte Vrijen

**Comment by privefl** [comment]
Hum, this is the first time I see this problem with `lo` (which I do not know what it is).
Do you have this installation issue with other packages as well? E.g. try things like {RcppArmadillo} or {data.table}.
Do you have this issue when installing {bigsnpr} from CRAN?

You don't use any special compilation instructions? E.g. you don't have any `Makevars` file?

**Comment by Charlotte-Vrijen** [comment]
Thanks for the fast reply! 

No, I did not use special compilation instructions.

I did not know that bigsnpr was also available from CRAN. I installed it from CRAN just now .... and everything seems to work fine now. So my problem is solved.

**Comment by privefl** [comment]
It would still be good to know why you get this problem when installing from GitHub.

I'm closing for now, but if someone has the same issue, feel free to post here.
