### ISSUE TITLE
Bus error when creating SFBM

### ISSUE THREAD

**Issue by opain** [privefl/bigsnpr#174]
Hello,

I have received the below error message a few times when converting my LD matrix into SFBM format. I am not sure what is causing it. It only happens when using certain GWAS to subset the SNPs.

*** caught bus error ***
address 0x7f79c720e278, cause 'non-existent physical address'

Traceback:
 1: write_indval_sym(sbkfile, spmat@p, spmat@i, spmat@x, 0L)
 2: .Object$initialize(...)
 3: initialize(value, ...)
 4: initialize(value, ...)
 5: new("SFBM", spmat = spmat, backingfile = backingfile, symmetric = sym)
 6: as_SFBM(corr0, paste0(opt$output_dir, "/LD_GW_sparse"))
An irrecoverable exception occurred. R is aborting now ...

I notice this error has been mentioned before (https://github.com/privefl/bigsnpr/issues/132) but I cannot see how to resolve it. Do you have any advice? You suggest this is due to a memory restriction in the /tmp folder. Would specifying a different folder to store the SFBM resolve the issue?

Many thanks,

Ollie

**Comment by privefl** [comment]
Yeah, try not to use the temporary directory for large files.
In the tutorial and the paper, I'm using some `"tmp-data"` directory instead. 
You must remember to clean it yourself though (code for that is also included).

**Comment by opain** [comment]
Thank you for the fast response. 

Apologies, I now remember that I am already specifying a non-temporary directory (like the tutorial), and that this error may in fact reflect limited disk space. 

I have now tried running again using a different temporary directory with more space, and the LD matrix is built successfully.

Many thanks,

Ollie
