### ISSUE TITLE
snp_readBed error

### ISSUE THREAD

**Issue by JasmRicard** [privefl/bigsnpr#175]
Weeks ago, I used the snp_readBed function on PLINK bfiles and it worked perfectly: the .bk and .rds files were created.
I recently tried to do use the same function on the same (after removing the existing .bk and .rds files) and on a new set of PLINK bfiles and, for both, I get the this error:
_Error: Inconsistency between size of backingfile and dimensions._
How can i manage this situation? It's actually strange to me because it has worked perfectly before.

Thanks a lot!

**Comment by privefl** [comment]
Can you tell me more? E.g.
- what is your operating system?
- are you writing to some temporary directory?
- has anything changed in the way you use this function compared to before?

**Comment by privefl** [comment]
Also, in RStudio, when you get the error, you can "Rerun with debug" and it should stop just before the error happens.
Then, you can see the state of all variables, and understand why you get the error.
Here, it is some problem that the size of the .bk file created does not correspond to the dimensions; it would be useful to know this.

**Comment by JasmRicard** [comment]
Hi Florian, thank you for your quick answer. You're right on it: it's simply that there's no more space available where I'm writing. Removing some stuff in my directory made it possible! I'm sorry for the concern.

**Comment by privefl** [comment]
No worries. 
I could also make the error message clearer; I actually thought another one would be triggered before instead.
