### ISSUE TITLE
Support for phased data (bigHAP class)

### ISSUE THREAD

**Issue by rborder** [privefl/bigsnpr#176]
Is there any possibility of adding support for phased data? At minimum, would require new haplotype data class + specialized versions of read/write BGEN (plink bfiles break phasing). Would be happy to contribute... Possible applications would include forward time simulation, calling relatives, imputation...

**Comment by privefl** [comment]
Yeah, this is a bit out of my league, but that could be very interesting.
I can definitely help with the implementation.

**Comment by privefl** [comment]
Maybe we can set up a call next week to discuss more about this? 
You can follow up by email (florian.prive.21@gmail.com) if you are interested.

**Comment by privefl** [comment]
Any update on this?

**Comment by rborder** [comment]
I have validated my R simulator with synthetic data against my python
simulator to make sure the new code is performing as expected. The next
step is add functionality to read phased vcf and write plink output, though
it might be a couple weeks before I get to this. Do you have plans to add
support for the plink2 binary format once the specification is finalized? I
think it should allow for some highly performant i/o without breaking
phasing the way the bfile specification does.

**Comment by privefl** [comment]
Are you talking about the pgen format?
Last time I checked it was still in alpha dev.

Basically, unless I have such data I need to analyze myself, or that someone does and is willing to try implementing something (where I can help), it won't be done.

**Comment by rborder** [comment]
Yes, still alpha for the moment, but pretty far along from what I've seen.
But fair enough! I'll keep you updated once I get to implementing an
interface with external genotype interfaces

**Comment by privefl** [comment]
Any update on this?

**Comment by rborder** [comment]
Not at the moment, working on finishing another project, I'll keep you
updated. Sorry to move slow on this

**Comment by sounkou-bioinfo** [comment]
hi @rborder  @privefl , any update on the support for the phased data ?
Thanks !

**Comment by privefl** [comment]
Basically, unless I have such data I need to analyze myself, or that someone does and is willing to try implementing something (where I can help), it won't be done.
