### ISSUE TITLE
What is the point of providing list_snp_id in snp_readBGEN? 

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#180]
What is the point of providing list_snp_id in snp_readBGEN? It has no default value but this should be in the .bgen file already.

If this is absolutely needed, how can I get this list out of the PLINK file? You said in the documentation

> List (same length as the number of BGEN files) of character vector of SNP IDs to read. These should be in the form "<chr>_<pos>_<a1>_<a2>" (e.g. "1_88169_C_T" or "01_88169_C_T"). This function assumes that these IDs are uniquely identifying variants.

What are <a1><a2>? Which one is REF/ALT/A1? Is there an easy way to extract this out of the PLINK file other than doing a GWAS first and extract from the result?

**Comment by privefl** [comment]
This parameter is used to access a subset of variants that you are interested in. E.g., in the UK Biobank there are 90M+ such variants, so you can't really read them all.
If you have PLINK files, this information is in the .bim or .map files.

**Comment by garyzhubc** [comment]
Is there an efficient way of getting this list? I think it’s already inside the bgen file somehow.

**Comment by garyzhubc** [comment]
Also what is the format of this list? I got a list like 
```                
  [21] "rs74417302"                                         "rs12070544"                                        
  [23] "rs144473081"                                        "1:54509957_C_T"                                    
  [25] "rs184218073"                                        "rs148840059"                                       
  [27] "rs116050768"                                        "rs41538044"                                        
  [29] "rs749134653"                                        "rs55897033"                                        
  [31] "rs41528748"                                         "rs141282402"     
```


but this doesn't work and throws error `Error in format_snp_id(list_snp_id[[ic]]) :  Wrong format of some variants.`. I saw your function is checking some format that I have never seen before.

```
format_snp_id <- function(snp_id) {
  # if chr is only one digit, append a '0' to the beginning
  snp_id <- ifelse(substr(snp_id, 2, 2) == "_", paste0("0", snp_id), snp_id)
  if (any(substr(snp_id, 3, 3) != "_")) stop("Wrong format of some variants.")
  snp_id
}
```

**Comment by garyzhubc** [comment]
While using the format required as input, I've got an error saying 'some variants have not been found'. When I look at the list it includes all the SNPs in the .bgen file. 

# error message
```
> ukb_imp_chr1_v3_pruned_trimmed_2m.bgen <- snp_readBGEN(ukb_imp_chr1_v3_pruned_trimmed_2m.bgen,tempfile(),list(paste0("1_",ukb_imp_chr1_v3_pruned_trimmed_2m.LDL.glm.linear$POS,"_",ukb_imp_chr1_v3_pruned_trimmed_2m.LDL.glm.linear$A1,"_",ukb_imp_chr1_v3_pruned_trimmed_2m.LDL.glm.linear$REF)),read_as="dosage")

Error: Some variants have not been found (stored in './ukb_imp_chr1_v3_pruned_trimmed_2m_not_found.rds').
```

# bim file
```
[zhupy@gra-login2 zhupy]$ head -9 ukb_imp_chr1_v3_pruned_trimmed_2m.bim
1	rs188975649	0	54505201	T	C
1	rs78521396	0	54505304	A	G
1	rs3766466	0	54505437	A	C
1	rs80255594	0	54505703	A	G
1	rs41331348	0	54505756	A	G
1	rs143684364	0	54505887	A	G
1	rs558240159	0	54506600	C	T
1	rs114165657	0	54507000	A	G
1	rs566596613	0	54507273	G	A
```

# list_snp_id
```
> list_snp_id
[1] "1_54505201_T_C" "1_54505304_A_G" "1_54505437_A_C" "1_54505703_A_G" "1_54505756_A_G" "1_54505887_A_G" "1_54506600_C_T" "1_54507000_A_G"
[9] "1_54507273_G_A"
```

**Comment by privefl** [comment]
Have you tried switching the two alleles?

**Comment by garyzhubc** [comment]
That works thanks. How can I create a numerical dosage matrix out of this bigSNP object?

**Comment by privefl** [comment]
`obj.bigsnp$genotypes[]`

You should look at the introductory vignettes maybe.
