### ISSUE TITLE
Error while preparing sumstats

### ISSUE THREAD

**Issue by pmk2020** [privefl/bigsnpr#181]
Hi Florian, 
I am trying to prepare summary stats as per the prepare-sumstats code that you have provided. 

In this step:
sd_val <- sd[info_snp$`_NUM_ID_`]

I am receiving the following error 
Error in sd[info_snp$`_NUM_ID_`] : 
  object of type 'closure' is not subsettable

I checked the issues but looks like no on else encountered it so I am not sure what to do.
Thank you!

**Comment by pmk2020** [comment]
Figured it out :)

**Comment by privefl** [comment]
I'll explain for others, if someone has the same issue.
If variable `sd` is not defined (should be a numeric vector), then it uses function `sd`, which you can't call with square brackets.
Try e.g. `stats::sd[1]`.
