### ISSUE TITLE
Error while using snp_grid_clumping

### ISSUE THREAD

**Issue by pmk2020** [privefl/bigsnpr#182]
Hi Florian, 
I am trying to use the SCT method as per your instructions here: https://privefl.github.io/bigsnpr/articles/SCT.html 

At the snp_grid_clumping step I am encountering the following error message:
'Error: Incompatibility between dimensions'

Here is the code I am using:
all_keep <- snp_grid_clumping(G2, CHR, POS, ind.row = ind.train, exclude = which(is.na(lpval)),
                              lpS = lpval, ncores = NCORES)

I just ran it for chromosome 22 and the numbers of G2, CHR, POS are same while lpval is slightly lower and that is why I included the "exclude" term but it doesn't seem to work. 

Thank you.

**Comment by privefl** [comment]
I'll update the vignette now to better explain this.

**Comment by privefl** [comment]
Basically, you need to get `beta` and `lpval` with the same number of variants as `G` (putting NAs for variants you do not have):
```r
info_snp <- snp_match(sumstats, map, strand_flip = FALSE)
# beta and lpval need to have the same length as ncol(G), CHR and POS
# -> one solution is to use missing values and use the 'exclude' parameter
beta <- rep(NA, ncol(G))
beta[info_snp$`_NUM_ID_`] <- info_snp$beta
lpval <- rep(NA, ncol(G))
lpval[info_snp$`_NUM_ID_`] <- -log10(info_snp$p)
```

And then use `exclude = which(is.na(lpval))` as you do.

I'll upload the updated vignette today.
