### ISSUE TITLE
Can I retrieve the list of sample ids from a bigsnpr object after reading BGEN files?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#184]
Can I retrieve the list of sample ids form a bigsnpr object?

**Comment by shugamoe** [comment]
If you're talking about a [bigSNP object](https://privefl.github.io/bigsnpr/reference/bigSNP-class.html) sample ids should be in the `fam` attribute:

`obj.bigSNP$fam$sample.ID`

See output of `str(obj.bigSNP, max.level = 2, strict.width = "cut")` from this [vignette](https://privefl.github.io/bigsnpr/articles/SCT.html) for an example of the other attributes.

**Comment by garyzhubc** [comment]
After loading a bgen file into a SNP object, I can only see map and genotype but not fam. How can I create a SNP object that has fam as in this example?

**Comment by privefl** [comment]
Did you read from BGEN data?
Then, the fam information is in the .sample file.

If you take e.g. [this code](https://github.com/privefl/UKBB-PGS/blob/main/code/prepare-data.R), then the eids should be `sample$ID_2[ind.indiv[sub]]`.
