### ISSUE TITLE
 FBM.code65636 | bigsnpr with more precise numbers | Feasible to implement into FBM.code256 "only" functions?

### ISSUE THREAD

**Issue by shugamoe** [privefl/bigsnpr#185]
I'm using [-1,1] scaled gene expression data* with bigsnpr. I've been able to use FBM.code256 and get `.01` precision but I saw that you mentioned [you could get `0.00005` precision by  implementing FBM.code65636.](https://github.com/privefl/bigsnpr/blob/eacc633b878f952509734e73fe59673d8024066b/tmp-save/dosage.Rmd#L31)

What would one** need to do, broadly speaking, to implement FBM.code65636 for use in any bigsnpr function that currently uses FBM.code256?

---

[* Intermediate output of PrediXcan](https://github.com/hakyimlab/MetaXcan/wiki/Individual-level-PrediXcan:-introduction,-tutorials-and-manual)
**I'd be happy to try and implement it, but it would be my first experience in a while with C and first with rcpp. Until I get more of that experience I'm stuck asking these broad questions.

**Comment by privefl** [comment]
Yes, I thought about implementing this at some point, but then I did not.
I'm not sure this would be really useful, as you can probably just use a matrix of floats (4-bytes precision) to achieve the same precision  using only twice as much space, without needing to re-implement anything in bigstatsr. 
For algorithms in bigsnpr, this is a different story, as you would need to write dispatchers to handle different types of FBMs. But functions in bigsnpr should be very specific to genotype data, so which functions are you using for gene expression data for example?

**Comment by shugamoe** [comment]
In general I'm looking to implement bigsnpr's SCT and LDpred2, so functions like `snp_grid_clumping`, `snp_grid_PRS`, `snp_grid_stacking`, and `snp_cor` are the functions that I've been using that require `FBM.code256`.

---

> But functions in bigsnpr should be very specific to genotype data [. . .]

The gene expression data I'm using is imputed using linear combinations of (.bgen) genotype data so I think bigsnpr should still be viable to use. (Though, I haven't exhaustively proved this.)

---

> I'm not sure this would be really useful [. . .]

Yeah, I'm not necessarily betting on higher precision data eventually resulting in some `AUCBoot` intervals with higher means and no overlap versus comparable `AUCBoot` intervals using `FBM.code256` precision data. In my case "useful" might be more accurately described as "satisfying my PI's desire to construct polygenic scores with higher precision data gene expression/splicing data".

Unfortunately, with a lot of PGS software I've seen it's difficult to get around the common restriction of needing `0, 1, 2` genotype data, so without independently recreating PGS methods or modifying PGS software many methods are unusable with this data (or even doseage data). bigsnpr at least allows me to get around this restriction more easily with `FBM.code256` (This has already been helpful for me in creating PGS using dosage data with LDpred2 so thanks for that!). 

The relative ease of building our own P+T/SCT method is making my PI lean toward using some homegrown P+T/SCT implementation with gene expression data at the precision it's calculated at, but from my point of view the convenience of bigsnpr's already built functionality, from calculating GWAS, `snp_grid_PRS`, AUC functions, etc. outweighs both only having `.01` precision and whatever bare bones functionality of any homegrown P+T/SCT we come up with from scratch.

**Comment by privefl** [comment]
Normally, bigsnpr does not really rely on any assumption of needing 0/1/2/NA because it also handles dosages (floating point numbers).
So I guess it may be just adding dispatchers to the already existing functions.

Do you want to fork the repo and try this to see if it meets your needs?

**Comment by shugamoe** [comment]
> **[I]t would be my first experience in a while with C and first with rcpp. [. . . ]

I'd be happy to fork the repo and give it a try. I'll just speak with my PI first and read some rcpp documentation to find out what exactly is going on.

Thank you for your replies!

**Comment by privefl** [comment]
Ah yeah, that might be difficult for you then.

Then, pick one function, one small data that would like to apply this function to, and then I can maybe start with this and show you how you could do this.

**Comment by shugamoe** [comment]
I think `snp_cor` would be the ideal function to modify to be able to use `FBM.code65536`.

If I could take a matrix like below, with the elements corresponding to some long code table, and  use it with `snp_cor` that's basically LDPred2 with more precision right there.
`matrix(data = sample(0:65535, 100, replace = T), nrow=5, ncol=20)`

**Comment by privefl** [comment]
So, I do not think I want to develop a `FBM.code65536`, but we can try with a matrix of floats if you want to save a bit of space.

**Comment by privefl** [comment]
Just to showcase, you can now try `remotes::install_github('privefl/bigsnpr@othertypes')` with this code:
```r
library(bigsnpr)
X <- FBM(5, 20, type = "float", init = rnorm(100))
snp_cor(X)[1:5, 1:5]
cor(X[, 1:5])
```

And see what I changed to achieve this: https://github.com/privefl/bigsnpr/commit/33451bf11f9f1f0d65a0fd691f610ed7da881b2a.

**Comment by shugamoe** [comment]
> So, I do not think I want to develop a FBM.code65536, but we can try with a matrix of floats if you want to save a bit of space.

No problem at all. A float FBM seems much more expedient.

--- 

> And see what I changed to achieve this: 33451bf.

Really appreciate the showcase. Can't wait to take a closer look!

**Comment by privefl** [comment]
Any update on this?

**Comment by shugamoe** [comment]
Sorry for keeping you waiting. Your modification worked brilliantly!

I basically copied it to the other functions I wanted to use float FBMs for.
