### ISSUE TITLE
SCT new beta values

### ISSUE THREAD

**Issue by pmk2020** [privefl/bigsnpr#187]
Hi Florian, 

In order to use the utilize the new beta values, I want to extract snps (rsid or chromosom/position/allele information) with the new betas. I was playing around with public dataset provided by you and running the vignette. 

After running the whole vignette, I just wanted to check if I could somehow merge info_snp and new betas but the new betas has few more values and those are NA and I can easily remove those but my question is: Is the order of new betas same as info_snp order and when I delete NA values, will there be changes to that order? The reason I was exporting the new betas was to apply this beta weights to another dataset to obtain individual level PRS and then regress it on the outcome. 
`> str(info_snp)`
 `data.frame:	130792 obs. of  9 variables:`
 `$ chr        : int  2 2 2 2 2 2 2 2 2 2 ...`
 `$ pos        : int  18506 21833 22398 28228 32003 32005 36787 55237 56916 61687 ...`
 `$ a0         : chr  "C" "G" "T" "A" ...`
 `$ a1         : chr  "T" "C" "C" "G" ...`
 `$ rsid       : chr  "rs13400442" "rs7594567" "rs7597758" "rs13383216" ...`
 `$ beta       : num  -0.073 0.0439 -0.3325 -0.5445 -0.4881 ...`
 `$ p          : num  0.7925 0.8593 0.0846 0.028 0.0439 ...`
 `$ _NUM_ID_.ss: int  1 2 3 4 5 6 7 8 9 10 ...`
 `$ _NUM_ID_   : int  1 2 3 4 5 6 7 8 9 10 ... `
`> sum(!is.na(info_snp$beta))`
`[1] 130792`
`> str(new_beta)`
 `num [1:130816] -5.79e-06 0.00 -4.03e-04 -5.92e-04 -9.03e-04 ...`
`> sum(!is.na(new_beta))`
`[1] 130792`

Please let me know your thoughts on it. 
Thank you.

**Comment by privefl** [comment]
`new_beta` should correspond to all variants in `G` / `map`.

**Comment by privefl** [comment]
You get NAs in `new_beta` for variants that have not been matched.
Would it be less confusing to get 0s instead for such variants?

**Comment by pmk2020** [comment]
Thank you, Florian! No I think NAs will help eliminate those if we use the new betas forward.
