### ISSUE TITLE
Segmentation fault with snp_readBGEN()

### ISSUE THREAD

**Issue by Allan-XuYu** [privefl/bigsnpr#189]
Hi Dr Prive,

I just copy your  code Prepare-genotypes.R from LDpred2 repository and only modified the file path to my own as well as set the parameter **ncores** of readBGEN() to 15.

It seems normally run and print some information utill running the func readBGEN(). The error message is below:
terminate called after throwing an instance of 'Rcpp::exception'
terminate called recursively
Aborted (core dumped)

When change the parameter **ncores** of readBGEN() to NCORE as the code defined. The error message is below:
address 0x7fc6b5830970, cause 'memory not mapped'
.....
.....
An irrecoverable exception occurred. R is aborting now...
Segment fault (core dumped)

And when change the parameter value 1:22 to 22 ,only read one chromosome & ncores=15. The error message is below:
terminate called after throwing an instance of 'Rcpp::exception'
what() : error while opening '~/UKBB/ukb_imp_chr22_v3.bgen'.
terminate called recursively
Aborted (core dumped)

My hardware: Xeon Gold 6230R/400+G RAM avaliable(check by free -m)
env: Centos8.2(64bit) / R 3.5.1 / bigsnpr , Rcpp and bigsparser are latest version installed by remotes install

Thanks!
XU

**Comment by privefl** [comment]
So, just to make sure, you're trying to read the exact same files (UKBB BGEN files)?

A common cause of error is that users do not have enough disk space to store the resulting FBM. Can you check how many individuals and variants you are asking for, and what disk space do you have where you're trying to write?

**Comment by Allan-XuYu** [comment]
> So, just to make sure, you're trying to read the exact same files (UKBB BGEN files)?
> 
> A common cause of error is that users do not have enough disk space to store the resulting FBM. Can you check how many individuals and variants you are asking for, and what disk space do you have where you're trying to write?

Yes, the .bgen file were downloaded from Uk biobank , same with yours.

And I check the disk which mounted at **backingfile** dir is still have 51TB space avaliable.  Also I tried using the eid of  individuals I want to evaluate , about 7500 individuals. Matching it with .sample file to covert to be row index vector , but the result is no any changed. Using Hapmap3 variants

**Comment by privefl** [comment]
Is there any special way you installed the packages using e.g. conda?

**Comment by privefl** [comment]
Are you trying to store the files in some temporary directory?

**Comment by Allan-XuYu** [comment]
> Are you trying to store the files in some temporary directory?

Installed the packages just using remotes::install_github(...)

Change the R temporary directory to my folder but still the same error message.

adding the following code in the start of .R file:
tempdir <- function() "~/xuyu/data/Rtmp" # my path
unlockBinding("tempdir", baseenv())
assignInNamespace("tempdir", tempdir, ns="base", envir=baseenv())
assign("tempdir", tempdir, baseenv())
lockBinding("tempdir", baseenv())

**Comment by privefl** [comment]
Please try with something simple like `backingfile = "test"`.

Is there anything you modified compared to the initial script? 
I would like to understand what could have gone wrong.

**Comment by Allan-XuYu** [comment]
> Please try with something simple like `backingfile = "test"`.
> 
> Is there anything you modified compared to the initial script?
> I would like to understand what could have gone wrong.

Just modified files path and **ncores=15** . The part of Haphap3&PCA QC is running well.

It will create .bk file in **backingfile** path. Using "ls -lht" check, it show 378G size but the total size of this dir is just 4k...

**Comment by privefl** [comment]
So, I don't understand, did it work?

**Comment by Allan-XuYu** [comment]
> So, I don't understand, did it work?

No,,still  "terminate called recursively".
Even I tried creating an new R env by Conda and installed all the dependent packages by CRAN source.

**Comment by Allan-XuYu** [comment]
I've tried this: [read-bgen.R](https://rdrr.io/cran/bigsnpr/src/R/read-bgen.R)
And set many **print()** , it was running normally to ~ read_bgen(). Because I'm unable to access the C soure, debug was done here. I guess the reason may be Iower level operation.

**Comment by privefl** [comment]
Can you tried with a small subset of individuals / variants?

**Comment by privefl** [comment]
At this point, it's very hard for me to help you more like this.
If you want, we could probably have a quick meeting where you share your screen (if you are allowed to), and we look at it on your computer.

**Comment by Allan-XuYu** [comment]
Thank goodness!!!!!!

I found where the mistake I made!!!! ooooh!!!
Coz I used the short path like this "~/xuyu/XXX" to access file. In other areas from the code , it is ok! But **bgenfiles="..." ** has to used absolute path. I mean, **bgenfiles="/home/xxx/...." if not declared **file.symlink("/home/../UKBB/", "UKBB")**.

Thanks your patient help!! Keep on learning your LDpred2 method

**Comment by privefl** [comment]
I'm not I understood completely what was the error.
Can you please explain it to me again? 
Then, I can do something about it to at least warn the user.

**Comment by Allan-XuYu** [comment]
OK, just modify this line **bgenfiles   = glue::glue("~/UKBB/bgen/ukb_imp_chr{chr}_v3.bgen", chr = 1:22)** and do not state **file.symlink("../../UKBB/", "UKBB")** for files path.  


Generally '~' represent '/home/username' and my .bgen file are storing in this dir: "/home/username/UKBB". So at first, I tried the below code and got the error.
> system.time(
  rds <- bigsnpr::snp_readBGEN(
    bgenfiles   = glue::glue("~/UKBB/bgen/ukb_imp_chr{chr}_v3.bgen", chr = 1:22),
    list_snp_id = list_snp_id,
    backingfile = "data/UKBB_imp_HM3",
    ind_row     = ind.indiv[sub2],
    ncores      = NCORES
     )
> )  

Then , modifid the file path to below, which is running well! 
 > system.time(
  rds <- bigsnpr::snp_readBGEN(
    bgenfiles   = glue::glue("/home/username/UKBB/bgen/ukb_imp_chr{chr}_v3.bgen", chr = 1:22),
    list_snp_id = list_snp_id,
    backingfile = "data/UKBB_imp_HM3",
    ind_row     = ind.indiv[sub2],
    ncores      = NCORES
     )
> ) 

replace username to yours.

**Comment by privefl** [comment]
Ah yeah I now remember that `~` mess things up when passed to C++.
I'll make sure this is not a problem anymore for this function.

Thanks a lot for the report.
