### ISSUE TITLE
Pred_auto issue in ldpred2

### ISSUE THREAD

**Issue by ricardocortezcardoso** [privefl/bigsnpr#190]
I am writing to you regarding some issues I am having while computing the PRS using the LDpred2 using the auto model for the genome-wide bed file.

Everything in the pipeline is working until I calculate the PRS itself for all the samples. It returns a matrix with NA values in pred_auto.

Do you have any suggestions? 
Data: 11k cases, 220k variants to calculate the prs. 

########Perform LD score regression
df_beta <- info_snp[,c("beta", "beta_se", "n_eff", "_NUM_ID_")]
ldsc <- snp_ldsc( ld,
length(ld),
chi2 = (df_beta$beta / df_beta$beta_se)^2,
sample_size = df_beta$n_eff,
blocks = NULL)
h2_est <- ldsc[["h2"]]

####### Get adjusted beta from the auto model
multi_auto <- snp_ldpred2_auto(
corr,
df_beta,
h2_init = h2_est,
vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
ncores = NCORES
)
beta_auto <- sapply(multi_auto, function(auto)
auto$beta_est)

########## calculate PRS for all samples
ind.test <- 1:nrow(genotype)
pred_auto <-
big_prodMat(genotype,
beta_auto,
ind.row = ind.test,
ind.col = df_beta$`_NUM_ID_`)
# scale the PRS generated from AUTO
pred_scaled <- apply(pred_auto, 2, sd)
final_beta_auto <-
rowMeans(beta_auto[,
abs(pred_scaled -
median(pred_scaled)) <
3 * mad(pred_scaled)])
pred_auto <-
big_prodVec(genotype,
final_beta_auto,
ind.row = ind.test, ind.col = df_beta$`_NUM_ID_`)

**Comment by privefl** [comment]
Do you have any missing values in your data? Or in `beta_auto`?

**Comment by ricardocortezcardoso** [comment]
I have just checked the beta_auto and my data.....there is no NAs

**Comment by privefl** [comment]
I just need to understand at which stage the missing values start to appear.

E.g. do you have any missing values in `apply(pred_auto, 2, sd)`? (BTW, this should not be called `pred_scaled`, maybe `pred_scaling`).

How many chains are passing the QC? `sum(abs(pred_scaled - median(pred_scaled)) < 3 * mad(pred_scaled))`

BTW, you do not need to use `big_prodVec()` at the very end, you can directly average the predictions (that pass QC).

**Comment by ricardocortezcardoso** [comment]
it is calculating the beta_auto.....I could not apply the script that filter bad chains by comparing the scale of the resulting predictions, because the pred_auto is returning a matrix of NAs

**Comment by ricardocortezcardoso** [comment]
<img width="488" alt="chains" src="https://user-images.githubusercontent.com/54276215/110768861-e6bf6280-8257-11eb-856b-67e9e28c19a7.png">

**Comment by privefl** [comment]
Sorry I got confused.
So, no NA in `beta_auto` but full NAs in `pred_auto`.

Then it means that you have NAs in the genotype matrix.
You can verify this by using something like `sum(big_counts(genotype)[4, ])`.

**Comment by ricardocortezcardoso** [comment]
after running "sum(big_counts(genotype)[4, ])", I got 4924872, which means that the problem is not related to a NA in the genotype

**Comment by privefl** [comment]
It means that you have 4924872 missing values in your data.
Which, given the dimensions you report, is 0.2% of the data.
You should be fine by using `snp_fastImputeSimple(method = "mean2")`.

**Comment by privefl** [comment]
Any update on this?
