### ISSUE TITLE
snp_readBed nThread >=1 error

### ISSUE THREAD

**Issue by alovdom** [privefl/bigsnpr#191]
Hello, 

I'm trying to read in a bed file using the snp_readBed() function, but keep receiving this error: 

> Error in data.table::fread(input, ..., data.table = data.table, nThread = nThread) : nThread >= 1L is not TRUE. 

I'm not sure if the trouble is actually occurring with the snp_readBed() function or the fread() function and what I can change to fix this error. The line of code I enter into R is just: 

> snp_readBed("~/Research/Data/round2_match.bed") 

Any help would be greatly appreciated. 

Thanks, 

Alicia

**Comment by privefl** [comment]
Hum, that's odd.
You can try using `options(bigreadr.nThread = 1)` before.

Can you also tell me what you get for `packageVersion("bigreadr")` and `parallelly::availableCores(logical = FALSE)`?

**Comment by alovdom** [comment]
Thanks for getting back to me so quickly! The results I got from the following commands are given after the # sign. 

`parallelly::availableCores(logical = FALSE) # nproc 1`
`packageVersion("bigreadr") # 0.2.2 `
`options(bigreader.nThread = 1) `
`snp_readBed("~/Research/Data/Combined/merged_MGI_Pret/og_yuhua/round2_match.bed") # Error in data.table::fread(input, ..., data.table = data.table, nThread = nThread) :nThread >= 1L is not TRUE
`
I tried reinstalling the bigreadr package again, but didn't have any change in my errors.

**Comment by privefl** [comment]
And what do you get for `nb_cores()`?

**Comment by alovdom** [comment]
`nb_cores()   # nproc 0`

**Comment by privefl** [comment]
Okay, that's clearly the issue here.
Is it normal that you have access to only one thread on the computer you use?

Please try again with the latest version of {bigreadr} now (`remotes::install_github('privefl/bigreadr')`).

**Comment by privefl** [comment]
The error `Wrong magic number.` means that you are not providing a standard binary PLINK format (with each variants stored contiguously). But it seems that you have the right magic number.. So I'm a bit confused.

Which version `packageVersion("bigsnpr")` do you have?

**Comment by alovdom** [comment]
`packageVersion("bigsnpr") # ‘1.6.1’ `

**Comment by privefl** [comment]
Please try with `snp_readBed(path.expand("~/Research/Data/round2_match.bed"))`

**Comment by privefl** [comment]
Ok, I was able to reproduce the issue, the problem is that C++ does not handle the `~` in the file path..
I'll update the package to fix this.
Thanks for reporting.

**Comment by alovdom** [comment]
I tried `snp_readBed(path.expand("~/Research/Data/round2_match.bed"))` and I think it worked. It created a corresponding round2_match.bk and round2_match.rds file. Thank you so much for all your help!
