### ISSUE TITLE
bigSNP object and FBM.code256

### ISSUE THREAD

**Issue by APUNC** [privefl/bigsnpr#194]
I'm intending to use bigsnpr for some work and encountered some challenges that I wanted to ask about:

1) I have created a FBM of my genotype matrix (which is in dosage format of 0,1,2). The FBM shows these as 00,01,and 02, which makes sense. However, to create a bigSNP object, the FBM must be code256 if I understand correctly. I'm specifying "code[1:3] <- c(0,1,2) so that the code256 FBM corresponds to the FBM and the original genotype matrix. Is this correct or can any code be used? 

2) It says that bigSNP is a named list with at least 4 slots. But, I only see inputs for genotypes, fam, and map in that named list. What should be the 4th element in that list?

**Comment by privefl** [comment]
1. Yes, have a look at the examples in the documentation `?FBM.code256`

2. Where does it say 4 slots? Usually, it is only 3, but you can have whatever you want, in the end, it is just a list with some class attribute. Some functions will use all three slots (e.g. `snp_writeBed()`), other functions do not really care, and most functions only use `G` (`$genotypes`) and some other information.

**Comment by privefl** [comment]
Any update on this?
