### ISSUE TITLE
snp_readBGEN without using snp_list_id

### ISSUE THREAD

**Issue by 229668880** [privefl/bigsnpr#196]
snp_list_id must use the format "chr_pos_a1_a2". Here comes an issue:
UK biobank genotype is based on GRCh38. Many SNPs on published papers use GRCh37 and earlier version. So, to calculate genetic score, we hope to extract genotype from BGEN only with SNP ids, ignoring the change of position due to different genome versions. How can I do this with bigsnpr?

**Comment by privefl** [comment]
UKBB is based on GRCh37 (hg19) I think.

You can always use https://privefl.github.io/bigsnpr/reference/snp_modifyBuild.html to change builds.

Or you can read the BGI files (with `snp_readBGI()`), match by rsid and construct the `snp_list_id` from the other fields of the matched variants.

**Comment by 229668880** [comment]
That is not my question. My question is about snp_list_id argument in snp_readBGEN. UK biobank is just an example. 
As you said, UK biobank is based on GRCh37 (whatever).  I am provide with a list of SNPs to calculate genetic score. These SNPs is based on a different version of genome, so their position is different from UK biobank. But I just want to use SNP id to extract genotype with snp_readBGEN, instead of "chr_pos_a1_a2". How can I do this? It seems that snp_readGBEN only accept "chr_pos_a1_a2" format

**Comment by privefl** [comment]
The last point of my answer is exactly the answer to your question.
You need to use this code: https://github.com/privefl/bigsnpr/blob/master/R/read-bgen.R#L29-L36, but matching by rsid.

**Comment by 229668880** [comment]
OK. thanks

**Comment by privefl** [comment]
You can also get this information from the MFI files, e.g. as in https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-genotypes.R#L5-L18.

**Comment by privefl** [comment]
Any update on this?

**Comment by 229668880** [comment]
I found my way to solve this issue. I used rbgen package to extract information according to rs ID. Then construct "chr_pos_a1_a2" with these extracted information, which can be used by snp_readBGEN.

**Comment by privefl** [comment]
Seems complicated. Couldn't you read from MFI files as done in the code linked?
