### ISSUE TITLE
Running time with snp_ldpred2_grid

### ISSUE THREAD

**Issue by xuyu-cam** [privefl/bigsnpr#198]
Hello Florian,

Many thanks for your effort and time to make this useful tool available to the community!

However, I found it takes long time for me to run the `snp_ldpred2_grid`  method with my data which has about 1M variants on a machine of 25 cores and 150G RAM.  So far, I couldn't finish my run within 12 hours.

I think it would be better to ask for your suggestions before I go for longer tests. Not sure it's normal running time for the method or I made any mistakes.

I attached my codes below.

Thank you for your help!

// read the number of cores to be used 
`NCORES <- as.integer(Sys.getenv("SLURM_JOB_CPUS_PER_NODE"))  - 1
`

// read summary stats data of a trait 
```
sumstat_file = "..."
sumstats <- bigreadr::fread2(sumstat_file)  

```

// read all genotype data (including variants of all variant sets)
```
genofile_rds =".....rds"   
obj.bigSNP <- snp_attach(genofile_rds)
G   <- obj.bigSNP$genotypes
CHR <- obj.bigSNP$map$chromosome
POS <- obj.bigSNP$map$physical.pos
```

// match variants in summary stats with variants in genotype data 
```
map <- obj.bigSNP$map[-(2:3)]
names(map) <- c("chr", "pos", "a0", "a1")
info_snp <- snp_match(sumstats, map,strand_flip=FALSE)
```

// Path for precomputed and saved correlation data between variants in genotype data (by chromosome )
```
corr_dir = "..."

```

// set temp file for correlation matrix 
```
temp_folder='...'
tmp <- tempfile(tmpdir = temp_folder)

```

// read correlation matrix and calculate ld vector for the matched variants
```
for (chr in 1:22) {
  
  # indices in 'sumstats'
  ind.chr <- which(info_snp$chr == chr)
  
  # make sure we have any variants in the chromosome
  if(length(ind.chr)>0) {

      ## indices in 'G'
      ind.chr2 <- info_snp$`_NUM_ID_`[ind.chr]
      ## indices in 'corr'
      ind.chr3 <- match(ind.chr2, which(CHR == chr))
      
      corr0 <- readRDS(paste0(corr_dir,"chr", chr, ".rds"))[ind.chr3, ind.chr3]

      ## if there is only one variants in this chromosome, we give ld = c(1)
      if (chr == 1) {
        df_beta <- info_snp[ind.chr, c("beta", "beta_se", "n_eff", "_NUM_ID_")]
        df_model_beta = info_snp[ind.chr, c('rsid','chr','pos','a0','a1')] 
    
        if (length(ind.chr)==1){
          ld = c(1)
        }
        else {
        ld <- Matrix::colSums(corr0^2)
        }
    
        // if there is only one variants in this chromosome, we need to make corr0 as a matrix (returned default is numeric )
        if (length(ind.chr)==1){
          corr = bigsparser::as_SFBM(as(as.matrix(corr0), "dgCMatrix"), tmp)
        }
        else {
          corr = bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp)
        }
   
        
      } else {
        df_beta <- rbind(df_beta, info_snp[ind.chr, c("beta", "beta_se", "n_eff", "_NUM_ID_")])
        df_model_beta <- rbind(df_model_beta, info_snp[ind.chr, c('rsid','chr','pos','a0','a1')])  
        
        if (length(ind.chr)==1){
          ld = c(ld, 1)
        }
        else {
          ld <- c(ld, Matrix::colSums(corr0^2))
        }

        if (length(ind.chr)==1){
          corr$add_columns(as(as.matrix(corr0), "dgCMatrix"), nrow(corr))
        }
        else {
          corr$add_columns(as(corr0, "dgCMatrix"), nrow(corr))
        }
      }
  }
}
```

// set intercept =1, because the default will throw "<1e-6" error for variant set with a small number variants
```
(ldsc <- with(df_beta, snp_ldsc(ld, length(ld), chi2 = (beta / beta_se)^2,sample_size = n_eff, intercept=1, blocks = NULL)))
h2_est <- ldsc[["h2"]]
```

// LDpred2-grid parameters setting
```
h2_seq <- round(h2_est * c(0.7, 1, 1.4), 4)
p_seq <- signif(seq_log(1e-5, 1, length.out = 21), 2)
params <- expand.grid(p = p_seq, h2 = h2_seq, sparse = c(FALSE, TRUE))
```

// running ldpred2 
`beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
`

// I will then calculate scores of these trained models with plink using separate codes, and perform the validation step. Because I found it takes long time to do the imputation with snp_fastImpute() (my data has missing genotype data)

**Comment by privefl** [comment]
Indeed, that's odd. Let's try to find what causes this.

1. Which version of {bigsparser} and {bigsnpr} do you use? I see that you are still using `bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp)`, instead of `as_SFBM(corr0, tmp)` in newer versions. More recent versions, especially of {bigsparser} should make LDpred2 faster. 

1. Do you write on disk with faststorage?

1. Are the cores that you ask for available only for you basically? How many are you asking for?

1. Why do you need all these conditions on `length(ind.chr)`?

1. What is the file size of your final correlation matrix (the `.sbk` file)? This will give me an idea of how many non-zero elements were including in the correlation, and in the computations of LDpred2. It should be 25-35 GB.

1. You can use `snp_fastImputeSimple()` to get some faster imputation if you do not have too many missing values.

**Comment by xuyu-cam** [comment]
Thank you Florian for your prompt response!

1. Versions of packages:
```
 packageVersion('bigsparser')
[1] ‘0.4.1’
```
```
packageVersion('bigsnpr')
[1] ‘1.6.1’
```
The reason why I used this way for getting correlation matrix is because I found it takes forever for me to run with `as_SFBM(corr0, tmp)`. It improved when I changed to `bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp)`; 
(ps: it runs ok with `as_SFBM(corr0, tmp)` if I have tmp set at my home folder, i.e. the login node storage - but I don't have that much storage under my home foder to allow runs of that many variants).

2. No - it's on some storage partition in university cluster;

3. Yes - that's a slurm job with 25 cores;

4. I need to test different variant sets (could be very small number), instead of only with this large set.

5. it's about 36G;

6. I made attempts with ` snp_fastImputeSimple()` but couldn't get through after a couple of hours, so I gave up. Because I need to have many runs. If that's the case, it will be too time-consuming for me.

**Comment by privefl** [comment]
You can try to upgrade both packages using `remotes::install_github()`. 

But `as_SFBM(corr0, tmp)` should take less than 2 minutes for one chromosome.. It seems that there is some IO speed issue with the disk partition you're using. Can you ask your IT team about this particular problem?

Yes, this is a slurm job with 25 cores, but are these reserved for you only? I.e. other can only ask for the remaining ones during the time you have those? If all users ask for a total of 100 cores where you have only 25 available, this can lead to huge speed issues.

`snp_fastImputeSimple()` should be very fast (almost just the time to read the data in basically).

**Comment by xuyu-cam** [comment]
Thanks Florian!

I've now upgraded the packages and the speed problem with using `as_SFBM(corr0, tmp)` still stays. 

I will raise this issue to the IT department on this. But I am not sure whether they can fix this if it involves something large. Meanwhile, I am just wondering can we just load all the correlation data to the memory for simplicity as we do have this size of memory.

Yes. the 25 cores are all reserved for the job. But one node has 32 cores in total and other users can request and use the remaining 7 cores on the same node. Also, it probably will be the case that all the users on the same node will share the I/O. Not sure whether this would be a problem.

Re `snp_fastImputeSimple()`, I can re-try but I didn't get any luck previously.

**Comment by privefl** [comment]
Writing the data for chromosome 1 at the beginning should be writing 3-4 GB, this is not large data at all.
It should be quite fast (as I said, < 2 min).
This is not normal that it takes you so much time.

**Comment by xuyu-cam** [comment]
What I found is it actually finished writing for the chr 1 which is 2.9G, but it just can't end the writing and continue the run (hanging over there forever).

**Comment by privefl** [comment]
It seems that memory-mapping just does not work properly on your system.
I can't do anything for you, you need to ask your IT dep about this.

**Comment by xuyu-cam** [comment]
Thanks! I am still in communicating with our IT team. 

Meanwhile, regardless of the problem with `as_SFBM(corr0, tmp)`, the current implementation using bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp) seems working no problem. It worked ok with various other smaller variant sets, like 60,000 variants or so. 

It just takes way too long with the `snp_ldpred2_grid` when I switch to the set with over 1M variants (still `bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp)` is ok). Do you think it is because I will have to use `as_SFBM(corr0, tmp)` to improve the efficiency ?

**Comment by privefl** [comment]
Using `as_SFBM(corr0, tmp)` will use memory-mapping to write to the file, but should be much faster than with the previous version. This is why I say that you have problem with memory-mapping.

LDpred2 always uses memory-mapping, and most of the functions of bigstatsr and bigsnpr do, so this is really a problem.

**Comment by xuyu-cam** [comment]
While awaiting responses from the IT team, I'm just wondering whether we can load all the correlation matrix to the memory instead of using the mapping?  (really in case the IT team also can't do anything)

**Comment by privefl** [comment]
The problem with in-memory is that when you start using parallelism, you copy the data for each core you have..

**Comment by xuyu-cam** [comment]
Hello Florian,

Thank you for your time and help again.

Just to give you some updates: by working with our IT team, we located the problem is with the file system on our cluster.

We have `Lustre` on our system which is quite unfriendly with jobs involving many metadata operations, which slows down the job a lot. Obviously, we can't change the filesystem. So we now solved the problem by using ramdisks (requesting extra memory for saving the file), i.e. using ram as disks and saving the temp file under ramdisk . However, this solution has a limitation which is it can only have temp files up to 96G (half of the memory of the whole node). 

I also tested the speed with `snp_fastImputeSimple()` using a machine of 20 cores, which takes about two hours. I think this much slower speed, compared with what you mentioned above, is also because of the large amount of metadata operations with the filesystem using memory mapping. However, the genotype data is much larger and we can't use ramdisk here, so probably there is nothing we can do for this.

**Comment by privefl** [comment]
I'm sorry you have such a special working environment, and can't use the packages.

**Comment by xuyu-cam** [comment]
Hi Florian,
Just to clarify, I believe we CAN use your package to train all the betas. But considering we don't have an efficient option for `snp_fastImputeSimple() `, we will have to just use plink to do all the score calculation and validation to get around the limitation.

**Comment by privefl** [comment]
What is the size of the data you're trying `snp_fastImputeSimple()` on?

**Comment by xuyu-cam** [comment]
.bk file is 500G

**Comment by privefl** [comment]
Ok then I guess it can take 2 hours if your system is not that fast for reading from disk.
