### ISSUE TITLE
Installation Error - lgfortran on Mac

### ISSUE THREAD

**Issue by lizilla1993** [privefl/bigsnpr#2]
Hello,

I have successfully installed bigstatsr but get the following error when I try to install bigsnpr with `devtools::install_github("privefl/bigsnpr")`:

```

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bigsnpr.so] Error 1
ERROR: compilation failed for package ‘bigsnpr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/bigsnpr’
Installation failed: Command failed (1)
```

Thanks.

**Comment by privefl** [comment]
Hello,

Try this command from [this blog post](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error)
```
curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
```

**Comment by brunogrande** [comment]
I ran into the same issue was able to solve it by running the appropriate installer from [this page](https://gcc.gnu.org/wiki/GFortranBinaries#MacOS). Note that I had gfortran already installed via homebrew, but I suppose R wasn't locating those Fortran libraries.
