### ISSUE TITLE
Discard some variants in LDpred2

### ISSUE THREAD

**Issue by privefl** [privefl/bigsnpr#201]
Would allow for using a global SFBM (e.g. for all HM3 variants) and then just discarding variants not matched with the sumstats for different phenotypes (instead of having to construct a subset of the SFBM).

- For LDpred2-grid and -auto, I think I could just set corresponding `curr_beta` to 0 and remove index from `order`
- Probably the same for lassosum2
- What about LDpred2-inf? Enough to set `curr_beta` to 0? (probably not)

**Comment by privefl** [comment]
Is this really needed?

Writing a new `SFBM` is quite fast now.

**Comment by mglev1n** [comment]
Any chance of reconsidering this option/feature? I'm currently trying to generate PRS for dozens of different traits using summary statistics that each contain slightly different SNPs. Although writing any individual SFBM is relatively fast, reading/writing many mostly redundant massive (~30GB) files is still quite inefficient. Storage is so cheap these days that saving a single global SFBM of that size is no big deal, particularly given the potential speed gains when iterating through many different phenotypes.

If this feature isn't developed further, would another option be to compute a global SFBM using something like this:
```
tmp <- tempfile(tmpdir = "tmp-data")

for (chr in 1:22) {

  cat(chr, ".. ", sep = "")

  corr_chr <- readRDS(paste0("data/corr_hm3_plus/LD_with_blocks_chr", chr, ".rds"))

  if (chr == 1) {
    corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
  } else {
    corr$add_columns(corr_chr, nrow(corr))
  }
}
```
And then subset the indices for the appropriate SNPs for a given phenotype in the call to `snp_ldpred2_auto`?
```
snp_ldpred2_auto(corr = corr[indices, indices], ...)
```

**Comment by privefl** [comment]
Again, is this feature really needed?
I think it takes less than 5 min to make the new SFBM anyway.
Then you can always delete it after doing the computations.

- Making a subset copy of the SFBM would be the same basically (computation and space -wise).

- Allowing LDpred2 to use a subset of the SFBM without making a copy of it should probably be possible by just looping over the indices of interest. I will think about it.

**Comment by privefl** [comment]
I've prototyped this for lassosum2, and it seems to work fine and not be hard to implement.
This would be basically a new parameter `ind.corr`, which would be used to "subset" `corr`, as if `corr[ind.corr, ind.corr]` was used instead.
Is this what you want?

**Comment by mglev1n** [comment]
This sounds right - thanks for considering.

**Comment by privefl** [comment]
This should be implemented now.
Please try the new GitHub version.
