### ISSUE TITLE
Error when using snp_ldsc(): Missing value where TRUE/FALSE needed. 

### ISSUE THREAD

**Issue by alovdom** [privefl/bigsnpr#202]
Hi Florian, 

I'm trying to calculate PRS with LDpred2 and have been primarily following your code from the [example with provided LD reference. ](https://github.com/privefl/paper-ldpred2/blob/master/code/example-with-provided-ldref.R) I'm trying to calculate the heritability now with the following code: 

`ldsc <- with(df_beta, snp_ldsc(ld,ld_size = nrow(df_beta),
                               blocks = 200, 
                               chi2 = (beta / beta_se)^2,
                               sample_size = n_eff,
                               ncores = NCORES))`

However, I  am getting the following error: 
` Error in { : task 1 failed - "missing value where TRUE/FALSE needed" `

I think the error is being caused by some if-else statement of some sort because I don't have any missing values in the df_beta dataframe. 

Any insight to how I can resolve this issue would be appreciated. 

Best, 

Alicia

**Comment by privefl** [comment]
Please try to rerun it line by line, using `debugonce(snp_ldsc)` before.

**Comment by alovdom** [comment]
Okay, this is the line of code where I receive the original error: 
`delete_values <- foreach(ic = 1:n_blocks, .combine = "cbind") %dopar%
    {ind_rm <- ind_blocks[[ic]]
     snp_ldsc(ld_score[-ind_rm], ld_size, chi2[-ind_rm], sample_size[-ind_rm],
      NULL, intercept, chi2_thr1, chi2_thr2)}`

If I change the option to `blocks = NULL`, then this is the error I receive "`Error in if (max(abs(pred - pred0)) < 1e-06) break : missing value where TRUE/FALSE needed`" with the code  `if (max(abs(pred - pred0)) < 1e-06) break`.

**Comment by privefl** [comment]
This is very helpful with `blocks = NULL`.

I now remember seeing this when there were some chi2 equal to 0, but this should have been fixed a while ago with 
https://github.com/privefl/bigsnpr/blob/master/R/ldsc.R#L73

Can you check `summary(with(df_beta, (beta / beta_se)^2))`?

Or again, rerun line by line with `blocks = NULL`.

**Comment by alovdom** [comment]
Okay, I get this
`summary(with(df_beta, (beta / beta_se)^2))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  86.45 1901.11 3233.47 2974.41 4153.84 5415.46
`
Is it normal for me to have such large chi2 values?

**Comment by privefl** [comment]
No, it's not normal.
You should have a lot of values between 0 and 30.

**Comment by alovdom** [comment]
Okay, that was the problem. I've fixed the chi2 values and now the code runs. Thanks for your help!

**Comment by SoleilChenxu** [comment]
> 

Hi, I have the same problem here, if you still remember,could you please let me know how you fixed the chi2? Thanks!
