### ISSUE TITLE
Error when reading bed files

### ISSUE THREAD

**Issue by JuRaGa** [privefl/bigsnpr#203]
Hi!

I am trying to use the "bed_projectPCA" function, but I am stuck at generating the bed objects with the bed() function. This is the error I get:

bedfile <- system.file("extdata", "example-missing.bed", package = "bigsnpr")
obj.bed <- bed(bedfile)

Error in data.table::fread(input, ..., data.table = data.table, nThread = nThread) :
  nThread >= 1L is not TRUE

Thank you,

**Comment by privefl** [comment]
Please see https://github.com/privefl/bigsnpr/issues?q=is%3Aissue+nThread+%3E%3D+1L+is+not+TRUE.

**Comment by JuRaGa** [comment]
Thank you! Now I don't get this error.

How can I save or see the output from the bed_projectPCA() function? I 
would like to plot PC1 versus PC2 and perform clustering to detect the 
underlying ethnicity.

Thanks again

**Comment by privefl** [comment]
To infer ancestry based on PCA, have a look at the corresponding supp note of https://doi.org/10.1101/2021.02.05.21251061 (and at the associated code with it).

**Comment by JuRaGa** [comment]
Thank you!
