### ISSUE TITLE
Attempting to run lassosum2

### ISSUE THREAD

**Issue by alovdom** [privefl/bigsnpr#204]
Hello, 

I'm currently trying to implement lassosum2, but it seems like the function `snp_lassosum2` is not in my version of bigsnpr. I tried to download the most recent version of bigsnpr with `remotes::install_github('privefl/bigsnpr')` and `install.packages("bigsnpr")` but the function does not come up after I run either of them.  Is lassosum2 and all of the functions to run it available on bigsnpr already?

Best, 

Alicia

**Comment by privefl** [comment]
Yes, it should be. In the GitHub version with `remotes::install_github('privefl/bigsnpr')`.

**Comment by alovdom** [comment]
Okay, I retried running the code and it's there. I have mostly everything working now, but am getting some errors when running 
`params$score <- big_univLogReg(as_FBM(pred_lassosum), y)$score`. 
The errors I get say:  
 `** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  5 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
For 1 columns, IRLS didn't converge; `glm` was used instead.`

Although I get this warning, the function does end up executing and I get values for `params$score`. Do you know why I might be receiving this error?

**Comment by privefl** [comment]
Have a look at https://github.com/statsmodels/statsmodels/issues/3596 or https://github.com/statsmodels/statsmodels/issues/5396, that I found a simple google search of "On entry to DLASCLS parameter".

**Comment by privefl** [comment]
Any update on this?

**Comment by alovdom** [comment]
Hi Prive, sorry for the delayed response-- I had to step away from my analysis for awhile. I started playing around with my code again and I'm not sure what I may have done to resolve the issue but  I'm not receiving the error anymore.
