### ISSUE TITLE
Error from snp_grid_stacking() when lpS has NA values

### ISSUE THREAD

**Issue by ClaraAlbi** [privefl/bigsnpr#205]
I am trying to compute an SCT PRS using the function snp_grid_stacking().

I get the following error: 

Error in 1L + sapply(lpS, function(lp) sum(lp > lpS_thr)) : non-numeric argument to binary operator

It think it is because the vector of -log10(pvalues) used to compute the multiPRS object has NA values, I included NA values in order not to subset the G matrix.

Any ideas on how to fix this? Thank you!

**Comment by privefl** [comment]
Did you follow the tutorial at https://privefl.github.io/bigsnpr/articles/SCT.html?

To "subset without subsetting" in SCT, you need to put missing values in beta and in lpval for variants you don't want to use, and then use `exclude = which(is.na(lpval))` in `snp_grid_clumping()`.
Then you should not have any issue with these missing values.

**Comment by ClaraAlbi** [comment]
Yes, I did follow the tutorial and excluded the NA values.

Then the error might come from something else, any ideas?

Thanks!

**Comment by privefl** [comment]
What is `summary(lpval)`? And `packageVersion("bigsnpr")`?

**Comment by ClaraAlbi** [comment]
![Uploading Screenshot 2021-04-12 at 15.48.28.png…]()

**Comment by privefl** [comment]
The screenshot didn't work. You just need to drag and drop in the text normally.

**Comment by privefl** [comment]
Any update on this?
