### ISSUE TITLE
Not enough variants have been matched

### ISSUE THREAD

**Issue by jialiwang1211** [privefl/bigsnpr#206]
Hi Florian, 

I have 750k variants in my summary statistics file and 500k variants in my study cohort. When I ran 'snp_match', it showed the following error message:

```
749,970 variants to be matched.
552 ambiguous SNPs have been removed.
Some duplicates were removed.
88,948 variants have been matched; 44,487 were flipped and 47,826 were reversed.
Error: Not enough variants have been matched.
```

I tried to switch a0 and a1 just in case the alt/ref alleles are reversed but it did not work. 

Any help would be appreciated!

**Comment by privefl** [comment]
Please look at the documentation of the function. There is a parameter to control for this.

**Comment by jialiwang1211** [comment]
Thank you! It worked by changing 'match.min.prop'.
