### ISSUE TITLE
LDpred2 convergence issue

### ISSUE THREAD

**Issue by getian107** [privefl/bigsnpr#207]
Hi Florian- I’m trying to implement and test run LDpred2 on simulated data, starting with some standard settings (1% causal variants; normally distributed effect sizes; h2=0.5; 100000 EUR training samples). The data for the reference panel is exactly the same as those I used to build the LD reference for PRS-CS. LDpred2 doesn’t converge on the simulation data, producing posterior effect sizes on the order of 1e+25 or larger. Have you seen such non-convergence issues before or do you have any idea what might be causing the issue? I attached my script below for your reference. Thanks in advance!

```
library(bigsnpr)

frac <- "1.0"
ovlp <- "100"
rg <- "0.7"
sst <- "pve50_100000EUR_trn"
n_trn <- "100000"
ref <- "eur"
sim <- "1"


SIM_DIR <- "/data/tge/Tian/PRScsx/sim"

# read sumstats
sst_file <- paste0(SIM_DIR, "/sumstats/sst_frac", frac, "_ovlp", ovlp, "_rg", rg, "_", sst, "_sim", sim)
sumstats <- bigreadr::fread2(sst_file)
sumstats$n_eff <- as.integer(n_trn)
names(sumstats) <- c("chr", "rsid", "pos", "a0", "a1", "beta", "beta_se", "p", "n_eff")

tmp <- tempfile(tmpdir = paste0(SIM_DIR, "/ldpred2_tmp"))
on.exit(file.remove(paste0(tmp, ".sbk")), add = TRUE)

# read reference files
ref_file <- paste0("/data/tge/Tian/UKBB_full/projects/genome_pred/1kgp/g1000_", ref, "/", ref, "_software/g1000_", ref, "_hm3.rds")
obj.bigSNP <- snp_attach(ref_file)
map <- obj.bigSNP$map[-3]
names(map) <- c("chr", "rsid", "pos", "a0", "a1")

# match SNPs
info_snp <- snp_match(sumstats, map)

genotype <- obj.bigSNP$genotypes
CHR <- map$chr
POS <- map$pos

UTL_DIR <- "/data/tge/Tian/Software"
POS2 <- snp_asGeneticPos(CHR, POS, dir=paste0(UTL_DIR, "/ldpred2"))

for (chr in 1:22) {
    print(chr)

    ind.chr <- which(info_snp$chr == chr)
    ind.chr2 <- info_snp$`_NUM_ID_`[ind.chr]

    corr0 <- snp_cor(
            genotype,
            ind.col = ind.chr2,
            infos.pos = POS2[ind.chr2],
            size = 3 / 1000
        )
    if (chr == 1) {
        ld <- Matrix::colSums(corr0^2)
        corr <- as_SFBM(corr0, tmp)
    } else {
        ld <- c(ld, Matrix::colSums(corr0^2))
        corr$add_columns(corr0, nrow(corr))
    }
}

# ld score regression
df_beta <- info_snp[,c("beta", "beta_se", "n_eff", "_NUM_ID_")]
ldsc <- snp_ldsc( ld, 
                  length(ld), 
                  chi2 = (df_beta$beta / df_beta$beta_se)^2,
                  sample_size = df_beta$n_eff, 
                  blocks = NULL)
h2_est <- ldsc[["h2"]]

# ldpred2-grid 
p_seq <- signif(seq_log(1e-2, 1e-2, length.out = 1), 2)
h2_seq <- round(h2_est, 4)
grid.param <- expand.grid(p = p_seq,
                          h2 = h2_seq,
                          sparse = FALSE)

beta_grid <- snp_ldpred2_grid(corr, df_beta, grid.param)
```

**Comment by privefl** [comment]
Hi Tian,

- Which `packageVersion("bigsnpr")` do you have?

- Could you produce and show me the QC plot as in https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html#exercises-ldpred2-and-lassosum2?

**Comment by getian107** [comment]
Hi Florian,

I'm using version 1.6.1

The equation to calculate the standard deviation of the genotype looks odd to me:
```2 / sqrt(n_eff * beta_se^2 + beta^2)```

What is your suggested equation for quantitative traits?
I'm not sure it's possible to calculate the standard deviation of the genotype without knowing phenotypic variation, as you are basically saying that we can infer the allele frequency of each variant from summary statistics (marginal beta, se of beta and sample size) only?

**Comment by privefl** [comment]
Yes, this is for binary traits. Replace `2` by `sd(y)` for quantitative traits.

**Comment by getian107** [comment]
I used ```sd(y) / sqrt (n_eff * beta_se^2)``` as the estimated sd of genotypes from summary stats.
A total of 84 SNPs out of ~1.1m SNPs were identified as "bad" SNPs; the large majority of them had sd_ss slightly below 0.1.
Removing these bad SNPs does not resolve the convergence issue.

**Comment by privefl** [comment]
Can you show the plot?

Have you tried other p/h2 values in the grid?

**Comment by getian107** [comment]
Here is the qc plot, which looks good I think:
[qc.pdf](https://github.com/privefl/bigsnpr/files/6344984/qc.pdf)

h2 estimate was very close to the simulated value.
I tried p grid = 0.001, 0.01 and 0.1

p = 0.1 converged and produced reasonable prediction accuracy.
p =  0.001 and 0.01 didn't converge.

In my previous test runs with an expanded grid, about half of the settings converged and the other half didn't.

Looks like there is some numerical instability in the algorithm?
p = 0.01 corresponded to the true fraction of causal variants simulated so I was expecting the model to converge at least for this setting.

**Comment by privefl** [comment]
Yes, this can happen when there is some misspecification (e.g. between LD and sumstats). 
But, there, you use simulations with in-sample LD, so I'm quite surprised there would be any convergence issue in such case.

Anyway, I'm currently working on adding some shrinkage for overcoming these issues. I can share the code with you if you're interested.

**Comment by getian107** [comment]
I used 1KG samples as the reference to simulate genotypes for a large number of individuals using HAPGEN2, and used 1KG samples as the LD reference in LDpred2. The frequencies and LD patterns matched well between LD and summary stats but it's not strictly an in-sample reference so some mild misspecification can exist.

Thanks for all the very quick response!

**Comment by privefl** [comment]
Hum okay, and it's also a quite small LD ref as well. Not sure whether LDpred2 behave well in such cases without using any shrinkage (e.g. Bjarni recommended using at least 2000 indivs in the ref panel for LDpred).
