### ISSUE TITLE
Choice of grid p for LDpred1 and LDpred2

### ISSUE THREAD

**Issue by eldronzhou** [privefl/bigsnpr#210]
Hi Florian,

I am revising my SDPR manuscript and one reviewer asked me to add LDpred2 for PRS comparison. I notice that you recommend using a grid of hyper parameters p from 10^-5 to 1 on a log-scale for LDpred2. For LDpred1, the grid of p is among 1e-5,3e-5,1e-4,3e-4,0.001,0.003,0.01,0.03,0.1,0.3,1. I was wondering do you have any experience or suggestions to use p of LDpred1, combined with h2 within {0.7, 1, 1.4}, for LDpred2? I asked this because currently running 126 combinations take too long time on our cluster (we are not able to reserve 30 cores in one node) and reducing the size of grid would be great.

Thanks,
Geyu

**Comment by privefl** [comment]
I'm surprised it takes that long. Are you running the latest versions? It should take 3-6 hours with 15 cores IIRC.
What is the size of the .sbk file?
If you really need a smaller grid, you can probably go for `p  = seq_log(1e-4, 1, 10)`, the 3 h2, and choose only one of TRUE or FALSE for `sparse` (then that's a grid of 30, for 30 cores).

**Comment by eldronzhou** [comment]
Thanks for your quick response. I'm running v1.6.1. The size of .sbk is 27Gb. Although reserved for 15 cores, LDpred2 only fully utilized ~2 cores (CPU 183%, Mem 30 Gb, status mostly in D state). It seems that IO process is the bottleneck here.
