### ISSUE TITLE
snp_readBGEN() could not generate .rds file 

### ISSUE THREAD

**Issue by xscapex** [privefl/bigsnpr#211]
Hi Florian,

Thank you so much for creating such convenient package. I have two questions about the **snp_readBGEN()** function and I'm wondering if you could give me some advice.

1. I got the "R session aborted" error when I tried to read **.bgen** file by using **snp_readBGEN()** function. In addition, the function had generated the **.bk file** but there're no **.rds file**. My R version is 4.0.5. The following is the screenshot of my code, is there anything I can do to import the data? 
 
![image](https://user-images.githubusercontent.com/38449391/117241613-22e0ff00-ae66-11eb-8b17-cb1ae013270d.png)

2. I've read your[ sample code](https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-genotypes.R#L1-L62) but I'm not sure whether if I can use "ukb_mfi_chrxx_v3.txt" as **list_snp_id** since in UK biobabnk data showcase **Resouce 531** has  indicated that _The order of markers in these files is not guaranteed to be the same as the BGEN files._

![image](https://user-images.githubusercontent.com/38449391/117241351-8c144280-ae65-11eb-8e88-3405e8dc7146.png)

Thank you and I look forward to hear from you.
Kind regards,
Monica

**Comment by privefl** [comment]
1. I think other people may have had the same problem, and reported it in other issues. Things that come to mind is "do you have enough disk space where you want to write?" (this should be checked in the latest version of {bigstatsr}) and "is it the UKBB BGEN files that they provide or some that you made yourself?".
And yes, this normal that you get the .bk file because it is the first thing that is produced (but probably not filled with any data), and the .rds file is the last thing that is produced.

2. The BGI files are used to find where the variants are stored in the BGEN files, so we don't really care about the order here. This is also why this function need SNP IDs instead of just position indices (as for the individuals).

**Comment by xscapex** [comment]
Hi Florian,

Thank you so much for the prompt reply, I’ll try it and update here!

**Comment by xscapex** [comment]
I have checked my disk space and it seems that it's enough to write. 

`setwd("E:\\readBGEN_test1")
#Load package
library(data.table)
library(bigsnpr)

###############################################################
# Check space                                                 #
###############################################################
#Change R temporary direction

write("TMPDIR = 'E:\\Rtmp'", file=file.path(Sys.getenv('R_USER'), '.Renviron'))
tempdir() #There are 9TB free space

#Check whether we have enough disk space

FBM(500000, 1261158,backingfile="E:\\readBGEN_test1\\test0") #We need 4.58 T space, enough!
FBM(10417, 1261158,backingfile="E:\\readBGEN_test1\\test1") #We need 98 G space, enough!

file.remove("test0.bk")
file.remove("test1.bk")`

The bigsnpr required Rcpp package, so I have installed it and make sure the Rtools work.

 `###############################################################
# Check Rcpp/Rtools                                           #
###############################################################

Rcpp::evalCpp("2+2") #this could output 4`


snp_readBGEN() required list_snp_id and I make sure it must be the form **<chr>_<pos>_<a1>_<a2>**.
I create the  list_snp_id from **ukb_mfi_chr21_v3.txt** which was provided by UK biobank.

`################################################################
# list_snp_id                                                  #
################################################################

list_snp_id <- fread("snpid_chr21.txt",header=F)

list_snp_id <- as.list(list_snp_id)`

This is how my list_snp_id looks like:

![image](https://user-images.githubusercontent.com/38449391/117435734-c1518b00-af60-11eb-9080-7d26858cd061.png)

I first read the .BGEN file which was provided by UK biobank but I got the session error.

`###############################################################
# Trial 1: read BGEN without subset                   #
###############################################################

rds <- snp_readBGEN( bgenfiles="ukb_chr21_v3.bgen",backingfile = "test2",ncores = nb_cores(),list_snp_id)

#this got session aborted error`

Then I create the subset file which contain 10,417 cases but got the same error, too.

`################################################################
# Trial 2: read BGEN subset                           #
################################################################

#Create a bgen subset

cmd <- paste0("plink2 --bgen ukb_chr21_v3.bgen ref-first --sample ukb22828_c21_b0_v3_s487268.sample --keep positive_list_10417.txt --export bgen-1.2 --out ukb_chr21_v3_10417")
system(cmd)

rds <- snp_readBGEN( bgenfiles="ukb_chr21_v3_10417.bgen",backingfile = "test3",ncores = nb_cores(),list_snp_id=list_snp_id)

#this got session aborted error `


I found that some of the list_snp_id  were strange, such as **21_19467441_CAA_C**. So I only use the one normal list_snp_id to read BGEN but still error,

`###############################################################
# Trial 3: only include 1 snp                                   #
###############################################################

snp1 <- list_snp_id[[1]][1] #snp1="21_9411239_G_A"

snp1 <- as.list(snp1)

rds <- snp_readBGEN( bgenfiles="ukb_chr21_v3_10417.bgen",backingfile = "test4",ncores = nb_cores(),list_snp_id=snp1)

#this got session aborted error`

I have no idea how to fix the problem. Was my list_snp_id wrong?


Thanks,
Monica

**Comment by privefl** [comment]
Can you try specifying a subset of individuals? 
And also with `ncores = 1`.
Are you using some specific environment, like conda?

**Comment by xscapex** [comment]
1. Try ind_row=1 and ncores=1, still doesn't work.

`rds <- snp_readBGEN( bgenfiles="ukb_chr21_v3_10417.bgen",backingfile = "F:\\readBGEN\\test4",ncores = 1,list_snp_id=snp1,ind_row = 1)`

2. No, I'm not using conda or other specific environment. In addition, the following is my R and the packages version.

![image](https://user-images.githubusercontent.com/38449391/117617945-d9631d80-b19f-11eb-8ff7-98680036ee1e.png)

**Comment by xscapex** [comment]
`rds <- snp_readBGEN( bgenfiles="ukb_chr21_v3_10417.bgen",backingfile = "test4",ncores = 1,list_snp_id=snp1,ind_row = 1)`

It still got session error, maybe I should use R 3.x.x version?

**Comment by privefl** [comment]
You can try, but the version that you're using is the CRAN version, right?
This is checked on all kinds of architectures and the newest versions of R.

**Comment by privefl** [comment]
Could it be due to a corrupted file like in https://github.com/privefl/bigsnpr/issues/212?

**Comment by privefl** [comment]
Any update on this?

**Comment by xscapex** [comment]
Hi Florian,

Thank you so much for the eply, I’ll try it next week and update here!

**Comment by privefl** [comment]
Any update on this?

**Comment by xscapex** [comment]
Hi Florian,

Sorry for the late reply. I have checked the  .bgen files and the md5 number are as same as UKBB (attached file). 
Still can't figure out why snp_readBGEN() could not generate .rds file. Maybe I should remove the missing value before I use snp_readBGEN().

![image](https://user-images.githubusercontent.com/38449391/125036405-8c2ef980-e0c5-11eb-9364-a690e5a97392.png)

**Comment by privefl** [comment]
Can you remind me of the exact issue you have?

What do you mean exactly by "Maybe I should remove the missing value before I use `snp_readBGEN()`."?

**Comment by privefl** [comment]
Looking at the md5sums, it seems the one for chromosome 5 is different; it should be `45f95365b17d4530a42faf95a70deddd`.
