### ISSUE TITLE
HapMap3 reference

### ISSUE THREAD

**Issue by NaokiKatsuragawa** [privefl/bigsnpr#213]
Bonjour Florian,

I love to use LDpred2 for my population research. 
Let me ask you a small question, I am sorry if you already write somewhere. 

I plan to use HapMap3 variants from the link below, and then further filter by MAF of my data(as you did in your paper)
https://github.com/privefl/bigsnpr/tree/master/data-raw/hm3_variants.rds
I believe third column "pos" is "hg19", correct? 
I found other column named "pos_hg19", so I just want to reconfirm this. 

All the best, 
Naoki

**Comment by privefl** [comment]
You can use 
```r
# $pos is in build GRCh37 / hg19, but we provide positions in 3 other builds 
info <- readRDS(url("https://ndownloader.figshare.com/files/25503788"))
str(info)
```
There is also hg17, hg18, and hg38 there.

**Comment by NaokiKatsuragawa** [comment]
Thank you for your quick reply. 
As far as I understand, "https://ndownloader.figshare.com/files/25503788" is filtered by European MAF, which I achieve 900K variants after MAF filtering by my population data.  Whereas I have 950K when I start with "hm3_variants.rds".

**Comment by privefl** [comment]
These have been processed after some quality control.
The original HM3 list contains more than 1.3M variants IIRC.

**Comment by NaokiKatsuragawa** [comment]
Then, I should use your quality controlled one. 
Thank you again for your sincere response.  Merci beaucoup.
