### ISSUE TITLE
HapMap3 deleted file

### ISSUE THREAD

**Issue by clairepalles** [privefl/bigsnpr#214]
Please could you provide some advice about which SNPs in our genotyping files to use for LDpred now that the hapmap3 file has been removed from the raw folder?  We thought the advice from the tutorial was to only use hapmap3 SNPs.  Please advise how to select SNPs?

**Comment by privefl** [comment]
Please use the ones from the tutorial
`info <- readRDS(url("https://ndownloader.figshare.com/files/25503788"))`

**Comment by clairepalles** [comment]
Thanks very much!


________________________________
