### ISSUE TITLE
Missing values in genotype matrix even after doing imputation - create error while running bigsnpr

### ISSUE THREAD

**Issue by tahseen-igib** [privefl/bigsnpr#215]
Hi 

I read the issue raised regarding missing value error. However, i am confused that even after performing imputation, my genotype matrix still has NA values. I did imputation using standard imputation tools. Do i need to do it again?

**Comment by tahseen-igib** [comment]
I read imputed bed file only. Imputation was done using Minimac

**Comment by privefl** [comment]
bed files are not supposed to store imputed data, as you can store only 0/1/2/NA.
I know that PLINK replaces some missing values when the imputation probability is not certain enough.
E.g., if you have P(0) = P(1) = P(2) = 1/3, then it can't really choose between one of them, so it just puts NAs.

**Comment by privefl** [comment]
Any update on this?
