### ISSUE TITLE
Error in format_snp_id(list_snp_id[[ic]]) :   Wrong format of some variants.

### ISSUE THREAD

**Issue by pjordab** [privefl/bigsnpr#216]
Hi Florian and users, 

I am using the function

snp_readBGEN(
  bgenfiles   = glue::glue("chr{chr}.bgen", chr = 1:22),   
  backingfile = ".",
  list_snp_id = as.list(glue::glue("chr{chr}.SNP_ID_LIST", chr = 1:22)),   
  ind_row = NULL,
  read_as = c("dosage"),
  ncores = 30
)

list_snp_id files are in this format, as specified in the tutorial:
22_15920698_C_T
22_16149547_C_T

I get this error:
Error in format_snp_id(list_snp_id[[ic]]) :
  Wrong format of some variants.

I have already filtered variants and I only have alleles containing A,C,T,G and also restricted to biallelic SNPs.

I'd appreciate any help. 

Many thanks!

**Comment by privefl** [comment]
Can you look at the file where it saves all these variants not matched?
If this is the case for all variants, try switching the alleles.

PS: I think this issue has already been reported here once or twice.

**Comment by pjordab** [comment]
Can you look at the file where it saves all these variants not matched? - Which file?

If this is the case for all variants, try switching the alleles. - I've switched the alleles in the list_snp_id file and I got the same error.

PS: I think this issue has already been reported here once or twice. - Sorry, I did not find the issue before posting, neither now, if you have the link I can look at the previous conversation.

Many thanks!

**Comment by privefl** [comment]
I am sorry, I think I'm mistaking between two issues when I'm talking about switching alleles, you can forget about that part.

You can check which one has a wrong format using
```r
snp_id2 <- ifelse(substr(snp_id, 2, 2) == "_", paste0("0", snp_id), snp_id)
(ind <- which(substr(snp_id2, 3, 3) != "_"))
snp_id[ind]
```

**Comment by pjordab** [comment]
Many thanks, it is solved!

**Comment by privefl** [comment]
Can you please explain what was the issue?
(in case others have the same problem)

**Comment by pjordab** [comment]
Sure. The input was not appropriate, as it was reading a list of files
instead of a list of vectors. I used your code to create the list of
vectors:
https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-genotypes.R
Thanks again!

Missatge de Florian Privé ***@***.***> del dia dt., 18 de
maig 2021 a les 10:10:
