### ISSUE TITLE
MAF versus effect allele frequency

### ISSUE THREAD

**Issue by pjordab** [privefl/bigsnpr#220]
Hi Florian and users,

I have a doubt regarding the sumstats:

To what I understand:
- a1 is the effect allele
- beta and beta_se are referred to a1
- We need to provide the MAF instead of the effect allele freq. When using the MAF should it be related to a1 so be the a1 always the minor allele? 

For example, if in my sumstats I have: 

a1: A    a0: G    EAF: **0.65**    beta: 0.02 

and I convert the EAF to MAF:

Should I only modify the frequency?

1) a1: A a0: G MAF: **0.35** beta: 0.02

Or should the MAF be also referred to a1 and I need switch alleles and corresponding beta effect?

2) a1: **G** a0: **A** MAF: **0.35** beta: **-0.02**

Many thanks again!!

Paloma

**Comment by privefl** [comment]
Hi,

Where are you using the frequencies?

**Comment by pjordab** [comment]
In the summary statistics file

**Comment by privefl** [comment]
What summary statistics file?
What are you trying to do?
Please give more details.

**Comment by pjordab** [comment]
Sure.
I’m using LDpred2. My question regarding MAF is referred to the summary statistics file used for the LDpred2 analysis. 
Thanks you!

**Comment by privefl** [comment]
Frequencies are not required to run LDpred2, only beta, beta_se and n_eff are needed, so I don't quite understand what you're referring to.

**Comment by privefl** [comment]
Please follow [this tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html).
