### ISSUE TITLE
Question: Do we need bigsnpr imputation in UK biobank imputation data?

### ISSUE THREAD

**Issue by jasmine9764** [privefl/bigsnpr#222]
Dear Florian,
Thank you for developing such an amazing tool.
As we found that there are still missing variants in UKB imputation and found it is possible to impute genotyped variants in bigsnpr, we are wondering: 
1.Do you have experience on imputing ukb imputation data? (72m SNPs after QC) Would this method improve our predictive accuracy?
2.How much of CPU scale, computational power and time effort needed?

We look forward to learning from your experience. Thank you in advance!

**Comment by privefl** [comment]
Hi,

0. I have never found any missing values in the UKBB BGEN data; are these rare variants? Could you share one of these variants (`<chr>_<pos>_<a0>_<a1>`) please?

1. I have only imputed genotyped data. Not sure about imputing already imputed data. I guess it would depend on many things, including the number of missing values (cf. I need to check some of them).

2. Again, depends on the number of (variants with) missing values.

**Comment by privefl** [comment]
This the code I have just tried:
![image](https://user-images.githubusercontent.com/11161036/120456551-03ba8c00-c396-11eb-92d1-d927a9513ae6.png)

I don't see any missing values in my data.
What could be different?

**Comment by privefl** [comment]
Please verify that the UKBB files have been downloaded properly.
By e.g. comparing md5sums `tools::md5sum("ukb_imp_chr1_v3.bgen"`) with the ones there: https://biobank.ctsu.ox.ac.uk/crystal/refer.cgi?id=997.
