### ISSUE TITLE
Question about not being able to take full advantage of CPU and memory

### ISSUE THREAD

**Issue by David-OSS** [privefl/bigsnpr#223]
Hi, 

We are trying to impute UK BioBank bed data but we found that the bigsnpr only consumed 3-5% CPU and very few memory. Our machine has 44 physical cores and over 300G memory.  Is this a known issue or by design ? any way to improve the HW utilization ?

Thanks

**Comment by privefl** [comment]
Which of the imputation functions are you talking about?

Why not directly using BGEN data?

**Comment by David-OSS** [comment]
snp_fastImpute. As for the BGEN, does it have any missing value ?

Thanks

**Comment by privefl** [comment]
`snp_fastImpute()` should use 100% CPU (if 100% CPU = 1 core).
IIRC, you can parallelize over chromosomes, and I think there is a discussion on how to parallelize further in another issue here.

UKBB BGEN data should not have any missing values, as it is already imputed data.
