### ISSUE TITLE
Recoding values in FBM.code256 matrix

### ISSUE THREAD

**Issue by linoferreira** [privefl/bigsnpr#224]
I'm using `bigsnpr` to read UK Biobank imputed data into R, which gives me a `bigSNP` object with an `FBM.code256` matrix as its first element:

```
geno_rds <- snp_readBGEN(bgen,
                              backingfile = paste0('chr', chr),
                              list_snp_id = list(variant_ids),
                              ind_row = sample_ids,
                              read_as = "dosage")
geno <- snp_attach(geno_rds)
```
```
> class(geno)
[1] "bigSNP"
> class(geno$genotypes)
[1] "FBM.code256"
attr(,"package")
[1] "bigstatsr"
```

This is working very well and giving the expected results, with dosages read correctly and rounded to two decimal places as mentioned in the documentation.

I would now like to recode some of the variants in this data so that the reference allele is counted instead of the alternative allele or vice-versa.

For example (with made-up numbers), I would like to change the third column of the `geno$genotypes` matrix from:
```
       [,3]
[1,]     0
[2,]   0.2
[3,]   1.7
[4,]     2
```
to:
```
       [,3]
[1,]     2
[2,]   1.8
[3,]   0.3
[4,]     0
```

I've tried to do `geno$genotypes[,3] <- 2 - geno$genotypes[,3]` but this gives errors of this type:
```
Warning message:
In replaceMatOne(x$address_rw, i, j, value[1]) :
  At least one value changed (1.8 -> 2)
  while converting from R type 'double' to C type 'unsigned char (raw)'.
```
It seems that, while integer allele counts are recoded correctly, dosages are rounded to the nearest integer in the process.

Is it possible to do this kind of simple changes to the matrix while keeping the 2 decimal place precision for imputed dosages?

Thank you very much for your time and work in developing this package.

**Comment by privefl** [comment]
Under the hood, unsigned chars are used (one-byte unsigned ints -> from 0 to 255), and decoded using the code.
Here the code is `bigsnpr::CODE_DOSAGE`.
```r
> bigsnpr::CODE_DOSAGE
 [1] 0.00 1.00 2.00   NA 0.00 1.00 2.00 0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08
[17] 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24
[33] 0.25 0.26 0.27 0.28 0.29 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40
[49] 0.41 0.42
 [ reached getOption("max.print") -- omitted 206 entries ]
```
Therefore, 0-3 are decoded as 0, 1, 2 and NA; 4-6 as 0-2; and 7-207 as 0, 0.01, 0.02,..., 1.99, 2.
This is explained e.g. at https://privefl.github.io/bigsnpr-extdoc/inputs-and-formats.html#in-bigsnpr.

What you need is therefore `7 + 100 * (2 - geno$genotypes[,3])`, or `207 - 100 * geno$genotypes[,3]`.

**Comment by linoferreira** [comment]
Thank you very much for this very prompt and detailed reply, I appreciate it.

I've tried both `7 + 100 * (2 - geno$genotypes[,3])` and `207 - 100 * geno$genotypes[,3]` and they work great. The resulting output is not exactly identical (in ~1% of cases there's a difference of 0.01) but I imagine this is expected and the precision is certainly good enough for my use case.

One small issue is that both operations give a warning. When doing `7 + 100 * (2 - geno$genotypes[,3])` I get:
```
Warning message:
In replaceMat(x$address_rw, i, j, value) :
  At least one value changed (9 -> 9)
  while converting from R type 'double' to C type 'unsigned char (raw)'.
```
and when doing `207 - 100 * geno$genotypes[,3]` I get:
```
Warning message:
In replaceMat(x$address_rw, i, j, value) :
  At least one value changed (97 -> 96)
  while converting from R type 'double' to C type 'unsigned char (raw)'.
```

Am I right in thinking that this is due to the conversion from a 0-based index in C to a 1-based index in R and so ignorable?

Thank you again for your help!

**Comment by privefl** [comment]
Hum, numerical issues..
`all.equal(as.integer(207 - 100 * seq(0, 2, by = 0.01)), 207:7)` is not TRUE.., right.

Seems, you need to use `207 - round(100 * seq(0, 2, by = 0.01))` instead.

**Comment by privefl** [comment]
The reason is 
```
> print(207 - 100 * 1.1, digits = 22)
[1] 96.999999999999986
```
is therefore converted to int 96 (instead of 97, which you can get using floor)

**Comment by linoferreira** [comment]
Thank you very much for the explanation, that makes sense!

Your suggestion of using `round()` fixed the warnings and I now get identical results for `7 + round(100 * (2 - geno$genotypes[,3]))` and `207 - round(100 * geno$genotypes[,3])`.

Thanks again for your help, really appreciate it!
