### ISSUE TITLE
Using Alternate LD Reference Panels

### ISSUE THREAD

**Issue by lizlitkowski** [privefl/bigsnpr#225]
Dear Dr. Privé,

I have been using your code to create a PRS for an asthma study that I am working on with participants of Hispanic ancestry.  I have been using the HapMap reference panel that you previously prepared as a starting point.

However, I am interested in using the TopMed reference panel which has a broader reach of ancestries.  Can you tell me how you built the HapMap reference panel? 

Thanks so much for your time.  
Best,
Liz

Liz Litkowski
Doctoral Research Assistant
University of Colorado 
Anschutz Medical Center

**Comment by privefl** [comment]
You can compute LD matrices using `snp_cor()`.

There is the code I used to provide the LD ref in the paper: https://github.com/privefl/paper-ldpred2/blob/master/code/provide-ld-ref.R.

Please ask if there is something you do not understand in the code.

**Comment by lizlitkowski** [comment]
Thanks for your help....now off to find the source of the reference panel itself!

**Comment by privefl** [comment]
If you get your hands on this data, it would be interesting to define ancestry groups there (following supp note of https://doi.org/10.1101/2021.02.05.21251061), and share LD refs for these.

**Comment by lizlitkowski** [comment]
Great.  Thanks for all of your advice.  I will see what I can do with the studies I have access to.
________________________________
