### ISSUE TITLE
How do I leverage GPUs when doing snp_fastImpute?

### ISSUE THREAD

**Issue by mengruts** [privefl/bigsnpr#226]
I have a server with 4 GPUs. Wen I run snp_fastImpute() it's not leveraging any of them, only using CPUs all the time.
How do I leverage GPUs to accelerate it?
Thanks!
Regards,
Raymond,

**Comment by privefl** [comment]
You know that using GPUs is not trivial, right?
Package {bigsnpr} is not designed to run with GPUs, sorry.

If you want to look at this yourself, `snp_fastImpute()` is using XGBoost under the hood, maybe there is a way to use GPUs with that.

**Comment by mengruts** [comment]
Thanks @privefl for the prompt reply! Will see if there's any I can contribute.
Regards,
Raymond,

**Comment by privefl** [comment]
Closing for now, feel free to reopen or comment.
