### ISSUE TITLE
A few questions to compute genetic risk scores with LDpred2

### ISSUE THREAD

**Issue by johannfaouzi** [privefl/bigsnpr#227]
Hi,

Thank you for your work in this library. I'm interested in computing genetic risk scores and I would like to use LDpred2. I do not have a validation set (I want to compute genetic risk scores for phenotypes that are not measured), so I think that the ‘auto’ version of LDpred2 is the relevant one for my use case.

I read the [tutorial](https://github.com/privefl/paper-ldpred2/blob/master/code/example-with-provided-ldref.R) in the GitHub repository of your paper and I would like to ask you a few questions (sorry if some questions are very dummy and not specific to LDpred2):

* Regarding the effective population size, how is it computed? Is it `4 / ((1 / n_cases) + (1 / n_controls))` for binary phenotypes? What is the formula for continuous phenotypes?
* In this piece of code, should I use `vec_p_init = seq_log(1e-4, 0.9, 30)` whatever the number of cores I use? In particular, the number of cores is set to 30 in the tutorial. I’m going to run the analyses on a cluster so the number of cores should not be an issue (but I'd guess that a too large value leads to redundant results and is waste of computational ressources).
* `beta_auto` seems to be an array with shape `(n_snps, length(vec_p_init))`. I guess it corresponds to the beta for each initial value of p. Am I right? Is the order of the SNPs the same as in `df_beta` ? I will probably export these coefficients and compute the genetic risk scores with Python as I’m much more comfortable with Python than R, so I just want to be sure.
* Regarding the filtering of the genetic risk scores, I understood that (let me know if I’m mistaken):
  + First you compute the standard deviation of each genetic risk score.
  + Finally you keep only the genetic risk scores such that the absolute value of the difference between the standard deviation and the median of the standard deviations is lower than three time the mean absolute deviation of the standard deviations.

Best regards,
Johann Faouzi

**Comment by privefl** [comment]
- For continuous pheno, just use total sample size.
- I find that 30 is good enough for the number of chains, in order to filter the bad ones. If you have 20 cores available, you can go for 40. 
- Yes, you're right (x2).
- yes, you can also filter on values that are too different for the estimated h2 and p.

**Comment by johannfaouzi** [comment]
Great, thank you for your quick reply!

**Comment by johannfaouzi** [comment]
Actually I have one more question: In the `map.rds` file (with the information on HapMap3 SNPs), is the second column (called `pos`) the position for the hg19 build? I would guess so since the last three columns are called `pos_hg17`, `pos_hg18` and `pos_hg38`, and the GRCh37 build seems to be the most common, but I just want to be sure.

**Comment by privefl** [comment]
- Yes, hg19.

- I don't know about the rsIDs. They should be independent I guess as they are often used to match between data from two different builds. One issue I found though is that they are not always unique.

**Comment by johannfaouzi** [comment]
Thank you very much!

**Comment by johannfaouzi** [comment]
Hi again,

I've been trying to apply the [LDpred2 tutorial](https://github.com/privefl/paper-ldpred2/blob/e625811ac85b845cbe36f6c3c7ec1cd58a298b29/code/example-with-provided-ldref.R) to other summary statistics and I faced a few issues:
* When [dropping rows with missing values in the `info_snp` dataframe](https://github.com/privefl/paper-ldpred2/blob/e625811ac85b845cbe36f6c3c7ec1cd58a298b29/code/example-with-provided-ldref.R#L25), some SNPs are removed because they don't have a position in other builds (columns `pos_hg17`, `pos_hg18` and `pos_hg38`). Is it necessary to remove them if I work with the default build (`pos`)?
* When [filtering out bad SNPs](https://github.com/privefl/paper-ldpred2/blob/e625811ac85b845cbe36f6c3c7ec1cd58a298b29/code/example-with-provided-ldref.R#L27-L31), could you explain the rationale of the four criteria? For my summary statistics ([GWAS on intracranial volume](https://pubmed.ncbi.nlm.nih.gov/27694991/)), out of 950,266 SNPs, 950,262 are considered bad for one criterium (`sd_ss > (sd_ldref + 0.1)`). I also plan to run LDpred2 to compute genetic risk scores for many phenotypes, so I wonder if I have to pay high attention to this filtering process.

Thanks in advance!

**Comment by privefl** [comment]
- you can drop the columns you don't use before removing missing values
- two are basically filters on MAF and the other two differences between sumstats and validation/LD set. You need to pay attention at the numerator, which can be 2 for binary traits and sd(y) for continuous traits (cf. paper).
- the formula you're using to get beta is the same formula as in LDpred2's QC
- there is something wrong with your code, bad_3 and bad_4 are about minimum MAF (sd = sqrt(2 * maf * (1 - maf)), so it's not possible you have all that are filtered out by this.

**Comment by johannfaouzi** [comment]
Thank you for your quick reply. I made a mistake when formatting the table, there are 7 columns and not 6 (I forgot thecolumn for the index, so the columns were offset).

I changed the numerator (2 for binary traits and 1 for continuous traits because I remember having looked for the standard deviation in a few papers and never finding it, so I made the assumption that they standardized it, I could be wrong though). Here is the new table:

"gwas" | "n_snps" | "n_bad" | "n_bad_1" | "n_bad_2" | "n_bad_3" | "n_bad_4"
--- | --- | --- | --- | --- | --- | ---
"adams_2016__intracranial_volume.txt" | 950266 | 20 | 0 | 20 | 0 | 0
"chia_2021__lewy_body_dementia.txt" | 873165 | 1 | 0 | 1 | 0 | 0
"davies_2016__memory_performance.txt" | 956390 | 656836 | 2896 | 653837 | 1240 | 0
"davies_2016__reasoning.txt" | 956389 | 643063 | 2757 | 640162 | 1244 | 0
"davies_2018__reaction_time.txt" | 956532 | 945733 | 1416 | 944314 | 531 | 0
"grasby_2020__mean_bankssts_surfavg.txt" | 953284 | 953284 | 953284 | 0 | 953284 | 0
"grasby_2020__mean_bankssts_thickavg.txt" | 953367 | 953367 | 0 | 953367 | 0 | 0
"grasby_2020__mean_caudalanteriorcingulate_surfavg.txt" | 953518 | 953518 | 953518 | 0 | 953518 | 0
"grasby_2020__mean_caudalanteriorcingulate_thickavg.txt" | 953583 | 953583 | 0 | 953583 | 0 | 0
"grasby_2020__mean_caudalmiddlefrontal_surfavg.txt" | 953505 | 953505 | 953505 | 0 | 953505 | 0
"grasby_2020__mean_caudalmiddlefrontal_thickavg.txt" | 953559 | 953559 | 0 | 953559 | 0 | 0
"grasby_2020__mean_cuneus_surfavg.txt" | 953516 | 953516 | 953516 | 0 | 953516 | 0
"grasby_2020__mean_cuneus_thickavg.txt" | 953454 | 953454 | 0 | 953454 | 0 | 0
"grasby_2020__mean_entorhinal_surfavg.txt" | 953135 | 953135 | 953135 | 0 | 953135 | 0
"grasby_2020__mean_entorhinal_thickavg.txt" | 953344 | 953344 | 0 | 953344 | 0 | 0
"grasby_2020__mean_frontalpole_surfavg.txt" | 953579 | 953579 | 953579 | 0 | 953579 | 0
"grasby_2020__mean_frontalpole_thickavg.txt" | 953585 | 953585 | 0 | 953585 | 0 | 0
"grasby_2020__mean_full_surfarea.txt" | 953402 | 953402 | 953402 | 0 | 953402 | 0
"grasby_2020__mean_full_thickness.txt" | 953599 | 953599 | 0 | 953599 | 0 | 0
"grasby_2020__mean_fusiform_surfavg.txt" | 953386 | 953386 | 953386 | 0 | 953386 | 0
"grasby_2020__mean_fusiform_thickavg.txt" | 953525 | 953525 | 0 | 953525 | 0 | 0
"grasby_2020__mean_inferiorparietal_surfavg.txt" | 953409 | 953409 | 953409 | 0 | 953409 | 0
"grasby_2020__mean_inferiorparietal_thickavg.txt" | 953492 | 953492 | 0 | 953492 | 0 | 0
"grasby_2020__mean_inferiortemporal_surfavg.txt" | 953499 | 953499 | 953499 | 0 | 953499 | 0
"grasby_2020__mean_inferiortemporal_thickavg.txt" | 953506 | 953506 | 0 | 953506 | 0 | 0
"grasby_2020__mean_insula_surfavg.txt" | 953380 | 953380 | 953380 | 0 | 953380 | 0
"grasby_2020__mean_insula_thickavg.txt" | 953267 | 953267 | 0 | 953267 | 0 | 0
"grasby_2020__mean_isthmuscingulate_surfavg.txt" | 953413 | 953413 | 953413 | 0 | 953413 | 0
"grasby_2020__mean_isthmuscingulate_thickavg.txt" | 953477 | 953477 | 0 | 953477 | 0 | 0
"grasby_2020__mean_lateraloccipital_surfavg.txt" | 953516 | 953516 | 953516 | 0 | 953516 | 0
"grasby_2020__mean_lateraloccipital_thickavg.txt" | 953455 | 953455 | 0 | 953455 | 0 | 0
"grasby_2020__mean_lateralorbitofrontal_surfavg.txt" | 953563 | 953563 | 953563 | 0 | 953563 | 0
"grasby_2020__mean_lateralorbitofrontal_thickavg.txt" | 953309 | 953309 | 0 | 953309 | 0 | 0
"grasby_2020__mean_lingual_surfavg.txt" | 953550 | 953550 | 953550 | 0 | 953550 | 0
"grasby_2020__mean_lingual_thickavg.txt" | 953458 | 953458 | 0 | 953458 | 0 | 0
"grasby_2020__mean_medialorbitofrontal_surfavg.txt" | 953470 | 953470 | 953470 | 0 | 953470 | 0
"grasby_2020__mean_medialorbitofrontal_thickavg.txt" | 952997 | 952997 | 0 | 952997 | 0 | 0
"grasby_2020__mean_middletemporal_surfavg.txt" | 953275 | 953275 | 953275 | 0 | 953275 | 0
"grasby_2020__mean_middletemporal_thickavg.txt" | 953366 | 953366 | 0 | 953366 | 0 | 0
"grasby_2020__mean_paracentral_surfavg.txt" | 953493 | 953493 | 953493 | 0 | 953493 | 0
"grasby_2020__mean_paracentral_thickavg.txt" | 953565 | 953565 | 0 | 953565 | 0 | 0
"grasby_2020__mean_parahippocampal_surfavg.txt" | 952437 | 952437 | 952437 | 0 | 952437 | 0
"grasby_2020__mean_parahippocampal_thickavg.txt" | 953048 | 953048 | 0 | 953048 | 0 | 0
"grasby_2020__mean_parsopercularis_surfavg.txt" | 953512 | 953512 | 953512 | 0 | 953512 | 0
"grasby_2020__mean_parsopercularis_thickavg.txt" | 953566 | 953566 | 0 | 953566 | 0 | 0
"grasby_2020__mean_parsorbitalis_surfavg.txt" | 953559 | 953559 | 953559 | 0 | 953559 | 0
"grasby_2020__mean_parsorbitalis_thickavg.txt" | 953570 | 953570 | 0 | 953570 | 0 | 0
"grasby_2020__mean_parstriangularis_surfavg.txt" | 953523 | 953523 | 953523 | 0 | 953523 | 0
"grasby_2020__mean_parstriangularis_thickavg.txt" | 953543 | 953543 | 0 | 953543 | 0 | 0
"grasby_2020__mean_pericalcarine_surfavg.txt" | 953522 | 953522 | 953522 | 0 | 953522 | 0
"grasby_2020__mean_pericalcarine_thickavg.txt" | 953176 | 953176 | 0 | 953176 | 0 | 0
"grasby_2020__mean_postcentral_surfavg.txt" | 953308 | 953308 | 953308 | 0 | 953308 | 0
"grasby_2020__mean_postcentral_thickavg.txt" | 953462 | 953462 | 0 | 953462 | 0 | 0
"grasby_2020__mean_posteriorcingulate_surfavg.txt" | 953566 | 953566 | 953566 | 0 | 953566 | 0
"grasby_2020__mean_posteriorcingulate_thickavg.txt" | 953482 | 953482 | 0 | 953482 | 0 | 0
"grasby_2020__mean_precentral_surfavg.txt" | 953361 | 953361 | 953361 | 0 | 953361 | 0
"grasby_2020__mean_precentral_thickavg.txt" | 953512 | 953512 | 0 | 953512 | 0 | 0
"grasby_2020__mean_precuneus_surfavg.txt" | 953551 | 953551 | 953551 | 0 | 953551 | 0
"grasby_2020__mean_precuneus_thickavg.txt" | 953577 | 953577 | 0 | 953577 | 0 | 0
"grasby_2020__mean_rostralanteriorcingulate_surfavg.txt" | 953451 | 953451 | 953451 | 0 | 953451 | 0
"grasby_2020__mean_rostralanteriorcingulate_thickavg.txt" | 953567 | 953567 | 0 | 953567 | 0 | 0
"grasby_2020__mean_rostralmiddlefrontal_surfavg.txt" | 953518 | 953518 | 953518 | 0 | 953518 | 0
"grasby_2020__mean_rostralmiddlefrontal_thickavg.txt" | 953421 | 953421 | 0 | 953421 | 0 | 0
"grasby_2020__mean_superiorfrontal_surfavg.txt" | 953417 | 953417 | 953417 | 0 | 953417 | 0
"grasby_2020__mean_superiorfrontal_thickavg.txt" | 953423 | 953423 | 0 | 953423 | 0 | 0
"grasby_2020__mean_superiorparietal_surfavg.txt" | 953394 | 953394 | 953394 | 0 | 953394 | 0
"grasby_2020__mean_superiorparietal_thickavg.txt" | 953416 | 953416 | 0 | 953416 | 0 | 0
"grasby_2020__mean_superiortemporal_surfavg.txt" | 953234 | 953234 | 953234 | 0 | 953234 | 0
"grasby_2020__mean_superiortemporal_thickavg.txt" | 953284 | 953284 | 0 | 953284 | 0 | 0
"grasby_2020__mean_supramarginal_surfavg.txt" | 953294 | 953294 | 953294 | 0 | 953294 | 0
"grasby_2020__mean_supramarginal_thickavg.txt" | 953316 | 953316 | 0 | 953316 | 0 | 0
"grasby_2020__mean_temporalpole_surfavg.txt" | 953476 | 953476 | 953476 | 0 | 953476 | 0
"grasby_2020__mean_temporalpole_thickavg.txt" | 953501 | 953501 | 0 | 953501 | 0 | 0
"grasby_2020__mean_transversetemporal_surfavg.txt" | 953573 | 953573 | 953573 | 0 | 953573 | 0
"grasby_2020__mean_transversetemporal_thickavg.txt" | 953532 | 953532 | 0 | 953532 | 0 | 0
"kunkle_2019__alzheimer_disease.txt" | 955454 | 1387 | 152 | 2 | 1267 | 0
"lee_2018__cognitive_performance.txt" | 953635 | 291 | 0 | 0 | 291 | 0
"lee_2018__educational_attainment.txt" | 953634 | 385 | 0 | 0 | 385 | 0
"malik_2018__any_ischemic_stroke.txt" | 952341 | 4165 | 433 | 1 | 4076 | 0
"malik_2018__any_stroke.txt" | 952132 | 3627 | 334 | 1 | 3532 | 0
"malik_2018__cardioembolic_stroke.txt" | 952012 | 3663 | 221 | 1 | 3614 | 0
"malik_2018__large_atery_stroke.txt" | 952681 | 3596 | 384 | 1 | 3526 | 0
"malik_2018__small_vessel_stroke.txt" | 952166 | 3449 | 212 | 1 | 3392 | 0
"sargurupremraj_2020__white_matter_hyperintensities.txt" | 918177 | 59998 | 3 | 59995 | 0 | 0
"satizabal_2019__subcortical_volume_accumbens.txt" | 941082 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_amygdala.txt" | 940927 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_brainstem.txt" | 941383 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_caudate.txt" | 939266 | 5 | 0 | 5 | 0 | 0
"satizabal_2019__subcortical_volume_pallidum.txt" | 940910 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_putamen.txt" | 939372 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_thalamus.txt" | 940934 | 6 | 0 | 6 | 0 | 0
"schwartzentruber_2021__alzheimer_disease_or_family_history.txt" | 955508 | 10795 | 323 | 0 | 10495 | 0

A few remarks:
* For the studies for which I computed `beta` and `beta_se` with the formula (`adams` and `satizabal`), it looks good!
* For binary phenotypes (`chia`, `kunkle`, `malik`, `schwartzentruber`, `sargurupremraj`), it doesn't look that bad.
* For continuous phenotypes, it's quite bad for some:
  + For `davies` studies, I computed `beta_se` from `beta` and `pval` since they don't provide it, but I probably made a mistake. Do you use a particular formula in your package?
  + For `grasby` studies, it's "interesting" to see such a clear pattern for cortical surface and cortical thickness phenotypes. All the necessary columns are provided in the summary statistics, so I didn't make a mistake with any kind of imputation. Do you have any suggestion?

**Comment by privefl** [comment]
- I do not know if you can expect sd(y) to be 1.
- `beta_se = beta / Z` if you have the Z-statistic, or you can use `sqrt(beta^2 / chi2)` where `chi2 = qchisq(pval, df = 1, lower.tail = FALSE)`.
- you can then me the link to download one of them, and I can have a quick look at them.

**Comment by johannfaouzi** [comment]
Thank you very much!
* I think that you are right. I looked at the distribution of `sd_ss` for different summary statistics and the scale can be much different from one to another. If I **manually** find a good scale factor (so that the histogram is kinda similar to the histogram for a study for which the filtering process works fine), I get more relevant results (only a few SNPs are removed). My question is: If I can't find the standard deviation of the phenotypes, what solution would you recommend? Skipping this quality control? Trying to (automatically) find the standard deviation of the phenotype?
* I used the second formula using `beta` and `pval` and it works much better!

**Comment by privefl** [comment]
There are two possible estimates of sd(y) mentioned in Section 3.4 of the paper (https://doi.org/10.1093/bioinformatics/btaa1029).

**Comment by johannfaouzi** [comment]
Thank you so much! Regarding the first estimation, do you provide the standard deviation of each SNP from HapMap3 estimated in UKBB? `af_UKBB` is the allele frequency (so the mean value over all binary pairs), but the standard deviation should be computed over the number of minor/major alleles (each value being in {0, 1, 2} if measured or in [0, 2] if imputed) if I'm not mistaken? Otherwise I will probably stick with the second estimation, which seems simpler to implement.

**Comment by privefl** [comment]
You can use sqrt(2 * af_UKBB * (1 - af_UKBB)) to estimate the standard deviations (under HWE).

**Comment by johannfaouzi** [comment]
Thank you again so much! Would you recommend one approach over the other one? I estimated the standard deviation of the phenotypes with both approaches and the results are pretty consistent in terms of relative difference (min: 0.017% median: 4.1%, mean: 5.8%, max: 34%). I could also take the mean value. You may have more hindsight with your experience.

For binary phenotypes, would you recommend setting the standard deviation of the phenotype to 2 or computing an approximation? Some GWAS use proxy phenotypes (family history of Alzheimer's disease instead of Alzheimer's disease), and the estimated standard deviation is higher (around 3.3 for both approaches). Plus meta-analyses with different definitions for the same phenotype... I would think than computing an approximation based on the data is better.

I just tried with the second approach (to compute the standard deviation) and the results are looking good! There is only one study where it's still not great (`davies_2018`). I computed the Pearson correlation between both methods to compute `beta_se` (from `beta` and `pval` on one hand and from `af` and `n_eff` on the other hand) and it's not high (0.71). However, for other studies (`davies_2016`), the coefficients are really high (0.9989 and 0.9987). I'm going to try another GWAS for this phenotype (there is also a smaller GWAS on reaction time in `davies_2016`). Thank you so much for your time and your explanations!

"gwas" | "n_snps" | "n_bad" | "n_bad_1" | "n_bad_2" | "n_bad_3" | "n_bad_4"
 --- | --- | --- | --- | --- | --- | ---
"adams_2016__intracranial_volume.txt" | 950266 | 20 | 0 | 20 | 0 | 0
"chia_2021__lewy_body_dementia.txt" | 873165 | 1 | 0 | 1 | 0 | 0
"davies_2016__memory_performance.txt" | 956390 | 2331 | 4 | 27 | 2300 | 0
"davies_2016__reasoning.txt" | 956389 | 2262 | 4 | 27 | 2231 | 0
"davies_2018__reaction_time.txt" | 956532 | 428140 | 0 | 428140 | 0 | 0
"grasby_2020__mean_bankssts_surfavg.txt" | 953284 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_bankssts_thickavg.txt" | 953367 | 3 | 0 | 1 | 2 | 0
"grasby_2020__mean_caudalanteriorcingulate_surfavg.txt" | 953518 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_caudalanteriorcingulate_thickavg.txt" | 953583 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_caudalmiddlefrontal_surfavg.txt" | 953505 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_caudalmiddlefrontal_thickavg.txt" | 953559 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_cuneus_surfavg.txt" | 953516 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_cuneus_thickavg.txt" | 953454 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_entorhinal_surfavg.txt" | 953135 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_entorhinal_thickavg.txt" | 953344 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_frontalpole_surfavg.txt" | 953579 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_frontalpole_thickavg.txt" | 953585 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_full_surfarea.txt" | 953402 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_full_thickness.txt" | 953599 | 4 | 0 | 1 | 3 | 0
"grasby_2020__mean_fusiform_surfavg.txt" | 953386 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_fusiform_thickavg.txt" | 953525 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_inferiorparietal_surfavg.txt" | 953409 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_inferiorparietal_thickavg.txt" | 953492 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_inferiortemporal_surfavg.txt" | 953499 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_inferiortemporal_thickavg.txt" | 953506 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_insula_surfavg.txt" | 953380 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_insula_thickavg.txt" | 953267 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_isthmuscingulate_surfavg.txt" | 953413 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_isthmuscingulate_thickavg.txt" | 953477 | 6 | 0 | 1 | 5 | 0
"grasby_2020__mean_lateraloccipital_surfavg.txt" | 953516 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_lateraloccipital_thickavg.txt" | 953455 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_lateralorbitofrontal_surfavg.txt" | 953563 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_lateralorbitofrontal_thickavg.txt" | 953309 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_lingual_surfavg.txt" | 953550 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_lingual_thickavg.txt" | 953458 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_medialorbitofrontal_surfavg.txt" | 953470 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_medialorbitofrontal_thickavg.txt" | 952997 | 7 | 0 | 1 | 6 | 0
"grasby_2020__mean_middletemporal_surfavg.txt" | 953275 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_middletemporal_thickavg.txt" | 953366 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_paracentral_surfavg.txt" | 953493 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_paracentral_thickavg.txt" | 953565 | 3 | 0 | 1 | 2 | 0
"grasby_2020__mean_parahippocampal_surfavg.txt" | 952437 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parahippocampal_thickavg.txt" | 953048 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parsopercularis_surfavg.txt" | 953512 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parsopercularis_thickavg.txt" | 953566 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parsorbitalis_surfavg.txt" | 953559 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parsorbitalis_thickavg.txt" | 953570 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parstriangularis_surfavg.txt" | 953523 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_parstriangularis_thickavg.txt" | 953543 | 10 | 0 | 1 | 9 | 0
"grasby_2020__mean_pericalcarine_surfavg.txt" | 953522 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_pericalcarine_thickavg.txt" | 953176 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_postcentral_surfavg.txt" | 953308 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_postcentral_thickavg.txt" | 953462 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_posteriorcingulate_surfavg.txt" | 953566 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_posteriorcingulate_thickavg.txt" | 953482 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_precentral_surfavg.txt" | 953361 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_precentral_thickavg.txt" | 953512 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_precuneus_surfavg.txt" | 953551 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_precuneus_thickavg.txt" | 953577 | 12 | 0 | 1 | 11 | 0
"grasby_2020__mean_rostralanteriorcingulate_surfavg.txt" | 953451 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_rostralanteriorcingulate_thickavg.txt" | 953567 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_rostralmiddlefrontal_surfavg.txt" | 953518 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_rostralmiddlefrontal_thickavg.txt" | 953421 | 2 | 0 | 1 | 1 | 0
"grasby_2020__mean_superiorfrontal_surfavg.txt" | 953417 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_superiorfrontal_thickavg.txt" | 953423 | 17 | 0 | 1 | 16 | 0
"grasby_2020__mean_superiorparietal_surfavg.txt" | 953394 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_superiorparietal_thickavg.txt" | 953416 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_superiortemporal_surfavg.txt" | 953234 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_superiortemporal_thickavg.txt" | 953284 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_supramarginal_surfavg.txt" | 953294 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_supramarginal_thickavg.txt" | 953316 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_temporalpole_surfavg.txt" | 953476 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_temporalpole_thickavg.txt" | 953501 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_transversetemporal_surfavg.txt" | 953573 | 1 | 0 | 1 | 0 | 0
"grasby_2020__mean_transversetemporal_thickavg.txt" | 953532 | 1 | 0 | 1 | 0 | 0
"kunkle_2019__alzheimer_disease.txt" | 955454 | 230 | 17 | 6 | 214 | 0
"lee_2018__cognitive_performance.txt" | 953635 | 214 | 0 | 0 | 214 | 0
"lee_2018__educational_attainment.txt" | 953634 | 181 | 0 | 0 | 181 | 0
"malik_2018__any_ischemic_stroke.txt" | 952341 | 2553 | 133 | 1 | 2515 | 0
"malik_2018__any_stroke.txt" | 952132 | 2193 | 108 | 1 | 2149 | 0
"malik_2018__cardioembolic_stroke.txt" | 952012 | 4006 | 282 | 1 | 3949 | 0
"malik_2018__large_atery_stroke.txt" | 952681 | 3032 | 264 | 1 | 2988 | 0
"malik_2018__small_vessel_stroke.txt" | 952166 | 2585 | 88 | 1 | 2556 | 0
"sargurupremraj_2020__white_matter_hyperintensities.txt" | 918177 | 3369 | 3190 | 0 | 213 | 0
"satizabal_2019__subcortical_volume_accumbens.txt" | 941082 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_amygdala.txt" | 940927 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_brainstem.txt" | 941383 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_caudate.txt" | 939266 | 5 | 0 | 5 | 0 | 0
"satizabal_2019__subcortical_volume_pallidum.txt" | 940910 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_putamen.txt" | 939372 | 6 | 0 | 6 | 0 | 0
"satizabal_2019__subcortical_volume_thalamus.txt" | 940934 | 6 | 0 | 6 | 0 | 0
"schwartzentruber_2021__alzheimer_disease_or_family_history.txt" | 955508 | 75 | 0 | 1 | 74 | 0

**Comment by privefl** [comment]
- Not sure which estimator is the best. The best would be to look at the QC plot afterwards.

- I think if logistic regression was used, this should always be 2 for the numerator (if you use n_eff).

- Could you show the QC plot for reaction time here? (just drag and drop your figure)

**Comment by johannfaouzi** [comment]
Thank you very much!

![scatter plot reaction time](https://user-images.githubusercontent.com/17053934/120285389-7b68b800-c2bd-11eb-8f1d-f178fd43fcc9.png)

Here is the scatter plot for two summary statistics on reaction time ([(Davies et al. 2018)](https://www.ebi.ac.uk/gwas/studies/GCST006268) and [(Davies et al. 2016)](https://www.ebi.ac.uk/gwas/studies/GCST003499)). On the x-axis, `beta_se` is computed using the formula that you gave me using `beta` and `pval`. On the y-axis, `beta_se` is computed using the formula based `n_eff` and `af_UKBB` (I set the numerator to 1 since we need `beta_se` to estimate the standard deviation of the phenotype, so I didn't plot the identity function since the scale is probably wrong).

(Davies et al. 2016) uses only UKBB, while (Davies et al. 2018) uses a lot of cohorts:
> The present study includes 300,486 individuals of European ancestry from 57 population-based cohorts brought
together by the Cohorts for Heart and Aging Research in Genomic Epidemiology (CHARGE), the Cognitive Genomics Consortium (COGENT) consortia, and UK Biobank.

**Comment by privefl** [comment]
You can send this sumstats to me if you want, I can have a quick look.
Please restrict to e.g. chr22 so that it is easy to download on my laptop.

**Comment by johannfaouzi** [comment]
Thank you very much! I sent you an email with the files.

**Comment by privefl** [comment]
It seems that chi2 ~ N beta^2, which means that beta are in fact correlations (~Z / sqrt(N)).

You can then probably get beta using the formula you provided (assuming sd(y) = 1), and then get beta_se using beta / Z.

**Comment by johannfaouzi** [comment]
Thank you very much, the results of the QC make much more sense now.

Thank you so so much for your help!
