### ISSUE TITLE
Is it possible to convert a `FBM.code256` to a regular matrix or data.frame?

### ISSUE THREAD

**Issue by caimiao0714** [privefl/bigsnpr#231]
Hi Florian,

I'm trying to replicate some part of [a paper that predicts BMI and body composition using selected SNPs](https://pubmed.ncbi.nlm.nih.gov/31195408/). The paper listed the SNPs they use and I have successfully extracted these SNPs from the UKBB data sets. That paper reported the percent of the variance explained by the SNPs and the corresponding F statistics (see the quote below), I'm having difficulty getting this result using `bigsnpr`.

    "The 96 BMI-related SNPs explained 1.6% of the variance in BMI (corresponding to an F statistic of 61), 
    whereas the 82 SNPs for body composition explained 0.8% of the variance in fat mass index (F statistic 52)".

What my thought (probably naive and not the correct way of doing this) is:

1. Merge the BMI and body composition phenotype from the baseline data to the selected SNPs stored in `FBM.code256` using eid as the key
2. Construct linear regression models using BMI or body composition as `y`, and the 96 SNPs as the `x` using R function `lm`.

But I failed to convert the `FBM.code256` into a data.frame or matrix at step 1, and I did not find any function/tutorial on converting that. Is my way of thinking about or geting the variance explained and F statistics wrong? Any comments or suggestions would be appreciated.

Thanks,
Miao

**Comment by privefl** [comment]
If `G` is the `FBM.code256`, then you can access the whole matrix with `G[]`.

**Comment by caimiao0714** [comment]
Ok. Thank you! That works for me. 

Is my way of getting the variance explained and F statistics correct? I saw that there are `big_spLinReg` in the `bigstatsr` package, but I'm not sure if it is correct to use this function to get variance explained and F statistics in this case.

Thanks,
Miao

**Comment by privefl** [comment]
Given the (small) size of the data, you can directly use R statistical tools.

**Comment by caimiao0714** [comment]
Ok. Thank you!

**Comment by linoferreira** [comment]
If I wanted to read only a subset of an `FBM.code256` object into memory, would there be a better (faster) way than just doing `gdf <- G[ind.row, ind.col]`?

**Comment by privefl** [comment]
Nope

**Comment by linoferreira** [comment]
Thanks!
