### ISSUE TITLE
Unused argument (s = c(0.2, 0.5, 0.8, 1)) in snp_lassosum2?

### ISSUE THREAD

**Issue by lincj1994** [privefl/bigsnpr#232]
Hi, I plan to perform lassosum2 with the following code:
```
beta_lassosum2 <- snp_lassosum2(
  corr, df_beta, ncores = NCORES,
  s = c(0.2, 0.5, 0.8, 1), nlambda = 10, maxiter = 50)
```
It returns an error:
```
Error in snp_lassosum2(corr, df_beta, ncores = NCORES, s = c(0.2, 0.5,  : 
  unused argument (s = c(0.2, 0.5, 0.8, 1))
```
How to deal with it?

**Comment by privefl** [comment]
I changed `lassosum2` a bit, the new parameter is now `delta` and you should be fine using the default value.

The preprint (and tutorial) will be updated soon, but it takes more time than I anticipated.

**Comment by privefl** [comment]
I have updated the tutorial.
