### ISSUE TITLE
snp_readBGEN Error

### ISSUE THREAD

**Issue by MatthewOGoodman** [privefl/bigsnpr#234]
Trying to follow snp_readBGEN example, here: https://github.com/privefl/UKBiobank/blob/master/10-get-dosages.R

Getting error below presumably because I cannot write to the directory in which the UKBB bgen files are located, because it is an institute-wide repository, which I do not have permissions for. Also why is there appended text "_not_found.rds", and why is there a double "//"?

Any suggestions? Thanks!

  rds <- bigsnpr::snp_readBGEN(
    bgenfiles = glue::glue("/broad/ukbb/imputed_v3/ukb_imp_chr{chr}_v3.bgen", chr = 1:22),
    list_snp_id = chr_pos_id_by_chr,
    backingfile = tempfile(pattern = "UKBB_BB", tmpdir = "~/BGEN_temp/"),
    ind_row = ind.indiv[sub2],
    bgi_dir = "/broad/ukbb/imputed_v3/",
    read_as = c("dosage"),
    ncores = 1
  )

output:
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/broad/ukbb/imputed_v3//ukb_imp_chr1_v3_not_found.rds', probable reason 'Permission denied'

str(chr_pos_id_by_chr)
List of 22
 $ 1 : chr [1:685466] "1_693731_G_A" "1_707522_C_G" "1_717587_A_G" "1_730087_C_T" ...
 $ 2 : chr [1:747284] "2_10596_T_G" "2_10797_T_C" "2_11247_G_C" "2_11274_G_C" ...
 ... ...

**Comment by privefl** [comment]
The file with appended `"_not_found.rds"` is there to tell you which of the ids couldn't be found in the BGI data.
There are 2 `\\` because you're already using one in `"/broad/ukbb/imputed_v3/"`.

What you can try to do is copy the BGI files in a directory you can write to.

**Comment by MatthewOGoodman** [comment]
Great, that explains it. 
Might want to mention the SNP not found file in "Value" in the help in future updates, and consider moving it to the output directory.
Many thanks, and thanks for your work on the package...

**Comment by privefl** [comment]
That might be a good idea indeed.

If you want, you could make a PR.
