### ISSUE TITLE
Float based FBM 

### ISSUE THREAD

**Issue by mfknie** [privefl/bigsnpr#235]
Going off of this prior issue from my colleague Julian - #185 . I attempted to make the exact same modifications to [snp_clumping](https://github.com/mfknie/bigsnpr/blob/master/src/clumping.cpp) and [snp_colstats](https://github.com/mfknie/bigsnpr/blob/master/src/colstats.cpp) to utilize the clumping functionality.

In my scenario, I am working with inferred local ancestry dosages (which would require 3 or 4 decimal places in precision at maximum), so hard call data was not available. In the code I was testing, I read this dosage data by chromosome in the following format - https://www.cog-genomics.org/plink/2.0/formats#traw - into R via fread and converted the numerical columns into a float FBM with as_FBM (I doubt this is best practice for bigsnpr, but I just wanted to test the float functionality). I then called `snp_clumping(G = fbm_dosage, infos.chr = chr, infos.pos = pos, S = pval_neglog10, thr.r2 = 0.9)` . I have double checked the inputs to make sure they were correct in format.

This worked for the two smallest chromosomes (21 and 22), which had 3155 and 10030 snps respectively. However, when I tried it for chromosome 20, which had 64125 snps, I began getting an error that looked like this:
![image](https://user-images.githubusercontent.com/22650325/124168257-83f21100-da6a-11eb-971f-f3260650e4fc.png)
In this case, 14931 is the number of individuals within the data. 

I did some minor digging, and it seems the issue is occuring [here](https://github.com/mfknie/bigsnpr/blob/master/src/clumping.cpp#L113) when the float matrix in Rcpp is defined. Allocating more memory to my job runs didn't seem to help. Would you have any suggestions here?

**Comment by privefl** [comment]
This error happens when you're trying to subset (usually with `ind.row` or `ind.col`) outside of the boundaries of `G`.
14931 is probably one of the dimensions of `G` and you have some subsetting somewhere that contains values larger than 14931.

**Comment by mfknie** [comment]
That makes sense. I went back and it turns out I formatted the input data to have individuals as columns and snps as rows. Silly on my part. I will close the thread when I confirm that clumping works. Thanks for the input.
