### ISSUE TITLE
Negative h2_est

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#236]
Hello Dr. Privé

Apologies for disturbing you but I am having an issue with LDpred2. After running the ld score regression, I got a negative h2_est and I am not quite sure why. 
Could you please provide some insights?

Much appreciated,

With kind regards,

**Comment by privefl** [comment]
LD score regression can output negative SNP heritability estimates, indeed.
Are you running it genome-wide?

You can just use another value, e.g. 0.01 for LDpred2-auto and a grid with e.g. `signif(seq_log(0.005, 0.1, 4), 3)` for LDpred2-grid.

But if the heritability is really very small (< 0.01), then you can't really expect to predict much with polygenic scores.

**Comment by nscarene** [comment]
Good morning Dr.

Thank you for your prompt response. 

Yes, I ran it genome-wide! It seems if the h2_est is negative LDpred-inf cannot get calculated. 
I am aware that the heritability will be very small; so, I am trying to compare different PRS calculation approaches.

**Comment by privefl** [comment]
LDpred2-inf is usually the worse of the LDpred2 models. 

But I can always use 0.01 for it as well.

**Comment by nscarene** [comment]
Thank you so much. 

What would the 0.01 be used for in the case of LDpred2-inf?

**Comment by privefl** [comment]
The SNP heritability you have to specify.

**Comment by nscarene** [comment]
Thank you so much for the clarification Dr.

**Comment by nscarene** [comment]
One last question, if I may Dr. Privé,

Can  **corr0 <- readRDS(paste0("data/corr/chr", chr, ".rds"))[ind.chr3, ind.chr3]**  from running LDpred2-genome_wide, be rewritten as: 
corr0 <- snp_cor( genotype,  ind.col = ind.chr2,  ncores = NCORES,  infos.pos = sort(POS2[ind.chr2]),   size = 3/1000 ) also running genome-wide?

**Comment by privefl** [comment]
Not sure I understand, you want to compute the correlation matrix genome-wide directly?

**Comment by nscarene** [comment]
Yes, I want to compute the correlation matrix genome-wide directly? Can I use this code **corr0 <- snp_cor( genotype, ind.col = ind.chr2, ncores = NCORES, infos.pos = sort(POS2[ind.chr2]), size = 3/1000 )** 

Thank you,

**Comment by privefl** [comment]
This should work:
```r
corr0 <- snp_cor(genotype, infos.pos = 1000 * CHR + POS2, size = 3 / 1000, ncores = NCORES)
```

**Comment by nscarene** [comment]
I will give it a try.

Once again, thank you very much for your time, Dr. Privé.
