### ISSUE TITLE
Error: Incompatibility between dimensions when running big_prodMat()

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#237]
Good morning Dr. Privé,

I hope this finds you well. I have an issue and was hoping you could help.
When I try to run the following line: pred_grid <- big_prodMat(G, beta_grid, ind.row = ind.val2,  ind.col = df_beta[["_NUM_ID_"]]); 
I automatically get an error message saying "error: you can't have missing values in 'X'). 

I tried using the snp_fastImputeSimple(G) to impute missing values but then I get another error message "error: Incompatibility between dimensions". 

Could you please provide some insight on how to manage the error messages?

Thank you very much!

With kind regards,

**Comment by privefl** [comment]
How to handle missing values is [a pinned issue here](https://github.com/privefl/bigsnpr/issues/49).

Just running `snp_fastImputeSimple(G)` gives you the error of incompatible dimensions? This seems hard to believe. Please provide a bit more details.

**Comment by nscarene** [comment]
Good morning Dr.

Thank you for your prompt response and my apologies for starting an issue that was already mentioned before.

I ran **snp_fastImputeSimple(G)** and then reran **pred_grid <- big_prodMat(G, beta_grid, ind.row = ind.val2, ind.col = df_beta[["NUM_ID"]])**

The error went from "Cannot have missing values in 'X'" before the imputation to "imcompatibility between dimensions". Should I rerun the analysis from the beginning, after that?

Also I was hoping you could help with a concern I have. I tried calculation LD correlation genome-wide using **corr0 <- snp_cor(G, infos.pos = 1000 * CHR + POS2, size = 3 / 1000, ncores = NCORES)**. Is it normal that the operation takes several hours? Or is something wrong with the way I do it?

Any insight will be greatly appreciated.

With regards,

**Comment by privefl** [comment]
Please try to keep issues separated; open a new one if you need to.

Let's focus on the error of incompatible dimensions here. 
Is it when running `G2 <- snp_fastImputeSimple(G)`? Or after running ` big_prodMat(G2, ...)`?

**Comment by nscarene** [comment]
My apologies, I just submitted a new issue for the second question. 

The error of incompatible dimensions arose after running **big_prodMat(G2, ...)** with G2 <- snp_fastImputeSimple(G)

**Comment by privefl** [comment]
It probably means that `nrow(beta_grid)` is not the same as `length(df_beta[["NUM_ID"]])`.

**Comment by nscarene** [comment]
I just checked and they are the same. See below,

 nrow(beta_grid)
[1] 108372
> length(df_beta[['_NUM_ID_']])
[1] 108372

**Comment by privefl** [comment]
Please reinstall `remotes::install_github('privefl/bigassertr')`.
You should now get a more explicit error message if you rerun the function.

**Comment by nscarene** [comment]
Thank you do much Dr.

**Comment by nscarene** [comment]
UPDATE

using G2 <- snp_fastImputeSimple(G) helped take care of the error message.

Thank you!
