### ISSUE TITLE
Computing LD correlation

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#238]
Good afternoon Dr.

I was hoping you could help with a concern I have. I tried calculating LD correlation genome-wide using corr0 <- snp_cor(G, infos.pos = 1000 * CHR + POS2, size = 3 / 1000, ncores = NCORES). Is it normal that the operation takes several hours? Or is something wrong with the way I do it?

With kind regards,

**Comment by privefl** [comment]
Please show what are `table(CHR)`, `dim(G)` and `NCORES`.

**Comment by nscarene** [comment]
Here is the information you requested,

>table(CHR)
CHR
     1      2      3      4      5      6      7      8      9     10     11
770979 850456 724583 741673 639071 678760 584768 564350 417562 507167 506901
    12     13     14     15     16     17     18     19     20     21     22
473900 369748 321741 273714 282729 252074 275470 195747 211178 127493 120661

> dim(G)
[1]     723 9890725

> NCORES
system
    47

**Comment by privefl** [comment]
That's 10M variants. I am surprised you do not have any issue with memory.

I would recommend to split the computation per chromosome. Try on chromosome 22 first, and report the computation time.

**Comment by nscarene** [comment]
Thank you for the suggestion. Will do it now and report back

**Comment by nscarene** [comment]
UPDATE

Computing time was much faster with by running just one chromosome. 
This code **corr0 <- snp_cor(G, infos.pos = 1000 * CHR + POS2, size = 3 / 1000, ncores = NCORES)** works well but when trying to run LD score regression using **(ldsc <- snp_ldsc2(corr0, df_beta))** then we get the same error about the incompatibility between dimensions.

**Comment by privefl** [comment]
Please look at e.g. the code from the paper which is linked in the tutorial: 
https://github.com/privefl/paper-ldpred2/blob/master/code/run-ldpred2-gwide.R#L39-L68

**Comment by privefl** [comment]
Any update on this?

**Comment by nscarene** [comment]
Good morning Dr. Privé

I hope this finds you well.

I followed the codes for running it genome-wide and everything went smoothly until LD score regression.
I used:
 (ldsc <- with(df_beta, snp_ldsc(ld, length(ld), chi2 = (beta / beta_se)^2,
                                sample_size = n_eff, blocks = NULL)))
 And I got an error:
Error: Incompatibility between dimensions.
'chi2' and 'ld_score' should have the same length.

To be honest I do not understand why! Could you please provide some insights?

Thank you for your time.

With kind regards,
Carene

**Comment by privefl** [comment]
`ld` and `chi2` should be two vectors of the same length.

**Comment by nscarene** [comment]
I followed the codes, shouldn't the two vectors automatically have the same length then?

**Comment by privefl** [comment]
Yes, they probably should. Can you verify it?
Which code are you talking about exactly?

**Comment by nscarene** [comment]
> Please look at e.g. the code from the paper which is linked in the tutorial:
> https://github.com/privefl/paper-ldpred2/blob/master/code/run-ldpred2-gwide.R#L39-L68

I am talking about this code! To compute LDpred2 genome-wide. 

I checked the length of each and they are not the same. Strangely enough

**Comment by privefl** [comment]
Yes, they should be the same.
Can tell me what are the lengths?

Also, if you are using the provided LD ref, you don't need to compute the `ld` as it should already be a column of the data frame.

**Comment by nscarene** [comment]
length(ld) = 8813
length(df_beta) = 54674

I'm trying to use my validation set to compute the ld

**Comment by privefl** [comment]
1. That's a very small number of variants in `df_beta`. You're not supposed to have so few.

2. Are you sure you're concatenating the `ld` info for all chromsomes?

**Comment by nscarene** [comment]
nrow(df_beta) = 54674

And yes df_beta is a data frame.

**Comment by privefl** [comment]
1. Why do you have so few variants?

2. Are you concatenating all `ld` for all chromosomes?

**Comment by nscarene** [comment]
1.I'm not sure but please let me give it a rerun and see if the mistake was not on my end.
2. Yes I believe I am concatenating all ld for all chromosomes!

**Comment by privefl** [comment]
Any update on this?

**Comment by nscarene** [comment]
Everything worked. My mistake was that I was using the wrong dataset for the ind.col and ind.row. I was able to run the software genome-wide.

Thank you very much for your time and hard work. And thank you for taking the time to provide some guidance

**Comment by YanxiaWei** [comment]
> Everything worked. My mistake was that I was using the wrong dataset for the ind.col and ind.row. I was able to run the software genome-wide.
> 
> Thank you very much for your time and hard work. And thank you for taking the time to provide some guidance

Hello Dr. nscarene,

I met the same problem as you did. could you please clarify how you solved this problem? Or is there any relevant code?

I will appreciate your help.

Kind regards,
Yanxia

**Comment by privefl** [comment]
Poke @nscarene

**Comment by nscarene** [comment]
@YanxiaWei sorry for just getting back at you now. I hope this finds you well.
Can you tell me which codes you used please? So I can tell you how different they looked from the ones I used. 
Thank you.
