### ISSUE TITLE
Error: Can't have missing values, when running big_univLogReg()

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#239]
Good morning Dr. Privé

I hope this message finds you well. 

While trying to use LDpred2-grid, I ran into an issue. 

I ran this code **params$score <- big_univLogReg(as_FBM(pred_grid), y[ind.val2])$score** and got the missing values error message. Prior to that, I ran **pred_grid <- big_prodMat(G2 <- snp_fastImputeSimple(G), beta_grid, ind.row = ind.val2,  ind.col = ind.chr2)**. Some missing values are indeed present in the "pred_grid" file. 

I guess my question is how can I handle the NA's so that the function big_univLogReg() still works the same.

Any help will be greatly appreciated! 

With kind regards,

**Comment by privefl** [comment]
You can use `apply(pred_grid, 2, cor, y = y[ind.val2])` instead.

**Comment by nscarene** [comment]
Dear Dr. Privé.

It worked. Thank you again for your time!

With kind regards,

**Comment by privefl** [comment]
I need to update the tuto with this.
Will do next week.
