### ISSUE TITLE
Apply LDPred2 PRS to WGS

### ISSUE THREAD

**Issue by Nhasbani** [privefl/bigsnpr#240]
I am interested in adapting your score/method for whole genome sequencing data which would involve not restricting to HapMap3 since the data will be well imputed, and allowing for a lower variant threshold. Since LDPred2 computes a sparse LD matrix, I am hoping that we can potentially adapt it, but would be thrilled to get your insights.  Do you think it is possible to adapt your score in this manner? What is the maximum number of variants do you think your score can handle?  
 
Thank you in advance for any insights you would be willing to provide!
 
 natalie

**Comment by privefl** [comment]
I am trying with a set of 2.8M variants right now; seems to work but I have not check the results (to see if we actually get an improved performance).
I've just designed a new format for the correlation matrix that is about twice as fast and needs half of the memory.
But the algorithm remains quadratric with the number of variants, so x2 means x4, x3 means x9, etc.
Other things that need to be considered is the extremely high correlation between many of the variants which will probably make the Gibbs sampler go crazy. And other things like the fact that sumstats are not perfect for all variants equally.

**Comment by Nhasbani** [comment]
Thank you for the insights. Do you find improved performance with the increase in variants?

**Comment by privefl** [comment]
Not consistently for several phenotypes, no.
I am starting to think that HapMap3 variants are enriched with known associations; I will have to read more about this.

**Comment by privefl** [comment]
I would be interested in knowing if you tried with more variants than HM3.
