### ISSUE TITLE
Reversing SNPs after running LDpred2

### ISSUE THREAD

**Issue by johannfaouzi** [privefl/bigsnpr#248]
Hi,

I would have a general question about genetic risk scores, which is not specific to LDpred2, but that's what I used.

I assumed that, in summary statistics, there would be a convention so that, for a genetic variant, the reported effect allele would always be the same (taken from a reference such as HapMap3), but I was wrong. It still baffles me that not everyone uses the same reference to avoid any confusion, but it was my bad for not checking it.

The `info_snp` function does the check (by reversing variants if necessary), but I had already replaced the `a0` and `a1` columns from the summary statistics with the ones from `map_ldref` because of my wrong assumption.
```
# Match SNPs between summary statistics and LD ref mapping
info_snp <- snp_match(sumstats, map_ldref)
```

That being said, I have already run LDpred2-auto for many summary statistics and, even though it may not be the cleanest solution, I would like to avoid rerunning everything. If I'm not mistaken, reversing variants only changes the signs of the beta coefficients from the summary statistics. I would like to know if changing the signs of the beta coefficients returned by LDpred2 (`beta_auto` in the code below) that need reversing is equivalent:
```
# Estimate beta coefficients using LDpred2-auto
multi_auto <- snp_ldpred2_auto(
    corr, df_beta, h2_init=h2_est,
    vec_p_init=seq_log(1e-4, 0.9, 30), ncores=NCORES
)

beta_auto <- sapply(multi_auto, function(auto) auto$beta_est)
```

Moreover, even the cohorts in which I compute the genetic risk scores have variants that need reversing. Since the genetic data is a matrix whose entries are the numbers of effect alleles, I can use the function `f(x) = 2 - x` to get the number of effect alleles in the HapMap3 reference for variants that need reversing. Am I right?

I think that, at the end, I'm going to put every genetic data (summary statistics and individual-level data from my cohorts of interest) in the HapMap3 and rerun everything to have something clean, but I was wondering if what I wrote looks sound to you. Because, for the moment, I think that the GRS that I had computed are wrong :(

**Comment by privefl** [comment]
You need to rerun everything.
It is really bad to have reversed effects, it had probably completely messed with the Gibbs sampler, and you will get awful predictions.

**Comment by johannfaouzi** [comment]
Thanks for the clarification, everything is currently rerunning!

One final dummy question. When I will compute genetic risk scores with individual-level genetic data, the effect allele (and the number of effect alleles) should be the same as in the input files for LDpred2, right? When the effect allele and the other allele are reversed in the individual-level data, I need to replace the count, let's say `x`, with `2-x` (to get the number of the other alleles, because the other allele in the individual-level data is actually the effect allele in the coefficients)?

**Comment by privefl** [comment]
Yes, you need to match also this if the LD is not the same data as the test set.

Usually, people just use -x instead of 2-x for simplicity, but you're right.

**Comment by johannfaouzi** [comment]
Ok, thank you very much!
