### ISSUE TITLE
Documentation for alleles 'a0' and 'a1'

### ISSUE THREAD

**Issue by sritchie73** [privefl/bigsnpr#249]
Hi, I am having some confusion over what 'a0' and 'a1' should refer to in each instance when using LDpred2

- In the GWAS summary statistics of interest, should 'a0' or 'a1' refer to the effect allele (the one to which the 'beta' pertains to?) when renaming the columns prior to running `snp_match()`? 

- When loading the PLINK format bed/bim/fam files, which of the two allele columns in the bim file map to 'a0' and 'a1'? 

- In the loaded genotype data, do the dosages (1 for heterozygous, 2 for homozygous) correspond to 'a0' or 'a1'?

**Comment by privefl** [comment]
My take on this:
- beta should correspond to the effect of a1 in the sumstats
- a0 is usually allele2, and a1 is allele1
- number of a1

But sometimes they are reversed somewhere, but it's easy to see because you get only negative predictions.

**Comment by sritchie73** [comment]
Thanks for the quick response!
