### ISSUE TITLE
Problems with SFBM on multi-node clusters (lustre filesystem)

### ISSUE THREAD

**Issue by sritchie73** [privefl/bigsnpr#250]
The cluster I'm working on makes working with SFBM objects quite difficult. 

In short, the lustre filesystem does not play nicely with file-backed shared memory objects - they're basically extremely slow unless being accessed only by a single core.

The cluster offers an alternative per-node tmpfs file system mount (/ramdisks/) which is supposed to play nicely with file-backed shared memory objects, however, when trying to build the genome-wide matrix (using the $add_columns() method) I'm consistently getting bus errors. This does not appear to be due to lack of space in /ramdisks/ (as issue #174 would suggest) - the partition is sized as 50% of the nodes' RAM, and even when I request a whole 512GB node to myself, I get bus errors. The size of the final .sbk file is ~20GB (when created on the lustre filesystem).

**Comment by sritchie73** [comment]
My current attempt at a workaround is to:

(1) aggregate all the per-chromosome genetic correlations into a single SFBM on the standard filesystem
(2) copy the backing file to the /ramdisks/ partition
(3) symlink the backing file to the original location expected by the SFBM object in R

I'm not sure whether moving the backing file has consequences for the object, but i'll see if this works

**Comment by privefl** [comment]
Does the problem come from using memory-mapping, or from appending to a file? 

Maybe the way I append to a file is not really clean enough.

If this is the problem, just make one big SFBM from one big dsCMatrix using Matrix::bdiag().

**Comment by sritchie73** [comment]
It appears to be the appending - the test runs I've dug into crash around chromosome 10 or so. Additionally, the appending works if I'm filtering to a small number of variants (e.g. when using summary stats from an exome GWAS).

Thanks for pointing out the `bdiag()` function - I had tried making one big dsCMatrix by preallocating an empty dsCMatrix and writing in the diagonal positions (e.g. corr <- `corr[indices, indices] <- corr0`) but this was too slow so I gave up on this approach

**Comment by sritchie73** [comment]
Moving the backing file and replacing it with a symbolic link seems to be the way to go in this instance. 

 `bdiag()` for some reason was very memory hungry, so I was unable to build one big dsCMatrix from the loaded per-chromosome dsCMatrix objects due to memory limits.

**Comment by privefl** [comment]
I guessed it shouldn't require more than twice the size of the matrices.

How do you run it?

**Comment by sritchie73** [comment]
That's what I would have guessed as well, but I've just done a test run, which took ~6 times the size of the matrices:

```
library(foreach)
library(bigsnpr)
library(Matrix)

# Load each pre-computed correlation matrix for each chromosome.
# corr becomes a list() of 22 dsCMatrix objects once running, taking ~13.5GB of RAM
# (1.04 million SNPs total across all chromosomes)
corr <- foreach(this_chr = 1:22) %do% {
   readRDS(sprintf("data/ldpred2/filtered_ukb_ldcorr_chr%s.rds", this_chr))
}

# Aggregate into a single large dsCMatrix. Peak RAM usage is ~80GB, RAM usage is 13.5GB once finished.
corr <- Matrix::bdiag(corr)
```

**Comment by privefl** [comment]
Yes, I was able to reproduce the same behaviour.

Looking at the code https://github.com/cran/Matrix/blob/2e9cdfc101b37e0dfe0ca046afdacb1d40b720c4/R/diagMatrix.R#L205 makes sense, it is building a dgTMatrix first, then converting from that.

**Comment by privefl** [comment]
My attempt at solving this for this particular use case:

```r
bdiag_sym <- function(list_corr) {
  num_tot <- sum(sapply(list_corr, function(.) length(.@x)))
  I <- integer(num_tot)
  X <- double(num_tot)
  P <- list()
  offset_I <- 0L
  offset_P <- 0
  for (k in seq_along(list_corr)) {
    corr_k <- list_corr[[k]]
    len <- length(corr_k@x)
    ind <- (1 + offset_P):(len + offset_P)
    I[ind] <- corr_k@i + offset_I
    X[ind] <- corr_k@x
    P[[k]] <- utils::head(corr_k@p, -1) + offset_P
    offset_I <- offset_I + nrow(corr_k)
    offset_P <- offset_P + len
  }
  P[[k + 1]] <- num_tot
  Matrix::sparseMatrix(i = I, p = unlist(P), x = X, symmetric = TRUE, 
                       check = FALSE, index1 = FALSE)
}

N <- sample(2e4 + -10:10, size = 10, replace = TRUE)
list_corr <- lapply(N, function(n) {
  Matrix::rsparsematrix(n, n, density = 0.002, symmetric = TRUE)
})

system.time(test <- bdiag_sym(list_corr))
system.time(true <- Matrix::bdiag(list_corr))

all.equal(test, true)
```

But it does not seem to use less memory, which I am not sure why.

**Comment by privefl** [comment]
Any update on this?

**Comment by privefl** [comment]
Are you asking for more than one node to run LDpred2?

**Comment by privefl** [comment]
@sritchie73 I have updated the function `bdiag_sym()` above. This should now use much less memory (and be a bit faster).

**Comment by privefl** [comment]
@sritchie73 Also, I've put much work on providing what I think is a better way of appending.
Please try {bigsparser} v0.6 (use `remotes::install_github("privefl/bigsparser")`).
