### ISSUE TITLE
Parallelisation in R script outside of LDpred2 functions

### ISSUE THREAD

**Issue by sritchie73** [privefl/bigsnpr#251]
Prior to running any of the LDpred2 code, I have set up paralellisation in my R session as follows:

```
library(data.table)
library(foreach)
library(doMC)

# Auto detect if we're on compute nodes and determine available CPUs for parallization
nCores <- Sys.getenv("SLURM_CPUS_ON_NODE")
if (nCores == "") {
  registerDoSEQ()
  setDTthreads(1L)
} else {
  nCores <- as.integer(nCores)
  registerDoMC(nCores)
  setDTthreads(nCores)
}
```

This does not appear to interfere with any of LDpred2's functions, however, when I try to run a parallel foreach loop later in my script:

```
foreach(i = 1:N) %dopar% {
   do something
}
```

I get an error relating to `summary.connection`. 

I suspect the way I've set up the parallel backend is conflicting with the way LDpred2 sets up parallelisation, causing foreach to get confused.

Is there an alternative method from the bigsnpr package (or associated packages) I should be using for setting up the foreach parallel backend?

**Comment by privefl** [comment]
Inside your foreach-parallel loop, you have other bigsnpr functions running also in parallel with foreach?

Would you be able to get me a small example I could reproduce?

**Comment by sritchie73** [comment]
No bigsnpr functions running in the parallel foreach loops, I'm mainly using them to test the predicted PGS against the phenotype data.

E.g. for the grid model:

```
  ###########################
  # Run Grid model
  ###########################
  h2_seq <- round(h2_est * c(0.3, 0.7, 1, 1.4), 4)
  p_seq <- signif(seq_log(1e-5, 1, length.out = 21), 2)
  params <- expand.grid(p = p_seq, h2 = h2_seq, sparse = c(FALSE, TRUE))

  beta_grid <- snp_ldpred2_grid(genocorr, gwas_ss[!(fail_qc)], params, ncores = nCores)

  # Get PGS levels for all models
  pgs_grid <- foreach(this_chr = 1:22, .combine=`+`) %do% {
    geno <- snp_attach(sprintf("data/ldpred2/filtered_ukb_chr%s.rds", this_chr))
    geno <- snp_fastImputeSimple(geno$genotypes, ncores=nCores) # doesn't work with missing genotypes, so need to impute as median
    big_prodMat(
      X = geno,
      A.col = beta_grid[gwas_ss[!(fail_qc), which(chr == this_chr)],],,
      ind.col = gwas_ss[!(fail_qc) & chr == this_chr, `_NUM_ID_`],
      ncores = nCores
    )
  }

  # Assess model performance
  pgs_grid_perf <- foreach(gi = seq_len(nrow(params)), .combine=rbind) %dopar% {
    this_pgs <- pgs_grid[, gi]
    if (all(is.na(this_pgs))) {
      return(data.table(model="grid", paramset=gi, OR=NA_real_, SE=NA_real_, P.value=NA_real_, AUC=NA_real_))
    }
    pheno[, pgs_grid := this_pgs]
    this_perf <- glm.test(sprintf(mf, "pgs_grid"), "case_status", pheno, skip.ci=TRUE)
    this_perf[coefficient %like% "scale", .(model="grid", paramset=gi, OR, SE=logOR.SE, P.value, AUC)]
  }
  pgs_grid_perf[, grid_param_p := params$p]
  pgs_grid_perf[, grid_param_h2 := params$h2]
  pgs_grid_perf[, grid_param_sparse := params$sparse]
  ```
  
  So its that final foreach loop that would error (no error if using %do% instead of %dopar%)

**Comment by privefl** [comment]
That's not an issue with {bigsnpr} then.

I'm not really using {data.table} so I don't know if this could be an issue with this, but maybe you should use `.packages = "data.table"` in `foreach()`.

**Comment by sritchie73** [comment]
Googling the error suggested the problem is due to another parallel backend being registered somewhere:  https://stackoverflow.com/questions/64519640/error-in-summary-connectionconnection-invalid-connection

E.g. where I've registered a parallel backed for foreach using `doMC::registerDoMC` the conflict could arise when some other code registers a backend using `doParallel::makeCluster()`

**Comment by sritchie73** [comment]
Digging through the `bigsnpr` dependencies: [bigparallelr::register_parallel()](https://github.com/privefl/bigparallelr/blob/master/R/register-parallel.R) seems like a likely culprit, although I couldn't find any obvious calls to that in the various LDpred2 functions I've used (at first glance they all pass off ncores to C++ code)

**Comment by privefl** [comment]
`big_prodMat()` might be using it.
What if you register the backend after using the function? Do you still get the error?

**Comment by sritchie73** [comment]
I'm now re-registering the backend using `doMC` prior to running my parallel foreach loops and so far no errors, so looks like that was the culprit. Thanks for helping track that down!

**Comment by privefl** [comment]
Not sure I followed everything but great that you solved your issue.

**Comment by sritchie73** [comment]
Minimal reproducibal example showing how the error arise:

```
library(foreach)
library(doMC)
library(bigparallelr)

# Register a parallel backend in my script for 4 cores
registerDoMC(4)

# Run parallel foreach loop:
res <- foreach(ii = 1:10) %dopar% { ii } # works fine, as expected

# Some function that uses bigparallelr::register_parallel to do some parallel work:
f <- function() {
  bigparallelr::register_parallel(4)
  foreach(ii = 1:10) %dopar% { ii }
}
res2 <- f() # works fine, as expected

# Now if we try to run a parallel foreach loop again, we get an error:
res3 <- foreach(ii = 1:10) %dopar% { ii }
# Error in summary.connection(connection) : invalid connection

# But we can fix this by re-registering a parallel backend:
registerDoMC(4)
res3 <- foreach(ii = 1:10) %dopar% { ii }
```

**Comment by privefl** [comment]
Thanks for the small reprex.

I see that running `bigparallelr::register_parallel()` will basically unregister the previous parallel backend (when run on the same level).

Let's talk about it in the PR you opened.

**Comment by privefl** [comment]
I might get rid of foreach in the packages at some point, as I think it's very good for interactive use (scripts) but no so much for packages functions.
