### ISSUE TITLE
large dataset 

### ISSUE THREAD

**Issue by fff0996** [privefl/bigsnpr#254]
Good afternoon Dr.

I was hoping you could help with a concern I have. 
I tried calculating LD correlation genome-wide using
for (chr in 1:22) {
    # Extract SNPs that are included in the chromosome
    ind.chr <- which(info_snp$chr == chr)
    ind.chr2 <- info_snp$`_NUM_ID_`[ind.chr]
    # Calculate the LD
    # Calculate the correlation 
    corr0 <- snp_cor(
            G, 
            ind.col = ind.chr2,
            ncores = NCORES,
            infos.pos =POS2[ind.chr2],
            size = 3 / 1000
        )
    if (chr == 1) {
        ld <- Matrix::colSums(corr0^2)
        corr <- as_SFBM(corr0, tmp)
    } else {
        ld <- c(ld, Matrix::colSums(corr0^2))
        corr$add_columns(corr0, nrow(corr))
    }
}

At this time , i have 5,874,788 SNP in info_snp 
The number of SNPs is so many that we are having a hard time in the process of obtaining correlation.
the error is...
"Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105"

Is there another way when the number of snp is too many?

With kind regards,

**Comment by privefl** [comment]
Please look here for issues with the same error message.
