### ISSUE TITLE
Subset of correlation matrix

### ISSUE THREAD

**Issue by biostat0903** [privefl/bigsnpr#255]
Hi, 
I need to get a subset of the output of `snp_cor(G, ind.col = ind.chr2, size = 3 / 1000, infos.pos = POS2[ind.chr2], ncores = NCORES)`. Could you tell me how to do it?
Thanks for your help!
Best, 
Sheng

**Comment by privefl** [comment]
That's a standard sparse Matrix, you can use normal accessors. I think I subset the output in the LDpred2 tutorial, don't I?

**Comment by biostat0903** [comment]
Thanks for your fast reply! 
When I store `corr` matrix on disk using `sbk`. How can I reload the file into a new R environment?
I hope to load it and subset like `corr0` which calculates `snp_cor(G, ind.col = ind.chr, size = 3 / 1000, infos.pos = POS2[ind.chr], ncores = 5)`. 
Best, 
Sheng

**Comment by biostat0903** [comment]
Thanks for your fast reply!
I want to subset the `corr` matrix in S4 class. 
````R
Reference class 'SFBM_compact' [package "bigsparser"] with 11 fields
 $ extptr     :<externalptr> 
 $ nrow       : int 206022
 $ p          : num [1:206023] 0 631 1262 1893 2526 ...
 $ backingfile: chr "/XX/corr_merge.sbk"
 $ address    :<externalptr> 
 $ ncol       : int 206022
 $ nval       : num 5.68e+08
 $ sbk        : chr "/XX/corr_merge.sbk"
 $ rds        : chr "/XX/corr_merge.rds"
 $ is_saved   : logi FALSE
 $ first_i    : int [1:206022] 0 0 0 0 0 0 0 0 0 0 ...
 and 21 methods, of which 7 are  possibly relevant:
   add_columns, add_columns#SFBM, initialize, initialize#SFBM, save,
   show#envRefClass, show#SFBM
````

**Comment by privefl** [comment]
You can't subset the SFBM, that's not a feature I have implemented, and not sure i will.

You have to do the subsetting before and then transform to SFBM, as shown e.g. in the tutorial.
