### ISSUE TITLE
Some NA columns in snp_ldpred2_grid() output

### ISSUE THREAD

**Issue by jianvhuang** [privefl/bigsnpr#259]
I used the below parameters for the grid model. But some columns in the pred_grid are all NA. I wonder if this is acceptable or is there anything I need to adjust in the parameters? Thank you.

```
h2_seq <- round(h2_est * c(0.3, 0.7, 1, 1.4), 4)
p_seq <- signif(seq_log(1e-5, 1, length.out = 21), 2)

params <- expand.grid(p = p_seq, h2 = h2_seq, sparse = c(FALSE, TRUE))

# Note that missing values represent models that diverged substantially.
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
pred_grid <- big_prodMat(G, beta_grid, ind.col = df_beta[["_NUM_ID_"]])
```

**Comment by privefl** [comment]
From the tutorial (https://privefl.github.io/bigsnpr/articles/LDpred2.html): 
>Note that missing values represent models that diverged substantially.

From the documentation (https://privefl.github.io/bigsnpr/reference/LDpred2.html):
> Missing values are returned when strong divergence is detected.

**Comment by jianvhuang** [comment]
Thank you.
