### ISSUE TITLE
Question on using biglasso with FBM file from bigsnpr 

### ISSUE THREAD

**Issue by JianqiaoWang** [privefl/bigsnpr#261]
Hi Dr. Privé,
 
I am using your packages for some large-scale real data analysis. I would like to use biglasso (for strict cross-validation ) with big.matrix. Can I use the FBM file generated from the big NPR directly? I have tried several ways

- (1) G$bm() to get big.matrix directly and use it as input for biglasso
- (2) bigmemory::attach.big.matrix(G$bm.desc()) and use it as the input 
- (3) Initiate a new big.matrix and assign values G[] to the new big.matrix 

For now, only (3) works but it needs more RAM. The other two ways will cause a fatal error in biglasso. Is there a more easy way to achieve this?  
 
Thanks

**Comment by privefl** [comment]
Do you have an FBM of type double?
It is the only type that works for biglasso.

**Comment by JianqiaoWang** [comment]
The FBM is generated fromsnp_readBed() function and then get imputed by the snp_fastImpute. it seems not double type. Is there a way to convert it?

**Comment by privefl** [comment]
Yes it is not.
You can use `big_copy(..., type = "double")`.
But note that it will take 8 times more space..
