### ISSUE TITLE
Problem while computing LD correlation

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#262]
Good evening Dr. Prive,

I hope this message finds you well.  .

While trying to compute the LD correlation matrix, I get "error: Only upper-triangle symmetric matrices are implemented". I have ran the same codes before and haven't encountered this error before.
Some help would be greatly appreciated.

With kind regards,

**Comment by privefl** [comment]
In function `snp_cor()`?

**Comment by nscarene** [comment]
Hello Dr. Prive,

No, I believe the error comes from the function as_SFBM()

**Comment by privefl** [comment]
Can you output `class(corr0)` and `str(corr0)`?

**Comment by nscarene** [comment]
Dear Dr. Prive,

This is what it reports:

> class(corr0_Ghana)
[1] "dsCMatrix"
attr(,"package")
[1] "Matrix"
> str(corr0_Ghana)
Formal class 'dsCMatrix' [package "Matrix"] with 7 slots
  ..@ i       : int [1:2] 0 1
  ..@ p       : int [1:3] 0 1 2
  ..@ Dim     : int [1:2] 2 2
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ x       : num [1:2] 1 1
  ..@ uplo    : chr "L"
  ..@ factors : list()

**Comment by privefl** [comment]
How do you compute this correlation matrix?
The problem comes from `@ uplo : chr "L"`; this should be `U` instead, for Upper, if you're using e.g. `snp_cor()`.

Anyway, you can just use `as_SFBM(as(corr0, "dgCMatrix"))`, but it will take a bit more time and memory.

**Comment by nscarene** [comment]
I still got the same error.

This is the code I used (from the tutorial)
for (chr in 1:22) {
  
  # print(chr)
  
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'G'
  ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
  
  corr0 <- snp_cor(G, ind.col = ind.chr2, size = 3 / 1000,
                   infos.pos = POS2[ind.chr2], ncores = NCORES)
  
  if (chr == 1) {
    ld <- Matrix::colSums(corr0^2)
    corr <- as_SFBM(as(corr0, "dgCMatrix"))
  } else {
    ld <- c(ld, Matrix::colSums(corr0^2))
    corr$add_columns(corr0, nrow(corr))
  }
}

**Comment by privefl** [comment]
You need to do the same in `corr$add_columns()` as well.
But do you really get this lower triangles with `snp_cor()`?
Was it a real example when you got only two values? Is this the length of `ind.chr2`?
E.g. what do you get for `table(df_beta$chr)`?

**Comment by privefl** [comment]
I see that you indeed get a lower triangle when using
```r
corr <- Matrix::sparseMatrix(i = 1:2, j = 1:2, x = c(1, 1),
                             dims = c(2, 2), symmetric = TRUE)
str(corr)
```

But that should not really happen in practice, you should not get only two variants on one chromosome.
Anyway, I'll try to fix this.

**Comment by nscarene** [comment]
Dear dr. Prive, 

Thank you very much.

The reason why some chromosomes may have has little as two variants is because there were a lot have matching variants between the sumstats and genotyped data. Although I am aware that we should kept the analysis to HapMap variants.

**Comment by privefl** [comment]
This should be fixed in the latest GitHub version.

Thanks for reporting.

**Comment by nscarene** [comment]
Thank you!!!

**Comment by williambrandler** [comment]
> How do you compute this correlation matrix? The problem comes from `@ uplo : chr "L"`; this should be `U` instead, for Upper, if you're using e.g. `snp_cor()`.
> 
> Anyway, you can just use `as_SFBM(as(corr0, "dgCMatrix"))`, but it will take a bit more time and memory.

this worked for me

**Comment by privefl** [comment]
You should not have to rely on `as_SFBM(as(corr0, "dgCMatrix"))` anymore.
Using `as_SFBM(corr0)` directly should be much faster and less memory-demanding.

**Comment by williambrandler** [comment]
must have hit an edge case because I did get the same error using bigsnpr (latest version from CRAN)

`as_SFBM(as(corr0, "dgCMatrix"))` solved the issue

I was writing corr0 to an r data file (.rda) first before loading back in and converting to `as_SFBM`

**Comment by privefl** [comment]
I'll try to push some more recent version on CRAN in a few weeks.

**Comment by williambrandler** [comment]
thanks, doesn't seem to be hurting us noticeably in terms of overall runtime
