### ISSUE TITLE
Segfault/memory not mapped/nb_cores()

### ISSUE THREAD

**Issue by MatthewMaher** [privefl/bigsnpr#263]
I was trying to test out and use LDpred2 following the tutorial at:
https://privefl.github.io/bigsnpr/articles/LDpred2.html

I initially got stuck with things falling over after encountered this error:

 ```
*** caught segfault ***
address 0xfffffffc154831d0, cause 'memory not mapped'

```
I believe this error can occur for various reasons, but after playing around a bit, it is clear that in my case the error stems from what is probably a portability issue with the function **nb_cores()** in bigsnpr/bigparallelr. 

For whatever reason, on my platform (RedHat, x86, R 4.0, bigparallelr_0.3.1)  **nb_cores() returns 0**. 

For LDpred, passing in this zero value seems to result in the above error.   Either hardcoding a valid (positive) value or simply removing the parameter and allowing it to default solves the issue.  

So the LDpred code should probably add a check for that zero and force it to 1 (after giving a warning message) to save someone else the confusion.

**Comment by privefl** [comment]
Thanks for reporting.

Which version of {bigparallelr} do you have?

Which function did you call with `ncores = 0`?

**Comment by MatthewMaher** [comment]
**bigparallelr_0.3.1**

The error occurred on the call to '**snp_cor**' .   But I don't think that's the only code that might benefit from a check:

I was following along your tutorial subsection for LDpred2-auto and so I just tested forcing the NCORES parameter to zero for the call to '**snp_ldpred2_auto**' and that also fell over, but with a different mysterious error: 

```
Error in makePSOCKcluster(names = spec, ...) : 
  numeric 'names' must be >= 1
```

**Comment by privefl** [comment]
What do you get for 
```r
parallelly::availableCores(logical = FALSE)
parallelly::availableCores(logical = TRUE)
```

**Comment by MatthewMaher** [comment]
```
> library("bigparallelr")
Loading required package: foreach
> nb_cores()
nproc 
    0 
> parallelly::availableCores(logical = TRUE)
nproc 
    1 
> parallelly::availableCores(logical = FALSE)
nproc 
    1 

```

**Comment by privefl** [comment]
I see..
That's my bad.
I will fix this tomorrow.

**Comment by privefl** [comment]
This should be fixed in the latest GitHub version of {bigparallelr} (`remotes::install_github("privefl/bigparallelr")`).

Please confirm and I will push it on CRAN.

**Comment by MatthewMaher** [comment]
Looks good:  
1.  nb_cores() now returns 1 
2.  the call to snp_cor() now errors out with a user level message:
`Error: 'ncores' should be at least 1.`

**Comment by privefl** [comment]
Great, I'll push this to CRAN then.
