### ISSUE TITLE
snp_cor() error

### ISSUE THREAD

**Issue by nscarene** [privefl/bigsnpr#266]
Good morning Dr. Privé,

I hope this finds you well. 

I'm having an issue with snp_cor(). I am running the codes as they were before (running just fine) and now I get this error when I try to compute LD correlation:
  Error: "ind.row should contain only integers.

This is what I am trying to run (it used to work just fine):
```r
for (chr in 1:22) {
  
  # print(chr)
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'G'
  ind.chr2 <- df_beta_$`_NUM_ID_`[ind.chr]
  
  corr0 <- snp_cor(G, ind.col = ind.chr2, size = 3/1000, '@alpha= "U"',
                         infos.pos = POS2[ind.chr2], ncores = NCORES)
  
  if (chr == 1) {
    ld_ <- Matrix::colSums(corr0^2)
    corr_ <- as_SFBM(as(corr0_), "dgCmatrix")
  } else {
    ld_ <- c(ld_, Matrix::colSums(corr0^2))
    corr$add_columns(corr0,nrow(corr), "dgCMatrix")
  }
}
```

Now I'm not sure what is going on. I have tried to trace back the error and I got:
```r
11: stop(sprintf(...), call. = FALSE)
10: stop2("'%s' should contain only integers.", deparse(substitute(x)))
9: assert_int(ind.row) at <text>#1
8: eval(parse(text = check[i]))
7: eval(parse(text = check[i]))
6: eval(substitute(expr), data, enclos = parent.frame())
5: eval(substitute(expr), data, enclos = parent.frame())
4: with.default(args, eval(parse(text = check[i])))
3: with(args, eval(parse(text = check[i])))
2: check_args()
1: snp_cor(G_Ghana, ind.col = ind.chr2_Ghana, size = 3/1000, "@alpha= \"U\"",
       fill.diag = 1, infos.pos = POS2_Ghana[ind.chr2_Ghana], ncores = NCORES)
```

My apologies for the lengthiness of this text. Your time is much appreciated.

Thank you!!!

**Comment by nscarene** [comment]
Thank you for editing. 

By "it used to work fine", I mean there was no error. I would run it as follows (without the @alpha = "U" or dgCMatrix arguments). But then I got an error about Class, cause it was using Lower triangle instead of Upper. Then you suggested to add dgCMatrix as an argument or '@alpha = "U"' in bigsnpr v 1.8.1
```
for (chr in 1:22) {
  
  # print(chr)
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'G'
  ind.chr2 <- df_beta_$`_NUM_ID_`[ind.chr]
  
  corr0 <- snp_cor(G, ind.col = ind.chr2, size = 3/1000,
                         infos.pos = POS2[ind.chr2], ncores = NCORES)
  
  if (chr == 1) {
    ld_ <- Matrix::colSums(corr0^2)
    corr_ <- as_SFBM(as(corr0_))
  } else {
    ld_ <- c(ld_, Matrix::colSums(corr0^2))
    corr$add_columns(corr0,nrow(corr))
  }
}
```

**Comment by privefl** [comment]
Any update on this?

**Comment by nscarene** [comment]
Hello Dr. Prive,

The problem was resolved by running theses codes while computing LD matrix:
`for (chr in 1:22) {
  
  # print(chr)
  
  ind.chr_Affy <- which(df_beta_Affy$chr == chr)
  ## indices in 'G'
  ind.chr2_Affy <- df_beta_Affy$`_NUM_ID_`[ind.chr_Affy]
  
  corr0_Affy <- snp_cor(G_Affy, ind.col = ind.chr2_Affy, size = 3/1000, 
                         infos.pos = POS2_Affy[ind.chr2_Affy], ncores = NCORES)
  
  if (chr == 1) {
    ld_Affy <- Matrix::colSums(corr0_Affy^2)
    corr_Affy <- as_SFBM(as(corr0_Affy,"dsCMatrix"))
  } else {
    ld_Affy <- c(ld_Affy, Matrix::colSums(corr0_Affy^2))
    corr_Affy$add_columns(corr0_Affy,nrow(corr_Affy))
  }
}
`

**Comment by privefl** [comment]
`corr0_Affy` should already be a dsCMatrix, right?

**Comment by nscarene** [comment]
Yes, it should! But when I do not specify it by adding the argument "dsCMatrix" I used to get an error that came from @ uplo : chr "L", where I should have add Upper, instead of lower (see issue #262 )

**Comment by privefl** [comment]
Yes, but this has been fixed. 
So, you should not need this conversion anymore.
