### ISSUE TITLE
Question about "inversed PRS distribution"

### ISSUE THREAD

**Issue by HasangaDM** [privefl/bigsnpr#268]
Salut Florian, 

Merci pour ton travail et d'être actif dans le support de tes packages, notamment pour LDpred2.

I am contacting you to have your insights concerning an issue that I get when I am working with :
- UKB data (as the reference LD panel, the one you provided)
- CARDIoGRAMplusC4D GWAS sumstats for CAD (Nikpay et al 2015)
- And imputed genotype data from a Canadian cohort of >25000 participants as a study cohort (only HM3 SNPs).

I am trying to calculate a PRS for CAD in the Canadian cohort. I have first adapted a pipeline based on your tutorial, and I succeeded to get PRS that outperformed a little bit the one that I pre-published on medRxiv, using the UKB as the study cohort and LDpred1.

But when I replace all the genotype info with the Canadian data, all my PRS (inf, grid-sparse, grid-no-sparse, auto) predict negatively (significantly) my CAD outcome (e.g. OR per 1SD of the PRS distribution of ldpred2-auto, adjusted for age + sex + genetic PC1-10: OR = 0.82 [95% CI; 0.79 to 0.85]. P-value = 8.48e-35)
I can reverse my PRS distribution (multiplying by -1) but I am not sure if it is the right way to do and I would like to understand what is happening.

Also, when I look at the grid parameters chart, I get this:

![param_test_grid_CAD_nikpay_CLSA_25092021](https://user-images.githubusercontent.com/90065422/137754646-f34b56e1-17a8-4fd6-ac07-7f369afd0eac.jpg)

Instead of this (from UKB data):

![param_test_grid_CAD_nikpay_UKB_2021-10-18](https://user-images.githubusercontent.com/90065422/137768176-7d820331-e7a0-46ce-9693-b8cdd4ec591b.jpg)

Do you have any idea explaining why or any suggestion/comment? I am suspecting the imputed genotype data call with snp_readBed() for my cohort (for UKB, I used the snp_readBGEN() as you recommend - I am not able to use this function with the Canadian cohort bgen files, as I am getting an error when using the following command:

```{r} 
SUMMARY <- function(info_snp) {
  chi2 <- with(info_snp, (beta / beta_se)^2)
  print(round(mean(chi2, na.rm = TRUE), 2))
  S <- rep(NA, ncol(G)); S[info_snp$`_NUM_ID_`] <- chi2
  signif <- pchisq(S, df = 1, lower.tail = FALSE) < 5e-8
  print(sum(signif, na.rm = TRUE))
  ind.keep <- snp_clumping(
    G, infos.chr = map$chr, infos.pos = map$pos, S = S,
    ind.row = ind.val, thr.r2 = 0.01, size = 10e3, ncores = NCORES,
    exclude = which(is.na(S) | !signif))
  print(length(ind.keep))
}

(info_snp <- tibble::as_tibble(info_snp))
> SUMMARY(info_snp)
[1] 1.13
[1] 352
Error: 'pos.chr' is not sorted.
stop2("'%s' is not sorted.", deparse(substitute(x)))

 ```
If I skip this step, I lose about 39K SNPs as they are considered as "bad SNPs" - after the following lines : 

```{r} 
sd <- runonce::save_run(
  sqrt(big_colstats(G, ind.val, ncores = NCORES)$var),
  file = paste0(main_nikpay,"/sd_bgen.rds")
)
sd_val <- sd[info_snp$`_NUM_ID_`]
sd_ss <- with(info_snp, 2 / sqrt(n_eff * beta_se^2))
is_bad <-
  sd_ss < (0.5 * sd_val) | sd_ss > (sd_val + 0.1) | sd_ss < 0.1 | sd_val < 0.05

 ```
Therefore, I am using plink files (obtained directly from vcf.gz files - bgen and sample files were obtained from the following command : 

for x in {1..22}
do 
qctool -g ./chr${x}.dose.vcf.gz -ofiletype bgen_v1.2 -bgen-bits 8 -og ./clsa_v3_chr${x}_hrc.bgen -os ./clsa_v3_chr${x}_hrc.sample
done

Merci beaucoup pour ton aide !
Hasanga

**Comment by privefl** [comment]
Any update on this?

**Comment by HasangaDM** [comment]
Hi Florian, Thanks for your answer and for asking a feedback.
Your idea with comparing the frequencies between the LDref and the sumstats were good, and I made the changes as you suggested (reversing all alleles).

Thanks again!
