### ISSUE TITLE
Errore: 'total_len' should have only positive values

### ISSUE THREAD

**Issue by Giuseppe1995** [privefl/bigsnpr#271]
I'm getting this error while running `bed_projectPCA`. More in detail, it gives me the following output:

`[Step 1/3] Matching variants of reference with target data..
1,664,852 variants to be matched.
81,849 ambiguous SNPs have been removed.
983,139 variants have been matched; 0 were flipped and 318,728 were reversed.

[Step 2/3] Computing (auto) SVD of reference..

Phase of clumping (on MAC) at r^2 > 0.2.. keep 321845 variants.
Discarding 321845 variants with MAC < 10.

Iteration 1:
Computing SVD..
Error: 'total_len' should have only positive values.`
I obviously checked that columns and rows indices were not negative. Moreover, although an apparently similar issue has been closed ([https://github.com/privefl/bigsnpr/issues/70](https://github.com/privefl/bigsnpr/issues/70)), it is far from helping me. I also tried to look up the keyword "total_len" in the manual, but it does not appear.
I know that this is maybe a very simple issue, but it is the first time I'm approaching to population genetics studies and I really don't know how to proceed.
Thank you,
Giuseppe.

**Comment by privefl** [comment]
I guess the issue is
```
Phase of clumping (on MAC) at r^2 > 0.2.. keep 321845 variants.
Discarding 321845 variants with MAC < 10.
```

Which is kind of weird, because it means all variants have been removed by this MAC threshold.

How many individuals do you use?

**Comment by Giuseppe1995** [comment]
I am doing a test with only 3 subjects of my dataset... Maybe this could be the problem?

**Comment by privefl** [comment]
Are you using 3 individuals as the reference dataset?
Yes, this is the problem.
You should be using at least 200 individuals I guess.

**Comment by Giuseppe1995** [comment]
However, I tried with my complete dataset (n=136), and it actually gives me another error in the third step:
...
[Step 3/3] Projecting PC scores on new data..
Error in { : task 1 failed - "Tested 136 < 136. Subscript out of bounds."

**Comment by privefl** [comment]
Are you sure you're not inverting them?
The clumping and the filtering (and the PCA) should be performed on the reference data.

**Comment by Giuseppe1995** [comment]
Actually, I am not doing any clumping/filtering as the function `bed_projectPCA` is provided with options to discard LD SNPs. Here is the command I run:

```
bed_projectPCA(
refBed,
myBed,
k = 10,
ind.row.new = rows_along(refBed),
ind.row.ref = rows_along(myBed),
ind.col.ref = cols_along(refBed),
strand_flip = TRUE,
join_by_pos = TRUE,
match.min.prop = 0.10,
build.new = "hg19",
build.ref = "hg19",
liftOver = NULL,
verbose = TRUE,
ncores =2
)
```
where `myBed` and `refBed` are the testing and the reference bed files, respectively.

**Comment by privefl** [comment]
Don't you see any problem in 
```r
ind.row.new = rows_along(refBed),
ind.row.ref = rows_along(myBed),
```
?

**Comment by privefl** [comment]
Were you able to fix the issue?

**Comment by Giuseppe1995** [comment]
Oh, I completely mistook the two options... it worked properly, however!
Thank you and sorry for the misunderstanding

**Comment by privefl** [comment]
No problem, it happens.
