### ISSUE TITLE
LDpred2 never finishes, poor RAM utilisation

### ISSUE THREAD

**Issue by mkelcb** [privefl/bigsnpr#273]
Using the latest version of LDpred2 (1.8.11) I have been unable to get it to successfully to run snp_ldpred2_auto ever since my project changed location on the cluster. I've tried various combinations of 5-10-15 and 32 Cores +125GBs of RAM. I also tried "allow_jump_sign=F" and "shrink_corr= 0.95", but to no avail. The jobs don't finish even in 48 hours.

Despite the assigned 125GBs of RAM, LDpred2 only seems to be using ~10GB. 
As I am also on a lustre based cluster so this issue may be related to https://github.com/privefl/bigsnpr/issues/250 .

**Comment by privefl** [comment]
How many variants do you have in the correlation matrix?
What is is size on disk? (`file.size(corr$sbk))`)

You may want to try using `verbose = TRUE`, no parallelization (default), and just one initial `p` (default).
The first iteration might take a few minutes (the time to read the correlation matrix from disk), but starting at the second iteration, you should get a pretty good sense of how fast is each iteration, and extrapolate from that.

**Comment by mkelcb** [comment]
@privefl 

```
nrow(corr) # 955712
file.size(corr$sbk) # 32146605696
```

So standard ~1 mil Hapmap3 SNPs, at 32GBs of RAM. Nothing out of the ordinary.

Running a single p on a single core:
`multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est,vec_p_init = 1e-4, allow_jump_sign=F, shrink_corr= 0.95, verbose = TRUE)  `

I get a count printed with some numeric output, which I assume is the iteration,  about once a minute (~40 secs).

**Comment by privefl** [comment]
OK. I guess you could use the new compact format, which should be twice as efficient (see https://twitter.com/privefl/status/1415713020924280840?s=20 and the LDpred2 tutorial).

So, every 40 seconds means that it should finish the 700 iterations in ~8H.
Then do you think it could be an issue with the type of cluster you use that somehow makes it inefficient to use parallelization over memory-mapped data?

What I would try to diagnose the issue is to run 20 iterations (burn_in + num_iter) with 1 core and 1 p. Then with 2 cores and 2 p, then 4, and finally 16. Benchmark this and see if there is a trend. Normally they should be approx the same times. If the cluster makes this somehow inefficient, I guess you would have something like an exponential growth maybe.

Also, do you have the same problem with LDpred2-grid (which uses a different kind of parallelization)?

**Comment by mkelcb** [comment]
I've tried running it with 10 cores:
`multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est, vec_p_init = seq_log(1e-4, 0.9, 30), allow_jump_sign=F, ncores=10, shrink_corr= 0.95, verbose = TRUE)  `

Unfortunately, since the 'verbose' output is disabled for multi core runs, it is impossible to know exactly how long each iteration takes on a single core. However, looking at the CPU utilisation in `top`, I am getting around 7-8% / core, so I suspect my issue is the same as https://github.com/privefl/bigsnpr/issues/250 : the SFBM format is incompatible with lustre based clusters. 

I also tried it with the "`compact = TRUE`" flag enabled. This reduced the matrix size about half (to 15GB) however, it appeared not to have have helped much otherwise, CPU utilisation remained  at around 10%. Going forward, you may have some hard decisions to make about the continued usage of the SFBM format...

PS: sadly my project does not use LDpred2-grid, so I cannot help there.

**Comment by privefl** [comment]
I think memory-mapping is a pretty standard way of accessing data from disk.
I think you should ask your IT department if they can tell you more about this, and ask if there is a way for you or me to make things easier to run on this kind of cluster.

**Comment by privefl** [comment]
Again, I think it would also be interesting to test the benchmarks I suggested.

And also try to run `snp_ldpred2_grid()` in parallel (you would need a grid with at least `ncores` elements) to see if the OpenMP parallelization works better on your cluster.

**Comment by privefl** [comment]
Any update on this?

**Comment by mkelcb** [comment]
This is the same issue as this: https://github.com/privefl/bigsnpr/issues/250. My current workaround is to use ldpred2 per-chrom, which I realise is not the recommended workflow, but I found no other way to make ldpred2 consistently work.

The issue originates from an incompatibility between the entire SFBM philosophy and lustre file systems, so the problem goes very deep into the core of bigsnpr, therefore it will need a lot more than any of the quick fixes/workarounds you have suggested so far. On the flipside, if you were to succeed, then researchers at Cambridge/Sanger would be able to use ldpred2 auto as intended, so depending on how much you want labs here to use bigsnpr, it may still be worth your time and effort. 

PS: I am so very happy that everything worked out for you at Aarhus and that you are now back in the game.

Martin

**Comment by privefl** [comment]
Thanks for the kind words.

To come back to the problem, the thing is that almost all data structures in my packages use memory-mapping.
In my opinion, this is something fairly common to access files.
There is nothing the IT department can do about it?

**Comment by privefl** [comment]
Are you asking for more than one node to run LDpred2?

**Comment by mkelcb** [comment]
I am not a sys admin, but from what I understood lustre's way of data/memory management that provides its high performance is the very same thing that causes this issue. So it seems this is a catch 22 situation.

Since lustre is the system that everyone uses at the institute, we are stuck with it and they are not going to change to accommodate a single R package, so it is the R package that would need to change... This is why I said that that this is going be a difficult choice for you, as the SFBM way of representing large objects is such a core part of your package, so changing that would be a real pain, but alas, there does not seem to be any other way I am afraid.

PS: all engaged cores are on the same host.

**Comment by privefl** [comment]
Could you just try to ask them if there is nothing you can do?
E.g. some temporary configuration that disable some of the Lustre features to enable a proper work of memory-mapping.
This can't be the first time someone at your institution uses some code with memory-mapping.

**Comment by privefl** [comment]
Any update on this?
