### ISSUE TITLE
Published LassoSum2 update equation differs from originally published LassoSum update equation

### ISSUE THREAD

**Issue by jordanero** [privefl/bigsnpr#278]
Hi,

While reading "Identifying and correcting multiple sources of misspecification in GWAS summary statistics for polygenic scores", I noticed that the published LassoSum2 update equation:
![Screen Shot 2021-12-01 at 12 17 27 PM](https://user-images.githubusercontent.com/18555843/144289743-cbfb764c-3955-4d6d-87ae-39d6d6a93b52.png)
differs from the originally published LassoSum update equation (from Mak et al. 2017):
![Screen Shot 2021-12-01 at 12 31 11 PM](https://user-images.githubusercontent.com/18555843/144289866-a10fa809-bd4f-4a67-b933-4f10a295b088.png)

The absolute value sign is in a different location. These expressions are not equivalent in some cases (for example, lambda = 1, u = -1.1).

I walked through the derivation, and it seems like this is a typo in the original LassoSum paper, not a difference caused by the LassoSum regularization reparameterization. Is this correct?

Thanks a lot! I really appreciate all the work you've done to make your methods easy for others to use.

Jordan

**Comment by privefl** [comment]
Yes, this is the formula for the coordinate descent algorithm for the elastic-net regularization.
I just assumed it was a typo in the original publication, and corrected it.

**Comment by jordanero** [comment]
That's great! Thanks a lot.
