### ISSUE TITLE
bigsnpr on Ubuntu 20.04

### ISSUE THREAD

**Issue by williambrandler** [privefl/bigsnpr#279]
We have a docker container that installs bigsnpr on Ubuntu 18.04, running the tutorial works.

Recently we upgraded to Ubuntu 20.04 (https://github.com/projectglow/glow/pull/452), updating from bionic-cran40 to focal-cran40. 

When we now import the library,

`library(bigsnpr)`

```
Error in library(bigsnpr) : there is no package called 'bigsnpr'
Some(<code style = 'font-size:10p'> Error in library(bigsnpr): there is no package called 'bigsnpr' </code>)
```

Other R packages in our Docker container import without issue. Manual install of bigsnpr also works. Any ideas?

**Comment by privefl** [comment]
No, sorry, I have never seen this issue before.
It is probably not related to my package specifically I guess.

**Comment by williambrandler** [comment]
hey @privefl thanks, I do think it is related specifically to bigsnpr, as other R packages (ukbtools, sim1000G, qqman) do load without error

**Comment by privefl** [comment]
The package is regularly tested on many architectures through CRAN and GitHub Actions.

I suggest you try to reinstall it. For now, the package does not seem to be installed at all.

**Comment by williambrandler** [comment]
hey @privefl it's working now. 

I had some issues with the Ubuntu 20.04 installation that I fixed. 
Wasn't able to pinpoint why bigsnpr wasn't working (but other libraries were), either way we're good now

**Comment by williambrandler** [comment]
hey @privefl I figured out the issue. 

When adding the `bgenix` tool to the docker container I get

`library(bigsnpr)`

`Error in library(bigsnpr) : there is no package called 'bigsnpr'
Some(<code style = 'font-size:10p'> Error in library(bigsnpr): there is no package called 'bigsnpr' </code>)`

but if I remove this tool I can load bigsnpr

Any ideas why these two tools do not play together?
