### ISSUE TITLE
Scale of sample_beta

### ISSUE THREAD

**Issue by yidingdd** [privefl/bigsnpr#280]
Hey Florian, 

I have some problem calibrating the posterior genetic value credible interval when using ldpred2-auto. The problem might be, the beta_est is scaled but the sample_beta is not. Could you look into it? 
https://github.com/privefl/bigsnpr/blob/b4a886be3c22696afa352622a9d6b8b04980e2db/R/LDpred2.R#L208-L212

Thanks!

**Comment by privefl** [comment]
Yes, this is actually on purpose (because I'm using these for another purpose); this is somewhat mentioned in the documentation:
https://github.com/privefl/bigsnpr/blob/master/R/LDpred2.R#L133-L134

You will have to do it yourself using
```r
scale <- with(df_beta, sqrt(n_eff * beta_se^2 + beta^2))
```

**Comment by privefl** [comment]
I've tried to make it clearer in the documentation now.
