### ISSUE TITLE
estimation GPS using more than 300M SNP 

### ISSUE THREAD

**Issue by dkssud24** [privefl/bigsnpr#286]
I am currently estimating genome-wide polygenic risk scores on various phenotypes in the UK Biobank samples.

However, we faced critical problems such as the following;

Firstly, we were not able to calculate genome-wide polygenic risk scores as more SNPs were used, most probably due to a lack of computer capacity (core model name: AMD EPYC 7702P, core count: 128, Memory (RAM) 350GB). For now, we could calculate up to 250M SNP.

Secondly, we found that there was a problem in calculating LDmatrix (ex, performing codings such as “coad”). On the other words, a problem occurs when LDmatrix is calculated in individual chromosomes and individual LD matrixes are combined.

So, to solve this problem, we tried to as the following;

Firstly, we tried to calculate genome-wide PRS in the individual chromosomes as you recommended (https://privefl.github.io/bigsnpr/articles/LDpred2.html). We calculated LDmatrix and genome-wide polygenic risk scores in individual chromosomes and then combined them.

Secondly, to confirm the third step, we used the maximum SNP to compare (1) the genome-wide polygenic risk scores that were combined in the last step following the calculation in individual chromosomes and (2) the genome-wide polygenic risk scores that were calculated in all 22 chromosomes together. However, the 2 genome-wide polygenic risk scores results were quite different (for example, order ranking, scale).

So I have a question for you as the following;

Q1. Is there an irrevocable problem with the genome-wide polygenic risk scores that s combined following calculation in individual chromosomes?

Q2. If so in Q1, then can we use the method that calculates genome-wide polygenic risk scores using the remnant SNPs after clumping based on allele frequency [https://privefl.github.io/bigsnpr/articles/pruning-vs-clumping.html]?

Q3. But, when we clumped SNP according to the method [https://privefl.github.io/bigsnpr/articles/pruning-vs-clumping.html], there were too few SNPs (5M – 50M). So, we set the criteria for clumping as r2 = 0.9, 1kb-around to leave as much as SNP. Will it be OK?

**Comment by privefl** [comment]
Sorry I didn't see this earlier.

Currently, LDpred2 is not suitable for running with 5M+ variants.
We recommend you restrict to the provided HapMap3 variants for good performance (computation- and prediction- wise).
