### ISSUE TITLE
Too high p parameter is okay?

### ISSUE THREAD

**Issue by kkonoo** [privefl/bigsnpr#287]
Hi, there!
Thank you for this great tool for PGS analysis!
I have several questions about my result.
I ran LDpred2-grid using my own summary statistics (QC-ed as you recommended) and recommended parameters grid (n=168).
(length of chain: 10,000 with 2,000 burn-in iterations as you did in your LDpred2 paper)
My summary statistics was from a single population (with very large sample size) and a disease with low prevalence (~0.1%).

Finally, I got some results but seems quite strange(?).

1) I've got NAs in many parameter combinations (in total, 110 parameters among 168).
Does this indicate that something was wrong in my process? Or is this just a usual phenomenon?
2)  My best parameters set is (p=5.6e-01, h2 = 1.4*ldsc_h2). From the biological perspective, the p-value seems quite high. 
Does this represent something different? Or is this reasonable in my dataset?

**Comment by privefl** [comment]
0. For LDpred2-grid, the default is to use 50 burn-in + 100 iterations. I believe this is what I used in the paper too.
1. I guess it is possible if these models are really far for from the truth. Can you show the plot with the prediction for all parameter combinations (as in the tuto)?
2. First, the best prediction does not mean that these are the true parameters. Which p-values seem high?

**Comment by kkonoo** [comment]
Thank you for your reply.
Oh, I misunderstood your option. The 10,000 with 2,000 burn-in iterations was used in the SBayesR..!
Here are some plots.

1) sumstat QC in chromosome 1
![sumstat_QC_chr1](https://user-images.githubusercontent.com/41933720/147445920-36abec7c-5742-4232-b033-a80d62242756.png)

2) model evaluation in chromsome 1 (grid mode)
![model_eval_grid_chr1](https://user-images.githubusercontent.com/41933720/147445988-0e468fd5-ca72-49c6-8e33-95d811a7b863.png)

**Comment by privefl** [comment]
- Beware that p is not a p-value, it is the proportion of causal variants assumed in the model.

- Retry with less iterations, it will have less opportunity to diverge. But I guess these results are possible if the trait is really polygenic. I'm just a bit surprised by the difference it makes with the different h2 values. You should probably try even larger values.

**Comment by kkonoo** [comment]
Oh, I thought p is the p-value, thank you for noticing it.
I will retry default interation. What do you mean by larger values? You mean that I should try more diverse h2 parameters?
e.g. ldsc_h2_est * c(0.3, 0.7, 1, 1.4) >> ldsc_h2_est * c(0.3, 0.7, 1, 1.4, 1.7, 2.0) ??

**Comment by privefl** [comment]
Yes, you can try that.

**Comment by privefl** [comment]
Any update on this?
