### ISSUE TITLE
What is the quickest way to get list_snp_id?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#290]
What is the quickest way to get list_snp_id? I have the bgen file and sample file, and one way I can think of is to run plink2 regression and extract id from the result, but I wonder if there's an easier way. It also seems the me the pgen isn't supported here am I correct?  That's the initial file format that I have, and I converted it into bgen to fit the program requirement.

**Comment by privefl** [comment]
Do you want to get the IDs of all variants in the data?

**Comment by garyzhubc** [comment]
yes

**Comment by privefl** [comment]
If you install the latest GitHub version, you can now do:
```r
info <- snp_readBGI(bgifile)
snp_id <- with(info, paste(chromosome, position, allele1, allele2, sep = "_"))
```

**Comment by garyzhubc** [comment]
I see. So then I can do:
`snp_readBGEN("chr.bgen","chr.bgen.bgi",snp_id)` is that right?

**Comment by garyzhubc** [comment]
I think I got error `Error: 'list_snp_id' is not of class 'list'.`

**Comment by garyzhubc** [comment]
Maybe the bgi file is no longer needed in the GitHub version?

**Comment by privefl** [comment]
You need to provide a list with elements corresponding to each bgen file you provide.
If only one, just wrap with `list()`.

**Comment by garyzhubc** [comment]
Hmm I got this, not sure what it means? 
```
> chr <- snp_readBGEN("chr.bgen","chr",list(snp_id))
Error: 'chr.bgen' is not compressed with zlib.
```

**Comment by garyzhubc** [comment]
I did `./plink2 -pfile chr --export bgen-1.3 --out chr` when converting from pgen

**Comment by garyzhubc** [comment]
Ah it works now when I use `./plink2 -pfile chr --export bgen-1.2 bits=8 --out chr`
