### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by williambrandler** [privefl/bigsnpr#292]
Hey, I get the following error when running ldpred2. 
Have you seen this before and what is the cause?

running ldpred2 on simulated data, it works on some subsets of the data but I get this error on other subsets

```
Error in if (max(abs(pred - pred0)) < 1e-06) break : 
missing value where TRUE/FALSE needed
Calls: with -> with.default -> eval -> eval -> snp_ldsc
```

This is the line of code where the error is thrown
https://github.com/privefl/bigsnpr/blob/f8074a4d3a181d5cad100bacc03612d0e0be6b70/R/ldsc.R#L99

I wonder if it is because I am using simulated data? heritability is 0 as the phenotype is just random numbers

**Comment by privefl** [comment]
I think this issue has already been reported here. 
Can you check this? 
And if the discussion there doesn't help you, please tell me again, and what is the difference between your issue and the previous one.

**Comment by williambrandler** [comment]
ah here https://github.com/privefl/bigsnpr/issues/102

**Comment by williambrandler** [comment]
thanks @privefl I reviewed the issue but it is not clear to me what the problem is. 

To help me troubleshoot, please explain what that line of the code is doing...

**Comment by privefl** [comment]
It is just checking convergence of the algo.

Can you check the distribution of the `ld_score`, `chi2`, and `sample_size` you provide to this function?

**Comment by privefl** [comment]
Any update on this?

**Comment by williambrandler** [comment]
I think the error was caused when testing on a v small amount of data, like <20 SNPs. 
But I cannot remember. Should have documented this, apologies. If it comes up again will document it here
