### ISSUE TITLE
snp_ldsc ( ) : $n_eff for binary traits ?

### ISSUE THREAD

**Issue by Imus** [privefl/bigsnpr#293]
Dear Florian, 
I've been using the LDpred2 software to derive a PRS for a binary trait. 
For the `snp_ldsc` function, you mention that for binary traits the sample size ( `$n_eff` argument ) should be =  `4 / (1 / n_control + 1 / n_case)`. Can you please briefly explain the rationale behind that formula? Also, can I just use the total N from the GWAS  (in my case, N cases and N controls per SNP  is not available in GWAS summary stats) ?
Thank you very much !

**Comment by privefl** [comment]
The effective sample size is the equivalent sample size (i.e. with same power) if you had the same number of cases and controls.

You can have a look at https://doi.org/10.1101/2021.03.29.437510 to see the impact of not using the per-SNP n_eff.
