### ISSUE TITLE
alternatives to SFBM matrix format

### ISSUE THREAD

**Issue by williambrandler** [privefl/bigsnpr#294]
I am working with ldpred2 in Databricks Platform.

Databricks has a tool called the local file API that abstracts cloud sotrage (Azure data lake, AWS S3, Google Cloud storage), allowing files to be synced to cloud object storage and read from storage as if it was on the local filesystem on the virtual machine where the tool is running

This tool works with any file type and even with bioinformatics tool executables. Except for this custom SFBM matrix format.

Are there alternatives to this representation?

I have tried writing the dsCMatrix type successfully, but then when I read it in it can automatically get converted to nsTMatrix

I want to write the correlation matrix to a backing cloud storage because I am running this tool in parallel in 3 centimorgan chunks, using Apache Spark to parallelize. Once the correlation matrices have been computed they can then be accessed to perform polygenic risk scoring for hundreds of phenotypes. 

Otherwise we will have to compute correlation matrix on the fly for each phenotype, which is costly (this correlation matrix generation is about 10x more expensive to run than linear regression is with regenie)

**Comment by privefl** [comment]
Computing LD matrices should not be split into chunks as it is assuming that they are block-diagonal (where you split). And they should be quite fast to compute anyway.

Just compute them (per chromosome and in `dsCMatrix` format), and store them (as done e.g. in https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-corr-spmat.R).
Then, filter them (with the variants available in the sumstats) and make the SFBM on the fly for each phenotype (as done e.g. in https://github.com/privefl/paper-ldpred2/blob/master/code/run-simu-ldpred2-gwide.R#L53-L76).

**Comment by williambrandler** [comment]
that makes sense, correlation matrix can be generated for each chromosome, then converted to SFBM on the fly when needed.

Can the adjusted betas be generated in an embarrassingly parallel fashion, splitting the summary stats up and processing?
Something like this:

`sumstats <- bigreadr::fread2("/path/to/chr1:0-3000000")`
`df_beta <- snp_match(sumstats, map, join_by_pos = FALSE)  # use rsid instead of pos`
`beta_inf <- snp_ldpred2_inf(corr_chr1, df_beta, h2 = h2_est)`

**Comment by privefl** [comment]
For LDpred2-inf and LDpred2-grid, you could in theory run per chromosome and merge later as parameters (h2 and p) are fixed.

Not for LDpred2-auto.

With the compact format and HM3 variants, the SFBM file is only 15-16 GB; is that really a problem?

**Comment by privefl** [comment]
There is not any clear benefits from using more than HM3 variants.

**Comment by williambrandler** [comment]
Rarer variants from exome sequencing will display more complex patterns of linkage disequilibrium relative to common variants uncovered from hapmap. Also the UK Biobank and other datasets will display different patterns of genetic variation to what was observed in hapmap

Will these considerations not have a significant influence when doing polygenic risk scoring?

**Comment by privefl** [comment]
Using more rarer SNPs tend to have a bad impact on predictive performance, for several PGS methods.

More work is needed to properly develop PGS with less common variants.

**Comment by williambrandler** [comment]
OK, the domain of applicability of ldpred2 is restricted to common variants since it relies on hapmap3, the latest release of which was in 2010. Incorporating newer datasets with rarer variants and different population structures will not improve the performance of ldpred2. New models / methods have to be developed. 

Are there any review articles on this you could point me to?
And is your group working on this, or other groups?

**Comment by privefl** [comment]
There have been several papers about combining known large-effect mutations (such as BRCA) with polygenic scores (that use common variants).

I'm sure there are people working on incorporating more low-frequency variants to some PGS methods, but I don't know what other teams are working on right now.

**Comment by williambrandler** [comment]
we're gonna press ahead, using UK Biobank instead of hapmap, and splitting chunks based on LD-blocks for european populations as opposed to arbitrary 3CM windows or whole chromosomes

https://bitbucket.org/nygcresearch/ldetect-data/src/master/EUR/fourier_ls-all.bed

**Comment by privefl** [comment]
Beware that these LD blocks are not really completely independent.
https://doi.org/10.1093/bioinformatics/btab519

**Comment by williambrandler** [comment]
yes there will be some sacrifice of accuracy here

We are trading off longer range effects against faster time to results...
