### ISSUE TITLE
Handling of Dosage data in PRS calculation

### ISSUE THREAD

**Issue by choishingwan** [privefl/bigsnpr#30]
Hi there, I'd like to ask if the use of snp_PRS() is compatible with BGEN file input? And if so, is the dosage data hard-coded?

Thanks

**Comment by privefl** [comment]
If you want to use `snp_PRS()`, you need first to convert data to my format `bigSNP`.
If you have BGEN input (with the same format as the UKBB), you can use `bigsnpr::snp_readBGEN()` to do so.

Example code: https://github.com/privefl/UKBiobank/blob/master/UKB1-height.R

**Comment by choishingwan** [comment]
So the PRS will be calculated using the expected value (Sum Probability * Genotype_i), correct?

**Comment by privefl** [comment]
Yes

**Comment by choishingwan** [comment]
Thank you

**Comment by privefl** [comment]
You can now sample BGEN probabilities as hard calls if you prefer.
