### ISSUE TITLE
Questions on LDpred2 models

### ISSUE THREAD

**Issue by junchcb** [privefl/bigsnpr#300]
Hi Florian,
1. I have a GWAS summary statistics and additional 2 independent GWAS individual data (GWAS-A [target] and GWAS-B [validation] data). After trying infinitesimal, grid and auto models for GWAS-A (target data), auto model worked best (best AUC). How can I know many variants are included in the best-fit auto model?
2. For the best-fit auto model above, how can I use it for GWAS-B data (validation) to calculate the polygenic risk score for each individuals? Do you have an example script?

Thank you so much!

**Comment by privefl** [comment]
1. There is no "best-fit" for LDpred2-auto, right? Also, if you don't use the `sparse` option, then all variants will be used. You can see that as all variants should have a non-zero effect in the final vector of effects.

2. I'm not sure I understand. What is the difference between GWAS-A and B?

**Comment by junchcb** [comment]
Thanks Florian. 
1. Yes, I did not use sparse option. As we know, GWAS variants have noise and also passages variants (with high LD with casual variants) in the GWAS summary statistics, how can I know what noise and passages variants are excluded in the LDpred2-auto model?
2. In the tradition P+T approach, GWAS target data (GWAS-A) is used to tune the PRS models and then select the best fit one. The validation  data (GWAS-B) is used to test the performance of the best-fit PRS selected in the previous step.  I wonder if the LDpred2 also need GWAS-B to validate the LDpred2 auto model. Thanks!

**Comment by privefl** [comment]
- I've never heard the expression "passage variant"; what do you mean exactly?

- LDpred2 uses all the variants that you provide to it.

- I usually use the opposite terminology, i.e. validation is used for tuning, and target is used for testing the final model, but that's not the point. You don't need any tuning dataset for LDpred2-auto. If it is a large dataset, you can always meta-analyze it with the sumstats you already have.

**Comment by junchcb** [comment]
Sorry, a typo here, I mean "passenger variant", the variants do not function but with high LD with casual variants. Do I understand correctly that LDpred2-auto take every variant (event noise and  all passenger variants) into account in the model to calculate the PRS? 

Could you clarify a little bit why LDpred2-auto do not need a tuning dataset to optimize the PRS model? Thank you so much!

**Comment by privefl** [comment]
- I usually call these variants "tagging variants".

- Yes, all variants as input are used.

- LDpred2-auto estimates the hyper-parameters h2_SNP and the polygenicity, so you don't need a tuning dataset as when you try many combination of these parameters (as in LDpred2-grid).

**Comment by junchcb** [comment]
Thanks Florian, these are very helpful! It is great that LDpred2-auto do not need a tuning dataset, unlike C+T approach.

**Comment by junchcb** [comment]
One last question, if I find h2 0.4 and p 0.005 generate the best LDpred2-auto model, how can I fix these settings for a target data? Do you have an example script or tutorial?  I did not see the way to fix the parameters from https://privefl.github.io/bigsnpr/articles/LDpred2.html. Many thanks!

**Comment by privefl** [comment]
If you want to use your own estimates, just use LDpred2-grid with one set of parameters.
Or to be on the safe side, use the same set many times and do some quality control over the chains (as for LDpred2-auto).

**Comment by junchcb** [comment]
Thanks Florian!
