### ISSUE TITLE
Unzip error when decompressing LDpred2 reference from figshare

### ISSUE THREAD

**Issue by opain** [privefl/bigsnpr#309]
Dear Florian,

I have noticed previously that the unzip command fails when trying to unzip the LDpred2 reference from figshare (https://figshare.com/articles/dataset/European_LD_reference/13034123).

![image](https://user-images.githubusercontent.com/43761992/152503956-65bdfb2b-6a32-4dde-b197-5729427c3eb1.png)

There are ways to get around this error, such as using 7z or downloading the files separately, but I wanted to raise the issue with you as I imagine it might cause struggle for other users. Have you noticed this before? Since the files can be downloaded separately without issue, perhaps this is a problem with how figshare compresses the .zip folder?

Many thanks,

Ollie

**Comment by privefl** [comment]
Indeed. In R, when using `unzip()`, I get `zip file is corrupt`. That seems to be starting with chr8.

[This SO answer](https://stackoverflow.com/a/35852179/6103040) suggests to download in binary mode, but I'm already doing that, so I don't know what the problem is here.

**Comment by sandralapinska** [comment]
Hi Florian, 

I am running into the same problem. Have you figured out how to resolve this?

**Comment by privefl** [comment]
I am reuploading a new version of these LD references, for which hopefully this error would disappear.

My uploading connection is not great so it might take a day.

**Comment by privefl** [comment]
Actually `unzip` in the terminal works fine for me.
In the R function `unzip()`, you need to use `unzip = "unzip"` for it to work.

BTW: the new version of the LD ref matrices: https://doi.org/10.6084/m9.figshare.19213299

**Comment by opain** [comment]
Thank you Florian. I confirm unzip works with the new LD reference :)

Feel free to close the issue.

Many thanks,

Ollie
