### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mfrancesconi81** [privefl/bigsnpr#31]
Hi,
 I tried to install bigsnpr and bigstatsr on a Mac book Pro with macOS Sierra and R 3.5.1 and I get the following error.

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
> devtools::install_github("privefl/bigstatsr")
Downloading GitHub repo privefl/bigstatsr@master
tar: Failed to set default locale
tar: Failed to set default locale
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
v  checking for file '/private/var/folders/r6/fttwjvts4tx456v09tzw9flr0000gn/T/RtmpQcCqhO/remotescecb4eb9368a/privefl-bigstatsr-fe0da7e/DESCRIPTION' ...
-  preparing 'bigstatsr':
v  checking DESCRIPTION meta-information ...
-  cleaning src
-  running 'cleanup'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'bigstatsr_0.9.3.tar.gz'
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/r6/fttwjvts4tx456v09tzw9flr0000gn/T//RtmpQcCqhO/filececb109eb0bd/bigstatsr_0.9.3.tar.gz' had non-zero exit status

Any clue?

Thanks

**Comment by privefl** [comment]
Seems you can't install {bigstatsr}.
Could you try `devtools::install_github("privefl/bigstatsr")` directly and report the error?

**Comment by privefl** [comment]
Any update on this?
