### ISSUE TITLE
'R session aborted - R encountered a fatal error' when adding columns to SFBM

### ISSUE THREAD

**Issue by antonsysojev** [privefl/bigsnpr#310]
Hi Florian! I apologize in advance if this question has been voiced previously, though I did not see any similar issues among those raised here.

I'm currently working on a project where I'm attempting to construct polygenic risk scores for rheumatoid arthritis. I've been going through the necessary steps and am now attempting to compute the LD matrix using my reference panel data. Computing LD works fine for each chromosome but the issue occurs when attempting to combine the data by adding columns onto my existing SFBM through the `$add_columns()` operation, upon which R crashes without an error message requiring a full session restart ('R session aborted - R encountered a fatal error').

Going through the `$add_columns()` operation line by line, I conclude that the error stems from the `write_val_compact()` function which I was unable to inspect more closely (I only looked at via `View()` so there may be something else that I've missed). I did some fairly basic testing and suspect that the problem has to do with the size of my data (see below for specifics) since it works fine for the provided tutorial data, as well as when I test the same code using the smallest chromosomes. 

My questions are twofold:
1): Is this an error you've experienced before and is there some type of solution for this that I'm not currently seeing?
2): The only solution I can think of (that does not include removing more data) would be to run LDpred2 per-chromosome instead of genome-wide. I am aware that this is not recommended but perhaps this is the sole option available for me?

**Data specifics:**

As reference panel data I'm using the European subset of the 1000 Genomes reference panel data that has been filtered through rigorous quality control leaving me with about 2.5 million SNPs when computing the LD matrix. I know that including non-HapMap3 SNPs is not recommended but using only that set of SNPs is not an option for this project (in short, because I do not want to lose out on important HLA SNPs that are not sufficiently covered within the HapMap3 set). While data is large, RAM and storage does not seem to be an issue with respect to the problem described above.

**Code example:**

`for(chrom in 1:22){`
`    corr0 <- read_RDS(paste0("tmp-data/corr_chr", chrom, ".rds")))    #Load LD-matrices computed by snp_cor()`
`    if(chrom == 1){
         corr <- as_SFBM(corr0, "tmp-data/corr", compact = T)    #This works fine for all chromosomes`
`    }else{`
`        corr$add_columns(corr0, nrow(corr))    #This is where the crash occurs`
`    }`
`}`

Please let me know if you would like any additional information on this!
Thanks in advance!

**Comment by antonsysojev** [comment]
Thank you for the quick reply!

Neither memory nor disk space seems to be the issue, but size of the data seems to still be the main problem. I've been toying around with the code you provided (that from the `bdiag_sym()` function) which works fine for its purpose but unfortunately leads to issues due to integer overflow. The problem lies within the pointers `P` which must be provided (via `@p`) as an integer class object to the LD-matrix, something that is not possible due to most pointers being far larger numbers than R can handle as integers (only about a third of these are below the `.Machine$integer.max`).

I tried working around this by using the `gmp` package to store larger values as integers, but it will still be unable to insert into the LD-matrix as it requires `is(unlist(P), "integer")` to evaluate to `TRUE`. I'm not very well versed in the coding of these types of matrices so I'm assuming that the requirement of an `integer` class input is important, otherwise one idea would be to try to circumvent this check and force it to accept input of type `numeric`, but perhaps this would be naive.

Currently, I'm leaning towards computing PRS coefficients per-chromsome, taking the loss of precision as a compromise necessary to make, to be able to keep the full set of SNPs that I'm interested in.

**Comment by privefl** [comment]
You can try to reduce the size of the correlation matrices, by e.g. using `Matrix::drop0(corr0, tol = 0.01)`.

**Comment by antonsysojev** [comment]
Unfortunately, the problem still remains. Without use of the `drop0()` function the maximum of my pointers is about 3.59 times the integer limit, whereas if I drop using `tol = 0.01` I'm still 3.08 times above the limit, still far from what I need to pass.

**Comment by privefl** [comment]
I don't understand how that's possible with only 2.5M variants.
Are you using mostly variants from HLA then? Or are they spread almost evenly along the genome?

**Comment by antonsysojev** [comment]
Yes, I found it surprising too. I double-checked the code to make sure I wasn't using the un-filtered data. I'm using SNPs spread evenly across the genome.

This is a the code that I'm running when trying to create the SFBM LD-matrix (it's a simple cut and paste from my working script, pardon if it's sloppily written). It's essentially the same as that provided within the tutorial and from your comment above though I did some changes that helped with memory usage to try to occupy less. I could provide a copy of the input data as .bed/.bim/.fam files (but it's more or less a subset of 2.7 million SNPs from the EUR 1000 Genomes Phase 3 sample). I think it's too big to attach here though, but I can output a copy and Dropbox it or something if it's of interest.

```
corr0_list <- vector("list", 22)
for(chrom in 1:22){
    target_SNPs <- map %>% filter(chr == chrom)    #Extract the SNPs for this chromosome
    corr0_list[[chrom]] <- snp_cor(genotype_data$genotypes, 
                                   ind.col = target_SNPs$genotype_idx,    #Column genotype_idx identifies targets SNPs
                                   size = 3/1000,
                                   infos.pos = target_SNPs$cM,    #Distances in cM loaded previously and appended to map
                                   ncores = NCORES)
    corr0_list[[chrom]] <- Matrix::drop0(corr0_list[[chrom]], tol = 0.01)
}

num_tot <- sum(sapply(corr0_list, function(.) length(.@x)))
dim <- sum(sapply(corr0_list, ncol))    #Do this here instead of after the loop for memory purposes
I <- vector("list", 22)
X <- vector("list", 22)
P <- vector("list", 22 + 1)
offest_I <- 0L
offset_P <- 0L

for(k in 1:22){
    print(k)
    len <- length(corr0_list[[k]]@x)
    I[[k]] <- corr0_list[[k]]@i + offset_I
    X[[k]] <- corr0_list[[k]]@x
    P[[k]] <- utils::head(corr0_list[[k]]@p, -1) + offset_P
    offset_I <- offset_I + nrow(corr0_list[[k]])
    offset_P <- offset_P + len
    corr0_list[[k]] <- ""    #Clear out the finished matrix to avoid storing unnecessary data
}
P[[k + 1]] <- num_tot

corr <- new("dscMatrix", uplo = "U")
corr@Dim <- c(dim, dim)
corr@i <- unlist(I)
corr@p <- unlist(P)
corr@x <- unlist(X)

corr_sfbm <- as_SFBM(corr, "tmp-data/corr", compact = TRUE)
```

I'll run into the same problem as long as the total number of non-zero elements across all chromsomes (in the upper triangular LD-matrix, sans diagonal), is bigger than `.Machine$integer.max`, I think. Since each pointer is distinct for each non-zero element, is it not? The only other option I can think of is identifying each non-zero observation a_ij per its row and column index, since I know that the LD-matrix is of dimension M x M where M is smaller than `.Machine$integer.max` for sure. But I don't think it's possible to give that information to the dscMatrix which seems to want pointers P, row-index I and non-zero observation X.

**Comment by privefl** [comment]
(Using an interactive session with 128 GB of RAM)
I've just tried to reproduce your first issue using the LD for chromosome 1 [here](https://figshare.com/articles/dataset/European_LD_reference/13034123).
I first converted it to an SFBM_compact, and then tried to append it 50 times (i.e. 51 times in total).

It took a few minutes only, and did not error.
I have more than 2^33 values in the final SFBM (i.e. 4 times more than the max int).
And the final backingfile size is about 75 GB.
***
![code-issue](https://user-images.githubusercontent.com/11161036/153551913-aee62f11-ef72-493c-8f22-0660e87c09d6.jpg)
***
Could you try to reproduce this, and assess when this fails for you?

**Comment by antonsysojev** [comment]
Sorry about the late reply, been upheld by other projects.

I tried the above code, both on the dedicated server that I've been using and on my work laptop. Running on the server crashes with the same "R session aborted - fatal error encountered" at k = 3. File size of the .sbk at the time of crash is about 4.4 gigs. On the server, my memory limit in gigs is about 262 (I believe, at least per `memory.limit() / 1000`).
Running on my work laptop leads to the same crash, again at k = 3 with the same file size of the .sbk at the time of the crash. Here, my memory limit is a bit lower though with about 16 gigs.
R version is the latest (4.1.2), bigsnpr is 1.8.1 and bigstatsr is 1.5.6.

I'm surprised to see this work for you on your machine but not on mine. At least it seems unlikely to be my particular data that is the root cause of the issues! I can't really think of any explanation for why this could occur but I guess my machine doesn't like these big files.

**Comment by privefl** [comment]
Are these both Windows machines? If so, I will also try using my Windows laptop.

Could you try to update to a more recent version of {bigsnpr} (just been reuploaded to CRAN, or from GitHub), and also make sure you have {bigsparser] v0.5.

**Comment by antonsysojev** [comment]
Yes, these are both Windows machines. I have access to a Linux server through which I could run it, but my R version on that server is quite old (it's R 3.6.0) and updating it is a bit of a hassle (I'm guessing that I may see problems with versions of packages not compliant with that R version if I don't update it to the most recent version).

Regarding the version of `bigsparser` it is version 0.5.0 which I believe should be OK.

**Comment by privefl** [comment]
My packages should not require a very recent version of R.
I think I put >= 3.4 because they use some better matrix algebra library starting from there, but that's not strictly required.

**Comment by privefl** [comment]
I can indeed reproduce the issue on Windows at k=3.
I will try to investigate a bit when I have more time.
Thanks for reporting.

**Comment by antonsysojev** [comment]
Perhaps it is a Windows problem then! I'm assuming you were more successful on a Linux machine? If so, I will try to update my current script and test it on our Linux server when I have some time over!

**Comment by privefl** [comment]
Yes, I am mostly using a Linux server for computations.
But, I try the best I can that the packages work properly on all types of OS.
I will try to look into this at the end of the week.

**Comment by privefl** [comment]
Okay, after much work on this, I think I now have a better way of appending.

Please try {bigsparser} v0.6 (use `remotes::install_github("privefl/bigsparser")`).

**Comment by antonsysojev** [comment]
I updated to v0.6 on my laptop and tried the above code (the one using LD for chromosome 1 repeatedly). I don't have the storage available to run it fifty times but running it thirty times is fast and leads to no crashes. So it seems to be working!

I haven't had the possibility of trying it on the server with my original data (the data that led to me posting this issue) but I would guess that this will work too as it should be smaller than in the above example. I'll get back to you once I've ran it and made sure it works.

**Comment by privefl** [comment]
Great :-)
Yes, please tell me if this okay, then I will upload the new version to CRAN.

**Comment by antonsysojev** [comment]
Pardon my late reply. It does indeed seem to be working for me! Thank you for all the help with this, I'll now be able to construct the PRS genome-wide as opposed to per-chromosome which should be more efficient in more than one aspect. 

It would indeed be a huge help if the update was available via CRAN, as it's currently not possible to install RTools on our Windows server, making me unable to use `remotes::install_github()`.

Thanks again for all the help and support with this, it has been much appreciated!

**Comment by privefl** [comment]
The new version is on CRAN.
