### ISSUE TITLE
Summary statistics filtration on HapMap SNPs is missing.

### ISSUE THREAD

**Issue by fmadani** [privefl/bigsnpr#311]
Hi Florian,

I am benchmarking the LDpred2 codes  presented in the PRS [tutorial](https://choishingwan.github.io/PRS-Tutorial/ldpred/) and LDpred2 codes presented [here](https://privefl.github.io/bigsnpr/articles/LDpred2.html#ldpred2-auto-automatic-model-1). I noticed that summary statistics is filtered out on hapmap SNPs in the tutorial. Here is the code

sumstats <- sumstats[sumstats$rsid%in% info$rsid,]

while I couldn't find such a filtration in [here](https://privefl.github.io/bigsnpr/articles/LDpred2.html#ldpred2-auto-automatic-model-1). If I am right, would you clarify why this filtration is not considered .

FYI: I did this filtration, and 5245 rows were filtered out.

Regards,
Farshad

**Comment by privefl** [comment]
If you're using the `info` there, it contains 1,054,330 HapMap3 variants.
And the filtering is performed when calling `snp_match()`.

**Comment by fmadani** [comment]
Dear Florian,

I'd think I didn't explain well my point. Let me explain it again. By using this code: sumstats <- sumstats[sumstats$rsid%in% info$rsid,]    literally, those SNPs of **the summary report** ,that they don't exist in HapMap SNPs, are filtered out. There is no such a filtrating in your code.  If you look at [here ](https://privefl.github.io/bigsnpr/articles/LDpred2.html#ldpred2-auto-automatic-model-1) and search for "info", you will see that 'info' is not used for any in the entire of the code. I did expect 'info' should be used for the filtration explained above. 

FYI: In the tutorial, snp_match() is used to match SNPs between base dataset (summary report) and the target dataset. It is not used for filtering SNPs of the summary report that not exist in HapMap.


I appreciate your time and attention.

Farshad

**Comment by privefl** [comment]
Yes, this tutorial does not use the HapMap3 variants.
It says
> This tutorial uses fake data for educational purposes only.

This is why I used "if".

**Comment by fmadani** [comment]
Thanks for the clarification, Florian. I assume that it is forgotten to use the filtration based on  HapMap3 in the LDPred2 presented in your github.
