### ISSUE TITLE
Mapping Principal Components to sample IDs

### ISSUE THREAD

**Issue by AlePilHen** [privefl/bigsnpr#313]
Hi Florian

I have performed PCA using `bigsnpr`, and identified outlier samples that I would like to remove from my data (plink format). This was done with inspiration from your article [(Link)](https://privefl.github.io/bigsnpr/articles/bedpca.html).

Now that I have identified the outliers I am wondering:
How do I map the sample IDs from the original `.bed` file to the PCs that I calculated using `bed_projectPCA`? 
Are the samples in the input `.bed` file and the produced `obj.svd` and `proj` objects in the same order? (Variable names are identical to the to the example in the article)

Thank you!

**Comment by privefl** [comment]
Yes, it should keep the same order if you don't use `ind.row` and `ind.col`.
So, you should be able to use `$fam[ind_out, ]` in `snp_plinkRmSamples()` to get subsetted PLINK files without these individuals.

**Comment by AlePilHen** [comment]
Great! 
Thank you very much!
