### ISSUE TITLE
Error: 'infos.pos' is not sorted.

### ISSUE THREAD

**Issue by forevertl** [privefl/bigsnpr#314]
Dear Florian,
When I run LDpred2 the "LD calculating" part as below, I got error: Error: 'infos.pos' is not sorted. I followed the example code, only change the test data to my data. Do you have any idea on how to fix it? When I use test data, same code, it can be run. Thank you very much. 
lin

```r
# calculate LD
for (chr in 1:22) {
    # Extract SNPs that are included in the chromosome
    ind.chr <- which(info_snp$chr == chr)
    ind.chr2 <- info_snp$`_NUM_ID_`[ind.chr]
    # Calculate the LD
    corr0 <- snp_cor(
            genotype,
            ind.col = ind.chr2,
            ncores = NCORES,
            infos.pos = POS2[ind.chr2],
            size = 3 / 1000
        )
    if (chr == 1) {
        ld <- Matrix::colSums(corr0^2)
        corr <- as_SFBM(corr0, tmp)
    } else {
        ld <- c(ld, Matrix::colSums(corr0^2))
        corr$add_columns(corr0, nrow(corr))
    }
}
```

**Comment by privefl** [comment]
For some reason, `infos.pos = POS2[ind.chr2]` is not sorted, for at least one chromosome.

**Comment by forevertl** [comment]
> For some reason, `infos.pos = POS2[ind.chr2]` is not sorted, for at least one chromosome.

Could you please let me know how to modify the code to solve it? I am not good at R code. Thank you very much. 
thansk, 
Lin

**Comment by privefl** [comment]
I will answer any questions and issues regarding the packages, but I don't have time to help you write your analysis code, sorry.

Isn't there someone in your team you could ask for help?
