### ISSUE TITLE
Trouble with obj.bed formatting

### ISSUE THREAD

**Issue by AlePilHen** [privefl/bigsnpr#315]
Hello Florian

I am currently using your `bigsnpr` package for some PCA and in doing so I am trying to project some data onto established principle components. However, I am having trouble with the `bed_projectPCA` function as it throws the following error: `Error in 'stop_vctrs()': Can't combine 'chr' <integer> and 'chr' <character>.` 

I found that the two `bed` objects needed for the `bed_projectPCA` function seem to be formatted differently. In the first the `$chromosome` is type `int` and in the other it is type `chr`. Both `bed` objects have been generated by using the `bed()` function.

Do you have any idea of how to fix / work around this? 

Thank you!
Alexander

**Comment by AlePilHen** [comment]
Hello
I found out what the issue is.
It was because my `bed` files contained also sex chromosomes.
No need to reply.

Thanks!

**Comment by privefl** [comment]
Note that
 - there is a similar issue already opened on this; try to search for similar issues to get quick answers
 - "principle component" is not a thing, it's "principal component"
 - please close the issue when you think it's resolved
