### ISSUE TITLE
Is it possible to compute fuzzy relational product with this package?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#317]
I'm interested in computing "square product" between a genotype matrix and a phenotype matrix. Is it possible to use this package to do this? The code of such computation can be written as

```
triangle_subproduct <- function(R,S,type,moderate=FALSE) {
  if(ncol(R) != nrow(S)) errorCondition("dimensions don't match")
  R_subprod_S <- matrix(0, nrow(R), ncol(S))
  for (i in 1:nrow(R)) {
    for (k in 1:ncol(S))
      R_subprod_S[i,k] <- ifelse(moderate,
                                 mean(mapply(implication,R[i,],S[,k],MoreArgs=list(type=type))),
                                 min(mapply(implication,R[i,],S[,k],MoreArgs=list(type=type))))
  }
  R_subprod_S
}
```

where R is the genotype matrix and S is the phenotype matrix. More about why computing this product can be found here https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.39.4217&rep=rep1&type=pdf.

**Comment by privefl** [comment]
No, this is not implemented. What is this `implication` function?

You can always use the code as is because the R accessors are implemented. 

Note1: this double R loop would probably be very slow.
Note2: accessing rows is very inefficient because FBMs are stored column-wise. But it seems like rows are genetic variants in your code?

**Comment by garyzhubc** [comment]
Implication: 
```
implication <- function(a, b, type) {
  switch (type,
    "S#" = ifelse(a!=1 || b==1, 1, 0),
    "S" = ifelse(a <= b, 1, 0),
    "S*" = ifelse(a <= b, 1, b),
    "G43" = min(1, b/1),
    "G43" = min(1,b/1,(1-a)/(1-b)),
    "L" = min(1,1-a+b),
    "KDL" = min(1,1-a+a*b),
    "KD" = max(1-a,b),
    "EZ" = max(min(a,b),1-a),
    "W" = min(max(1-a,b),max(max(a,1-b),min(b,1-a)))
  )
}
```
Yes rows are generic variants. Is there any tool you recommend to do this? This is just like matrix multiplication replacing addition and summation with something else.

**Comment by privefl** [comment]
`outer()` might work well if you want to use a specific `type` here.
But you should rather post these types of questions on StackOverflow.

**Comment by garyzhubc** [comment]
Ah I just realized that I might have made mistake. If I have rows as generic, is it possible to do this operation on the genotype-phenotype matrices?
