### ISSUE TITLE
Computing pred_auto with LD reference 

### ISSUE THREAD

**Issue by sandralapinska** [privefl/bigsnpr#318]
Hi Florian, 

I am trying to calculate `pred_auto` using the European LD reference that you provided, but I am having trouble understanding what this part in your _example-with-provided-ldref.R_ is doing

```r
map <- dplyr::transmute(ukb$map,
                        chr = as.integer(chromosome), pos = physical.pos,
                        a0 = allele1, a1 = allele2)  # reversed somehow..
map_pgs <- df_beta[1:4]; map_pgs$beta <- 1
map_pgs2 <- snp_match(map_pgs, map)

load("data/ind_val_test.RData")
pred_auto <- big_prodMat(G, sweep(beta_auto, 1, map_pgs2$beta, '*'),
                         ind.row = ind.test,
                         ind.col = map_pgs2[["_NUM_ID_"]],
                         ncores = NCORES)
```

Why do you recalculate the mapping and then use the `sweep()` function?

**Comment by privefl** [comment]
In real settings, you can have three different datasets:
 - the GWAS summary statistics
 - the LD ref
 - the test set
 
 You need to first align the GWAS sumstats on the LD.
 But you also need to align the test set on these at the end.
 The `sweep()` function is used to change the sign of the effects for which the alleles are swapped in this last `snp_match()`.

**Comment by sandralapinska** [comment]
Thank you for the response. So in this line of code, you are restricting to the variants present in the test data
in_test <- vctrs::vec_in(df_beta[, c("chr", "pos")], map_test[, c("chr", "pos")])

Is this test data from obj.bigSNP$map? Where does map_test come from?

**Comment by privefl** [comment]
`map_test` is your own test data.

**Comment by privefl** [comment]
`in_test` is just to make sure that you're not training on variants you won't have in your test set anyway.
