### ISSUE TITLE
Settings of snp_ldsplit()

### ISSUE THREAD

**Issue by LucieTroubat** [privefl/bigsnpr#323]
Hello,

I use snp_ldsplit() with some settings (thr_r2 = 0.05, min_size = 3000,  max_size = 4000, max_K = 100) on chromosome 22 (EUR ancestry) and it's work. But if I want to use the same settings on other chromosome like 1,2 or 3, it's not work (I have a NULL result).
Do you have an explanation to this ?

Thanks for your help,

Lucie Troubat

**Comment by privefl** [comment]
Same as in https://github.com/privefl/bigsnpr/issues/307 I guess.

`min_size = 3000, max_size = 4000` seems overly restrictive.

Maybe have a look at this code (this is for 1M variants overall): 
https://github.com/privefl/paper-misspec/blob/main/code/prepare-corr-with-blocks.R#L11-L43
