### ISSUE TITLE
snp_modifyBuild gives truncated results

### ISSUE THREAD

**Issue by yidingdd** [privefl/bigsnpr#325]
Hey Florian,

I'm trying to lift the genome build for PGS catalogue scores from hg19 to hg38 with snp_modifyBuild (bigsnpr version 1.9.11). The function shows there are only 272 unmapped variants, but in fact there are about 191,106 unmapped variants, with all chromosome 16-22 position missing. It also give a warning message:
Expecting integer field 2 line 928405 of /tmp/Rtmp5sBLbF/file293685f0e44.BED, got 8.1e+07
Could you help to look into it?

```
suppressPackageStartupMessages({
    library(readr)
    library(dplyr)
    library(bigsnpr)
})

liftOver <- runonce::download_file("http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/liftOver", "tmp-data")
pgs <- runonce::download_file("http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000358/ScoringFiles/PGS000358.txt.gz", "tmp-data")
bigsnpr:::make_executable(liftOver)

effect_df <- read_tsv(pgs, skip = 14, col_types = cols())
effect_df <- effect_df %>%select(chr_name, chr_position, effect_allele, other_allele, effect_weight) %>% 
    rename(chr = chr_name, pos = chr_position )
effect_df$POS_hg38 <- snp_modifyBuild(effect_df, liftOver, from = "hg19", to = "hg38")$pos
sum(is.na(effect_df$POS_hg38))
```

**Comment by KangchengHou** [comment]
FYI, the line 928405 in this case corresponds to 
"chr15 8.1e+07 81000001 928405"

@privefl you can probably enforce integer formatting when writing file at https://github.com/privefl/bigsnpr/blob/265ea91de6759275047bd35b10be02007c537707/R/match-alleles.R#L164

**Comment by privefl** [comment]
I should probably enforce this option.

For reference: https://stackoverflow.com/q/43227387/6103040.

**Comment by privefl** [comment]
Part of the issue seems to come from `chr_position` being read as a column of `double` with `readr::read_tsv()`; using `bigreadr::fread2()` (which just wraps `data.table::fread()`) is a better alternative in this case (it also automatically detects the `skip` needed). 

Anyway, I will push some fix.
