### ISSUE TITLE
z-value used as z-score

### ISSUE THREAD

**Issue by fmadani** [privefl/bigsnpr#327]
Hi Florian,

In the LDpred2 practice ([here](https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html#exercises-ldpred2-and-lassosum2)), you have taken 'z values' from  the summary of the GLM, and then applied them as z-scores for performance evaluation. As you know, z-value is different from z-score. Would you clarify.  Here is the related code:

```r
params2$score <- apply(pred_grid2, 2, function(x) {
  if (all([is.na](http://is.na/)(x))) return(NA)
  summary(glm(CAD ~ x + sex + age, data = obj.bigsnp$fam, family = "binomial"))$coef["x", 3]
})
```

Thanks,
Farshad

**Comment by privefl** [comment]
No, I don't know. I never use "z-value", always "z-score".
But I would think both are the same thing.
Could you explain where you think there is a difference between these two namings?
