### ISSUE TITLE
A minor modifications in naming data variables

### ISSUE THREAD

**Issue by fmadani** [privefl/bigsnpr#328]
Hi Florian,

As you know, there are two datasets used in PRS projects; one is GWAS summary report that is sometimes called 'base' dataset, and another is 'target' dataset that contains genomic information of patients whose PRS scores are supposed to be calculated. In the Lassosum2 and LDpred2 practice,  a GWAS summary is downloaded and used [here](https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html), and stored in the 'sumstats' variable. Earlier in the practice ([here](https://privefl.github.io/bigsnpr-extdoc/preprocessing.html)), a target dataset is downloaded and used from a GWAS project, and then called 'GWAS-data'. Using 'GWAS-data' for naming the target dataset is sort of confusing for inexperienced users  like me ;). It is more confusing when some files related to the target dataset analysis are named 'GWAS_...'.

 I'd suggest using another name like 'target-data', so it helps user to not get confused.

Regards,
Farshad

**Comment by privefl** [comment]
There are tutorials for the whole package, including PCA and GWAS analyses, not just PGS.
I've just kept the naming from https://www.mtholyoke.edu/courses/afoulkes/Data/statsTeachR/.
