### ISSUE TITLE
Scale of beta in the source code of LDpred2.R is not the same as described in the original paper

### ISSUE THREAD

**Issue by xyang619** [privefl/bigsnpr#329]
In the source code of LDpred2.R line 80-81, the scaling of beta likes
```
scale <- sqrt(N * df_beta$beta_se^2 + df_beta$beta^2)
beta_hat <- df_beta$beta / scale
```
However, this is different from the paper (page 9) beta_hat = gamma_hat / (se(gamma_hat) * sqrt(n)). So which one could I use?

**Comment by privefl** [comment]
Yes, the updated formula comes from https://doi.org/10.1016/j.ajhg.2021.11.008.
It is more precise (does less approximation).

**Comment by xyang619** [comment]
> 

OK, thanks
