### ISSUE TITLE
adjusted beta for PRS model taking too long

### ISSUE THREAD

**Issue by Charlkb** [privefl/bigsnpr#330]
Hi,

I hope this is the right forum for my question on LDPred2. Am trying to get the adjusted beta value to use in the PRS model but it takes so long for both the auto and grid models that I have tried and yet it should take about 2 minutes according to the tutorial, what could the problem be? NCORES is 4L, the SNPs are 660,000 and memory is 120GB memory. The first step below is taking hours. Thanks in advance

>multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est, vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES), ncores =NCORES)

>beta_auto <- sapply(multi_auto, function(auto)auto$beta_est)

**Comment by privefl** [comment]
It takes a few minutes in the tutorial, where there are only 50K variants.
If you use HapMap3 variants (a bit more than 1M) and the compact format, it should take 2-4 hours with 15 cores.
For 660K variants and 4 cores, it should take about the same.

**Comment by Charlkb** [comment]
thank you, it did finish after about that time
