### ISSUE TITLE
A small number of matched variants causes small SNP heritability estimate

### ISSUE THREAD

**Issue by singh-p** [privefl/bigsnpr#331]
We have been using your Polygenic risk score analysis (https://choishingwan.github.io/PRS-Tutorial/ldpred/). We could run all the scripts successfully however we are unable to interpret the results appropriately. I will brief you about my project, we are working on a case-control GWAS analysis between a neuro-psychiatric disease and compared it with healthy controls. The cohort includes the Indian population.  On filtering out HAMPMAP SNPs using

sumstats <- sumstats[sumstats$rsid%in% info$rsid,]
we retrieved 719204 observations of 12 variables

Later, on comparing base and target data, 
info_snp <- snp_match(sumstats, map, match.min.prop=0.1)
we retrieved 74,513 SNPs.

The h2_est value was 0.002

The genetic heritability of our disease of interest is ~30-40%. But our h2_est value is so low. Is it because our base data and target data belongs to two different populations? (base data- European, Target data- Indian) or Because we do not have enough comparable snps between our data and hapmap? or any other reasons?

With such low h2-est values, can we still proceed with PRS?
Also, for case-control analysis, do we follow linear or logistic model?

We performed our analysis on ~400 cases and 400 controls and screened ~4 lakh markers.

**Comment by privefl** [comment]
First, the tutorial you're pointing to is not mine; I would recommend following https://privefl.github.io/bigsnpr/articles/LDpred2.html instead.

The number SNPs in common is indeed too small. If you don't have imputed data, which provides generally a very good coverage of the HapMap3 variants, I would recommend to use the genotyped variants you have access to instead.

For case-control, you can use the logistic model.

**Comment by singh-p** [comment]
Thanks! We are now following your given scripts. The summary statistics includes data without imputation.  Do we need to impute the data before performing PRS, or we can move forward without imputation. 
 Is this imputation step enough to proceed with PRS?
**G2<-snp_fastImputeSimple(genotype)** 

Additionally, Can we use our own data for base as well as target data?
What do you mean by "recommend to use the genotyped variants you have access to instead"?

**Comment by privefl** [comment]
I guess the problem is that, for your target data, you did not impute it using an external reference panel (to get millions of variants instead of a few hundreds thousands that you get from your genotyping chip).

If you can't or don't want to perform this imputation, you would need to use the variants in your target data (the genotyped variants) instead of the HapMap3 variants. 

But then, you need to recompute the LD for these variants (in a population similar to the GWAS sumstats).

**Comment by singh-p** [comment]
Great!
Please excuse if i sound silly coz i'm new to this field.
I skipped the hapmap matching, and on comparing variants between  base and target data i got 206,371 variants matched.
further i calculate the LD and now the h2_est value is 0.0275.
