### ISSUE TITLE
Run snp_ldpred2_grid in a for loop trigger Warning: stack imbalance in 'for'

### ISSUE THREAD

**Issue by xyang619** [privefl/bigsnpr#332]
When I try to run snp_ldpred2_grid several times in a for loop, For example,
```R
for(rep in 1:5) {
    snp_ldpred2_grid(corr, df_beta, params, ncores=NCORES)
}
```
It will trigger warning like below
`Warning: stack imbalance in 'for', 2 then 5`

Does anyone have the similar problem?

**Comment by privefl** [comment]
I do get this warning from time to time in R recently.

However, I can't reproduce this using the data from [the tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html) (that I saved in rds files for convenience):
```r
df_beta <- readRDS("tmp-data/sumstats_tuto.rds")
corr    <- readRDS("tmp-data/corr_tuto.rds")

library(bigsnpr)
(p_seq  <- signif(seq_log(1, 1e-5, length.out = 10), 2))
(params <- expand.grid(h2 = 0.3, sparse = c(FALSE, TRUE), p = p_seq))

for (rep in 1:5) {
  snp_ldpred2_grid(corr, df_beta, params, ncores = nb_cores())
}
```

**Comment by privefl** [comment]
It seems the issue might come from using OpenMP, and may happen quite stochastically (cf. https://github.com/szcf-weiya/fRLR/issues/1#issuecomment-888099081).

If you have a reproducible example using the tutorial data, that would be really helpful for me to investigate more.

**Comment by xyang619** [comment]
> It seems the issue might come from using OpenMP, and may happen quite stochastically (cf. [szcf-weiya/fRLR#1 (comment)](https://github.com/szcf-weiya/fRLR/issues/1#issuecomment-888099081)).
> 
> If you have a reproducible example using the tutorial data, that would be really helpful for me to investigate more.
Hi, Florian, thanks for your quick response. I follow the tutorial and  can reproduce the warning. ( Only difference from your post is that I have not the cached rds file, so I calculate corr from the beginning)
And my OS is Linux debian 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux and the version of R is  4.0.4 (2021-02-15)
```

> library(bigsnpr)
(p_seq  <- signif(seq_log(1, 1e-5, length.out = 10), 2))
(params <- expand.grid(h2 = 0.3, sparse = c(FALSE, TRUE), p = p_seq))
 [1] 1.0e+00 2.8e-01 7.7e-02 2.2e-02 6.0e-03 1.7e-03 4.6e-04 1.3e-04 3.6e-05
[10] 1.0e-05
    h2 sparse       p
1  0.3  FALSE 1.0e+00
2  0.3   TRUE 1.0e+00
3  0.3  FALSE 2.8e-01
4  0.3   TRUE 2.8e-01
5  0.3  FALSE 7.7e-02
6  0.3   TRUE 7.7e-02
7  0.3  FALSE 2.2e-02
8  0.3   TRUE 2.2e-02
9  0.3  FALSE 6.0e-03
10 0.3   TRUE 6.0e-03
11 0.3  FALSE 1.7e-03
12 0.3   TRUE 1.7e-03
13 0.3  FALSE 4.6e-04
14 0.3   TRUE 4.6e-04
15 0.3  FALSE 1.3e-04
16 0.3   TRUE 1.3e-04
17 0.3  FALSE 3.6e-05
18 0.3   TRUE 3.6e-05
19 0.3  FALSE 1.0e-05
20 0.3   TRUE 1.0e-05
> for (rep in 1:5) {
  snp_ldpred2_grid(corr, df_beta, params, ncores = nb_cores())
}
Warning: stack imbalance in 'for', 2 then 1

```

**Comment by xyang619** [comment]
I use the saved rds files and  run the R script can also reproduce the warning.
```bash
$cat rep.R
```
```R
df_beta <- readRDS("tmp-data/sumstats_tuto.rds")
corr    <- readRDS("tmp-data/corr_tuto.rds")
library(bigsnpr)
(p_seq  <- signif(seq_log(1, 1e-5, length.out = 10), 2))
(params <- expand.grid(h2 = 0.3, sparse = c(FALSE, TRUE), p = p_seq))

for (rep in 1:5) {
  snp_ldpred2_grid(corr, df_beta, params, ncores = 1)
}
```
```bash
$ Rscript rep.R 
Loading required package: bigstatsr
 [1] 1.0e+00 2.8e-01 7.7e-02 2.2e-02 6.0e-03 1.7e-03 4.6e-04 1.3e-04 3.6e-05
[10] 1.0e-05
    h2 sparse       p
1  0.3  FALSE 1.0e+00
2  0.3   TRUE 1.0e+00
3  0.3  FALSE 2.8e-01
4  0.3   TRUE 2.8e-01
5  0.3  FALSE 7.7e-02
6  0.3   TRUE 7.7e-02
7  0.3  FALSE 2.2e-02
8  0.3   TRUE 2.2e-02
9  0.3  FALSE 6.0e-03
10 0.3   TRUE 6.0e-03
11 0.3  FALSE 1.7e-03
12 0.3   TRUE 1.7e-03
13 0.3  FALSE 4.6e-04
14 0.3   TRUE 4.6e-04
15 0.3  FALSE 1.3e-04
16 0.3   TRUE 1.3e-04
17 0.3  FALSE 3.6e-05
18 0.3   TRUE 3.6e-05
19 0.3  FALSE 1.0e-05
20 0.3   TRUE 1.0e-05
Warning: stack imbalance in 'for', 2 then 3
```

**Comment by privefl** [comment]
Could you try installing `remotes::install_github("privefl/bigsnpr@dorng")` and rerunning please?

**Comment by xyang619** [comment]
No warning now and It's seems that the problem is fixed.

**Comment by privefl** [comment]
Ok, I'll try to work on this new version next week to add support for seeds (reproducibility) in LDpred2 (https://github.com/privefl/bigsnpr/issues/156), and merge to the master branch when it's done.

**Comment by xyang619** [comment]
Thanks and I will temporally close the issue
