### ISSUE TITLE
NA values in the resulting correlation matrix

### ISSUE THREAD

**Issue by alejocrojo09** [privefl/bigsnpr#333]
Dear Florian,

I am have a base dataset of 100K individuals and 180,000 variants. When I matched the variants with the target dataset and calculate the correlation matrix, I get missing values even if I impute the genotype matrix with `G2 = snp_fastImputeSimple(G)`. If I use this correlation matrix, then I get errors calculating the h2 parameters and I cannot continue calculating the scores. This the code with the following warning issues

```
POS2 = snp_asGeneticPos(CHR, POS, dir = "/data/lcorreara/IAM/PRS_II/Low/bmi//ldpred")
tmp = tempfile(tmpdir = "/data/lcorreara/IAM/PRS_II/tmp-data")
for (chr in 1:22) {
    ## indices in 'df_beta'
    ind.chr = which(df_beta$chr == chr)
    ## indices in 'G'
    ind.chr2 = df_beta$`_NUM_ID_`[ind.chr]
    corr0 = snp_cor(G2, ind.col = ind.chr2, size = 3 /1000, infos.pos = POS2[ind.chr2], ncores = NCORES)
    if (chr == 1){
        ld = Matrix::colSums(corr0^2)
        corr = as_SFBM(corr0, tmp, compact = TRUE)
    } else {
        ld = c(ld, Matrix::colSums(corr0^2))
        corr$add_columns(corr0, nrow(corr))
    }
}

```

```
Warning message:
“NA or NaN values in the resulting correlation matrix.”
Warning message:
“NA or NaN values in the resulting correlation matrix.”
Warning message:
“NA or NaN values in the resulting correlation matrix.”
Warning message:
“NA or NaN values in the resulting correlation matrix.”
```

How can I fix the matrix to continue with the analyses? 

Thank you very much for your help!

**Comment by privefl** [comment]
First, you don't need to impute the genotype matrix to compute the correlation matrix; this is one of the few functions where it is actually allowed to have a few missing values.

Then, the missing values in the corr matrix usually mean that you have some variables with no variance at all (e.g. when MAF = 0). You should filter low-frequency variants beforehand.

**Comment by privefl** [comment]
Any update on this?

**Comment by alejocrojo09** [comment]
Yes, I apologize for my very late reply. Indeed, there were some variants with low MAF. I removed them from my dataset and then everything worked. Thank you very much!

One final question, what is the min MAF value to consider in the correlation matrix? I want to also include variants with MAF = 0.0001 but I face again the error of missing values. 

Thank you very much for your help!

**Comment by alejocrojo09** [comment]
I see. Thank you very much for all the help!
