### ISSUE TITLE
Summary statistics comparison

### ISSUE THREAD

**Issue by rameez500** [privefl/bigsnpr#335]
Hi Florian,

I have two summary statistics (Aud and Audit_C) and one target dataset. I’m trying to follow Quality control steps in summary statistics sections: (https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-sumstats.R). I calculated standard deviation for summary statistics and target datasets as shown below.

sd <- sqrt(big_colstats(G,  ind.val, ncores = NCORES)$var)
sd_val <- sd[info_snp$`_NUM_ID_`]
sd_ss <- with(info_snp, 1 / sqrt(n_eff / 4 * beta_se^2))

 
I noticed that correlation is almost equal to 1 for both standard deviation of Aud and Audit_c summary statistics; shown in Figure 1.  The  figure 2 & 3 show the standard deviation of summary statistics vs target dataset. I found a lot of purple dots for Audit_C, even though correlation of standard deviation for both summary statistics is 1. Do you think, we should still remove the purple dots (SNP ID) for the Audit_C ?

Figure 1:
 
![image](https://user-images.githubusercontent.com/25560462/164748668-5515be4b-69c8-480a-8c4f-e61614f81a6a.png)

Figure2: Alcohol use disorder (AUD)

![image](https://user-images.githubusercontent.com/25560462/164748995-7516c516-8184-48fd-878c-17d0fdcf74db.png)

 Figure3: Alcohol consumption (AUDIT-C )

![image](https://user-images.githubusercontent.com/25560462/164749033-7a093f88-91aa-430b-98bc-b6c11086bdbe.png)

Thank you so much

**Comment by privefl** [comment]
No, it is just a problem of calibration. It happens:
- when sd of phenotype is not 1
- when sample size is not the real effective one (here, it would be larger N)

**Comment by privefl** [comment]
Any update on this?

**Comment by rameez500** [comment]
Hi Florian,

Thanks for getting back to me.

I am a little confused about phenotype. I didn't use phenotype data to generate plot of standard deviation in the validation set vs
 standard deviation in summary statistics. Instead I only used the Genotype dataset in line 59 (https://github.com/privefl/paper-ldpred2/blob/master/code/prepare-sumstats.R)
 and summary statistics used in line 60. My question is that whether the phenotype data relates to quality control of summary statistics?

Thank you so much for your help.

**Comment by privefl** [comment]
Any update on this?
