### ISSUE TITLE
Precision concerning bed_cprodVec

### ISSUE THREAD

**Issue by JasmRicard** [privefl/bigsnpr#336]
Hi,

Context: I'm using `bed_cprodVec`  for multiple reasons. Sometimes, I'd like to use the function on a standardized version of my `bed` object. Then, I obviously compute every marker's mean and sd to finally use the arguments `center` and `scale` of `bed_cprodVec`. The description of the arguments is given as follow:
`center`- Vector of same length of ind.col to subtract from columns of X.
`scale` - Vector of same length of ind.col to divide from columns of X.

Question: When `center` and `scale` are use in concert, I'd like to know if, precisely, the `scale`  vector is dividing columns of X **after the subtraction of from columns of the `center`  vector**, acting as a way to standardize the bed matrix.

Many thanks,
JR

**Comment by privefl** [comment]
yes, it should be the same as using (G_i,j - center_j) / scale_j.

**Comment by JasmRicard** [comment]
Thank you for your answer!
