### ISSUE TITLE
BackingFile creation

### ISSUE THREAD

**Issue by dzimmerman-amc** [privefl/bigsnpr#337]
Hi there,

I'm using .bgen files to run bigsnpr, I've seen from the documentation that a backingfile is needed for the .bgen file is needed? I am not entirely sure what this is or how to create it. I have all other files in the right format (.bgenfiles, list_snp_id, bgi etc.) I'm probably mistaken but in the code it seems you need a backingfile to create a  backingfile? I am quite new to this type of technology so am not entirely sure how to go forward here. I have seen this in regards to the backingfiles

#' @param backingfile The path (without extension) for the backing files
#'   for the cache of the [bigSNP][bigSNP-class] object.

This there a specific way to generate this backingfile needed for the snp_readBGEN() function?

Thanks in advance!

**Comment by privefl** [comment]
Sorry, the documentation might be a bit misleading.
This the prefix you specify for the two files (.bk and .rds) that **will be created**.
I'll try to make this a bit clearer in the next versions.

**Comment by privefl** [comment]
Would it be clearer like this?

![changes](https://user-images.githubusercontent.com/11161036/167837430-f0feb3da-aa17-4c39-a11c-07e30c4cb32c.jpg)

**Comment by dzimmerman-amc** [comment]
Hi there,

I see, this makes perfect sense. So it is actually the output file. The edit is have made is a lot more clearer, thank you for the quick help!
