### ISSUE TITLE
heritability in function snp_simuPheno()

### ISSUE THREAD

**Issue by Harry-Yihe-Yang** [privefl/bigsnpr#338]
I am a researcher in the field of GWAS and also a user of your package bigsnpr. I am very grateful to you for providing such an excellent package, which greatly facilitates my research, including generating data, calculating GWAS summary statistics, and estimating PGS.

I have a question about the function snp_simuPheno(). In this function, heritability is defined as the square of the L2 norm of the effect size beta  (assume that var(y)=1, i.e., the variance of the phenotype is 1). However, the heritability should be the variation of the phenotype explained by the genetic architecture, and hence var(G%*%beta) may be the heritability instead of ||beta||_2^2. I understand that in many papers, the heritability is defined as ||beta||_2^2. But I guess that in these papers, the authors may assume the LD matrix of G is the identity matrix. I am not sure if ||beta||_2^2 is a good definition of  heritability and so I send this email for your help. Could you please help me distinguish this issue?

I am looking forward to your reply and I appreciate your help.

**Comment by privefl** [comment]
In this function, h2 is the same as var(G %*% beta).
Cf. https://github.com/privefl/bigsnpr/blob/ce62857844acaa0c57ab2e3e2d2198bfc3ff6ef9/R/simu-pheno.R#L50-L59.
Where do you see I use sum(beta^2)?

**Comment by privefl** [comment]
And the new version of this function:
https://github.com/privefl/bigsnpr/blob/alpha/R/simu-pheno.R#L60-L68

**Comment by Harry-Yihe-Yang** [comment]
> > In this function, h2 is the same as var(G %*% beta). Cf.
> > https://github.com/privefl/bigsnpr/blob/ce62857844acaa0c57ab2e3e2d2198bfc3ff6ef9/R/simu-pheno.R#L50-L59
> > 
> > .
> > Where do you see I use sum(beta^2)?
> 
> At the beginning of the function, you generate beta from a normal distribution N(0,h2/M), and so I falesly beleived you use sum(beta^2). I recognize this problem as I checked the results in my simulation: I calculated norm(result$effect,"2")^2 and found it is equal to h2 I set. I understand that your definition is correct and I am checking my code. Thank you.

I use the raw individual data downloaded from the UKBB and so the LD matrix of SNPs of the raw individual data is not the identity matrix. I will reply when I find the cause of my problem.
