### ISSUE TITLE
Discovered outliers detected in different iterations of SVD

### ISSUE THREAD

**Issue by fmadani** [privefl/bigsnpr#340]
Hi Florian,

Actually, I need your clarification about the outliers  detected in different iterations of SVD. Here is an example output resulting from this code:
obj.svd <- runonce::save_run(
  bed_autoSVD(obj.bed, k = 20, ncores = nb_cores()),
  file = "PCA_GWAS_data.rds")

![image](https://user-images.githubusercontent.com/7520134/169928296-575887b9-47ec-4357-b3c7-3d7c7c06c02e.png)

Q1 ) Should we filter out ALL outliers detected in ALL iterations? Or we should filter out those detected in the last iteration that is 0 in the above case?
Q2) How can we extract the the ID of the outliers in order to filter them out from the target dataset?

I appreciate your time in advance.
Farshad

**Comment by privefl** [comment]
1) Outliers are filtered progressively, so they are all removed in the end.

2) You can use `attr(obj.svd, "subset")` to get the column indices kept. You can then use e.g. `setdiff()` to get the indices that have been removed. I'll add this information in the doc in the next versions.

**Comment by fmadani** [comment]
Florian
