### ISSUE TITLE
Questions about QC Process

### ISSUE THREAD

**Issue by jfrank94** [privefl/bigsnpr#341]
I have some questions about the overall QC process based on your blog, Florian. There's an outlier check based on MAF and standard deviations of the internal/external datasets on [chapter 6](https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html). Is that a part of the QC process, or the only QC process is based on [chapters 3](https://privefl.github.io/bigsnpr-extdoc/preprocessing.html) and [4](https://privefl.github.io/bigsnpr-extdoc/population-structure.html) with Pre-processing/Imputation and Population Structure Analysis respectively? 

Secondly, can you explain the logic for this piece of code for detecting the outliers in chapter 6? Are these numbers based on confidence intervals or something else? 
```is_bad <- sd_ss < (0.5 * sd_val) | sd_ss > (sd_val + 0.1) | sd_ss < 0.1 | sd_val < 0.05```

Lastly, is all of chapter 6 a standard setup for LDpred2 and other PRS modeling (i.e. C+T, Lassosum, etc.)?

Thank you in advance for your help.

**Comment by privefl** [comment]
The bigsnpr-extdoc is more an overview of what you can do.
You can refer to each tutorial of the different PRS methods for building each.

The QC on sd_ss or sd_val alone is basically a QC on MAF. 
And the other two QCs are to check departure from sd_ss==sd_val.

**Comment by jfrank94** [comment]
Thank you for confirming that it's a QC process and it's based on MAF, but where did you derive the numbers from? 

Also on your blog, you're using LDpred2 with this method, but can this applied to other methods of PRS (ie C+T or Lassosum)?

**Comment by privefl** [comment]
Yes, this can be applied prior to any PGS method, or sumstats-based method actually. It's kind of what we argue in [this preprint](https://doi.org/10.1101/2021.03.29.437510). I guess C+T would be more robust to this.
We also argue that this should perform as part of the GWAS, e.g. before meta-analyzing results.
The QC from chapter 3 is based on individual-level data, not summary statistics.

**Comment by privefl** [comment]
Any update on this?

**Comment by jfrank94** [comment]
Apologies @privefl. Thank you for your help and explanations. That's pretty much it.
