### ISSUE TITLE
How to save a .bed,.bim.,.fam set from an .rdx like object?

### ISSUE THREAD

**Issue by watplatt** [privefl/bigsnpr#342]
Having done a sequence of operations (QC and imputation) having loaded an object from an .rdx file - e.g. output of snp_attach() - I'd like to save the .bim, .fam, .bed files for other analyses.

How do I do that?

Thx!!

**Comment by privefl** [comment]
https://privefl.github.io/bigsnpr/reference/index.html#section-i-o

**Comment by watplatt** [comment]
Thanks!!
