### ISSUE TITLE
Error using snp_fastImpute

### ISSUE THREAD

**Issue by watplatt** [privefl/bigsnpr#343]
When I call snp_fastImpute(G, CHR, ncores = 32), w/ G and CHR appropriately populated (file labels filled), I get:

Error in getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type): Error when mapping file:
  No such file or directory.

Traceback:

1. snp_fastImpute(G, CHR, ncores = 32)
2. imputeChr(X, X2, infos.imp, ind, alpha, size, p.train, n.cor, 
 .     seed, ncores)
3. infos.imp[1, ind.chr]
4. infos.imp[1, ind.chr]
5. extract_matrix(x, transform_ind(i, n), transform_ind(j, m))
6. (new("activeBindingFunction", .Data = function () 
 . {
 .     if (identical(.self$extptr, NIL_PTR)) {
 .         .self$extptr <- getXPtrFBM(path = .self$bk, n = .self$nrow, 
 .             m = .self$ncol, type = .self$type)
 .     }
 .     .self$extptr
 . }))()
7. getXPtrFBM(path = .self$bk, n = .self$nrow, m = .self$ncol, type = .self$type)

What does this mean? and how to fix it?

Thx!

**Comment by privefl** [comment]
> No such file or directory.

Are you using a temp file from another session or something?
It seems the `G$backingfile` does not exist anymore.

**Comment by watplatt** [comment]
That backingfile is there but it seems it isn't being found.  

$ backingfile : chr "/home/data/MergedData/MissFiltered/niagadsMergedChr19.bk"

watplatt@cg-alz:/home/watplatt $ stat /home/data/MergedData/MissFiltered/niagadsMergedChr19.bk
  File: /home/data/MergedData/MissFiltered/niagadsMergedChr19.bk
  Size: 1539136212	Blocks: 3006136    IO Block: 4096   regular file
Device: 810h/2064d	Inode: 717324949   Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1002/watplatt)   Gid: ( 1002/watplatt)
Access: 2022-05-30 00:10:06.866606961 -0500
Modify: 2022-05-26 22:04:51.715928275 -0500
Change: 2022-05-26 22:04:51.715928275 -0500
 Birth: -

**Comment by privefl** [comment]
No idea what's going on then.
I will need more info to be able to help you.

**Comment by privefl** [comment]
Any update on this?

**Comment by watplatt** [comment]
I plan to be back to this later this week/weekend.

Thank you!

From: Florian Privé ***@***.***>
Date: Wednesday, June 8, 2022 at 4:04 PM
To: privefl/bigsnpr ***@***.***>
Cc: Daniel Platt ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [privefl/bigsnpr] Error using snp_fastImpute (Issue #343)
Any update on this? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Any update on this?

**Comment by privefl** [comment]
Any update on this?
