### ISSUE TITLE
h2 calculated to be negative value

### ISSUE THREAD

**Issue by AlisaBIG** [privefl/bigsnpr#347]
Hi, @privefl I was running ldpred2 grid model. I have about 50k variants. When I calculate h2, and it occurs error :
` 'h2' should have only positive values.` 
My R code as follow:
`ldsc <- snp_ldsc(   ld, 
                    length(ld), 
                    chi2 = (df_beta$beta / df_beta$beta_se)^2,
                    sample_size = df_beta$n_eff, 
                    blocks = NULL)
h2_est <- ldsc[["h2"]]`
I have looked at [#146](https://github.com/privefl/bigsnpr/issues/146), you said  that the heritability estimate that we input to LDpred2 is negative, I can't quite grasp that meaning. So what may cause this problem?

**Comment by privefl** [comment]
50K variants is very small, you should have many more (close to 1M usually).
You're maybe not capturing much.
You should also check the distribution of ld and chi2.

**Comment by AlisaBIG** [comment]
> 
Thank you for your reply. I think there may be some problems with my data because I estimated h2 by ldsc and also showed that heritability is negative.
