### ISSUE TITLE
PRS coefficients

### ISSUE THREAD

**Issue by Robbie-RL** [privefl/bigsnpr#348]
Is there a way to get the PRS coefficients from the "snp_grid_stacking" step?

**Comment by privefl** [comment]
There is `final_mod$beta.G` in [the tutorial](https://privefl.github.io/bigsnpr/articles/SCT.html).
Isn't it what you are looking for?

**Comment by Robbie-RL** [comment]
From what I understand, those are the updated beta coefficients for the SNPs derived from the summary statistics?

Either way, I looked at the source code and managed to get the PRS coefficients. From 600K SNPs, there was 30800 PRS so I got a vector of 30800 which looks to be the coefficients.


```
best_mod <- summary(mod, best.only = TRUE)
beta_best_mod <- best_mod$beta[[1]]
beta_stacking <- rep(0, ncol(multi_PRS))
ind_col <- attr(mod, "ind.col")
beta_stacking[ind_col] <- head(beta_best_mod, length(ind_col))
  
return(beta_stacking)
```

**Comment by privefl** [comment]
You want the effects sizes for the final PGS model?
That's `$beta.G`.

**Comment by Robbie-RL** [comment]
All good mate. I've got the 600K effect sizes using ```$beta.G```. I just wanted to also get the 30K+ PRS coefficient from the penalised regression step in  ```snp_grid_stacking```.

**Comment by privefl** [comment]
Are you talking about all the effect sizes for all C+T models corresponding to the different combination of parameters?

**Comment by Robbie-RL** [comment]
Perhaps I'm interpreting the stacking process wrong but I'm referring to the penalised regression part of ```snp_grid_stacking```. Specifically:
```
mod <- `if`(length(unique(y.train)) == 2, big_spLogReg, big_spLinReg)(
      multi_PRS, y.train, alphas = alphas, ncores = ncores, ...)
```
So I want to get the coefficients of all the all C+T models (30800 in my case) from the regression.
$\beta_0 + \beta_1PRS_1+...+\beta_{30800}PRS_{30800}$

I've managed to get a 30800 vector (1400 each chromosome) with suspected chromosomes that play a large role in a disease I'm investigating having high coefficients so I think I've managed to get the correct information.

Again, I might be understanding the SCT model wrong...

**Comment by privefl** [comment]
I see, then I think what you did is right.
