### ISSUE TITLE
Quality control of summary statistics exclude (almost) all SNPs

### ISSUE THREAD

**Issue by jianvhuang** [privefl/bigsnpr#349]
Hi Florian,

I tried LDPRED2 on GWAS with small sample sizes (8000 to 35000), and the QC procedure based on the below script categories almost all of the SNPs as "bad". My target population also has a small sample size (<1000). 

`is_bad <- sd_ss < (0.5 * sd_val) | sd_ss > (sd_val + 0.1) | sd_ss < 0.1 | sd_val < 0.05`

I wonder if you have any advice on this.

Thank you.

**Comment by privefl** [comment]
Can you show me the plot?

**Comment by jianvhuang** [comment]
See below three examples

![QQPLOT-SummaryStatQC-example1](https://user-images.githubusercontent.com/30910276/179479986-595eca77-70e7-40a5-85c7-32a2fe174345.png)

![QQPLOT-SummaryStatQC-example2](https://user-images.githubusercontent.com/30910276/179480039-80ba6cd5-46ef-4ba2-b662-8b362629e360.png)

![QQPLOT-SummaryStatQC-example3](https://user-images.githubusercontent.com/30910276/179480079-e6ef9407-b7fa-48d4-9c21-c224a9689c94.png)

**Comment by privefl** [comment]
The first one looks good, it is probably just you forgot the `sd(y)` in the estimate of `sd_ss`.

You can estimate it with e.g. `with(df_beta, sqrt(quantile(0.5 * (n_eff * beta_se^2 + beta^2), 0.01)))`.

**Comment by privefl** [comment]
Yes, you should try that.

**Comment by jianvhuang** [comment]
Thank you very much! I will try that.

**Comment by privefl** [comment]
You should always use the beta^2, it does one approximation less, so it should be a better fit.
But that makes a difference only when there are large effects, otherwise it is just negligible.

**Comment by jianvhuang** [comment]
Thank you for clarifying.
