### ISSUE TITLE
UKBB and hapmap3 variants

### ISSUE THREAD

**Issue by alek0991** [privefl/bigsnpr#353]
Hi, 
I am using the bigsnpr (v1.10.8) to calculate beta_auto for pan-UKBB phenotypes using HAPMAP3 variants and the LD-reference provided in the ldpred2 paper. I have a few questions but first I want to thank you for providing such a great and well documented tool. I have found it extremely useful for my work.
I have the following questions and highly appreciate it if you could share your insight: 

- The SFBM (.sbk) file is ~35G and when I use 16 cores and 128G RAM the ldpred2-auto takes 1-4 hours. I have to run many jobs and trying to use the resources efficiently. I played with number of cores and memory a bit but couldn't figure out what is the optimal configuration. What is the recommended setting for such cases?
- Is it okay to initialize h2 with a fixed value in (0,1), e.g., `h2_init=0.2`? I am hesitant to use h2 estimate of the ldsc because: the GWAS is from a generalized mixed model; In multiple case-control studies (e.g., Celiac) samples are not balanced and sometimes gives h2>1; I am not confident about estimated n_eff for some phenotypes and not sure how the phenotype is normalized (e.g., skin color).
- For some phenotypes the sd_ldref vs sd_ss filtering step is removing almost all of the variants. For example, the filtering for the skin color removed 99.8% of the variants (Figure 1) while it keeps 100% of the variant for standing height (Figure 2). I am using the eq 2 of ldpred2 paper for continuous (assuming the phenotype is normalized) and eq 3 for binary phenotypes. Is this step necessary for a phenotype like skin color (Figure 1)? 

I have attached two figures and a brief script hope it helps to address this questions.
Thank you, 
Ali

Figure 1: Skin color
---------------------------------------------------------------------

<img src="https://user-images.githubusercontent.com/11303721/182208777-fe07e5a2-4cec-4fb3-9c23-22f2511f9fbf.png" alt="drawing" width="500"/>

Figure 2: Standing height
---------------------------------------------------------------------

<img src="https://user-images.githubusercontent.com/11303721/182208979-c970ec3d-00b6-468f-949f-6233cefd7e56.png" alt="drawing" width="500"/>

---------------------------------------------------------------------

```R

# binary traits
# n_eff = 4 / (1 / n_cases + 1 / n_controls)
# sd_ss = 2 / sqrt(n_eff * beta_se^2))


# continuous traits
# n_eff = number of samples
# sd_ss = 1 / sqrt(n_eff * beta_se^2))

(ldsc <- with(df_beta, snp_ldsc(ld, ld_size = nrow(map_ldref),
                                chi2 = (beta / beta_se)^2,
                                sample_size = n_eff,
                                ncores = NCORES)))

# h2_est <- ldsc[["h2"]]
h2_est <- 0.2
# LDpred2-auto
multi_auto <- snp_ldpred2_auto(corr, df_beta, h2_init = h2_est,
                               vec_p_init = seq_log(1e-4, 0.9, 30),
                               ncores = NCORES, sparse = TRUE)  # 13 hours

**Comment by privefl** [comment]
- You should use the format `compact = TRUE` to make the matrix twice as small, and use the newest version of the package (on CRAN) in which LDpred2 should be much faster (less than 1 hour). 128 GB RAM is enough (50 should be okay if using compact). I recommend to use 15 cores and 30 initial values so that each core run 2 of them. I will soon recommend 50 values and 13 cores (i.e. ~4 each).

- I have found it okay to initialize a value that is far from the true value, it generally converge quite fast (as opposed to the p parameter). There are issues with using sumstats from e.g. mixed models, I would recommend simple linear or logistic regression sumstats. h2 > 1 is okay for binary traits, as it can be < 1 when you transform it to the liability scale.

- Have a look at https://github.com/privefl/bigsnpr/issues/349.

**Comment by alek0991** [comment]
I appreciate your prompt response.

**Comment by privefl** [comment]
If this answered all the questions you had, please close this issue.

**Comment by alek0991** [comment]
It does answer my questions. Thanks! I close this issue.
