### ISSUE TITLE
remove duplicates leads to index larger than maximal 46367

### ISSUE THREAD

**Issue by AlisaBIG** [privefl/bigsnpr#355]
I am running LDpred2 grid model with about 700,000 variants. when performing snp match, error occurs as below:
```
0 ambiguous SNPs have been removed.
Some duplicates were removed.
46,367 variants have been matched; 0 were flipped and 3,808 were reversed.
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  index larger than maximal 46367
Calls: [ ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_ij -> intI
Execution halted
```
However, I have checked that there are no duplicated snps in my data. Is anyone encountered the same problem as mine? Or I wonder if I could be told what's the duplicates removed by ldpred2 according to this process?

**Comment by privefl** [comment]
I have never encountered this problem before.
Could you share the two input dataframes you provide to this function? (e.g. as RDS files)

**Comment by AlisaBIG** [comment]
Here are my RDS file and my summary statistics look like; 
`str(obj.bigSNP, max.level = 2, strict.width = "cut")
List of 3
 $ genotypes:Reference class 'FBM.code256' [package "bigstatsr"] with 16 fields
  ..and 26 methods, of which 12 are  possibly relevant:
  ..  add_columns, as.FBM, bm, bm.desc, check_dimensions,
  ..  check_write_permissions, copy#envRefClass, initialize, initialize#FBM,
  ..  save, show#envRefClass, show#FBM
 $ fam      :'data.frame':      503 obs. of  6 variables:
  ..$ family.ID  : int [1:503] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ sample.ID  : chr [1:503] "HG00096" "HG00097" "HG00099" "HG00100" ...
  ..$ paternal.ID: int [1:503] 0 0 0 0 0 0 0 0 0 0 ...  ..$ maternal.ID: int [1:503] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ sex        : int [1:503] 1 2 2 2 1 2 1 1 2 1 ...
  ..$ affection  : int [1:503] -9 -9 -9 -9 -9 -9 -9 -9 -9 -9 ...
 $ map      :'data.frame':      46369 obs. of  6 variables:
  ..$ chromosome  : int [1:46369] 4 4 4 4 4 4 4 4 4 4 ...
  ..$ marker.ID   : chr [1:46369] "4:72510:C:T" "4:79340:A:G" "4:84610:A:C" ""..
  ..$ genetic.dist: int [1:46369] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ physical.pos: int [1:46369] 72510 79340 84610 84792 88519 89945 94481 98..
  ..$ allele1     : chr [1:46369] "C" "A" "C" "T" ...
  ..$ allele2     : chr [1:46369] "T" "G" "A" "C" ...
 - attr(*, "class")= chr "bigSNP"
`
`
>map<-obj.bigSNP$map[-3]
> head(map)
  chromosome   marker.ID physical.pos allele1 allele2
1          4 4:72510:C:T        72510       C       T
2          4 4:79340:A:G        79340       A       G
3          4 4:84610:A:C        84610       C       A
4          4 4:84792:C:T        84792       T       C
5          4 4:88519:A:G        88519       A       G
6          4 4:89945:D:I        89945       D       I

> dim(map)
[1] 46369     5`

`rsid          chr  pos     a0  a1  beta      beta_se   n_eff   p
1:812743:C:T  1    812743  T   C   .042515   .0217158  162973  .39797
1:931362:A:G  1    931362  A   G   -.046678  .0144964  162973  1.630e-06
1:940005:A:G  1    940005  G   A   -.044383  .013749   162973  .000196
1:940809:D:I  1    940809  I   D   -.043737  .0140423  162973  .000107
1:941334:A:G  1    941334  A   G   -.044173  .0137838  162973  .000175
1:941539:C:T  1    941539  T   C   -.045347  .0137219  162973  .000447
1:943968:C:T  1    943968  T   C   .035504   .012868   162973  .0000188
1:944564:C:T  1    944564  C   T   -.040101  .0136393  162973  .0000537
1:949608:A:G  1    949608  A   G   -.040148  .0133895  162973  .000179`

**Comment by privefl** [comment]
I need the `sumstats` and `info_snp` you provide to `snp_match()`.
I need you to send them to me.

If you can identify a small enough subset that still causes the issue, then you can directly paste it here after using `dput()`.

**Comment by AlisaBIG** [comment]
Thanks a lot!!! I have sent them to your email.

**Comment by privefl** [comment]
With the data you provided, I have no issue running
```r
map <- bigreadr::fread2("tmp-data/map")
sumstats <- bigreadr::fread2("tmp-data/sumstats.txt")
bigsnpr::snp_match(sumstats, map)
```
***
Please provide package version numbers 
```r
packageVersion("bigsnpr")
packageVersion("data.table")
```

**Comment by AlisaBIG** [comment]
`> packageVersion("data.table")
[1] ‘1.12.4’
> packageVersion("bigsnpr")
[1] ‘1.10.8’`

**Comment by privefl** [comment]
Are you really sure this error comes from `snp_match()`?

It seems to be an error with accessing a sparse matrix outside of its dimensions, e.g.
```r
spmat <- Matrix::rsparsematrix(100, 100, 0.01)
spmat[, 101]
```

**Comment by AlisaBIG** [comment]
Well, you are right. After I remove duplicates from my data by myself, the problem solved. Thanks your warm and patient help!
