### ISSUE TITLE
GWAS summary statistics from a mixed model

### ISSUE THREAD

**Issue by alek0991** [privefl/bigsnpr#356]
Hi, 
In another issue (#355) you recommended using ldpred2 with summary stats from a GLM. The problem is we only have GLMM summary stats from pan-ukbb and it's not easy to get GLM stats for all the phenotypes we are analyzing.

1. Does it make sense to apply ldpred2 on mixed model summary stats (GLMM from pan-ukbb) with [European LD reference (with blocks)](https://figshare.com/articles/dataset/European_LD_reference_with_blocks_/19213299)? 
2. If the sd_ss vs. sd_ldref are matching well, based on the quality control criteria provided in ldpred2 paper,  is the ldpred2 analysis on mixed model summary stats reliable?

Best,
Ali

**Comment by privefl** [comment]
I think there can be a few issues from time to time, but never had the time to properly investigate the potential issues.

I did use some of these sumstats in my latest paper, where my strategy was to estimate the effective sample size (smaller with SAIGE and larger with BOLT-LMM).
- https://github.com/privefl/paper-misspec/tree/main/code/prepare-sumstats-bbj (BOLT)
- https://github.com/privefl/paper-misspec/tree/main/code/prepare-sumstats-finngen (SAIGE)

I think you shouldn't have a problem with this strategy when the QC plots of SDs are fine (after correcting Neff).
