### ISSUE TITLE
genetic correlation using ldpred2 summary statistics

### ISSUE THREAD

**Issue by alek0991** [privefl/bigsnpr#360]
Dear Florian, 
I have made a lot of progress thanks to your helpful responses to my questions in the past few weeks and I highly appreciate that. I am trying to calculate the genetic correlation between phenotypes and I was wondering if I can use the joint effect predicted by ldpred2 to calculate the genetic correlation between phenotype $x$ and $y$ like below:
$$C_nx=C_nG\lambda_{joint}$$
$$C_ny=C_nG\gamma_{joint}$$
$$~~~~~~~~~x^TC_ny=\lambda_{joint}^TG^TC_nG\gamma_{joint}~~~~~~~~~(1)$$
From the ldpred2 paper we have:
$$G^TC_nG=(n-1)SRS$$
$$RS\gamma_{joint}=S\gamma_{marg}$$
If we plug them into Eq. 1 we have:
$$\frac{1}{n-1}x^TC_ny=\lambda_{joint}^TS^2\gamma_{marg} $$
Therefore,
$$cov(x,y)=\lambda_{joint}^TS^2\gamma_{marg}$$
Probably due to approximations, estimated cov(x,y) and cov(y,x) are not necessarily identical. Therefore, the genetic correlation is estimated like below:
$$r_{xy} = \frac{cov(x,y)+cov(y,x)}{2\sqrt{cov(x,x)cov(y,y)}}$$
- Does this  approximation of the genetic correlation make sense or I am missing something here? 
- I am also a bit confused by the definition of $\beta=S\gamma$ in the ldpred2 paper. $\gamma_{marg}$ is the beta score from the summary statistics file, right? Or it should be scaled?

**Comment by privefl** [comment]
$\gamma$ are the effects on the allele scale (e.g. from the marginals from GWAS or the joints you want to use for polygenic scores), while $\beta$ are the effects of the scaled genotypes, which is the scale I use internally in LDpred2.

I'll test your equation and get back to you.

**Comment by privefl** [comment]
If you forget about this approximation $$RS\gamma_{joint} \approx S\gamma_{marg}$$ you get $$cov(x,y)=\lambda_{joint}^TSRS\gamma_{joint}=\delta_{joint}^TR\beta_{joint}$$ where $\delta$ and $\beta$ are the scaled versions.

**Comment by privefl** [comment]
This is the formula I use to get $h^2_x=cov(x,x)$.
For two different iterations, I get $r^2_x = \delta_1^T R \delta_2$ (still need to justify why, but it works very well in practice).
So, I think $\delta^T R \beta$ should give the co-predictability, and not the co-heritability, which will underestimate $r_{xy}$.

**Comment by privefl** [comment]
Sometime ago, I tried instead using $$r_{xy} = \frac{\delta^T R \beta}{\sqrt{r_x^2 r_y^2}}$$
IIRC, it worked well in practice in case of complete sample overlap between GWAS of x and y, but not when there was no overlap.

**Comment by bvilhjal** [comment]
Hi @alek0991 

I do believe one should be able to account for sample overlap, e.g. by inferring it in the Gibbs sampler.

Best,
Bjarni

**Comment by alek0991** [comment]
Dear Florian and Bjarni, 
Thanks for your useful comments. I have been testing all these formulas and they are usually very similar when the sd_ldref and sd_ss are matching well. 

However, I am working with pan-ukbb summary data which is mixed model using SAIGE and probably not the best summary data especially for binary treat with large-effect loci like red hair, bilirubin, and celiac disease. 

As you have already mentioned in Fig. S15 of your recent [paper](https://doi.org/10.1101/2021.03.29.437510), regions with high LD can correlate with PCs and create ouliers in sd_ldref vs. sd_ss plot. It seems when a large effect loci overlaps a high LD region the estimated joint effects become unreliable. I have already mentioned the celiac disease case here https://github.com/privefl/bigsnpr/issues/354#issue-1325122440 and I have seen similar pattern for red hair, bilirubin and a few other binary treats with large-effect loci.
I should mention that for quantitative treats everything looks normal as far as I have noticed.

**Comment by privefl** [comment]
Yes, sumstats from LMM or GLMM are not recommended to use with LDpred2.
My guess is that this is a problem for most sumstats-based methods.
