### ISSUE TITLE
Error in format_snp_id(snp_id) in snp_readBGEN and snp_readBGI

### ISSUE THREAD

**Issue by JasperHof** [privefl/bigsnpr#361]
Hello,

I have tried to load a BGI file in R, but I keep stumbling upon an error that I did not encounter in previous analyses.
The head of my BGI file looks like this:

![image](https://user-images.githubusercontent.com/79317570/187619952-304e79e1-2f22-40b1-ad4f-8b6f088424b5.png)

But when I try to load a subset of SNPs from the BGI file, my formatting seems to be wrong:

![image](https://user-images.githubusercontent.com/79317570/187620275-db89bc0a-f1d5-4d21-876f-d6e36830aae5.png)

Also when I add the 'chr' part which is included in the chromsome column of the BGI file:

![image](https://user-images.githubusercontent.com/79317570/187620405-89e2b32d-f67c-4fe2-a0c2-f710e63a3f03.png)

Is there something wrong with the formatting of the BGI file perhaps? The bgen file should be 8bits and of bgen version 1.2.

Any help is much appreciated!

**Comment by privefl** [comment]
I think you don't need to wrap `snp_id` with `list()`.

**Comment by JasperHof** [comment]
Thank you for the suggestion!
Unfortunately it is still not working if I leave out list(), for both options:
![image](https://user-images.githubusercontent.com/79317570/187629139-2013651c-3a4a-4e67-bed7-2cb1e5dd045a.png)

**Comment by privefl** [comment]
I see. This function just does not expect to have `chrAB` in the `chromosome` column (just `AB`).
Can you change how BGI files are generated on your end?
Otherwise, I would need to update the function to also allow for this.

**Comment by JasperHof** [comment]
I think so too. My first attempts at changing the BGI file today failed, will keep you posted..

**Comment by JasperHof** [comment]
Hi privefl,

The issue is now resolved by removing 'chr' from the chromosome column in the BGI file. Not sure how it got there.

Thanks again!
