### ISSUE TITLE
LDPred2 halts when *snp_ldsc()* is called

### ISSUE THREAD

**Issue by jspatane** [privefl/bigsnpr#364]
Dear Florian Privè,

I've run the tutorial on LDPred2 available here (https://privefl.github.io/bigsnpr/articles/LDpred2.html), and it ran smoothly, even plotting was fine.

Nevertheless, when I tried it with a dataset of 2,904 individuals and 10,404,494 SNPs, it halted at the call to *snp_ldsc()* function. I've tried it at my home computer (with 64 GB), and also at my institute's server (CentOS, 1 node with 10 cores). 

When running on my desktop, I had a RAM issue, it kept growing past 64 GB then the computer stopped responding (I had to reboot it).

On the server (a conda-environment R build), the error was different. I post below the error returned by the server, and the server config details: 

----------------------------------

> packageVersion("bigsnpr")
[1] ‘1.10.8’

------------------------------------------------------

Loading required package: bigstatsr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

tibble [1,054,330 × 10] (S3: tbl_df/tbl/data.frame)
 $ chr     : int [1:1054330] 1 1 1 1 1 1 1 1 1 1 ...
 $ pos     : int [1:1054330] 752721 754182 760912 768448 779322 838555 846808 853954 854250 864938 ...
 $ a0      : chr [1:1054330] "A" "A" "C" "G" ...
 $ a1      : chr [1:1054330] "G" "G" "T" "A" ...
 $ rsid    : chr [1:1054330] "rs3131972" "rs3131969" "rs1048488" "rs12562034" ...
 $ af_UKBB : num [1:1054330] 0.841 0.87 0.84 0.106 0.128 ...
 $ ld      : num [1:1054330] 3.69 3.73 3.69 1.4 3.68 ...
 $ pos_hg17: int [1:1054330] 792584 794045 800775 808311 819185 878418 886671 893817 894113 904801 ...
 $ pos_hg18: int [1:1054330] 742584 744045 750775 758311 769185 828418 836671 843817 844113 854801 ...
 $ pos_hg38: int [1:1054330] 817341 818802 825532 833068 843942 903175 911428 918574 918870 929558 ...
[1] "/temporario/jspatane/xxx_LDPred2/xxx_merged_tmp.rds"
List of 3
 $ genotypes:Reference class 'FBM.code256' [package "bigstatsr"] with 16 fields
  ..and 26 methods, of which 12 are  possibly relevant:
  ..  add_columns, as.FBM, bm, bm.desc, check_dimensions,
  ..  check_write_permissions, copy#envRefClass, initialize, initialize#FBM,
  ..  save, show#envRefClass, show#FBM
 $ fam      :'data.frame': 2904 obs. of  6 variables:
  ..$ family.ID  : int [1:2904] 202646 300027 100853 301062 100502 102305 2029..
  ..$ sample.ID  : int [1:2904] 202646 300027 100853 301062 100502 102305 2029..
  ..$ paternal.ID: int [1:2904] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ maternal.ID: int [1:2904] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ sex        : int [1:2904] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ affection  : int [1:2904] -9 -9 -9 -9 -9 -9 -9 -9 -9 -9 ...
 $ map      :'data.frame': 10404494 obs. of  6 variables:
  ..$ chromosome  : int [1:10404494] 1 1 1 1 1 1 1 1 1 1 ...
  ..$ marker.ID   : chr [1:10404494] "rs4565649" "rs141090730" "rs141784362" "..
  ..$ genetic.dist: int [1:10404494] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ physical.pos: int [1:10404494] 713092 715205 717474 720583 722559 722603..
  ..$ allele1     : chr [1:10404494] "A" "G" "T" "A" ...
  ..$ allele2     : chr [1:10404494] "G" "C" "C" "G" ...
 - attr(*, "class")= chr "bigSNP"
'data.frame': 10404494 obs. of  9 variables:
 $ rsid   : chr  "rs4565649" "rs141090730" "rs141784362" "rs551231909" ...
 $ chr    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ pos    : int  713092 715205 717474 720583 722559 722603 722980 723918 729940 732801 ...
 $ a0     : chr  "A" "G" "T" "A" ...
 $ a1     : chr  "G" "C" "C" "G" ...
 $ beta   : num  -0.231 -0.268 -0.231 0.384 0.373 ...
 $ beta_se: num  0.901 0.863 0.901 0.886 0.834 ...
 $ N      : int  2904 2904 2904 2904 2904 2904 2904 2904 2904 2904 ...
 $ p      : num  0.798 0.756 0.798 0.665 0.654 ...
10,404,494 variants to be matched.
1,516,458 ambiguous SNPs have been removed.
Some duplicates were removed.
8,881,550 variants have been matched; 0 were flipped and 8,881,550 were reversed.
Error in asMethod(object) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
Calls: <Anonymous> ... <Anonymous> -> .local -> as_gCsimpl -> as -> asMethod
In addition: Warning message:
In (function (Gna, ind.row = rows_along(Gna), ind.col = cols_along(Gna),  :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
Execution halted

---------

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
--------------------------------------------------------------------------

Any help would be welcome! Thks in advance,

José

**Comment by jspatane** [comment]
Dear Florian, thks a lot for the quick reply! I was able to filter it down.

**Comment by privefl** [comment]
Great
If the problem is solved, please close the issue.
