### ISSUE TITLE
Only NAs in pred_auto

### ISSUE THREAD

**Issue by Janina24** [privefl/bigsnpr#365]
Hi Florian, 

I´m testing the LDPred2 package on my own genotypes (500,000 variants, 2447 individuals) but using the provided reference for the HapMap3 variants. 

When creating pred_auto with G2 from snp_fastImpute(G) I get a matrix containing NAs only.  

Thanks for your help!

**Comment by Janina24** [comment]
Now I tried the new snp_fastImputeSimple() and get another error message when running 
pred_auto <- big_prodMat(G2, sweep(beta_auto, 1, map_pgs2$beta, '*'),
                         ind.row = ind.test,
                         ind.col = map_pgs2[["_NUM_ID_"]])

Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
In addition: Warning messages:
1: In sweep(track[, -1], 2, track[1, -1]) :
  STATS is longer than the extent of 'dim(x)[MARGIN]'

**Comment by privefl** [comment]
The error comes from the use of sweep(), not my function.
