### ISSUE TITLE
How to add_code256 to data type other than 'raw' and 'unsigned char'?

### ISSUE THREAD

**Issue by jianvhuang** [privefl/bigsnpr#366]
Hi Florian,

I have a small genetic dataset and would like to do resampling. I have created a new sample list and would like to select the genetic data for the subjects being selected into the new sample.

I successfully used the `snp_attach` command to load the "bigSNP" object into R.
I also replaced the `obj.bigSNP$fam` data frame with the information on the new sample. Since the new sample was created with replacement, I replaced the ID with PseudoID.

I came across a problem when I was reconstructing the `obj.bigSNP$genotypes` for the new sample. Basically, I want to select some rows from the original `obj.bigSNP$genotypes` to create a  `obj.bigSNP$genotypes.resample` .
However, since `obj.bigSNP$genotypes` is a FBM.code256 object, I first created a data.table object for the resampled genotype data using the below script. 
```
raw=data.table(as.data.frame(obj.bigSNP$genotypes[]))
raw.resample=raw[df.resample$seq,]  # df.resample$seq is the sequence of the ID to be selected
```

Next , I would like to use the `as_FBM `and `add_code256 ` function to format the `obj.bigSNP$genotypes.resample` for constructing LDPRED2 PRS.
However, when I used `type="raw"` or  `type="unsigned char"`, NA values in the genetic data were converted into "00". This cause a problem when I applied add_code256 (the 00 became genotype 0, instead of NA as it should be).

```
obj.bigSNP$genotypes.resample=as_FBM(raw.resample, type="raw") # NA becomes "00"
obj.bigSNP$genotypes.resample=add_code256(obj.bigSNP$genotypes.resample, code)  # "00" coded as "0" 
```

Using  `type="double"` allows me to convert `raw.resample` to FBM, but not FBM.code256. But an error was returned when I ran `add_code256`

```
obj.bigSNP$genotypes.resample=as_FBM(raw.resample, type="double") # NA remains as NA
obj.bigSNP$genotypes.resample=add_code256(obj.bigSNP$genotypes.resample, code)  # See below error message
# Error in if (x$type != 1) stop2("'x' must be of type 'raw' (unsigned char)") :
  argument is of length zero
```

Do you have any advice? Thank you.

**Comment by privefl** [comment]
I think you should use big_copy(), or directly use the ind.row and ind.col parameters of the functions you want to use next.

**Comment by jianvhuang** [comment]
Thank you. big_copy() works for me.
