### ISSUE TITLE
effect allele for LDpred scores?

### ISSUE THREAD

**Issue by gunns2** [privefl/bigsnpr#367]
Hi, 
Thank you for creating a great package!
After computing a PRS using LDpred2 I would like to take said PRS and apply it using plink2. I know snp_match() handles the directions within the bigsnpr package, but I would like to produce a dataframe with the variant id, effect size and of effect and non-effect alleles for using the score. Is the a1 and a0 of the score the same as the input summary statistics? Or do the alleles correspond with the genotype data used to make the correlation matrix?
thanks so much!!
Sophie

**Comment by privefl** [comment]
After using `snp_match()`, the effect alleles should be all `a1` in `df_beta` and resulting PGS.

**Comment by gunns2** [comment]
great, thanks!
