### ISSUE TITLE
define _FLIP_ and _REV_

### ISSUE THREAD

**Issue by earosenthal** [privefl/bigsnpr#368]
Hi. Can you give a defintion for _FLIP_ and _REV_ in the manual page for snp_match(). I am currently assuming the following, but I want to be sure:
_REV_  genotyped in reverse direction from what is expected
_FLIP_  genotyped on opposite strand than expected
If both _REV_ and _FLIP_ are true, then the SNP is genotyped on the opposite strand and in the reverse direction of what is expected

Thanks

**Comment by privefl** [comment]
Yes, you assume correctly.
And yes, documentation could always be improved.
Do you want to make a PR for this?

**Comment by earosenthal** [comment]
You mean a pull request? I could try, when I have some extra time.

**Comment by privefl** [comment]
Yes
