### ISSUE TITLE
Converting SE of OR to SE of beta

### ISSUE THREAD

**Issue by oalavijeh** [privefl/bigsnpr#369]
Great tool and many thanks for the tutorials. 

I have this dataset: https://ora.ox.ac.uk/objects/uuid:226b9ceb-aef1-4abe-a62f-be3cfd6277c6/download_file?file_format=plain&hyrax_fileset_id=m87d288bb6f3efddccec55f815ef367f1&safe_filename=ukb_renal_stone_gwas_sumstats.txt&type_of_work=Dataset

The weights are given as OR (with their confidence intervals) which I can convert easily enough to betas. Beta_SE isn't quite so simple and I was wondering if you had a method or an implementation within the package to deal with this? 

Many thanks

**Comment by privefl** [comment]
Are you sure these are the SE of OR, and not for the logOR directly?
It is rare to get the SE of an OR, and also a bit odd as the CI for an OR should not be symmetrical.

**Comment by oalavijeh** [comment]
I am sure but I managed to convert them thanks!

**Comment by privefl** [comment]
Maybe you could share your solution here, if others need this as well.

**Comment by oalavijeh** [comment]
Sure:
Taking a summary stats file with OR and OR_U95L and OR_L95L:
sumstats$beta <- log(sumstats$OR)

#calculate beta and beta_se 
sumstats$beta_95L <- log(sumstats$OR_95L)
sumstats$beta_95U <- log(sumstats$OR_95U)
sumstats$beta_se <- (sumstats$beta-sumstats$beta_95L)/1.96
