### ISSUE TITLE
Non-numeric Chromosome IDs

### ISSUE THREAD

**Issue by perot57** [privefl/bigsnpr#37]
I noticed that many of the functions (ex. snp_indLRLDR) appear to assume integer chromosome IDs (1-26 etc) and produce errors when non-numeric. I was wondering if either there was support for non-traditional chromosome IDs (NC_####, chr##, etc)? Or if there was an easy way to transition the non-numeric IDs to numeric values within the objects used.

Going through the package, I couldn't see why it would be absolutely required for them to be numeric  and could help increase the flexibility as lots of system require all sorts of designations for chromosomes.

Thanks!

**Comment by privefl** [comment]
I think it was easier for me to allow only integers.
I think I'll keep it that way to keep the code simple, unless there is a strong point for making it more flexible.

I can think of two ways to go from names to integers:
```
> CHR <- c("chr1", "chr1", "chr2", "chr3")

> as.integer(as.factor(CHR))
[1] 1 1 2 3

> readr::parse_number(CHR)
[1] 1 1 2 3
```

Hope it is helping.

**Comment by privefl** [comment]
Any update on this?

**Comment by perot57** [comment]
This solution actually worked great! I did have to presort to make sure the randomly assign integers for unplaced scaffolds (common in my dataset). I have been working through to see if that has made any further issues but at the moment its been fine. Thanks for the help!
