### ISSUE TITLE
Can 'delta' be 0?

### ISSUE THREAD

**Issue by xcyang17** [privefl/bigsnpr#370]
Thank you for the great software! We have two questions about the value of 'delta':

Q1: Can 'delta' in the example code at https://privefl.github.io/bigsnpr/reference/snp_lassosum2.html be set to 0, so that lassosum2 runs without L2 regularization?
q2: If the current version of lassosum2 does not accept 0 for the value of 'delta', is it possible to modify lassosum2 so that it accepts 0?

**Comment by privefl** [comment]
I guess it can, but it either will lead to possible divergence, or provide similar results as with e.g. 0.001.

Have you tried it?

**Comment by privefl** [comment]
Have you tried it?

**Comment by xcyang17** [comment]
Hi, sorry I have not tried it. I will let you know when I try it, hopefully
in next 1-2 weeks.

**Comment by privefl** [comment]
Any update on this?
