### ISSUE TITLE
Running tutorial across multiple chunks

### ISSUE THREAD

**Issue by oalavijeh** [privefl/bigsnpr#371]
I am using the 100,000 genomes project aggregated dataset which is an aggregated plink bed file of 78,000 people chunked into 1500 segments/files spanning the entire genome and summary stats from the UKBB. Does your tool have an option for a file list to be read in such as in PRSice? Or would you write a loop over each bed file and then aggregate the results? 

All the best

**Comment by privefl** [comment]
No, I would recommend using PLINK to aggregate the files (you should restrict to the variants used here).

One example with bed files:
https://github.com/privefl/paper-ancestry-matching/blob/master/code/prepare-UKBB.R#L5-L21

**Comment by oalavijeh** [comment]
In this example you just used chr22. Could I run your LDpred2 tutorial (https://privefl.github.io/bigsnpr/articles/LDpred2.html) using my own data obviously, on a per chromosome basis and then amalgamate the results?

**Comment by privefl** [comment]
No, this is not recommended.
But you could compute the correlation per chromosome, and build the SFBM on the fly, as done in the tuto.

**Comment by privefl** [comment]
If you're using the computed LD for HapMap3 variants, then just restrict to those that you have in common.

Then, you can always compute the final PGS with PLINK without having to aggregate the files.

**Comment by privefl** [comment]
For the validation / test sets, when you compute the polygenic scores from the effect sizes obtained from LDpred2.

**Comment by oalavijeh** [comment]
Sorry last stupid question. If I am using this guide: https://choishingwan.github.io/PRS-Tutorial/ldpred/

My inputs are:
- Summary stats 
- A PLINK file aggregated across all the genomic chunks with just those variants that are in both HapMap3 AND my summary stats 
-  Phenotype/covariate/PC file

All the best

**Comment by privefl** [comment]
The tuto you should follow is this one: https://privefl.github.io/bigsnpr/articles/LDpred2.html.
I am not responsible of the other one. And I don't think it is updated at all since its author left academia.

**Comment by oalavijeh** [comment]
I have tried this tutorial and it's quite confusing! Before the actual tutorial there are many recommended links that all seem to carry similar code. I have now made an aggregated plink file with all the summary stat variants across the whole genome in my cases and controls (3 million variants, 23000 people). I believe this is enough people to not need another LD reference? 

Should I now intersect my summary stats with the HapMap3 variants to get a whittled down list of summary stats to apply the rest of tutorial too?

**Comment by privefl** [comment]
I agree the tutorial could be improved.
I'll try to do it soon.
What would you like to see changed / added?

**Comment by privefl** [comment]
I tried to improve the tuto a bit.
Feedback welcome

**Comment by oalavijeh** [comment]
Dear Florian, 

Apologies for the delay in getting back to you. t looks much better thanks! I have put an example of a tutorial format below that might help us clinicians approaching this with limited coding ability (apologies if any of this is wrong):

Start with a quick bullet point overview:
- Get variant set 
- Get summary stats and perform QC as per link
- Match summary stats to variant set
- Generate LDpred2 automatic model if variant set is large enough (as in an external LD source isn't needed)
- Then explain other models available as per your walk through 

Then a more detailed walk through as you have done:

1. LDpred2 in the automatic model mode needs:
- A reference SNP set e.g. HAPmap - I would also add what you would recommend with WGS data (I use 100,000 genome project data for example). 
- Summary stats 
- Could you make it more explicit if you need a third data source? As in if I have a large WGS case/control sample do I also need a third input which is an LD map or can it all be generated from the same variants. 

I would start with automatic model mode as it is what people are aiming for and then I would discuss the other models personally but I do not want to tell you what to do! 

Again thank you for being so receptive to feedback and answering (what I imagine) are annoying questions from noobs! 
All the best

**Comment by privefl** [comment]
For the second part of your comment, you basically want to have an idea of the input data needed to run LDpred2, right?

And the first part, list an overview of the coming sections?
