### ISSUE TITLE
Run LDSC inside R with snp_ldsc?

### ISSUE THREAD

**Issue by Ararder** [privefl/bigsnpr#373]
Hi!
Is it possible to run LDSC inside R, using the snp_ldsc function? Is there a tutorial somewhere for how to input the canonical LD scores from https://github.com/bulik/ldsc/wiki/Heritability-and-Genetic-Correlation into bigsnpr format?

/Arvid

**Comment by privefl** [comment]
It shouldn't be too hard to use.
You just need to provide the LD scores, chi2 stats and sample size.
You can use the precomputed LD scores in the LDpred2 tutorial if you want.

If you are very familiar with the format from ldsc, you can also try GenomicSEM::ldsc().

**Comment by privefl** [comment]
Did you manage to run one of the two functions?

**Comment by Ararder** [comment]
Yes! I was able to run it using GenomicSEM. Thanks for the recommendation!

GenomicSEM::ldsc(
  traits = c("an2019.sumstats.gz","crohns.sumstats.gz"),
  sample.prev = c(NA, NA),
  population.prev =  c(NA, NA),
  ld = "ldsc/eur_w_ld_chr",
  wld = "ldsc/eur_w_ld_chr"
)
`
