### ISSUE TITLE
Ldpred2-auto subset SNPs or genomewide fit?

### ISSUE THREAD

**Issue by szhan1000** [privefl/bigsnpr#374]
Dear Florian,

I have a very general question about LDpred2-auto. I understand you have recommended to run LDpred2-auto on all SNPs genome-wide. But I wonder if I can run it by SNP subsets that have different proportions of causal variants (e.g., as indicated by different folds of heritability enrichment from stratified LDSC ). Since each subset SNP could have different proportion of causal SNPs, I thought LDpred2-auto could have a better and customized fit for each subset? After I run each subset, I will then combine estimated coefficients and compute the genomewide PRS.

I would appreciate if you can provide some further advice.

Best,
Shizhong

**Comment by privefl** [comment]
No, I would not recommend it.

Perhaps, if there is one chromosome (or one region) contributing a lot, you could try running it once for this region, and once genome-wide excluding just this region. I am not sure if this would actually provide better fit.

In future work, I will probably consider allowing for enrichment (e.g. in the prior). But I am working on something else right now.

**Comment by privefl** [comment]
Also, I would not trust enrichments from S-LDSC, I think they are often overestimated.

**Comment by privefl** [comment]
Maybe they are not after all: https://doi.org/10.1101/2022.10.12.510418.

Anyway, I'll probably work on using more variants and functional annotations.
It will take a bit of time, so closing for now.
