### ISSUE TITLE
NULL value returned by function snp_ldsplit

### ISSUE THREAD

**Issue by rmehta1987** [privefl/bigsnpr#375]
What are the conditions for `snp_ldsplit` to return `NULL`?   
I am not familiar with R so I am having a hard time debugging.   
I am using a correlation matrix generated via `snp_cor` from a reference panel from 1000 human genomes and filtered SNPs that are common from variants of the FinnGen GWAS resulting in a corr size of about 300k x 300k.

**Comment by privefl** [comment]
First, are you sure your `POS2 <- test$map$genetic.dist` is not just full of 0s? You should probably do the conversion from CHR and POS.

Then, because you're using a small sample size, you should at least use `thr_r2 = 0.05` (r2 is usually larger than 0.01 just due to sampling error)..
Also use `min_size = 100` (not too small).
Finally, if you still get `NULL`, try increasing `max_r2` (by steps of 0.05).

**Comment by rmehta1987** [comment]
Awesome it worked by increasing the min_size and max_r2.  Is there a way to extract the blocks from the best_split for the downstream tasks?  I could not find or did not know where to look in the examples/scripts available.

**Comment by privefl** [comment]
The block ID of each SNP?
This is mentioned in the documentation I believe.

**Comment by rmehta1987** [comment]
Okay the commit helped!  Also how do I interpret the indices of the matrix/list.  Does index 1 correspond to the first SNP in the .bed file ?  Ideally I would like to create a subset of data that consist of the GWAS summary statistics with respect to the blocks the SNPs belong to.

**Comment by privefl** [comment]
Each row of the resulting data frame is one possible solution.
Look at the examples of the function to better understand maybe?

**Comment by rmehta1987** [comment]
Sorry I think you misunderstood the question.  Suppose I have 10 SNPS , in the resulting correlation matrix of size 10x10 and the resulting best solution of block_num that is a list of size 10x1.  Does block_num[[1]][1] and correlation_matrix[1,1] correspond to block and r^2 of SNP 1 or  is it sorted by SNP position ?

**Comment by privefl** [comment]
I'm not sure I get it.
But should be in the same order as your data.

**Comment by rmehta1987** [comment]
Okay, I just wanted to make sure the order doesn't change.  Thank you so much for the help!
