### ISSUE TITLE
Restrict to HapMap3(+) variants / LD reference

### ISSUE THREAD

**Issue by Smarzels** [privefl/bigsnpr#378]
I'm currently trying to compute a polygenic score for BMI in a sample of N=~1,700 using the new LDpred2-auto (bigsnpr 1.11.4). Unfortunately, until now I've not been successful and I'm achieving much lower R2 than with LDpred1.

I have two short questions. First, I was wondering if there are instances where you don't restrict to HapMap3(+) variants. When we computed the PGS for BMI with LDpred1, we included 1,967,822 SNPs, but when I'm restricting to HapMap3 or HapMap3+ using LDpred2, we can include only 905,721 and 920,317 SNPs, respectively. Would it be advisable to use all SNPs (i.e., not restrict to HapMap(+) variants)?

Second, what is the difference between using 1000 Genomes Project data versus HapMap genetic maps to interpolate to genetic positions? And after converting to genetic positions, in which instances would you use your own data as LD reference and when would you use an alternative LD reference?

Thank you!

**Comment by privefl** [comment]
So, your comparing the new LDpred2-auto to LDpred2-inf?
Which sumstats are you using? Is it from the 1700 indivs?

You can try with the 2M variants, but you'll have to compute the LD yourself, and maybe try to make LD blocks as well.

For the conversion to genetic positions, it should not change much I think.

About the LD, you should have a look at this new section of the tutorial: https://privefl.github.io/bigsnpr/articles/LDpred2.html#which-set-of-variants-to-use.

**Comment by privefl** [comment]
There is an example in the tutorial itself

**Comment by privefl** [comment]
Try this code instead: https://github.com/privefl/paper-infer/blob/main/code/example-with-provided-LD.R
