### ISSUE TITLE
Categorical Covariate

### ISSUE THREAD

**Issue by oceallc** [privefl/bigsnpr#38]
How would one include categorical covariates using snp_grid_PRS() or predict() such as sex or membership of a certain stratum? I see that covar.row can be used to load in results from a PCA but is there a way to specify separate categorical covariables, or include them together with the PCA? Thank you.

**Comment by privefl** [comment]
The easiest way to deal with categorical variables I know is using one-hot encoding (also called dummy encoding).

There are many packages to help you do this.
One possibility is using `dummies::dummy(iris$Species)`.
You might want to remove one of the dummy variable created to avoid problems with intercept, e.g. use `dummies::dummy(iris$Species)[, -1]`.

**Comment by oceallc** [comment]
Thanks, yes that makes sense. And with regard to the snp_grid_PRS() function the documentation doesn't seem to have a covar argument. In the original PRS tutorial the predict() from big_spLogReg() allows for covar.row as an argument. Where should this be introduced when implmenting the SCT method for prediction? Thank you.

**Comment by privefl** [comment]
Function `snp_grid_PRS()` just build C+T scores.
Then, `snp_grid_stacking()` is where you combine them with possible covariates.

**Comment by oceallc** [comment]
Thanks again, I now see that snp_grid_stacking() calls to big_spLogReg() which can accept a covar.train argument. I think there should also be a similar covar.test somewhere right? Where could the covariates for the test group be included for the final prediction? Thank you.

**Comment by privefl** [comment]
Usually, `covar.row` goes into the `predict()` method.
But, I did not implemented a special class for the output of `snp_grid_stacking()`. Maybe I shoud have.

You can find one example here: https://github.com/privefl/simus-PRS/blob/master/paper3-SCT/code_real/07-SCT-CAD.R#L282-L287.
If you have more than one covariate, make sure to use the matrix product `%*%` instead of just `*`.

I'm just manually doing what is implemented there: https://github.com/privefl/bigstatsr/blob/master/R/predict.R#L39-L42.

**Comment by privefl** [comment]
Any update on this?

**Comment by oceallc** [comment]
> Any update on this?

Yes, so it seems to work using that method thank you.

**Comment by privefl** [comment]
Thank for the feedback.

If some other people want me to implement this, tell me and I'll find some time.

**Comment by privefl** [comment]
Might be of interest: `bigstatsr::covar_from_df()`.
