### ISSUE TITLE
Interpreting output of `snp_grid_clumping`

### ISSUE THREAD

**Issue by glm729** [privefl/bigsnpr#381]
I am following the tutorial for running SCT, and I've been a bit confused about
how to interpret the output of `snp_grid_clumping`.  I may have understood part
of it, but I am unsure.  My questions are as follows:

* The results are a list, with indices for names.  Do these names represent the
  autosome for which the variants are selected?

* Each list is of length 28, which corresponds to the number of combinations of
  correlation threshold and window size.  Does each item in each list then
  represent the variants (by index) for the corresponding combination of
  correlation threshold and window size?

* Window size appears to be `floor(size / thr.r2)`, e.g. for `size = 50` and
  `thr.r2 = 0.95` the value is `floor(50 / 0.95) == 52` -- am I interpreting
  this correctly?

Please let me know if I should elaborate or give specific examples, or if
anything I have said is unclear!

**Comment by privefl** [comment]
- The first layer of the loop corresponds to different chromosomes (from `CHR`).
- The second layer corresponds to the different parameters in `attr(all_keep, "grid")`.
- And, yes for the size, see https://github.com/privefl/bigsnpr/blob/37ce6e86629d056aa2dae14542647b809ae37584/R/SCT.R#L58.

**Comment by glm729** [comment]
Thank you for the quick response!  And thank you for the information.  I was
getting a bit close but a bit lost too.  The results from running SCT on a
certain dataset were a bit confusing.  It looks like the results I'm getting
make sense, given your description, though admittedly I wasn't quite certain
about the list names being the chromosome.

I should probably go back to the paper on the subject, but why is the window
size scaled proportionally to the correlation threshold?  Is this to restrict
the window to a region of the "umbrella" captured by the correlation threshold,
such that the window captures an adequately-sized region but doesn't exceed the
bounds defined by the correlation threshold?

**Comment by privefl** [comment]
LD decays with genetic distance, so there's no need to look at a large window when you're using e.g. r2>0.95, but, on the contrary, you need a large window to capture most of the r2>0.01.

**Comment by glm729** [comment]
LD is generally a bit new to me, so I will need to do a bit more reading I
think!  But that makes sense to me -- the window size effectively becomes
scaled relative to the region captured by the correlation threshold.

Thank you again!  I may have more questions in future, if they're not a bother,
but I think I understand the results of my most recent tests.  I will also be
trying [this][tk0] and the "best-only" model, but I am not quite there yet.


[tk0]: https://github.com/privefl/bigsnpr/issues/348

**Comment by privefl** [comment]
Feel free to open a new issue when you have a new question.
