### ISSUE TITLE
Error in .sparse2g(x) : negative length vectors are not allowed

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [privefl/bigsnpr#384]
Hi Florian, 

When I tried to calculate LD using following script, I'm getting an error and warning. Can you please suggest how I can troubleshoot this?

My script:

```r
# calculate LD
for (chr in 1:22) {
  # Extract SNPs that are included in the chromosome
  ind.chr <- which(info_snp$chr == chr)
  ind.chr2 <- info_snp$`_NUM_ID_`[ind.chr]
  # Calculate the LD
  corr0 <- snp_cor(
    genotype2,
    ind.col = ind.chr2,
    ncores = NCORES,
    infos.pos = POS2[ind.chr2],
    size = 3 / 1000
  )
  if (chr == 1) {
    ld <- Matrix::colSums(corr0^2)
    corr <- as_SFBM(corr0, tmp)
  } else {
    ld <- c(ld, Matrix::colSums(corr0^2))
    corr$add_columns(corr0, nrow(corr))
  }
}
```
Error message:
```
Error in .sparse2g(x) : negative length vectors are not allowed
In addition: Warning message:
In (function (Gna, ind.row = rows_along(Gna), ind.col = cols_along(Gna),  :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
```

**Comment by privefl** [comment]
It means that you're computing and storing too many non-zero pairwise correlations.
I would say, either you're using too many variants per chromosome, or there is a problem with `POS2`.

**Comment by Mahantesh-Biradar** [comment]
So I was able to run it on smaller chromosomes like 21 and 22. There seems to be no problem with POS2 and I think its somethin to do with memory. 

Can you please suggest how I can address this?

**Comment by privefl** [comment]
How many variants are you trying to use?

**Comment by Mahantesh-Biradar** [comment]
About 1M

**Comment by Mahantesh-Biradar** [comment]
Overall

**Comment by privefl** [comment]
That does not make sense.

Could you check again `POS2`, maybe show some plot of it here.

**Comment by Mahantesh-Biradar** [comment]
Let me check and get back. Thanks

**Comment by privefl** [comment]
Any update on this?

**Comment by Mahantesh-Biradar** [comment]
Hi Florian, I think I have missed the step for restricting the analysis to hapmap SNPs.
