### ISSUE TITLE
snp_readBGEN incompatible with rlang > v 1.0.0

### ISSUE THREAD

**Issue by jebbd** [privefl/bigsnpr#385]
When reading in a subset of variants and samples from a BGEN I got the error

`function overscope_clean does not exist`

A quick search turned up the rlang package and that the function was soft deprecated some time in the past and I think is now no longer available at all since rlang 1.0.0 

Downgrading my version of rlang to the v 0.4.12 release solved the issue for now

**Comment by privefl** [comment]
Does `snp_readBGI()` work?

That is probably an issue with {dbplyr} or {dplyr}; have you updated them with {rlang}?

**Comment by jebbd** [comment]
Hi Florian,

Thanks for the quick reply. This was indeed an issue with conflicting rlang and dplyr in my environment.

Thanks
