### ISSUE TITLE
"long vectors not supported yet" issue when using snp_ldsplit

### ISSUE THREAD

**Issue by cz354** [privefl/bigsnpr#387]
Hi, when I tried to split a chromosome with 408759 SNPs, this problem appears. May I ask how to solve it ?

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'tril': long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

**Comment by privefl** [comment]
There are too many non-zero values in the correlation matrix; I'm a bit surprised that you were able to construct it in the first place.

Try to use `corr2 <- Matrix::drop0(corr, tol = sqrt(thr_r2))` as input instead, where `thr_r2` is the parameter you use in `snp_ldsplit()`.

**Comment by cz354** [comment]
Hi,
Thank you for your reply! But when I used corr2 <- Matrix::drop0(corr0, tol = sqrt(0.08)), there is still some error like:

Error in Matrix::drop0(corr0, tol = sqrt(0.08)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

**Comment by privefl** [comment]
Are you able to divide the matrix in two or three? E.g. `Matrix::drop0(corr0[, 1:2e5], tol = sqrt(0.08))`.
And then `cbind()` the results.

Otherwise, you can recompute the initial `corr` using `thr_r2` in `snp_cor()`.

**Comment by privefl** [comment]
Any update on this?

**Comment by cz354** [comment]
Dear Florian,

I recompute the initial corr using thr_r2 in snp_cor() and it works. Thank
you for your help.

Best,
Chi
