### ISSUE TITLE
L-BFGS-B error

### ISSUE THREAD

**Issue by Sabor117** [privefl/bigsnpr#389]
Hi Florian!

I am attempting to computer some PRS weights using LDpred2-auto with the `snp_ldpred2_auto()` function.

This has began to throw the following error in every instance of my current set of testing:

`Error in { : task 1 failed - "L-BFGS-B needs finite values of 'fn'"`

I've tried using a couple of variations of the following code:

My old version (based on the previous LDpred2 tutorial):

```
multi_auto = snp_ldpred2_auto(ref_corr,
		ref_df_beta,
		h2_init = h2_est,
		vec_p_init = seq_log(1e-4, 0.9, 1),
		num_iter = 500,
		ncores = 1)
```

And a newer version based on the updated tutorial:

```
multi_auto = snp_ldpred2_auto(ref_corr,
		ref_df_beta,
		h2_init = h2_est,
		vec_p_init = seq_log(1e-4, 0.2, length.out = 30),
		num_iter = 500,
		allow_jump_sign = FALSE, shrink_corr = 0.95,
		ncores = 1)
```

My h2_est is positive, the reference correlation matrix and data frame of betas/se/n_eff is aligned and so-on as per the LDpred2 tutorial and because of my unfamiliarity with the L-BFGS-B aspect of this I've no idea where to even start looking for trying to fix this.

Any help appreciated as always!

**Comment by privefl** [comment]
Yes, this happened to me when the model diverged substantially (when I used some bad LD).
It's because the alpha solver gets some weird values as input.
Are you sure the LD is okay? Do you still have the error when using `allow_jump_sign = FALSE, shrink_corr = 0.95`?

Otherwise, I'll make a quick fix where these chains are just discarded when this error happens.

**Comment by Sabor117** [comment]
When you ask whether the LD is okay, is there a way to check this? So that it's within reasonable boundaries?

All the SNPs used (should) be in reasonably close LD with each other though. I was also getting the same error with both versions of the script I used.

**Comment by privefl** [comment]
What is the LD you're using?
Does it match the population of the GWAS?

**Comment by Sabor117** [comment]
Oh, I see what you mean. Yes, that I believe the LD of the GWAS and reference panel should be equivalent as both populations are of European descent (using a subset of UK Biobank as the reference panel).

**Comment by privefl** [comment]
What do you get if using e.g. `alpha_bounds = c(-0.7, -0.7)`?

**Comment by privefl** [comment]
I think I can detect the divergence before this error happens.

What would you have me do with the chains that diverged?
- don't return anything `NULL`?
- don't return anything `NULL`? + remove the NULLs from the resulting list
- return everything up to when it diverged (and possibly NAs for the later values) -> a bit harder for me to code, but might be better

**Comment by Sabor117** [comment]
> What do you get when using e.g. `alpha_bounds = c(-0.7, -0.7)`?

Did you mean `alpha_bounds = c(-0.7, 0.7)` or actually `c(-0.7, -0.7)`? I'm currently running some tests so can easily test both.



> I think I can detect the divergence before this error happens.
> 
> What would you have me do with the chains that diverged?
> 
> * don't return anything `NULL`?
> * don't return anything `NULL`? + remove the NULLs from the resulting list
> * return everything up to when it diverged (and possibly NAs for the later values) -> a bit harder for me to code, but might be better

The latter option does potentially sound like the best one, however in the LDpred2 tutorial you then use the output of `snp_ldpred2_auto` with `rowMeans(sapply(multi_auto .. ))`. And so the presence of NAs would likely cause issues there, right?

**Comment by privefl** [comment]
Okay, I've implemented the last option.
Please give it a try.

**Comment by Sabor117** [comment]
Okay, so I've ran a few tests now.

I first wanted to just make sure the previous version wouldn't work with the `alpha_bounds` option. So I tried that with both `c(-0.7, 0.7)` and `c(-0.7, 0.7)` both of which also resulted in the same error.

I have then updated the package through Git (thanks for doing that by the way Florian) and tested again with the new version.

This time it completed but unfortunately has returned `multi_auto` as ENTIRELY NAs...

So, clearly, if it is stopping when it starts to produce NAs, then for me it starts producing them literally immediately?

**Comment by privefl** [comment]
You can check after how many iterations it diverged by looking at the path of h2 estimates.

**Comment by Sabor117** [comment]
Ah! Yeah, okay! It's not entirely NAs then! It's producing values for the first 26 iterations in `multi_auto[[1]]$path_h2_est` (and the other 29 as well).

So, if I go back and change num_iter to 26 or so, will that then possibly work?

**Comment by privefl** [comment]
So you're using [Full cis-eQTL summary statistics](https://molgenis26.gcc.rug.nl/downloads/eqtlgen/cis-eqtl/2019-12-11-cis-eQTLsFDR-ProbeLevel-CohortInfoRemoved-BonferroniAdded.txt.gz)?

And, you're saying that it worked fine with the previous version of LDpred2-auto? (i.e. prior to v1.11?

**Comment by Sabor117** [comment]
Correct.

And I believe so. I unfortunately have not been as diligent at tracking versions as I should have but I believe I was successfuly calculating PRS with LDpred2 in (most) of the genes I tried it on using v1.9 (or thereabouts). With the exception being some which produced a -ve h2.

**Comment by privefl** [comment]
Would you like me to add an option to be able to run LDpred2-auto as the previous version?
In the meantime, can you retry with `install.packages("https://cran.r-project.org/src/contrib/Archive/bigsnpr/bigsnpr_1.10.8.tar.gz", repos = NULL)`?

I will be busy this week, but I can investigate this further next week.

**Comment by Sabor117** [comment]
Depending on how easy that is to implement for you, given that it seems to rely a number of sub-functions so I've no idea how much different the varying versions are.

I can give that a go as well, but it's actually worth saying that when trying to install version 1.9.10 and 1.9.11 from CRAN (either downloading the zip from the archive or using `install_version` from `devtools` both versions actually wouldn't load in R because they were "corrupted".

**Comment by privefl** [comment]
Just make sure to close all R sessions, and restart one when you want to install a package.

**Comment by privefl** [comment]
I see that in the sumstats, only Z-scores are available; what do you use for `beta` and `beta_se` then?

**Comment by privefl** [comment]
Also, I can't seem to be able to match more than 78K variants with the HapMap3+ variants; do you have the same problem?

Could you send me the code that you used so far?

**Comment by Sabor117** [comment]
> I see that in the sumstats, only Z-scores are available; what do you use for `beta` and `beta_se` then?

For `beta` I did:
```
gene_stats$beta = as.numeric(gene_stats$Zscore) / sqrt(2 * as.numeric(gene_stats$AlleleB_all) * (1 - as.numeric(gene_stats$AlleleB_all)) * (as.numeric(gene_stats$NrSamples) + as.numeric(gene_stats$Zscore) ^ 2))
```

And for `se`:
```
gene_stats$se = 1 / sqrt(2 * as.numeric(gene_stats$AlleleB_all) * (1 - as.numeric(gene_stats$AlleleB_all)) * (as.numeric(gene_stats$NrSamples) + as.numeric(gene_stats$Zscore) ^ 2))
```



> Also, I can't seem to be able to match more than 78K variants with the HapMap3+ variants; do you have the same problem?
> 
> Could you send me the code that you used so far?

So, actually prior to this issue I was not using the HapMap3+ variants as a filter whatsoever. As I mentioned in my last reply I actually ended up trying them out for the first time the other week and wasn't able to match enough variants either.

I could send you the code I've been using? Should I e-mail it over?

**Comment by privefl** [comment]
Yes, please email me the code if you want.

Which set of variants have you tried?

Where do you get `AlleleB_all`? I don't remember seeing this variable in the sumstats.

**Comment by Sabor117** [comment]
> Yes, please email me the code if you want.
> 
> Which set of variants have you tried?
> 
> Where do you get `AlleleB_all`? I don't remember seeing this variable in the sumstats.

Okay, can do.

Ah, you also need the allele frequency file: https://molgenis26.gcc.rug.nl/downloads/eqtlgen/cis-eqtl/2018-07-18_SNP_AF_for_AlleleB_combined_allele_counts_and_MAF_pos_added.txt.gz

**Comment by privefl** [comment]
So, which set of variants have you tried?

**Comment by Sabor117** [comment]
So, as previously mentioned, I'm using a 10k individual reference panel from UK Biobank.

This was created by randomly selecting 10,000 unrelated British individuals ( ancestry evaluated on the basis of genomic data). It's based on imputed UKB genotypes (upwards of 10M SNPs in the total data-set). So variant selection was done using that.

**Comment by privefl** [comment]
Yeah, using 10M variants is really not recommended for now.
I'm surprised you managed to store the full LD matrix of that in the first place?

**Comment by Sabor117** [comment]
> Yeah, using 10M variants is really not recommended for now. I'm surprised you managed to store the full LD matrix of that in the first place?

That's actually something that has been a bit of a headache for a while but I think it's only possible because I'm specifically working with eQTLs.

So A. I'm only working on a chromosome by chromosome basis (I know that's also not something you recommend, but in terms of using cis-QTLs it simply makes sense) and actually B. I even refine the chromosome .bgens to only include the SNPs that overlap between the QTL summary stats and the reference panel. That was the only way to actually create the LD matrices in the first place.

**Comment by privefl** [comment]
If you install the newest GitHub version, you can now run LDpred2-auto as before when using `use_MLE = FALSE`.
