### ISSUE TITLE
snp_grid_PRS output all missing values

### ISSUE THREAD

**Issue by xcliu-oc** [privefl/bigsnpr#394]
Hi,
I'm trying to do the stacking C+T PRS with my dataset by following tutorial (https://privefl.github.io/bigsnpr/articles/SCT.html).

my obj.bigSNP object contains 836 subjects with 2,482,495 SNPs, and summary stats has 1,385,734 SNPs. 
After snp_match, 1,195,940 variants have been matched.

Before clumping, I did a quick imputation using `Gimp<-snp_fastImputeSimple(
  G,
  method = c("mode"),
  ncores =NCORES
)`
then Clumping: `all_keep <- snp_grid_clumping(Gimp, CHR, POS, ind.row = ind.train,
                              lpS = lpval, exclude = which(is.na(lpval)),
                              ncores = NCORES)`

thresholding: `multi_PRS <- snp_grid_PRS(Gimp, all_keep, beta, lpval, ind.row = ind.train,
                          backingfile = "tmp-data/data-scores", 
                          n_thr_lpS = 50, ncores = NCORES)`

all the codes have no error or warning messages. But my **multi_PRS are all NaNs**

dim(multi_PRS)
[1]   600 30800

multi_PRS[1:10, 1:10]
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [2,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [3,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [4,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [5,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [6,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [7,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [8,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 [9,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
[10,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN

I have no clue where I should start to trouble shot, please advice. 
Thank you so much!!!

**Comment by privefl** [comment]
I would check `str(all_keep)`.
Then I would check `beta` (no NA or weird values?), and `lpval` (you put -log10(pval) there, right?).

**Comment by xcliu-oc** [comment]
> I would check `str(all_keep)`. Then I would check `beta` (no NA or weird values?), and `lpval` (you put -log10(pval) there, right?).

Thank you for your prompt reply!
yes, I did find there are several NAs in my beta values! I will remove them and rerun,  and see if it works.

**Comment by privefl** [comment]
You can probably use `exclude = which(is.na(lpval) | is.na(beta))`.

**Comment by xcliu-oc** [comment]
solved! thank you!
