### ISSUE TITLE
Q about hm3 variants

### ISSUE THREAD

**Issue by gunns2** [privefl/bigsnpr#395]
Hi,
Thank you for putting together such a great tool for researchers. I have a hopefully easy question, where does your list of hapmap variants come from? I've noticed some discrepancies between this set of variants and others (in particular the list of hapmap variants provided by the creators of PRS-CS), and would love to understand where these discrepancies come from.

thank you,
Sophie

**Comment by privefl** [comment]
IIRC it is the ones from PRS-CS + some additional QC.
Isn't it explained somewhere in the paper or the code associated to it?

**Comment by gunns2** [comment]
Hi, thank you for your quick response! I could not find an explanation of the QC to explain the reduction from  1,117,493 variants to the 1,054,315 in the LD reference provided. Is it perhaps variants that were available in the UKBB? 

thanks

**Comment by privefl** [comment]
I think this is the code here:
https://github.com/privefl/paper-ldpred2/blob/master/code/provide-ld-ref.R

**Comment by gunns2** [comment]
thank you!
