### ISSUE TITLE
model saturated

### ISSUE THREAD

**Issue by xcliu-oc** [privefl/bigsnpr#396]
Hi,
I'm trying to do the stacking C+T PRS with my dataset by following tutorial (https://privefl.github.io/bigsnpr/articles/SCT.html).

my obj.bigSNP object contains 836 subjects, and I split 600 for training and leftover are testing.
after clumping + thresholding, I got 30800 C+T scores. however, `snp_grid_stacking` results messages showed that **models are saturated.** 

 `final_mod <- snp_grid_stacking(multi_PRS, y[ind.train], ncores = NCORES, K = 2)`
`summary(final_mod$mod)`
tibble: 3 x 9
alpha power_adaptive power_scale validation_loss intercept beta   nb_var message   all_conv
   <dbl>          <dbl>       <dbl>           <dbl>     <dbl> <list>  <int> <list>    <lgl>   
1 0.0001              0           1          0.0104     -295. <dbl>    7692 <chr [2]> FALSE   
2 0.01                0           1          0.0129     -457. <dbl>     515 <chr [2]> FALSE   
3 1                   0           1          0.0133     -428. <dbl>     113 <chr [2]> FALSE   
`summary(final_mod$mod)$message`
[[1]]
[1] "Model saturated" "Model saturated"

Is this because I have **small sample size but too many C+T scores?** Do you have any suggestions?
thank you!!!

**Comment by privefl** [comment]
Honestly, I think your sample size is too small to use stacking here.
I would just pick the best C+T score after having merged all chromosomes here.

**Comment by xcliu-oc** [comment]
> 
I thought so...
and I assume it is also too small for LDpred as well?

**Comment by privefl** [comment]
In LDpred2-grid (or lassosum2), you just choose the best model so it's the same as choosing the best C+T score.

**Comment by xcliu-oc** [comment]
I see. Thank you.
