### ISSUE TITLE
Issues with LD reference in blocks

### ISSUE THREAD

**Issue by lindseysinclair** [privefl/bigsnpr#399]
Dear Florian

Thanks ever so much for this very helpful new LD reference set. It's a great idea. I've amended my code to include it, based on the example script that you helpfully provided and your LDpred2 tutorial. 

Now the correlation matrix stage has stopped working and I don't understand why. My code is identical to yours and other published scripts at this stage, at least as far as I can tell. All of the snp matching between the LD reference and my GWAS was fine, as was the QC of that data. 

The error message (see attached log) is that the index is larger than the maximal size. I can't find anything helpful on google about this. Is this something that needs setting at the start of the script??

Thanks ever so much

Lindsey

Relevant section of script

```r
# Restrict to the variants present in the actual data as well as LDref and the summary stats. 

map_test <- subset(obj.bigsnp$map, select=c(chromosome, physical.pos, allele1, allele2))
colnames(map_test) <- c("chr", "pos", "a0", "a1")
in_test2 <- vctrs::vec_in(df_beta[, c("chr", "pos")], map_test[, c("chr", "pos")])
df_beta <- df_beta[in_test2, ]

# as have less than 2000 individuals in my dataset need to use the reference set provided by Florian Prive for LD
# file now in ldref folder at this location /user/home/eplis/ldref
tmp <- tempfile(tmpdir = "tmp-data")
for (chr in 1:22) {
  
  cat(chr, ".. ", sep = "")
  
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'map_ldref'
  ind.chr2 <-df_beta$'_NUM_ID_'[ind.chr]
  ## indices in 'corr_chr'
  ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))
  
  corr_chr <- readRDS(paste0("BDR/ldref/LD_with_blocks_chr",chr,".rds"))[ind.chr3, ind.chr3]
  
  if (chr == 1) {
    corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
  } else {
    corr$add_columns(corr_chr, nrow(corr))
  }
}
```

[BDR_Rscript_LDblocks.log](https://github.com/privefl/bigsnpr/files/10210840/BDR_Rscript_LDblocks.log)

**Comment by lindseysinclair** [comment]
Thanks Florian. Alas even removing the extra snp_match doesn't change the error message about the index being larger than the maximal size. I've done some line by line testing and the error is in the line

corr0 <- readRDS(paste0("data/corr/chr", chr, ".rds"))[ind.chr3, ind.chr3]

Bizarrely chr1 and chr22 give different size maximal size errors but the chr2 file can be read in without any problems.

Is there something that I need to set about maximum variable size?

Thanks again. Lindsey

**Comment by privefl** [comment]
Try to start again from scratch from the script in the tutorial.

**Comment by privefl** [comment]
Did you find what was not working?

**Comment by lindseysinclair** [comment]
Thanks for asking Florian. I've been all the way through the tutorial again from scratch and it still produced the same error. It's very odd. Bizarrely reading in the LD_with_blocks files chromosome by chromosome seemed to work, so I am working on finding a way of specifying those variables in the loop.
________________________________

**Comment by lindseysinclair** [comment]
So I tried that with chr22 as a test and it still failed at the corr_chr <- corr_chr22[ind.chr3, ind.chr3] stage with the same error.
I'm going to try a different dataset where I have thousands more individuals and I can generate my own LD matrix to see if LDpred2 works on that one. Hopefully it will be much easier.

Thanks again

**Comment by privefl** [comment]
You're using the right LD with the right map, right?
There are fore HM3 and HM3+ variants.

**Comment by lindseysinclair** [comment]
To the best of my knowledge I am. My GWAS summary data that I'm using to test it out was cleaned by me in a different program to only include HM3 SNPs.

**Comment by privefl** [comment]
What I mean is that the `info` provided in the LDpred2 tutorial is for the 1,444,196 HapMap3+ variants.
If you're using the LD matrices corresponding to the 1,054,330 HapMap3 variants instead, you need to use the corresponding `info`.

**Comment by privefl** [comment]
Any update on this?
