### ISSUE TITLE
Extracting genotype data from imputed "bgen files" for certain variants using the 'bigsnpr" R package

### ISSUE THREAD

**Issue by Musty1988** [privefl/bigsnpr#400]
Hi dear 
I'm a regular R user. However, I'm new on dealing with imputed genotype data and bgen files. I have developed some codes to extract the genotype data for an example SNP in chromosome 22 (22_42524947_C_T) but not sure if my method was correct. I extracted the genotype data for this SNP but this was extracted without participants ids. I used the "sample" file to extract ids, then I combined both columns (the genotype column with the ids column). However, not sure if ids are ordered in the same order of the genotype data. Please have a look at my codes below and let me know if I need to correct anything, please help me by providing a correct syntax if there were some errors below:

 

```r
# install.packages("bigsnpr")
library(bigsnpr)

# (1) Read the bgen file of interest and generate the "bgen.bk.rds" file : 

x<- snp_readBGEN(
bgenfiles= "ukb22828_c22_b0_v3.bgen" ,
backingfile = "ukb22828_c22_b0_v3.bgen.bk" ,
list_snp_id = list("22_42524947_C_T"),
ind_row = NULL,
read_as = c("dosage", "random"),
ncores = 8)

# (2) Read the "bgen.bk.rds" file : 

R <- snp_attach(rdsfile = "ukb22828_c22_b0_v3.bgen.bk.rds")

# (3) Extract the genotype data for all participants:

Genotype.data <- as.data.frame(R$genotypes[1:487409, ])

# (4) Extract particpants' Ids :

sample <- bigreadr::fread2("ukb22828_c22_b0_v3.sample")[-1, ]

ID.sex <- sample[,c(2,4)]

# (5) Link genotype data with ids :
Final.Genotype <- cbind(ID.sex, Genotype.data)
```

Please correct me if there is anything wrong.
I highly appreciate your help.

Regards

**Comment by privefl** [comment]
Yes, if you don't provide `ind_row`, it reads all individuals from the BGEN file, and those should be in the same order as in the sample file.

**Comment by Musty1988** [comment]
Many thanks dear Florian. 

So can I understand that the codes provided above are correctly extracting the genotype data for my selected SNPs for the correct participants?

If so, is there a method to extract the genotype data using rsids ? or the readBgen () function can only read the "chr.position.1st allele.2nd allele" format ?

**Comment by Musty1988** [comment]
Brilliant! 

Thank you so much, I really appreciate your swift and informative replies.

The last question please: In case that I need to extract multiple variants in multiple chromosomes, can this be done 
by including multiple variants in "list_snp_id" argument and multiple bgne files for different chromososmes in "bgnefiles" argument ?

Kind Regard

**Comment by privefl** [comment]
Yes, please see the documentation + some example R scripts linked from there.

**Comment by Musty1988** [comment]
Thank you so much , this is really helpful.

I appreciate your valuable help
