### ISSUE TITLE
'bigsnpr' problem in snp_cor(), dependent on version

### ISSUE THREAD

**Issue by NoraEszlari** [privefl/bigsnpr#401]
Dear Florian,

We are using your LDpred2-auto software and 'bigsnpr' package, and like it very much, but now unfortunately facing a problem with that.

On the same Linux computer, we have two different versions of 'bigsnpr' (under different users).
We used our very same datasets and commands under the two different 'bigsnpr' versions.
We found that snp_cor() command did run without any error under bigsnpr v1.9.3, and we could get till "final_beta_auto" calculation and even using it in linear regression models as predictor.
However, under the newer bigsnpr v1.11.6, snp_cor() returned the error message: "NA or NaN values in the resulting correlation matrix." And indeed, calculating an LD matrix from that, resulted in a matrix full of NAs.
What could be the problem?

Thank you a lot in advance!

**Comment by privefl** [comment]
Any update on this?

**Comment by NoraEszlari** [comment]
Oh, sorry, I will definitely give a try to MAF filtering on my test sample,
but unfortunately nowadays I have to keep up with very urgent other tasks
of mine....

Thank you again,
Nóra.

Florian Privé ***@***.***> ezt írta (időpont: 2023. jan. 18.,
Sze, 14:25):

**Comment by privefl** [comment]
Any update on this?
