### ISSUE TITLE
'bigsnpr' problem in snp_ldsc(), dependent on version 1.10.8

### ISSUE THREAD

**Issue by Anewgithubuse** [privefl/bigsnpr#402]
Dear Florian, 
We are using bigsnpr package. I have problem when I  want to use snp_ldsc(ld_score = ld, ld_size = length(ld), chi2 = ((df_beta$beta/df_beta$beta_se)^2), sample_size = df_beta$n_eff) function to estimate h2 from LD Score regression.
It shows error happened in if (max(abs(pred - pred0)) < 1e-06) break:  missing value TRUE/FALSE needed.
I'm not sure what values we still need to addd, or something wrong in this function. 

Thank you for answering.

**Comment by privefl** [comment]
For which version did it work/not work?

Also, be careful that `ld_size` is rarely `length(ld)`, it should corresponds to the initial number of variants used to compute the LD scores.

**Comment by Anewgithubuse** [comment]
in version 1.10.8. 
It looks like there are some NA values in ld scores, is it the result for the error message?
If so, can I just fill the NA values by 0 or some

**Comment by privefl** [comment]
Yes, that's probably the problem.
You should go back and understand why you have NAs, that's not normal.

**Comment by privefl** [comment]
Any update on this?
