### ISSUE TITLE
Question about models

### ISSUE THREAD

**Issue by JuanJoMV** [privefl/bigsnpr#404]
Dear Florian,

Thank you so much for such a really good software. I am trying to calculate polygenic scores for several phenotypes using data from my lab.

I would like to use LDpred2 but I am a little bit confused about the different models. I have read the tutorial and the paper (LDpred2: better, faster, stronger) but I am still confused.

If I am not wrong, with the auto-model a tunning sample is not needed since they are estimated from the data. Would not this produce overfitting? Should this model produce the higher R2 always? What should be the criterion to select one model or the other?

Thank you so much in advance.

**Comment by privefl** [comment]
It won't produce any overfitting because we are not using the predictive accuracy for selecting the best model.

If you have validation data, it is safer to use LDpred2-grid.
If you do not have validation data, you can use LDpred2-auto.

**Comment by JuanJoMV** [comment]
Thank you so much for your prompt response. 

Then, if am not wrong the phenotypic information of the target sample is not used (nor needed) and polygenic scores using all models (i.e. Grid, Infinitesimal and Auto) can be calculated without phenotypic information. Am I wrong? 
And the parameters (h2 and p) are estimated using the genotypic data in the auto-model? In the auto model only information (PGS) for the “estimated” p and h2 value is given right?

With all good wishes. Thank you so much again.

**Comment by privefl** [comment]
No it does not use the phenotypic information, especially if you do not provide it.
This is used only in the validation step (to choose the best model in LDpred2-grid) and in the test step (to evaluate the final model, for all LDpred2 variants).

The auto-model, as the others, only uses summary-level information (GWAS summary statistics + LD ref).

**Comment by JuanJoMV** [comment]
Thank you so much! Really helpful.

With all good wishes
