### ISSUE TITLE
Trouble running LDpred2-auto with a reference panel

### ISSUE THREAD

**Issue by lm380-r** [privefl/bigsnpr#405]
Dear Dr. Prive,

I am able to run LDPRED2 if I use my own data to create the correlation but I need to run it with the LD reference panel you provided (and using hapmap3+ snps). For some reason when I run: 

```r
multi_auto <- snp_ldpred2_auto(
  corr, df_beta, h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 0.5, length.out = 30), ncores = NCORES)
```

It only takes a few seconds to run and if I head(multi_auto) it just says NA for everything (and if I try to plot the chains the plot is also empty). I'm not sure what I'm doing wrong. I took the code to create the correlation matrix with the LD reference panel from your script:

```r
tmp <- tempfile(tmpdir = "tmp-data")

for (chr in 1:22) {

  cat(chr, ".. ", sep = "")

  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'map_ldref'
  ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
  ## indices in 'corr_chr'
  ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))

  corr_chr <- readRDS(paste0("LD_with_blocks_chr", chr, ".rds"))[ind.chr3, ind.chr3]

  if (chr == 1) {
    corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
  } else {
    corr$add_columns(corr_chr, nrow(corr))
  }
}
```

And this does run and finish. I can also calculate the SNP heritability (which is similar to the SNP heritability calculated when I use my own sample). I think the error is in the corr file because the df_beta file looks correct but I'm not sure how to troubleshoot the corr file.

Any help would be greatly appreciated. Thank you in advance.

**Comment by privefl** [comment]
Is the path fully empty, or do you have a few non-missing values at the beginning?

My criterion for detecting strong divergence (and outputting NAs) was probably not optimal, and I actually changed it 3d ago. 
Could you please try the latest GitHub version and tell me if it changes anything?

**Comment by lm380-r** [comment]
Sure! I will uptake the software and see if that helps. I will get back to you. 

The path is fully empty. It takes ~5 mins to run snp_ldpred2_auto (my first clue to something being wrong) and then the output was all NAs

**Comment by privefl** [comment]
In no case should the path (e.g. `$path_h2_est`) should have full missing values.

It means that there is an issue in either `corr` or `df_beta`. You can check 
```r
ld <- bigsnpr:::ld_scores_sfbm(corr, ind_sub = 1:ncol(corr) - 1L,
                               ncores = bigstatsr::nb_cores())
summary(ld)
anyNA(df_beta)
hist(with(df_beta, 
          pchisq((beta / beta_se)^2, df = 1, lower.tail = FALSE)))
```

**Comment by lm380-r** [comment]
Thank you! The updates you provided fixed everything.

**Comment by privefl** [comment]
Could you tell what was the issue?
