### ISSUE TITLE
LDPred2 with custom reference panel

### ISSUE THREAD

**Issue by sourena-s** [privefl/bigsnpr#406]
Hi,
I am planning to use LDpred2 to build PGS in UK Biobank subjects. After variant QC, I have > ~9 million variants. I wonder if I will get any accuracy boost if I build the LD reference from two thousand individuals of the same cohort (instead of filtering to the HapMap plus panel, which leaves ~1.3M after matching with UKB).

So far, I could manage to create LD matrices following the example code for the smaller chromosomes (chr 15-20). However, for those chromosomes with > 300k variants, I receive a memory-related error when the below line tries to generate SFBM matrices:

corr <- as_SFBM(corr0, tmp)

 *** caught segfault ***
address 0x151d19847000, cause 'memory not mapped'

Traceback:
 1: col_count_sym(spmat@p, spmat@i)
 2: .Object$initialize(...)
 3: initialize(value, ...)
 4: initialize(value, ...)
 5: methods::new("SFBM", spmat = spmat, backingfile = backingfile)
 6: as_SFBM(corr0, tmp)

Any advice is greatly appreciated.
Thanks,
Sourena

**Comment by privefl** [comment]
The current version of LDpred is not suitable to use with 9M variants for now, sorry.
Moreover, this does not always lead to better predictive power.
I have discussed this in multiple issues here.

**Comment by sourena-s** [comment]
Thanks for the clarification. A follow-up question: While using the grid model, out of 50 chains, only 18 of them converge and the rest generate nans. The h2_est of the trait is 0.028, and I use the below parameters in the grid search:

> h2_seq <- round(h2_est *  seq_log(0.2,5,5) , 4)
> p_seq <- signif(seq_log(1e-5, 0.9, length. Out = 5), 2)
> params <- expand. Grid(p = p_seq, h2 = h2_seq, sparse = c(FALSE, TRUE))
 
Am I using the correct setting?

Thanks,
Sourena

**Comment by privefl** [comment]
Which `packageVersion("bigsnpr")` do you have?

There is no need to run a huge number of iterations as you did.

**Comment by sourena-s** [comment]
> packageVersion("bigsnpr")
[1] ‘1.12.0’

**Comment by sourena-s** [comment]
Thanks, I updated to 1.12.1 from GitHub. This time I used the following settings:

_set. Seed(1)
n_iter=1000
n_burn=250

multi_auto_no_alpha <- snp_ldpred2_auto(corr, 
burn_in=n_burn, num_iter = n_iter, 
df_beta, verbose=TRUE, sparse=TRUE, h2_init = h2_est, use_MLE=FALSE, allow_jump_sign=FALSE,
                shrink_corr = 0.95, vec_p_init = seq_log(0.01, 1, length. Out =25), ncores = 64, ind.cor = info_snp$`_NUM_ID_`)_

The simulation paths look as attached. Although there was no divergence this time (i.e. no NANs), all 25 chains show the same oscillating h2 paths.

Should I accept these results or continue troubleshooting?
![Gibbs](https://user-images.githubusercontent.com/24783447/217795959-9bfd0a1c-b0b4-4ccc-ad53-02f981b984d6.png)
Sourena

**Comment by privefl** [comment]
No, this path is odd. There is something wrong here.
What LD are you using? Is it from the same population as the summary statistics in `df_beta`?
Did you check `hist(with(df_beta, pchisq((beta / beta_se)^2, df = 1, lower.tail = FALSE)))`?

**Comment by sourena-s** [comment]
That's what I thought. As an additional note, all chains with use_MLE=TRUE had diverged before.
I calculated LD from 2000 random subjects of the target population (white British ancestry from UKB). The GWAS is of a closely related ancestry.

I used the below template code for creating LD matrices:

for (chr in 1:22) {
    ind.chr <- which(as.integer(genotype$map$chromosome) == chr)
print (paste("calculating LD for ", length(ind.chr), "variants in chromosome", chr))
    corr0 <- snp_cor(genotype$genotype, ind.col = ind.chr, ncores = 1, infos.pos = POS2[ind.chr], size= 3/1000)

if (chr == 1) {
        ld <- Matrix::colSums(corr0^2)
        corr <- as_SFBM(corr0, tmp)
    } else {
        ld <- c(ld, Matrix::colSums(corr0^2))
        corr$add_columns(corr0, nrow(corr))
    }
    print (paste("Chromosome", chr,"processed."))
}

And the Chisq histogram looks as below:
![hist](https://user-images.githubusercontent.com/24783447/218072105-fbfcf42b-2f15-4ad0-8262-f4bfc92ded1d.png)

**Comment by privefl** [comment]
The distribution of p-values looks fine.

What are `dim(corr)` and `file.size(corr$backingfile)`?

**Comment by privefl** [comment]
Seems fine as well.

Did you try with another set of GWAS summary statistics? 
Are the ones you're using publicly available? So that I could maybe try them.

BTW, why did you choose not to use the LD provided?

**Comment by sourena-s** [comment]
I am using two GWASs at this moment, this one is publicly available:
https://www.ebi.ac.uk/gwas/studies/GCST90027158
I only keep those variants with the maximum sample size.

Well in the beginning I thought I could make the polygenic model work with 8M variants (how this thread started), so I calculated the LD locally. But now the problem is with convergence.

Thanks for your advice

**Comment by privefl** [comment]
I see, so you're restricting to 1.3M variants with max N. There may be highly correlated and might not cover well the genome.

I think you would benefit from restricting to HM3 or HM3+ variants, and keeping all of those with N > 0.7*max(N).

**Comment by privefl** [comment]
A value of 100 basically means you're using the identity matrix.
So, yes there must be something wrong.
You shouldn't have to use more than 1 (or maybe 3 in extreme cases).

**Comment by privefl** [comment]
Any update on this?

**Comment by sourena-s** [comment]
I made some observation; some context:
So the GWASs from which I am developing PRS are case/control psychiatric and neurological disorder GWASs. But I am optimizing them in my target cohort, not with regard to the same (binary) phenotype, but rather wrt continuous phenotypes derived from brain MRI. These are volumetric measures of the brains (regional volume) and 'integrity' of white-matter tracts. Both of which are well-behaved and quite Gaussian distributed.

In some cases, for example when I use a GWAS of the same MRI phenotypes to develop PRS using lassosum2, the L1/L2 penalties and optimization paths are as expected (i.e., very low L2). For example, this is a PRS generated from cortical surface area GWAS and then optimized in the target population using the same class of structural brain MRI phenotypes:

![lh_surface_area_lassosum_PC198](https://user-images.githubusercontent.com/24783447/224719777-c70cdca0-0ff0-40fc-a934-234daddb716a.png)

However, when I try to generate PRS using e.g. schizophrenia GWAS, I get different optimization paths for structural MRI (regional volume phenotype) versus diffusion MRI (white-matter integrity phenotype):


![SCZ_TBM](https://user-images.githubusercontent.com/24783447/224720260-fe2b334e-c03a-4006-852e-ee35a24218d2.png)


![SCZ_DMRI](https://user-images.githubusercontent.com/24783447/224720294-e6953a33-86fb-4920-9d8d-ceeaa6dd8283.png)


In the above plots, it is apparent that a strong L2 penalty increases the accuracy of the PRS in structural but not diffusion MRI.

As far as I understand, such a strong L2 would 'destroy' the LD contribution in suppressing variants that take part in the PRS model, making the model assume that all variants are independent. So I checked the Pearson correlation of each PRS generated in the grid seach with an orthogonal method (SBayesR), and it turns out that the correlation is very high anyway (r > 0.8-0.9).

![lassosum2_hapmap_corr_sbayesR](https://user-images.githubusercontent.com/24783447/224721149-08b448e8-a429-4b7e-8136-3b1aa699523e.png)

I don't know what the exact reason is, but it seems that increasing L2 in some cases gives an extra boost of accuracy in generating a PRS from a neuropsychiatric case/control GWAS in explaining phenotypes derived from quantitative brain MRI.

Extra notes: calculating LD from 2000 subjects of the target population vs the off-the-shelf reference panels doesn't affect the accuracy at all, as doesn't the use of the top 3 million significant variants from the GWAS instead of the HapMap3+ variants (I found the latter very interesting).

**Comment by privefl** [comment]
As far as I understand, using a very strong L2 reg corresponds to using the identity matrix as LD ref, which corresponds to just using (some scaled version) of the GWAS effect sizes directly.
This is clumping and thresholding without clumping nor thresholding.. i.e. simply using the GWAS effect sizes as predictive effects without any filtering. 
That should not be the optimal solution.

But because you're trying to predict something else, I don't know..

**Comment by privefl** [comment]
Are your questions answered, or do you still have a few more?

**Comment by sourena-s** [comment]
Following this conversation, I think I better understand how the software works, but I need to explore this particular use case and make sense of the results in the coming weeks. Thanks for following up.
