### ISSUE TITLE
Using own correlation matrix of LD values.

### ISSUE THREAD

**Issue by boseb** [privefl/bigsnpr#407]
Hi Florian,
I am using a correlation matrix of LD values (dsCMatrix) made from our own study genotype, rather than using reference LD in the below function:
snp_ldsc2(My.Corr, df_beta, blocks = LDSC_blocks, intercept = NULL, ncores = ncores)
Could you please confirm if I can do this? 

Thanks,
Bose

**Comment by privefl** [comment]
It will compute the LD scores from your correlation matrix. If you have enough variants, this should be fine.

**Comment by boseb** [comment]
Great, thanks for confirming.
