### ISSUE TITLE
Error in { : task 1 failed - "L-BFGS-B needs finite values of 'fn'"

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [privefl/bigsnpr#408]
I'm getting the following error, when I run:

Error: Error in { : task 1 failed - "L-BFGS-B needs finite values of 'fn'"

# Get adjusted beta from the auto model
```
multi_auto <- snp_ldpred2_auto(
  corr,
  df_beta,
  h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
  ncores = NCORES
)
```

Can you please suggest whats the issue?

**Comment by privefl** [comment]
This is discussed in https://github.com/privefl/bigsnpr/issues/389.

Did you try the latest GitHub version of the package?

**Comment by Mahantesh-Biradar** [comment]
I'm using [1] ‘1.11.6’. Whats the best way to install latest version?

I did try reinstalling, but looks like I still have the older version. Thanks

**Comment by Mahantesh-Biradar** [comment]
I got the latest version (1.12.1 and trying the following again):

multi_auto <- snp_ldpred2_auto(
  corr,
  df_beta,
  h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
  ncores = NCORES
)

**Comment by Mahantesh-Biradar** [comment]
I tried the following scripts, but looks like I have a new error message:

```
multi_auto <- snp_ldpred2_auto(
corr,
df_beta,
h2_init = h2_est,
vec_p_init = seq_log(1e-4, 0.9, length.out = NCORES),
ncores = NCORES
)
```

AND

```
set.seed(1)  # to get the same result every time
# takes less than 2 min with 4 cores
multi_auto <- snp_ldpred2_auto(
  corr, df_beta, h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 0.2, length.out = 30), ncores = NCORES,
  # use_MLE = FALSE,  # uncomment if you have convergence issues (need v1.11.9)
  allow_jump_sign = FALSE, shrink_corr = 0.95)
str(multi_auto, max.level = 1)
```

Error: Error in { : task 1 failed - "Expecting a single value: [extent=1123223]."

**Comment by privefl** [comment]
I've never encounter this issue before.
Please try with `vec_p_init = 0.01, ncores = 1, verbose = TRUE`.

**Comment by privefl** [comment]
Yes, this is what happened before. I think some effect sizes blow up in magnitude. But that should be detected and LDpred2-auto should stop and return missing values in that case (not that it will solve your issue..).

- So, are you sure you have the latest version of the package?
- What do you use for the LD matrix?

Otherwise, if you do not care about the `alpha` estimates, you can always use `use_MLE = FALSE`, which should behave as previous versions of LDpred2-auto.

**Comment by Mahantesh-Biradar** [comment]
Let me try this. 

I'm using 1.12.1 version

I'm using the target data to compute LD matrix.

**Comment by Mahantesh-Biradar** [comment]
`#Auto model

```
set.seed(1)  # to get the same result every time
# takes less than 2 min with 4 cores
multi_auto <- snp_ldpred2_auto(
  corr, df_beta, h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 0.2, length.out = 30), ncores = NCORES,
  use_MLE = FALSE,  # uncomment if you have convergence issues (need v1.11.9)
  allow_jump_sign = FALSE, shrink_corr = 0.95)
str(multi_auto, max.level = 1)`

```

Error in snp_ldpred2_auto(corr, df_beta, h2_init = h2_est, vec_p_init = seq_log(1e-04,  : 
  unused argument (use_MLE = FALSE)
  
  I'm wondering if I'm using use_MLE = FALSE option in the right place?

**Comment by privefl** [comment]
Are you sure you have the latest version? 
`packageVersion("bigsnpr")`

**Comment by Mahantesh-Biradar** [comment]
> packageVersion("bigsnpr")
[1] ‘1.12.1’

**Comment by privefl** [comment]
With v1.12.1, I've uncommented this line as you did, and was able to run the tutorial without any problem.
So, I have no idea why you get this error.
You may need to restart all your R sessions so that the updated package is used?
How did you install the package? Using `remotes::install_github("privefl/bigsnpr")`?

**Comment by privefl** [comment]
Any update on this?

**Comment by Mahantesh-Biradar** [comment]
Hi, thanks. I was able to run the script after restarting the R session.
