### ISSUE TITLE
Suggested model with no individual-level training data

### ISSUE THREAD

**Issue by Fiwx** [privefl/bigsnpr#410]
Hi Florian,

What is the best LDpred2 model for generating a PRS using only sumstats and a reference panel (i.e., no individual-level training/validation data)? I'd like to construct a PRS without any individual-level data, and then test it using individual-level data; I assume LDpred2-auto should be of use. Also, would you expect this method to still have decent accuracy if already thresholded summary statistics (500-20,000 SNPs) are being used? Thank you!

**Comment by privefl** [comment]
Any update on this?

**Comment by Fiwx** [comment]
Thank you! That is very helpful information.
