### ISSUE TITLE
Delete backing files and folders?

### ISSUE THREAD

**Issue by Jocelyn37** [privefl/bigsnpr#412]
Hi Florian,
 
after reading the bgen files "snp_readBGEN" function, there are some backing files generated in my path folder, is there a way to detach these files and delete these folders without restart the R session?  (I am using parallel computing and need to delete these folders automatically using some deleting functions for example "unlink")

Thank you!

Best,
Joyce

**Comment by Jocelyn37** [comment]
gc() function helped me to delete the folders thanks!

**Comment by privefl** [comment]
You can use e.g. https://github.com/privefl/freq-ancestry/blob/f5b03a2d639eb8244889f5f32a4c8fb2e1fcd2e9/code/3-prepare-ukbb-freq.R#L43.

If you're on Windows, you need to `rm()` the object, then use `gc()`, then you can delete the files.
