### ISSUE TITLE
OpenMP flag is not passed

### ISSUE THREAD

**Issue by barracuda156** [privefl/bigsnpr#418]
Same issue as here: https://github.com/privefl/bigstatsr/issues/162

Makevars has `$(SHLIB_OPENMP_CXXFLAGS)`, but it does nothing, apparently because there is no configure to determine correct flags. To make it work, there should be a test for support for OpenMP, conditional on compiler used, and then GCC needs `-fopenmp`, while Clang also needs `-lomp` in addition to the former (user may have to specify then the location of `libomp`, if Clang is used, since different package managers install it in different locations).

**Comment by privefl** [comment]
Let's use only one issue, discuss in the other one.
