### ISSUE TITLE
FBM. code256

### ISSUE THREAD

**Issue by gulinlin** [privefl/bigsnpr#42]
Excuse me,How to convert genotype files into FBM. code256 format?
How to determine the code file？

**Comment by privefl** [comment]
What type of genotype file?
You can read from bed/bim/fam (PLINK binary format) or BGEN files (UK Biobank format).
Have a look at the I/O section of https://privefl.github.io/bigsnpr/reference/index.html.

**Comment by gulinlin** [comment]
Hello, my genotype file is a big matrix.

**Comment by privefl** [comment]
Can you be more precise?
Can you give some minimal reproducible example?

If you have some filebacked big matrix, then you might want to look at the corresponding vignette (about bigstatsr and bigmemory) on the bigstatsr website.

**Comment by gulinlin** [comment]
Hello, thank you very much for your patient answer. I have solved this problem. Thank you again.

**Comment by privefl** [comment]
Don't hesitate to state it and put your solution too, if it can be of any help for others.
