### ISSUE TITLE
Inflated Q-Q

### ISSUE THREAD

**Issue by boseb** [privefl/bigsnpr#421]
Hi Florian,
I am using the function pkg.paper.PRS::get_pheno to generate binary phenotypes. If I select causal variants to be spread across the multiple chromosomes (5 chromosomes) with default parameters, the q-q plot from logistic regression (from PLINK) gets highly inflated. Do you have any recommendations about how to use the parameters of this function to control this issue?

Thanks,
Bose

**Comment by privefl** [comment]
Any update on this?
