### ISSUE TITLE
  error from : corr$add_columns(corr0, nrow(corr))

### ISSUE THREAD

**Issue by SoleilChenxu** [privefl/bigsnpr#424]
Hi Privefl, i got the error when calculating LD matrix about no function in  ***_corr$add_columns(corr0, nrow(corr))_***. 
I was confusing if i could do the same for chr 2 to 22 as chr1 instead of using _**if...else**_ function. That is, for all chromosomes,  _**ld <- Matrix::colSums(corr0^2)
        corr <- as_SFBM(corr0, tmp)**_

Thanks in advance for your anwser.

**Comment by privefl** [comment]
You need to create `corr` with `corr <- as_SFBM(corr0, tmp)` for the first chromosome, and then you just add more data to it for the other chromosomes.

Is this your question?

**Comment by SoleilChenxu** [comment]
Oh yes that makes sense. Now I understand, because I only take chromosome 21 and 22 for example because of the partition limit.  Is it possible to run the LD_matrix by choromosome and in parallel?  Thanks!

**Comment by privefl** [comment]
What do you mean exactly by "run the LD_matrix"?

**Comment by SoleilChenxu** [comment]
I mean the step to calculate the correlations between variants. In the tutorial this step is processed from chromosome 1 to chromosome 22 right?
 _for (chr in 1:22) {
  
  # print(chr)
  
  ## indices in 'df_beta'
  ind.chr <- which(df_beta$chr == chr)
  ## indices in 'G'
  ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
  
  corr0 <- snp_cor(G, ind.col = ind.chr2, size = 3 / 1000,
                   infos.pos = POS2[ind.chr2], ncores = NCORES)
  
  if (chr == 1) {
    ld <- Matrix::colSums(corr0^2)
    corr <- as_SFBM(corr0, tmp, compact = TRUE)
  } else {
    ld <- c(ld, Matrix::colSums(corr0^2))
    corr$add_columns(corr0, nrow(corr))
  }
}_
My question is whether I could claculate the correlation several times and merge the data later.

**Comment by privefl** [comment]
Yes, you could compute `corr0` with `snp_corr()` for each chromosome separately (or use the ones precomputed). 
And then merge all those with `$add_columns`.
It's what I actually do in most of my papers.

**Comment by SoleilChenxu** [comment]
Okay this helps. Thank you very much!
