### ISSUE TITLE
LDSC heritability

### ISSUE THREAD

**Issue by lingjoyo** [privefl/bigsnpr#425]
Hallo Florian

I'm trying to calculate the heritability of coronary artery disease (CAD) which is reported to be around 40%. I used the GWAS data which was also used in your paper. But the heritability calculated using snp_ldsc() is only ~9%. Do you think it's reasonable?

**Comment by privefl** [comment]
It depends.
How many variants do you use?
Do you talk about the same kind of heritability (full additive vs SNP heritability)?
Are these estimates on the same scale (observed vs liability scale)?

**Comment by lingjoyo** [comment]
Hi Florian,

Thanks for your instant reply.

I used 1.2 million SNPs that existed in HapMap3+.
Then I randomly select 10000 samples from UK Biobank to calculate the LD correlation matrix.

What do the full additive and SNP heritability mean respectively?

________________________________
发件人: Florian Privé ***@***.***>
发送时间: 2023年5月11日 1:13
收件人: privefl/bigsnpr ***@***.***>
抄送: lingjoyo ***@***.***>; Author ***@***.***>
主题: Re: [privefl/bigsnpr] LDSC heritability (Issue #425)


It depends.
How many variants do you use?
Do you talk about the same kind of heritability (full additive vs SNP heritability)?
Are these estimates on the same scale (observed vs liability scale)?

―

**Comment by privefl** [comment]
The numbers you used are fine.
The example data is simulated.

Have a look at the literature for the difference between the SNP heritability and the narrow-sense (additive) heritability. Or maybe at this lecture: https://www.youtube.com/watch?v=kG-Zn6Wq6Ac.

**Comment by privefl** [comment]
Any update on this?
