### ISSUE TITLE
NA in LDSC

### ISSUE THREAD

**Issue by SoleilChenxu** [privefl/bigsnpr#427]
Hi, I was running ldsc based your tutorial, the code is 
```
ldsc<- snp_ldsc(ld, length(ld), chi2 = (df_beta$beta / df_beta$beta_se)^2,
                                sample_size = df_beta$n_eff, blocks = NULL)
```
I received the error of "Error in if (max(abs(pred - pred0)) < 1e-06) break : 
  missing value where TRUE/FALSE needed"

Is there anything I could do to fix?

**Comment by privefl** [comment]
Any update on this?

**Comment by SoleilChenxu** [comment]
> Any update on this?

Thanks for following up. I am checking today. Will keep you updated!

**Comment by privefl** [comment]
Any update on this?
