### ISSUE TITLE
Re-use .sbk file

### ISSUE THREAD

**Issue by fmorgante** [privefl/bigsnpr#428]
Hi Florian, is there a way to re-use a previously created .sbk file?

I am running some simulations where the LD matrix (per-chromosome) is the same but the summary stats are different for each replicate. So, ideally I would want to create the genome-wide LD matrix in SFBM format once, save the .sbk file and use it for all the replicates in my simulations.

**Comment by privefl** [comment]
You can use `$save()`.

**Comment by fmorgante** [comment]
Once saved, how do I use it in `snp_ldpred2` or `lassosum2` in a different session?

**Comment by privefl** [comment]
This is just an rds file, then you can use readRDS.

Sometimes instead I use runonce::save_run() to store it when made the first time, and reread the next time.

**Comment by fmorgante** [comment]
Got it, thank you!

**Comment by lukepilling** [comment]
Hi Florian. I tried using `readRDS("file35f9bf249f5b0f.sbk")` but get an "unknown unput format" error. Could you advise? Thanks
