### ISSUE TITLE
Heritability

### ISSUE THREAD

**Issue by JuanJoMV** [privefl/bigsnpr#429]
Dear Florian,

Thank you so much for your really good software.

I would like to know a little bit more about how LDpred2 estimates heritability. I am not sure if it estimates heritability from the target sample to use it as a parameter or h2 is estimated from the base sample using summary statistics?
And how LDpred2 calculates h2? Using LDscore regression, right?

Thank you so much in advance.

**Comment by privefl** [comment]
- LDpred2-grid uses the LD score regression estimate and tests different values around this estimate.
- LDpred2-auto estimates the heritability from the GWAS sumstats, and only uses the LDSc estimate as a starting value in the Gibbs sampler.

**Comment by JuanJoMV** [comment]
Thank you so much for your prompt response.

But this value is always the h2 of the base sample using summary statistics (from the reference GWAS), right? So, the heritability of the target sample is not used in any of the models.

Thank you so much.

**Comment by privefl** [comment]
No, the target sample is not used.

**Comment by JuanJoMV** [comment]
Thank you so much!
