### ISSUE TITLE
`ncores` option is ignored in `snp_fastImpute`

### ISSUE THREAD

**Issue by domiden** [privefl/bigsnpr#430]
First of all, thanks a lot for your hard work!

By implementing the `snp_fastImpute` function in my workflow, I have noticed that the option dealing with number of cores/threads/clusters to be used (`ncores`) seems ignored. In this workflow, I implemented two backends (`arrow` and `data.table` package) for preparing data wrangling. If I use the arrow backend, I have just enough RAM, but it takes longer to process data. If I use the data.table backend, which is faster, the RAM is running out and `xgboost` error out. I intentionally use therefore just half of the threads available on my machine due to the limit in availability of RAM. 

I wonder if this might be a `bigsnpr` or `xgboost` issue. 

As a side note, QC has been done. Everything worked well except for the `ncores` issue.

Code snippet I have used:
```r
fbm_c256_imputed <-
   bigsnpr::snp_fastImpute(
      fbm_c256, # bigsnpr::CODE_012 has been used for coding
      infos.chr = .chrom_loc, # integer vector
      size = 100,
      seed = .seed, # integer sclar
      ncores = .n_cluster # integer sclar
   )
fbm_c256$code256 <- bigsnpr::CODE_IMPUTE_PRED
```

**Comment by privefl** [comment]
What does make you say that the parallelization is ignored exactly?

What is the problem exactly?

**Comment by domiden** [comment]
If select any number of threads, e.g., `3L`, it will be ignored and still use all available threads minus one. I suppose that each thread use additional RAM, so, it might lead to an memory overflow, which error out and abort the calculation. Make that sense?

**Comment by privefl** [comment]
This definitely should not happen.

There are two parts that are parallelized:
- computing of variant correlations to know which nearby variants can be used for imputation,
- the xgboost models for imputation.    

Both have the `ncores` parameter passed and should work properly. Moreover, I don't think they should use much more memory when parallelizing.

Are you absolutely sure of the value you pass for `.n_cluster`? Can you try setting to `1` instead?

Also, I did not get why you were talking about two different backends (`arrow` and `data.table` packages).

**Comment by domiden** [comment]
Thanks for coming back so quick.

I've tried one thread, but it's still ignoring the settings and using all the available threads minus one (max – 1). I also investigated the memory allocation before and after the use of `snp_fastImpute`, which was 1.2 and 10.6 GB, respectively. The imputation process causes more than 9 GB of memory allocation. In this case, I use about 12.5k SNP in around 960 OTUs, with < 5% missing value per SNP.

Just ignore the backends, I thought, they might be helpful for the context.

**Comment by privefl** [comment]
Do you know how to use debugging?
E.g. with debugonce() to run the code inside functions line by line.
Would be nice to know which line uses parallelism where it shouldn't.

**Comment by privefl** [comment]
The only part I can think of is when using predict(), but it should be so fast compared to the rest, that you should not even see it.

**Comment by privefl** [comment]
Any update on this?

**Comment by domiden** [comment]
@privefl: Sorry, I haven't had time to investigate it further. I'm going to try to squeeze it in.

**Comment by privefl** [comment]
Any update on this?
