### ISSUE TITLE
LD-pred 2 issue, All NAs in the final PRS file

### ISSUE THREAD

**Issue by ShoaibBME** [privefl/bigsnpr#432]
Hi Florian,
I am using LD pred 2 and used this tutorial, https://choishingwan.github.io/PRS-Tutorial/ldpred/
Actually, I have run the entire code with no errors but at the last step, where it is required to select one model. I am getting all NAs in the final PRS (pred_file) file, Same with other models, can you mention how to fix this?  I am getting values in the previous R object beta_inf. Thanks @privefl.
if(is.null(obj.bigSNP)){
    obj.bigSNP <- snp_attach("EUR.QC.rds")
}
genotype <- obj.bigSNP$genotypes
# calculate PRS for all samples
ind.test <- 1:nrow(genotype)
pred_inf <- big_prodVec(    genotype,
                            beta_inf,
                            ind.row = ind.test,
                            ind.col = info_snp$`_NUM_ID_`)

**Comment by privefl** [comment]
Are you now able to run LDpred2 successfully?

**Comment by ShoaibBME** [comment]
yes, there was  missing genotype in my 'genotype file'. I removed all SNPs with missing genotypes. There are less SNPs now with complete genotype data but I think thats how LDpred work, correct me if I am wrong, thanks for making this useful PRS tool.

**Comment by privefl** [comment]
- If there are not many missing values, you could impute them quickly with `snp_fastImputeSimple()`.
- The better way is to use already imputed data (dosages) using an external reference imputation panel.
- Also, you can use PLINK to compute the final PGS as the product of the genotypes x effects, which handles missing values (I still need to implement this in bigsnpr).

**Comment by privefl** [comment]
Any update on this?
