### ISSUE TITLE
MCMCchain not converging

### ISSUE THREAD

**Issue by xuxwen** [privefl/bigsnpr#433]
Hi Florian!
I was surprised to find that MCMC chains converged strangely when I used LD_pred2_auto for PRS.
Our code is set up as follows
“multi_auto <- try(snp_ldpred2_auto(
    corr, df_beta, h2_init = h2_est,
    vec_p_init = seq_log(1e-4, 0.2, length.out = 30), ncores = NCORES,
    use_MLE = FALSE,  # uncomment if you have convergence issues (need v1.11.9)
    allow_jump_sign = FALSE, shrink_corr = 0.95,num_iter = 500),silent=T)”
First we used pQTL data containing three hundred and fifty thousand SNPs，and the number of iterations was chosen to be 1000.
The MCMC heritability convergence plots are shown below respectively
<img width="521" alt="d390808a5bccf7108ee2301ee26f99c" src="https://github.com/privefl/bigsnpr/assets/129174614/733f3bf8-32d6-474e-ac06-633dacd8caeb">，This is the convergence plot of the heritability of our randomly selected thirtieth chain。
<img width="1105" alt="178831aa461f43a30af77d3ba014c08" src="https://github.com/privefl/bigsnpr/assets/129174614/0b2ee2f9-e57a-44ef-9a17-da9775f31d63">，This is a randomly selected five MCMC chain heritability convergence plot, and was surprised to find that basically all chains are so strange.

Second， we used mQTL data containing 2,000,000 SNPs， and the number of iterations was also chosen to be 1000.
![d6d4990c38b0f28f3b715efccde6a5d](https://github.com/privefl/bigsnpr/assets/129174614/e2729c40-a317-4a47-8662-58f3991d3613)
It is difficult to converge the same for a randomly selected number of chains.
How to solve this situation?

**Comment by privefl** [comment]
Are there very large effects in your sumstats?
`r2 <- with(sumstats, beta^2 / (beta^2 + n_eff * beta_se^2))`

And what is the sample size associated with the sumstats?

**Comment by xuxwen** [comment]
The number of proteins is 4907, an Icelandic database of data QTL;
The number of metabolites is more than four hundred, less than five hundred.

**Comment by xuxwen** [comment]
The protein QTL data is a summary of the whole set of data, the total number of SNPs is eight million, but we excluded the SNPs with P<0.05, and the final number of SNPs for analysis is about 500,000.

**Comment by xuxwen** [comment]
We wonder if the number of SNPs is so large that the Markov chain is difficult to converge, and we set the number of iterations to converge to 1000. The reason for this suspicion is that our methylation and expression QTL data have an average number of several hundred methylation SNPs each and only over 10,000 expressions, so we are now testing increasing the number of iterations to see if this will alleviate the situation.

**Comment by xuxwen** [comment]
The protein QTL data is a summary of the whole set of data, the total number of SNPs is eight million, but we excluded the SNPs with P>0.05, and the final number of SNPs for analysis is about 500,000.

**Comment by privefl** [comment]
What is the sample size (number of individuals)?

Are there large effects?

You should not filter small p-values, since this will lead to overestimating effect sizes (due to winner's curse). Or at least you need to use `snp_thr_correct()`.

**Comment by xuxwen** [comment]
The individual protein is about thirty-five thousand, we are now trying Is it because the number of iterations is too small, whether there is a larger amount of effect, followed by the next I will check, thank you for your answer, what progress will be promptly replied to you!

**Comment by privefl** [comment]
Any update on this?
