### ISSUE TITLE
Clumping without genotype data ?

### ISSUE THREAD

**Issue by eliorzou** [privefl/bigsnpr#436]
Hi Florian, 

I am working with GWAS from Finngen biobank and I would like to do clumping to prioritize SNP from my analysis. 
I am wondering if it is possible to do clumping with a .bed file from the summary statistics and LD panel only. I do not have genotype data and PLINK files for my analysis (I just have LD panels available on Gnomad).
From what I can see on the tutorial of bigsnpR, it seems that I need the genotypes and summary statistics, but maybe you have know another way to do it ? 

Thanks a lot for your answer, 
Best regards, 

Eulalie

**Comment by eliorzou** [comment]
Hi Florian ! 
Thank you for your answer and sorry for the delay, 
I read the issue #316, it indeed answer partially my question. If I understand correctly you do not recommend using only LD matrix (and it's not implemented in this method). 
I have LD panel generated by LDSC but I can also get LD scores Hail Table. I'm not very familiar with all these formats. 

My issue is that I understand that the genetic architecture of Finnish individuals is quite different from other europeans. Therefore, I guess it would be problematic to use european reference panels and genotypes available for clumping on this data. What do you think ?

**Comment by privefl** [comment]
For fancy methods like LDpred2 that use LD to recover joint effects from marginal effects, it is best to get an LD reference as close as possible from the GWAS pop. But it also works fairly well with one from e.g. UK ancestry (cf. https://doi.org/10.1016/j.xhgg.2022.100136).

For clumping, I think that matters less. What is the purpose of clumping you have here?

Alternatively, you could identify a few Finnish-like individuals within the UKBB as I did, and perform clumping from their genetic data.

**Comment by privefl** [comment]
If you're happy with this and have no further question on this, you can close the issue.
