### ISSUE TITLE
NAs with LDPred2 using UKBB and Finngen sumstats

### ISSUE THREAD

**Issue by Herest** [privefl/bigsnpr#437]
Hi Florian,

I'm using LDPred2 for training  a T2D model using the UK Bio bank data and summary statistics downloaded from Finngen. I followed the steps written in the most recent tutorial from your [GitHub](https://privefl.github.io/bigsnpr/articles/LDpred2.html) and for the QC of the summary statistics I followed the script you have in another [repo](https://github.com/privefl/paper-misspec/blob/main/code/prepare-sumstats-finngen/T2D.R), however I'm getting all NAs in the final model using the _snp_ldpred2_auto_. 

Do you have idea what am I doing wrong? I'm also getting a warning when calculating the LD correlation matrix `Warning message:
NA or NaN values in the resulting correlation matrix.` 
that was not appearing in other tests that I preformed before doing this training. Thanks @privefl

**Comment by privefl** [comment]
Yeah, you can't have these `NaN` values in the correlation matrix.
It usually means you have variants with no variation at all (MAF = 0); you should remove those (cf. similar issues).

**Comment by privefl** [comment]
Please have a look at `Matrix::which(is.nan(corr0), arr.ind = TRUE)`.
And report the MAF (e.g. with `snp_MAF()` for the variant(s) having all NaNs.

**Comment by Herest** [comment]
Hi again Florian, I fixed the warning about the NAs in the correlation matrix, however, I'm still unable to train the model with auto mode. I keep getting only NAs

**Comment by privefl** [comment]
Could you say what was the issue, for the record, for people having a similar issue in the future.

For the problem of getting NAs with LDpred2-auto, this has been discussed in other issues here; have you looked at those?
Please comment there.

**Comment by Herest** [comment]
The issue was that there were many SNP with MAF == 0 and missing MAF (i.e. NA). I filtered them using `Matrix::which(is.nan(corr0), arr.ind = TRUE)` along with `snp_MAF()`.

I also fixed the other issue with the `snp_ldpred2_auto` function [using the solution in this comment](https://github.com/privefl/bigsnpr/issues/416#issuecomment-1487155785).

Thanks a lot for your help
