### ISSUE TITLE
Where to get SNP IDs corresponding to LDpred2 effect sizes?

### ISSUE THREAD

**Issue by isobel16** [privefl/bigsnpr#438]
Hi Florian,

I am hoping to validate the PRS I have built using LDpred2 in an external population. I can't quite work out how the beta_grid is matched to the SNPs to do this. I essentially need a data frame of the SNP ID and the adjusted betas from LDpred2. Do you have suggestions on the best way to do this? Thanks.

**Comment by privefl** [comment]
Don't you have a SNP ID in either one of the data frames you pass to `snp_match()`?
Without some code, it would be hard to help you more with this.

PS: the correct name of the method is LDpred2, not LDPred2

**Comment by privefl** [comment]
Any update on this?

**Comment by isobel16** [comment]
Hi Florian, 

Apologies for the late response I was distracted by another analysis. I am going to give this another go over the weekend. So the SNP IDs and the updated betas are in separate data frames and just require a merge to be matched and implemented to calculate PRS for an external population?

**Comment by privefl** [comment]
They should be in the same order, so just something like `cbind()` should work.

**Comment by privefl** [comment]
Any update on this?

**Comment by isobel16** [comment]
I have figured out that binding df_beta to beta_grid gives the updated effect sizes, thank you!
