### ISSUE TITLE
Memory size issues in snp_cor()

### ISSUE THREAD

**Issue by kkleinoros** [privefl/bigsnpr#439]
I am trying to run ldpred2 with  sample size of 7304
and 1422515 snps.  
I am calling snp_cor with nthreads=12.   
Although I am running snp_cor function on one chromosome at a time, I am still running out of memory. 
Any solutions?

**Comment by privefl** [comment]
So, the issue is with `snp_cor()`, not LDpred2, right?

How many variants on chromosome 1? Did you try chromosome 22?
Which positions are you using? And what window size?

**Comment by kkleinoros** [comment]
correct.
115717 variants on chromosome 1.
window size = 3 / 1000 as in the tutorial.
chr22 does work.

**Comment by privefl** [comment]
How much time for chr22?
How much memory for chr1?

**Comment by privefl** [comment]
Please verify the vector of positions you're giving to that function.

**Comment by kkleinoros** [comment]
chr 22  20621 snps
system.time(corr0 <- snp_cor(G, ind.col = ind.chr2, size = 3 / 1000,infos.pos = POS2[ind.chr2], 
ncores = 12))
    user   system  elapsed
2819.791    3.573  260.073

**Comment by privefl** [comment]
Did you check `POS2`?

**Comment by kkleinoros** [comment]
POS2 is 0 for all elements.

**Comment by kkleinoros** [comment]
I went back to your tutorial I see I missed
# To convert physical positions (in bp) to genetic positions (in cM), use
# POS2 <- snp_asGeneticPos(CHR, POS, dir = "tmp-data", ncores = NCORES)

**Comment by privefl** [comment]
Yeah, this explains it.

So, this is working now?

**Comment by kkleinoros** [comment]
yes thank you
