### ISSUE TITLE
Implement LDSc regression

### ISSUE THREAD

**Issue by privefl** [privefl/bigsnpr#44]

**Comment by privefl** [comment]
This is implemented in `snp_ldsc()` and `snp_ldsc2()` starting with version 1.4.

**Comment by cqgd** [comment]
Hi Florian,

Hope you're well.

Just curious if you had considered implementing bivariate LDSC, to estimate genetic correlations from two sets of chi-squared statistics? I think [the current implementation allows one set](https://github.com/privefl/bigsnpr/blob/master/R/ldsc.R#L38).

If it's already in there, apologies for missing it! Please do point me in the right direction, in that case.

Best wishes,

Chris

**Comment by privefl** [comment]
I've considered it, but I've never spent enough time on this to provide a similar implementation for genetic correlation as ldsc in R.

When I wanted to do this in R, I've looked at package {GenomicSEM} which does implement it (or at least something similar).
There is a function `ldsc()` that should give you the genetic correlation for many traits (when using `stand = TRUE`).

If someone wants to provide an implementation in {bigsnpr}, I'll be happy to review the code.
