### ISSUE TITLE
NA when running snp_ldpred2_grid

### ISSUE THREAD

**Issue by kkleinoros** [privefl/bigsnpr#440]
What causes the output of snp_ldpred2_grid to contain NAs?

**Comment by privefl** [comment]
You'll find the answer in the documentation, as well as in the tutorial.

**Comment by kkleinoros** [comment]
"Missing values are returned when strong divergence is detected. "
Some of the parameters do converge, can I keep only these and continue the tutorial?

**Comment by privefl** [comment]
Yes, just consider these have no predictive value, and find the best one in some validation set.
