### ISSUE TITLE
LDPred2 PRS for one outcome?

### ISSUE THREAD

**Issue by JNajar** [privefl/bigsnpr#441]
Hi!

I am pretty new to coding and especially computing PRSs using other methods than clumping/thresholding. 

I have successfully managed to create several PRSs using LDPred2 method. However, i have a question regarding the step where the null R2 is calculated. In that step a regression is done, where an outcome variable is included (outcome of which you are going to analyze, right?)... Is it so that you need to calculate a PRS for a single outcome everytime? not like other PRSs that you have for all individuals in the dataset? Because in my case i only get values for the PRS for those with either 1 or 0 in my binary trait. Am I understanding correcly or misunderstanding something? Is there a way to calculate PRS for say music, without having the outcome of choice?

all the best, 
Jenna

**Comment by privefl** [comment]
Any update on this?

**Comment by JNajar** [comment]
Hi!

Sorry im so new to github! 😊

Hope I did it correctly this time!
Thank you,
Jenna

**Comment by JNajar** [comment]
After getting your response i realized that i didnt need to conduct the regressions in order to compute the PRSs! So it worked :)
