### ISSUE TITLE
Question about LDpred2 Vignettes

### ISSUE THREAD

**Issue by hrafnfaedhir** [privefl/bigsnpr#442]
Hello,
I'm in the process of trying to use LDpred2 to calculate scores.  I worked with LDpred1 on the same datasets, but I am a little confused by the files used in your vignettes.

Is obj.bigSNP the LD Reference panel or the Validation dataset genotypes?  It appears that the G matrix extracted from obj,bigSNP is used to estimate the correlation between SNPs and also during the construction of the PRS scores.  
```
corr0 <- snp_cor(G, ind.col = ind.chr2, ncores = NCORES, infos.pos = POS2[ind.chr2], size = 3 / 1000)
corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"), tmp)
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
pred_grid <- big_prodMat(G, beta_grid, ind.col = ind.chr2)
params$score <- big_univLogReg(as_FBM(pred_grid[ind.val, ]), y[ind.val])$score
```
In LDpred1, these datasets were distinct and it was recommended that the LD Reference panel should be the same that was used to create the summary statistics.  I do see that there is a step to randomly select a subset of the G to estimate LD and the rest is used as the test set to validate the model.
```
set.seed(1)
ind.val <- sample(nrow(G), 400)
ind.test <- setdiff(rows_along(G), ind.val)
```
However, I don't see the ind.val index being called when calculating the corr0 or corr matrices.  Am I misunderstanding the logical flow of the script?

**Comment by privefl** [comment]
It seems I didn't see that issue since it was not posted in the right repo, sorry about that.

What is the status?
