### ISSUE TITLE
`Integer overflow` warning in `snp_cor` function

### ISSUE THREAD

**Issue by filosi** [privefl/bigsnpr#446]
When computing a large LD_matrix I got into the warning message:
```
Warning message:
In (function (Gna, ind.row = rows_along(Gna), ind.col = cols_along(Gna),  :
integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
```
producing an invalid `dsCmatrix` with `NA` values in the `p` slots. 
This is produced by the `snp_cor` function, and I believe the stacktrace comes from the `bigsnpr/R/corr.R:46` line of code.

In my case it happened with matrix with more than 200000 rows and columns.
After QC on the genotype data and gwas data the matching variants are > 6ml, and that's why a huge LD matrix should be computed.

**Comment by privefl** [comment]
It means there are too many non-zero correlations being stored.
Are you using a 3cM window?

**Comment by filosi** [comment]
Yes indeed

**Comment by privefl** [comment]
And you have this issue with 200,000 variants?

**Comment by filosi** [comment]
With all the chromosomes with > 200k variants, yes.

**Comment by privefl** [comment]
Yes, you cannot use too many variants (e.g. 400K per chromosome); this would give you too many non-zero correlations. This has been discussed in several issues here.

What do you want to use it for? Prediction? Something else?

**Comment by filosi** [comment]
I just need to use in prediction mode for now.

**Comment by privefl** [comment]
Yes, so it is not recommended to use either LDpred2 or lassosum2 with so many variants for now.
Please use either HapMap3 or HapMap3+ variants as recommended in the tutorial.
