### ISSUE TITLE
Error in running snp_readBed

### ISSUE THREAD

**Issue by Rui127** [privefl/bigsnpr#448]
I received an error using snp_redBed: not enough space on disk to create the .bk file.
I am working on an external drive (also set it as working directory)
My bed file is around 820 GB and I have 3.13 TB space left on my drive. How could I know how many space that I will need?
Thank you

**Comment by privefl** [comment]
The FBM object should be around 4x as large as the bed file.
That's starts to be very large. Do you really need all individuals and variants?
You can use `snp_readBed2()` to only read a subset (and to read in parallel).

**Comment by privefl** [comment]
Does it work for you?
