### ISSUE TITLE
Duplicate rsids

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#450]
How to remove duplicate SNPs from a bigsnpr object? I observed in my dataset some SNPs have the same rsids, and it's a dataset downloaded from UKBiobank? Is it a common issue here?

**Comment by privefl** [comment]
Please provide more details.
What data is this? Bgen/bed?
The size of the data you currently have.
Some example of some rsid that is present multiple times.

**Comment by garyzhubc** [comment]
bgen from UKBiobank. rs751773215 repeats twice.

**Comment by privefl** [comment]
You can filter those when making `list_snp_id`.

Also most functions from bigstatsr/bigsnpr have a parameter to subset the rows/columns you want to use, as if you had just a subset of the data.

**Comment by privefl** [comment]
Any update on this?

**Comment by garyzhubc** [comment]
I ended up filtering duplicate with PLINK2 --rm-dup

**Comment by privefl** [comment]
Not the solution I would recommend since it copies almost the full data, but okay.
