### ISSUE TITLE
Is there a way to access LD structure via bigsnpr?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#452]
Is there a way to access LD structure via bigsnpr?

**Comment by privefl** [comment]
Please clarify your question; I'm not sure I understand what you're asking for.

**Comment by garyzhubc** [comment]
I was wondering if there's a way to show linkage disequilibrium structure between SNPs using bigsnpr.

**Comment by privefl** [comment]
To plot it?
I've started a discussion on this 6y ago, but didn't get much feedback on this.
See https://github.com/privefl/bigsnpr/issues/4

**Comment by garyzhubc** [comment]
Seems like something good to have in bigsnpr. Do you intend to package it?

**Comment by privefl** [comment]
Since I'm not completely satisfied with it, and that I don't really know what people would like to have, I find it difficult to package anything right now.
