### ISSUE TITLE
PCA calculation: outlier removal

### ISSUE THREAD

**Issue by aepacker** [privefl/bigsnpr#457]
I have been following your tutorial on the steps to perform PCA at [https://privefl.github.io/bigsnpr/articles/bedpca.html](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivefl.github.io%2Fbigsnpr%2Farticles%2Fbedpca.html&data=05%7C01%7Camy.packer%40kcl.ac.uk%7C5aef92b6acdd44f0103b08dbd6e6c84b%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C638340058921504514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mRbfTFknhXyU406ldDOrhOc9VJaOhAg5n31C9by%2FN58%3D&reserved=0).

In the final step “Project remaining individuals”, am I correct in thinking that all remaining individuals are projected (i.e., the related individuals and individuals identified as outliers in the first PCA who were subsequently excluded from the final PCA calculation)? If so, should I subsequently remove participants who were previously identified as PCA outliers?

Working through the materials, I remove outliers with S > 0.275 based on the histogram of “outlierness”. Perhaps I am mistaken but after looking at other PCA methods, I had thought that I would need to remove these sample outliers from the projection of individuals onto my final PCs…

Below are a histogram and two plots of the PC scores coloured by the outlierness statistic:

Thanks in advance!

![PCA_outlier_hist](https://github.com/privefl/bigsnpr/assets/48684589/cd5dfb78-fde1-400f-854b-f20b900b196d)

![PCA_outlier_scores_scatter](https://github.com/privefl/bigsnpr/assets/48684589/3dcf87f4-c690-495d-9245-c0d6c769f493)

![PCA_outlier_scores_scatter_bin_0275](https://github.com/privefl/bigsnpr/assets/48684589/eea53601-0df0-485a-86e8-0506c01a8863)

**Comment by privefl** [comment]
If it's only 4 individuals, it is probably safe to remove them from all your analyses.
