### ISSUE TITLE
negative heritablity result

### ISSUE THREAD

**Issue by DUAN-GAO** [privefl/bigsnpr#461]
Sir,Madam
Hello, thanks for the remarkable algorithm developed.
I used HapMap3 LD blocks and one GWAS summary statistics file I downloaded from GWAS summary official website.
I followed your script all along, I succeeded halfway without any error, however, the h2 I estimated is negative, not positive, something like -0.5803676.
Could u help.
Many thanks.

**Comment by privefl** [comment]
Could you provide the 4 numbers you get from LDSC?
Have you verified the distribution of chi-squared statistics?

**Comment by DUAN-GAO** [comment]
Bonjour, Monsieur
Merci de votre réponse rapide : )

La question a été résolue en changeant les fichiers de GWAS summary.
Je voudrais savoir comment interpréter le score, parce que j'ai obtenu des scores positifs et négatifs allant de -99 à 30.
Et ne soyez pas surpris de voir que je parle français, car j'ai étudié en Belgique.

**Comment by privefl** [comment]
Please write in English, so that others can benefit from our discussion.
