### ISSUE TITLE
EUR reference panel for GRChr38 to run LDpred2

### ISSUE THREAD

**Issue by habraham17** [privefl/bigsnpr#462]
Hello! I was wondering if you have a EUR reference panel for GRChr38 to run LDpred2 and generate some PRS from sumstats. Thank you.

**Comment by privefl** [comment]
Have you looked at the tutorial? https://privefl.github.io/bigsnpr/articles/LDpred2.html
There are 3 solutions presented there.

**Comment by privefl** [comment]
Any update on this?
