### ISSUE TITLE
Error: Tested 13641 < 13641. Subscript out of bounds.

### ISSUE THREAD

**Issue by DUAN-GAO** [privefl/bigsnpr#463]
Hello, encountered following bug:
Error: Tested 13641 < 13641. Subscript out of bounds.
could u help, many thanks.

**Comment by privefl** [comment]
Which function? Can you provide a bit more detail?

**Comment by DUAN-GAO** [comment]
> pred_auto <- big_prodVec(G_iPSCs_002, beta_auto * map_pgs2_iPSCs_002$beta,
+                          ind.col = df_beta[["_NUM_ID_"]],
+                          ncores = 16)

Error: Tested 13641 < 13641. Subscript out of bounds.
In addition: Warning message:
In beta_auto * map_pgs2_iPSCs_002$beta :
  longer object length is not a multiple of shorter object length

It went all fine until this step.

**Comment by DUAN-GAO** [comment]
If change the ind.col parameter to the same object as beta_auto* 

> pred_auto <- big_prodVec(G_iPSCs_002, beta_auto * map_pgs2_iPSCs_002$beta,
+                          ind.col = map_pgs2_iPSCs_002[["_NUM_ID_"]],
+                          ncores = 16)

then got this error instead

Error: Incompatibility between dimensions.
'y.col' and 'ind.col' should have the same length.
In addition: Warning message:
In beta_auto * map_pgs2_iPSCs_002$beta :
  longer object length is not a multiple of shorter object length

**Comment by DUAN-GAO** [comment]
If change the ind.col parameter to the same object as beta_auto* 

> pred_auto <- big_prodVec(G_iPSCs_002, beta_auto * map_pgs2_iPSCs_002$beta,
+                          ind.col = map_pgs2_iPSCs_002[["_NUM_ID_"]],
+                          ncores = 16)

then got this error instead

Error: Incompatibility between dimensions.
'y.col' and 'ind.col' should have the same length.
In addition: Warning message:
In beta_auto * map_pgs2_iPSCs_002$beta :
  longer object length is not a multiple of shorter object length

**Comment by privefl** [comment]
Two issues here I guess:
 - `beta_auto` and `map_pgs2_iPSCs_002$beta` do not have compatible dimensions
 - `ind.col = df_beta[["_NUM_ID_"]]` should be the column indices used in `G_iPSCs_002`; this means that `max(df_beta[["_NUM_ID_"]])` should be lower or equal to `ncol(G_iPSCs_002)`

**Comment by privefl** [comment]
Any update on this?
