### ISSUE TITLE
Error in { :   task 1 failed - "Incorrect number of arguments (17), expecting 16 for '_bigsnpr_ldpred2_gibbs_auto'"

### ISSUE THREAD

**Issue by jfertaj** [privefl/bigsnpr#467]
Hi,

I am using LDpred2-auto: automatic model but I got an error. I have used the infinitesimal model without problems.

The error is the following: 
```
Error in { :
  task 1 failed - "Incorrect number of arguments (17), expecting 16 for '_bigsnpr_ldpred2_gibbs_auto'"

```

And the code I am using is this one:

```
multi_auto <- snp_ldpred2_auto(
        corr,
        df_beta,
        h2_init = h2_est,
        vec_p_init = seq_log(1e-4, 0.2, length.out = 30),
        use_MLE = FALSE,
        ncores = 4,
        allow_jump_sign = FALSE, shrink_corr = 0.95
        )
```

Any suggestions? Thanks

P.S I am using this version

```
> packageVersion("bigsnpr")
[1] '1.12.6'
```

**UPDATE**

If i run the code with just one core it works, so it seems there is a problem when going in parallel

**Comment by privefl** [comment]
Have you updated the package recently?
I think something in the installation might not have worked.
Please close all R sessions, reinstall, and try again.

**Comment by privefl** [comment]
Any update on this?
