### ISSUE TITLE
comparison of PCA from bigsnpr and PLINK

### ISSUE THREAD

**Issue by ndimou** [privefl/bigsnpr#468]
Hello,

My objective is to calculate PCs that I can use to adjust my GWAS. I computed the first 20 PCs following all the steps available here https://privefl.github.io/bigsnpr/articles/bedpca.html (using the predict option) and using the --pca option in plink (eigenevec values from plink) and I get completely different estimates. I see people simply use eigenvec as adjustment factors and I was wondering which is the way to go?

Thank you
Niki

**Comment by privefl** [comment]
I guess there are two things going on here:
- PLINK does some unprecise approximation (especially for later PCs) -> cf. Fig 5 of https://doi.org/10.1093/bioinformatics/bty185
- `bed_autoSVD()` (if you're using this function) handles removal of LD to capture only population structure, so that the two decomposition would not use the same set of variants

In conclusion, you should really use `bed_autoSVD()` over PLINK :')

**Comment by ndimou** [comment]
Thanks Florian. I removed variants in LD and forced bed_autoSVD() not to do any further prunning to make sure plink/bignpr number of variants are the same. However, the difference I get is quite substancial like 0.012 in plink and 16.51 in bigsnpr for a given PC/sample. Is it a transformation needed in the ".eigenvec! file I get from plink that could mirror what you are getting from the "predict" option in bigsnpr?

Thanks!

**Comment by ndimou** [comment]
Thanks. I checked ".eigenvec" file is "similar" (at least some scale) with obj.svd$u. Then going back to my original question which should I use as a covariate in my GWAS? I see eigenvec are used in previous GWAS.

**Comment by privefl** [comment]
You should use autoSVD to make sure there is no LD left in PCs.

**Comment by ndimou** [comment]
LD is accounted for. Let me put it in another way. Is obj.svd$u OR PC_init <- predict(obj.svd_init) you would use as a covariate in the GWAS?

**Comment by privefl** [comment]
I don't think it makes a difference to use U or UD as covariates (because the scale of covariates does not matter in an unpenalized regression).

**Comment by ndimou** [comment]
Great! Thank you for your help.
