### ISSUE TITLE
myassert_size was not declared in this scope

### ISSUE THREAD

**Issue by pcarbo** [privefl/bigsnpr#47]
I am using R 3.6.1 and gcc 4.8.5 on Linux (CentOS 7.4), and when I try to install the package I get the following error:

```
clumping.cpp: In function 'Rcpp::List clumping_chr_cached(Rcpp::Environment, arma::sp_mat, const IntegerVector&, const IntegerVector&, const IntegerVector&, const IntegerVector&, const IntegerVector&, const NumericVector&, const NumericVector&, int, double)':
clumping.cpp:101:32: error: 'myassert_size' was not declared in this scope
   myassert_size(spInd.size(), m);
```

Can you please advise? Thank you.

**Comment by pcarbo** [comment]
Okay, I was able to install successfully after first installing bigstatsr from GitHub. So it seems that there is a missing version requirement for bigstatsr in `DESCRIPTION`.

**Comment by privefl** [comment]
The dependency is there: https://github.com/privefl/bigsnpr/blob/master/DESCRIPTION#L25.
I don't know why it is not used, or at least why there is no error saying that the version of {bigstatsr} is not the one required.

Anyway, as you pointed out, using the most recent version of {bigstatsr} is needed for {bigsnpr}.

**Comment by pcarbo** [comment]
You are right. Using the `Remotes:`  tag in DESCRIPTION may help when using `devtools`, but would have to be removed before submitting to CRAN.

**Comment by privefl** [comment]
I already use `Remotes:` (https://github.com/privefl/bigsnpr/blob/master/DESCRIPTION#L56).

Yet, I think it is only useful for Travis if I remember correctly.

**Comment by pcarbo** [comment]
In the past it has worked for me, but `devtools` has changed a lot. One potential workaround is to simply add a step in the README to install bigstatsr from GitHub.

By the way, I am using bigstatsr because it is a dependency of [knockoffzoom](https://msesia.github.io/knockoffzoom).

**Comment by diegoquattrone** [comment]
I have a similar issue when installing bigsnpr:
clumping.cpp:101:3: error: use of undeclared identifier 'myassert_size'
  myassert_size(spInd.size(), m);

I tried to update bigstatsr to the last version, however I got another error now when installing bigstatsr:

**Comment by diegoquattrone** [comment]
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bigstatsr.so] Error 1
ERROR: compilation failed for package ‘bigstatsr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/bigstatsr’
Error: Failed to install 'bigstatsr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/dk/pg_7gxh10d33v1jqtvb7fvfr0000gn/T//RtmpairyLA/file298d6cff9c9b/bigstatsr_0.9.9.tar.gz’ had non-zero exit status

**Comment by privefl** [comment]
This one is related to {RcppArmadillo}.
Please see https://github.com/privefl/bigsnpr/issues/6.
