### ISSUE TITLE
Why do I get zero p-values?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#476]
Zero p-values from: 

`gwas <- big_univLogReg(ukb_abca1$genotypes, 1-df[[var_name]], df$id, range)`

and

`snp_manhattan(gwas, ukb_x1$map$chromosome, ukb_x1$map$physical.pos)`

In particular:

```
> min(predict(gwas, log10=FALSE), na.rm = TRUE)
[1] 0
```

So the plot looks like:

![image](https://github.com/privefl/bigsnpr/assets/30366447/c33e89cc-d44c-42fb-b166-9c4da1b48a66)

**Comment by privefl** [comment]
The p-value is so small that it cannot be stored as a number by computers. It has to be rounded to 0.
This is why I usually work with log10(pval).

**Comment by garyzhubc** [comment]
Is it possible to get rid of that point (or make amendment) in the plot?

**Comment by privefl** [comment]
I would add `+ scale_y_log10()`.
But the -log10(pval) seems really large.
If you want to remove it, you can probably do something like `gwas$score[which.max(gwas$score^2)] <- 0`.

**Comment by garyzhubc** [comment]
After adding `+ scale_y_log10()` now I got a plot like this:
![image](https://github.com/privefl/bigsnpr/assets/30366447/ca886d8e-37fc-4b8b-9b5f-7e235cb527c8)
How to change the y-axis label to -log10(log10(p-value))?

**Comment by privefl** [comment]
The y-values are -log10(pval), but on top you represent them on a log-scale (of y, so on a log-log-scale of pval), which is fine.
Then the intercept is simply `-log10(5e-8)`.

**Comment by garyzhubc** [comment]
Why isn't the intercept now in log-log-scale too?
