### ISSUE TITLE
Is it possible to plot p-values with multiple corrections?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#483]
Is it possible to plot p-values with multiple corrections? Like `p.adjust`

**Comment by privefl** [comment]
Just use this function or any other R package of your choice that can do this.

**Comment by garyzhubc** [comment]
But I cannot plot it with `snp_manhattan` right?

**Comment by privefl** [comment]
Not directly, no.
You can probably modify `attr(obj.gwas, "predict")`, or simply adapt the code from `snp_manhattan()`.
