### ISSUE TITLE
Question about LDpred2 on PRS

### ISSUE THREAD

**Issue by wendy-xiaozong** [privefl/bigsnpr#484]
Hi Florian, 

Thanks a lot for this great work!

I am following these two tutorials to compute the PRS using LDpred2: [PRS-Tutorial](https://choishingwan.github.io/PRS-Tutorial/ldpred/#7-obtain-model-prs) and [LDpred2](https://privefl.github.io/bigsnpr/articles/LDpred2.html#lassosum2-grid-of-models).

However, I got this histogram of the two binary classes using the infinitesimal method on LDpred2:
![image](https://github.com/privefl/bigsnpr/assets/32104051/61ed75fc-1c77-4964-8992-d84da44cc2dd)

The increase Nagelkerke $R^2$ = 0.6741554 - 0.001468591 = 0.6726 looks good, **but you can see from the histogram plot that the PRS is from -32 to -26. I wonder whether this is normal or not for the LDpred2 result.** This is [the code](https://github.com/wendy-xiaozong/Genetics-ML/blob/main/PRS/SSC/LDpred2.R) I use. Could you let me know whether I made any mistake or not for the result?

Thanks for great work again!

Jueqi

**Comment by privefl** [comment]
No, I would not worry about this range.
If you need something very well calibrated, I think it should be recalibrated using another dataset.

**Comment by wendy-xiaozong** [comment]
Thanks for answering my question! I will check the newest official tutorial again to make sure everything is correct!
