### ISSUE TITLE
Error when running example-with-provided-LD.R

### ISSUE THREAD

**Issue by alhannae** [privefl/bigsnpr#486]
Hi Florian,

I ran your LDpred2 script without the pre-computed matrices successfully.
However, when running the script with the pre-computed matrices, I ran into a few errors (https://github.com/privefl/paper-infer/blob/main/code/example-with-provided-LD.R)

There is a problem when reading in the breast cancer GWAS, I can not run the rest of the script because of this.
However, when I adjust the script to the GWAS that I use for the script without the pre-computed matrices (the public data used here > https://privefl.github.io/bigsnpr/articles/LDpred2.html) , everything goes smoothly untill I have to calculate the scores:

> pred_auto <- big_prodVec(G, beta_auto, ind.col = df_beta[["_NUM_ID_"]])
Error: Tested 45338 < 45337. Subscript out of bounds.

any idea why this is?  If needed, I can provide the full R script that I run.

Thanks in advance! Much appreciated.

Kind regards, 

Hannae

**Comment by privefl** [comment]
Basically, `max(df_beta[["NUM_ID"]])` is larger than `ncol(G)`; you should verify the column indices you provide to this function.

**Comment by privefl** [comment]
For the error reading the GWAS summary statistics, please open another issue.

**Comment by alhannae** [comment]
Hi Florian, 

The problem occurs when I run this: 

in_test <- vctrs::vec_in(df_beta[, c("chr", "pos")], map_test[, c("chr", "pos")])
df_beta <- df_beta[in_test, ]

Since the _NUM_ID_ column refers to the matching of the hapmap file and sumstats [ info_snp <- snp_match(sumstats, map_ldref)], this error occurs.

I tried to fix it by adding this to the script (after the part where the genome-wide correlation matrix is calculated):



I added now

**Comment by privefl** [comment]
A good indication that `df_beta2[["NUM_ID"]]` is the right indices to use if when its `range()` is close to `c(1, ncol(G))`.

**Comment by alhannae** [comment]
Yes that is the case!

> range(df_beta2[["_NUM_ID_"]])
[1]     1 45332
> c(1, ncol(G))
[1]     1 45337

I am just scared that maybe by matching the df_beta with map, something goes wrong with assigning the beta to the correct variant.

**Comment by privefl** [comment]
Seems fine.
You'll see if you find some association between the PGS and the outcome.
