### ISSUE TITLE
Script example-with-provided-LD.R does not work

### ISSUE THREAD

**Issue by alhannae** [privefl/bigsnpr#487]
Hi Florian, 

The script [example-with-provided-LD.R](https://github.com/privefl/paper-infer/blob/main/code/example-with-provided-LD.R) does not work with the sumstats provided.

I get a warning when I read in the sumstats. 

```r
sumstats <- fread2("tmp-data/sumstats_BRCA.txt", na.strings = "NULL",
                    select = c("chr", "position_b37", "a0", "a1",
                               "bcac_onco_icogs_gwas_beta",
                              "bcac_onco_icogs_gwas_se"),
                    col.names = c("chr", "pos", "a0", "a1", "beta", "beta_se"))
```

```
Warning message:
In data.table::fread(input, ..., data.table = data.table, nThread = nThread) :
  Discarded single-line footer: <<3_42>>
```

When I then want to match the sumstats with hapmap, it errors because not enough variants have been matched. Do you also encounter the same error?

```r
info_snp <- snp_match(sumstats, map_ldref)
```

```
1,847,056 variants to be matched.
9 ambiguous SNPs have been removed.
232,984 variants have been matched; 0 were flipped and 0 were reversed.
Error: Not enough variants have been matched.
```

Thanks very much for looking into this. Much appreciated!

Hannae

**Comment by privefl** [comment]
- Which `packageVersion("data.table")` do you have?

- Are you sure the full summary statistics have been dowloaded and uncompressed with no error or interruption; it is odd that you have only "1,847,056 variants to be matched".
