### ISSUE TITLE
Handling missing values in SNP matrix

### ISSUE THREAD

**Issue by naglemi** [privefl/bigsnpr#49]
Thanks for making this tool available. I wasn't sure whether to mark this as a question or issue because it's unclear to me if there is existing support for PCA and GWAS with SNP matrices that contain NAs. I am accustomed to setting thresholds in PLINK and GEMMA for which all SNPs missing in more than X genotypes are excluded, but haven't found a similar feature for bigsnpr in documentation or the demo.

I'm trying to run my data, which I've formatted the same way as the demo data, but there are NAs in my SNP set (from QC filtering, indels, etc) and this leads me to the error below.

Do I need to format the NAs a particular way, or do anything else to build models that include SNPs not found in all genotypes?

```
Error: You can't have missing values in 'X'.
Traceback:

1. big_univLogReg(G, y01.train = y01, covar.train = covariates, ncores = NCORES)
2. check_args()
3. with(args, eval(parse(text = check[i])))
4. with.default(args, eval(parse(text = check[i])))
5. eval(substitute(expr), data, enclos = parent.frame())
6. eval(substitute(expr), data, enclos = parent.frame())
7. eval(parse(text = check[i]))
8. eval(parse(text = check[i]))
9. assert_noNA(X)
10. stop2("You can't have missing values in '%s'.", deparse(substitute(x)))
11. stop(sprintf(...), call. = FALSE)
```

**Comment by privefl** [comment]
Yes, most of the functions in the packages don't handle missing values.
Note that I will add a PCA algorithm that handle missing values soon (in @bedpca branch).
This is not planned for GWAS since I extensively use linear algebra, which does not mix well with missing values.

If you want to use {bigsnpr}, you should therefore filter to no missing values or impute them. 
To impute, you can impute using `snp_fastImpute()` which should be taking a few hours for say 10K samples and 500K variants. 
Otherwise, you could impute with the mean (rounded), or the mode, or randomly according to frequencies, or by 0. Although these are not very hard to code, I should probably make them available as functions in {bigsnpr}.

**Comment by privefl** [comment]
I've just added `snp_fastImputeSimple()` to do a very fast imputation.

**Comment by privefl** [comment]
Is this answering your questions?

**Comment by naglemi** [comment]
Thanks for clarifying. Is imputation mathematically equivalent to excluding genotypes missing a given SNP when building the model for that SNP? Should it produce the same test statistics? I think most of the other GWAS methods we use (particularly GEMMA) exclude those genotypes instead of imputing.

**Comment by privefl** [comment]
No, I don't think that this is equivalent.
If the imputation is good, then I think you get more power. 
Also the best thing to do might be multiple imputation, but requires more computation.

**Comment by wongck-kevin** [comment]
Hi Florian,
Thanks for making the very fast imputation function. Will it be possible that you add "impute by 0" option as well?

**Comment by privefl** [comment]
Yes, I guess it would be easy.
I just feel like it is should be best to impute by any of the other methods.
What do you think?

**Comment by wongck-kevin** [comment]
I just think this is more conservative.

**Comment by privefl** [comment]
Should be now implemented in latest version, using `method = "zero"`.

**Comment by wongck-kevin** [comment]
Thanks so much Florian!

**Comment by privefl** [comment]
@wongck-kevin I just remembered why I didn't implement this before.

In fact, you can do `G2 <- G$copy(code = c(0, 1, 2, 0, rep(NA, 252)))`, and you will access all NAs as 0s when using `G2` instead of `G`.
So, you could impute by 1 or 2 using this method as well.

**Comment by wongck-kevin** [comment]
Thanks for the update Florian.

**Comment by privefl** [comment]
Note that I will soon deprecate 'method = "zero"' in favor of using "$copy()".
This will give a warning only.

**Comment by yu-zhang-oYo** [comment]
> Yes, most of the functions in the packages don't handle missing values. Note that I will add a PCA algorithm that handle missing values soon (in @bedpca branch). This is not planned for GWAS since I extensively use linear algebra, which does not mix well with missing values.
> 
> If you want to use {bigsnpr}, you should therefore filter to no missing values or impute them. To impute, you can impute using `snp_fastImpute()` which should be taking a few hours for say 10K samples and 500K variants. Otherwise, you could impute with the mean (rounded), or the mode, or randomly according to frequencies, or by 0. Although these are not very hard to code, I should probably make them available as functions in {bigsnpr}.

Hi Florian, thanks for providing the software, I used this snp_fastImpute to impute missing values (still missing after the TOPMED imputation), the sample is 3K individuals and 9000K variants, 4 days is even not enough to impute, I tried to set ncores=60, but the computation time is similar to 2 cores, I would appreciate any guidance on how to impute in a limited time. Thanks!

**Comment by privefl** [comment]
This function should produce an FBM stored in `{Gna$backingfile}-infos-impute.bk` to keep track of the imputation.
You can load it with the rds file with `big_attach()` in another R session and look for how many columns don't have missing values anymore (what was your progress so far?).
For the columns with values, they store the percentages of missing values and imputation errors. It is reported at the end (for post-QC) and is used internally to keep track of the variants already imputed (if you stopped the imputation and rerun it).

Note that the imputation using external reference panels like TOPMED should not result in any missing value; they usually come from the conversion to the format storing imputation probabilities to bed files (storing 0/1/2, with an NA when e.g. one prob is not at least 80%). This is not a great way to use imputed data in my opinion, you should try to keep as much information as possible (e.g. by transforming the probabilities to dosage data). To get a bigSNP object from these, have a look at https://privefl.github.io/statgen-course/inputs-and-formats.html#getting-bigsnp.

**Comment by yu-zhang-oYo** [comment]
> This function should produce an FBM stored in `{Gna$backingfile}-infos-impute.bk` to keep track of the imputation. You can load it with the rds file with `big_attach()` in another R session and look for how many columns don't have missing values anymore (what was your progress so far?). For the columns with values, they store the percentages of missing values and imputation errors. It is reported at the end (for post-QC) and is used internally to keep track of the variants already imputed (if you stopped the imputation and rerun it).
> 
> Note that the imputation using external reference panels like TOPMED should not result in any missing value; they usually come from the conversion to the format storing imputation probabilities to bed files (storing 0/1/2, with an NA when e.g. one prob is not at least 80%). This is not a great way to use imputed data in my opinion, you should try to keep as much information as possible (e.g. by transforming the probabilities to dosage data). To get a bigSNP object from these, have a look at https://privefl.github.io/statgen-course/inputs-and-formats.html#getting-bigsnp.

Hi Florian,

Thank you very much for the detailed explanation — that was extremely helpful.

I checked the {Gna$backingfile}-infos-impute.bk file as you suggested. From the first row (proportion of missing values by SNP), it looks like about 3,788,267 SNPs have already been imputed, while ~5,745,225 SNPs still have NA (i.e., have not yet been processed). My understanding is that this means the imputation can be safely resumed by rerunning snp_fastImpute(), and the function will skip variants that were already completed and continue imputing the remaining ones. Please let me know if this interpretation is correct.

Thanks also for the important note about TOPMed imputation. I now realize that the remaining missing values likely come from the conversion to hard calls (0/1/2) rather than from the imputation itself. I will go back and check the original data source to confirm it.

Thank you again for your time and for providing such a useful tool.

Best regards,
Yu

**Comment by privefl** [comment]
Yes, as it can be long process, I think I've made it so that it can be resumed. But it will still take a lot of time.
You can maybe reduce it a bit by using e.g. `alpha = 1e-20`.

But I would rather go back to using dosages instead.

**Comment by yu-zhang-oYo** [comment]
> Yes, as it can be long process, I think I've made it so that it can be resumed. But it will still take a lot of time. You can maybe reduce it a bit by using e.g. `alpha = 1e-20`.
> 
> But I would rather go back to using dosages instead.

Hi Florian,

Got it, thanks for your guidance. I appreciate your kind help.

Best
Yu
