### ISSUE TITLE
Getting this error while trying to convert from hg19 to hg38

### ISSUE THREAD

**Issue by znayema** [privefl/bigsnpr#491]
my code

lifted <- snp_modifyBuild(data, "/work/larylab/NAYEMA/liftover/liftOver", from = "hg19",
                               to = "hg38",
                               check_reverse = TRUE)

Error in utils::download.file(url, destfile = chain, quiet = TRUE) : 
  cannot open URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz'
In addition: Warning message:
In utils::download.file(url, destfile = chain, quiet = TRUE) :
  URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz': Timeout of 60 seconds was reached

**Comment by privefl** [comment]
These aren't particularly large files; this should take less than 60 sec to download.
You can set `options(timeout = 1000)` and try again (maybe you'll need to delete partially downloaded files first).

**Comment by privefl** [comment]
Another possible issue is that downloads are blocked on your server.
And you should ask someone to download this file for you.

**Comment by privefl** [comment]
Any update on this?

**Comment by Hugolyu** [comment]
Hi privefl,

I encountered the same bug. Here's the error message:
```
Error in utils::download.file(url, destfile = chain, quiet = TRUE) : 
  cannot open URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz'
In addition: Warning message:
In utils::download.file(url, destfile = chain, quiet = TRUE) :
  URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz': Timeout of 60 seconds was reached
```
It appears that the URL needs to be updated. File :  bigsnpr / R / modify-positions.R On line 47, the URL is constructed as follows:
```
url <- paste0("ftp://hgdownload.cse.ucsc.edu/goldenPath/", from, "/liftOver/",
```
The new download URL should be:

```
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz
```
Thanks for the tool , hope it helps.

**Comment by privefl** [comment]
Thanks for reporting.

So, just changing `soe` to `cse`?

The local file is probably a good idea too. Would you like to submit a PR for both of this?

**Comment by znayema** [comment]
Thank you Privefl. I had problem downloading files due to my server. The problem is fixed

**Comment by znayema** [comment]
Thank you for the updates
________________________________
