### ISSUE TITLE
scale of MCMC sampling of beta 

### ISSUE THREAD

**Issue by yidingdd** [privefl/bigsnpr#499]
Hi Florian,

Could you help to confirm the scale of betas from the MCMC sampling in your newest bigsnpr release?

It looks like the beta sample returned by snp_ldpred2_grid is on allelic scale, but the beta sample returned by snp_ldpred2_auto is on standardized scale, is it correct? 

https://github.com/privefl/bigsnpr/blob/ee9f2ed5a069cf63401b9b922bae0b9492c46afc/R/LDpred2.R#L139
https://github.com/privefl/bigsnpr/blob/ee9f2ed5a069cf63401b9b922bae0b9492c46afc/R/LDpred2.R#L182

Best,
Yi

**Comment by privefl** [comment]
Hi Yi,

For LDpred2-auto, 
- `$beta_est` is also on allelic scale
- but `$sample_beta` is indeed on the standardized scale
