### ISSUE TITLE
Is it possible to call `big_univLogReg` on simulated data?

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#504]
Is it possible to call `big_univLogReg` on simulated data `x,y` where `x` is a binary matrix and `y` is a binary vector?

```
> gwas <- big_univLogReg(x, y)
Error: 'X' is not of class 'FBM'.
```

I know that I could've done this in `lm` but I would like to make a test myself on `bigsnpr`. Thank you.

**Comment by privefl** [comment]
This function is from {bigstatsr}, not {bigsnpr}.
You can always call `as_FBM()` on your matrix to transform it before using this function.
