### ISSUE TITLE
snp_match removed ambiguous SNPs

### ISSUE THREAD

**Issue by koujiaodahan** [privefl/bigsnpr#510]
I run the snp_ match function, and the the following log:
 > df_beta <- snp_match(sumstats_reanme, map)
"31,519 variants to be matched.
4,555 ambiguous SNPs have been removed.
26,964 variants have been matched; 0 were flipped and 0 were reversed."

The question is why there are variants to be removed. Because the sumstats_reanme and map files have been extracted from sites that overlap each other. and I had checked the concordance:
> identical(map$rsid,sumstats_reanme$rsid)
[1] TRUE
 > identical(map$a0,sumstats_reanme$a0)
[1] TRUE
> identical(map$a1,sumstats_reanme$a1)
[1] TRUE
> identical(map$pos,sumstats_reanme$pos)
[1] TRUE
> identical(map$chr,sumstats_reanme$chr)
[1] TRUE

**Comment by privefl** [comment]
Ambiguous variants are removed by default.
Because you have no variant that is flipped, you can probably safely use `strand_flip = FALSE`.

**Comment by koujiaodahan** [comment]
> Ambiguous variants are removed by default. Because you have no variant that is flipped, you can probably safely use `strand_flip = FALSE`.

what's the ambiguous variants' meaning?  why do ambiguous variants exist in this dataset?

**Comment by privefl** [comment]
A quick search on the internet: https://www.biostars.org/p/375143/#375157

**Comment by koujiaodahan** [comment]
> A quick search on the internet: https://www.biostars.org/p/375143/#375157

Oh，I see. thanks for you suggestion. I will use strand_flip = FALSE
