### ISSUE TITLE
'chi2' and 'ld_score' should have the same length

### ISSUE THREAD

**Issue by koujiaodahan** [privefl/bigsnpr#512]
Before running the program, I extracted the overlap sites among the genotype, gwas summary statistics and Map files. I checked all of the variants are the same. and the program is worked on the chr22. 
But  when I run all the chromosome data, there is bug log:

"2,395,488 variants to be matched.
2,395,488 variants have been matched; 0 were flipped and 0 were reversed.
Error: Incompatibility between dimensions.
'chi2' and 'ld_score' should have the same length.
Execution halted"

**Comment by privefl** [comment]
I guess this is from `snp_ldsc()`. You need to provide these two vectors of the same length.

**Comment by koujiaodahan** [comment]
Oh， I find the bug.  Because the program didn't handle chrX, there are sites on chrX that I've included in my inputs. So do you suggest not inputting chrX when computing h2 and running LDpred2-auto?

**Comment by koujiaodahan** [comment]
> I guess this is from `snp_ldsc()`. You need to provide these two vectors of the same length.

Oh， I find the bug.  Because the program didn't handle chrX, there are sites on chrX that I've included in my inputs. So do you suggest not inputting chrX when computing h2 and running LDpred2-auto?

**Comment by privefl** [comment]
I don't know whether it is valid to use chrX in LD Score regression or not.
But in terms of code, if you input both corresponding `chi2` and `ld`, that should give you some result, since the chromosome information is not used anywhere.
