### ISSUE TITLE
(fast) matrix operations on bigsnp_obj genotype matrix

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#521]
Is there any way of performing matrix-vector multiplication on the bigsnp_obj genotype matrix? For instance, I'd like to perform such an operation:

```
bigsnp_obj <- snp_attach("data/geno.rds")
sigma <- sqrt(var(bigsnp_obj$genotypes * b) / phi - var(bigsnp_obj$genotypes * b))
```

**Comment by privefl** [comment]
You can use `big_prodVec()` on `bigsnp_obj$genotypes`.
