### ISSUE TITLE
Ancestry estimator applied to UKB using PCs calculated 

### ISSUE THREAD

**Issue by gtdoctor** [privefl/bigsnpr#523]
Hi Florian, 

I am using the ancestry estimator on a population cohort taken from UKB. 
My cohort is n~ 403,000, multiancestry, processed to remove people so that no one remaining is  <=2 degrees related. I am projecting ancestry based on a subset of about 37000 common snps (loci defined by some other requirements).

The guidance states that the correction factor for projection is not needed when projecting the reference population back to itself. However I wasn't sure if by 'reference', you meant only the samples used to create the original PCs and labels, or the whole of the wider UKB set.
 
Thus I wanted to check that this code below is correct.  As I undersand it, it is really only 1 line that needed to be changed:

```{r}
counts <- bed_counts(obj.bed, ind.col = matched$`_NUM_ID_.ss`, ncores = NCORES)
ind <- which(counts[4, ] < (nrow(obj.bed) * 0.05))        
PROJ <- as.matrix(projection[matched$`_NUM_ID_`[ind], -(1:5)])
```

**i have adjusted this line here to remove scaling by correction, multiply by 0.5 (instead of divide by 2)**
```{r}
all_proj <- apply(sweep(PROJ, 2, 0.5, '*'), 2, function(x) {
  bed_prodVec(obj.bed, x, ind.col = matched$`_NUM_ID_.ss`[ind], ncores = NCORES,
              # scaling to get G if beta = 1 and (2 - G) if beta = -1
              center = 1 - matched$beta[ind],
              scale = matched$beta[ind])
})
```
then continues without any further change:
```{r}
REF_FREQ <- as.matrix(all_freq[matched$"_NUM_ID_"[ind], -(1:5)])
all_centres <- crossprod(REF_FREQ,PROJ)
# this calculates the distance of each individual from the centre of the population: 
#note that 
all_sq_dist <- apply(all_centres, 1, function(one_centre) {
  rowSums(sweep(all_proj, 2, one_centre, '-')^2)
})
THR <- 0.002  
thr_sq_dist <- max(dist(all_centres)^2) * THR / 0.16
group <- colnames(all_freq)[-(1:5)]
group[group %in% c("Scandinavia", "United Kingdom", "Ireland")]   <- "Europe (North West)"
group[group %in% c("Europe (South East)", "Europe (North East)")] <- "Europe (East)"

### ASSIGN INDIVIDUALS TO ONE OF THE GROUPS ###
cluster<- apply(all_sq_dist, 1, function(sq_dist) {
  ind <- which.min(sq_dist)
  if (sq_dist[ind] < thr_sq_dist) group[ind] else NA
})
```

Thanks again.

**Comment by privefl** [comment]
This is a bit tricky to apply this to the UK Biobank, because you'll need the correction for some of the individuals (those who were not included in the PCA).

If using 9 larger groups is fine with you, you should use this code instead:
https://github.com/privefl/UKBB-PGS?tab=readme-ov-file#code-to-reproduce-ancestry-groups

**Comment by gtdoctor** [comment]
Thanks for your reply... ideally woulnd't use the 9 larger groups as e.g. I have quite a lot of specific Sri Lankan and ME/North African samples from my external samples to compare with UKB.
Since the introduction of user-specific pseudonymised UKBdata it's presumably impossible to share the EIDs of those you used to build the reference and hence to know which UKB samples to treat with and without correction. Oh well.

**Comment by privefl** [comment]
You should be able to reproduce the groups I used using the (longer) code [here](https://github.com/privefl/freq-ancestry/blob/main/code/1-prepare-ukbb-groups.R).

**Comment by gtdoctor** [comment]
thanks, i was thinking about getting this running on the UKRAP Rstudio app.
 
Incidentally, do you have a list of UKB genotype snps that were identified as likely misspecified? You reference this paper by Kunert-Graf et al https://doi.org/10.1101/2020.08.03.235150 but the link in his paper to his 'bad snps' list is depreciated and I can't easilly find an active email address.

**Comment by privefl** [comment]
I guess they never published this paper, and the first author might have left academia.
I don't think this was removing a lot of variants.
But why do you need this list?

**Comment by gtdoctor** [comment]
It’s part of my snp Qc before imputation. I want to impute the ukb genotype data against the same server and reference panel (TOPMED server  R3) that I am using for my external data (hence not just using the Ukb provided imputation data which used topmed r2). theoretically this will make posterior dosages more comparable. Your paper and my own intuition, suggest that if you give the imputation engine “bad” data in it is likelier to give bad data out that won’t be detectable by the RSQ quality metric. It seemed a useful list of bad snps  Hence wanted to weed these out before submitting to server.

My current (possibly crazy) plan is to compete allele


Best wishes
Gabriel

On 26 Nov 2024, at 13:17, Florian Privé ***@***.***> wrote:

﻿

⚠ Caution: External sender


I guess they never published this paper, and the first author might have left academia.
I don't think this was removing a lot of variants.
But why do you need this list?

**Comment by privefl** [comment]
Yes, I think it was useful.
They were merely comparing allele frequencies with other external cohorts IIRC. Maybe this could be done again.
