### ISSUE TITLE
Deciding how many genetic PCs to use in GWAS

### ISSUE THREAD

**Issue by AnnaFurtjes** [privefl/bigsnpr#524]
Hi Florian, 
Thanks for providing bigsnpr, it ran really smoothly for me.

I used bigsnpr to generate genetic PCs in a subsample of UKB (N = 43k), and now I am having difficulty deciding how many PCs I should use in my GWAS. Please find attached the plots. 
Would you agree that 7 genetic PCs should be sufficient?
Am I right in thinking that you judge this by looking at all three attached plots?
What are the most important metrics to decide how many to include?
It really seem that my plots don't have this very obvious drop in genome-wide loadings like you found in the paper for PCs 19 and onwards.

Thanks!!

![hist_outlier_detection](https://github.com/user-attachments/assets/837e16c6-b40a-4217-a810-31a9fadd876e)
![PC_scores](https://github.com/user-attachments/assets/6e42bb9f-15d8-435e-be16-8b453da1bf2b)
![PC_vs_genomic_loc](https://github.com/user-attachments/assets/9ec8ec91-ad32-42b3-a9ee-fb0f885a4493)
![Scree_plot](https://github.com/user-attachments/assets/6878b264-fb66-4d8b-927e-ef4004a9f424)

**Comment by privefl** [comment]
I would say that the scree plot would suggest keeping 8 PCs, and the PC scores as well.

Which subset is this?

**Comment by AnnaFurtjes** [comment]
Okay, thank you! 
What is it about the PC scores that tells you this? Is it that there is structure (rather than just a random blob) when you plot the PC scores against one another?
These participants are the ones with available neuroimaging data.

**Comment by privefl** [comment]
Yes, there seems to be some pop structure on PC8 as well.

If this is a random subset, I would probably use the PCs derived from the full cohort. You can use 16 there.

**Comment by AnnaFurtjes** [comment]
I don't think I would necessarily say that the UKB neuroimaging subset can be described as a random subset. Participants who return for their MRI scanning were only recruited across three sites (i.e., fewer than the whole sample) and they tend to be much wealthier/ healthier participants, for example. 
Why would you prefer using PCs from the full cohort?
Am I wrong in thinking that calculating PCs in the smaller subset would allow picking up on population structure specific to that subset (and therefore better correct for pop structure relevant to that subset)?

**Comment by privefl** [comment]
If it's a random subset, using more individuals would give better estimates I guess.

If it's not (e.g. restricting to some more homogeneous population), then you're right that it is useful to recompute PCs.

**Comment by AnnaFurtjes** [comment]
Amazing, thank you!
