### ISSUE TITLE
Add percentage of variance explained by PCs

### ISSUE THREAD

**Issue by privefl** [privefl/bigsnpr#53]
If you have a `bigSNP` object, see https://github.com/privefl/bigstatsr/issues/83.

If you have a `bed` object (directly mapping a bed file), see this example:
```r
library(bigsnpr)
bedfile <- system.file("extdata/example.bed", package = "bigsnpr")
obj.bed <- bed(bedfile)
obj.svd <- bed_autoSVD(obj.bed)
ind.keep <- attr(obj.svd, "subset")

rssq <- bigsnpr:::prod_and_rowSumsSq(
  obj.bed, ind_row = rows_along(obj.bed), ind_col = ind.keep,
  center = obj.svd$center, scale = obj.svd$scale, 
  V = matrix(0, length(ind.keep), 0)  # skip product here
)[[2]]
sum(rssq)  # squared frobenius norm of genotype matrix for subset (= total variance explained)
var_exp <- obj.svd$d^2 / sum(rssq)
signif(var_exp, 2)
round(cumsum(var_exp), 3)
```

**Comment by xsun1229** [comment]
Hi privefl!

I have a question about the PVE. 

It seems that your codes are used to compute the PVE on whole genotype matrix. But the bigsnpr will do ld clumping first and obtain a subset of the variants before doing PCA(as shown [here](https://privefl.github.io/bigsnpr/articles/bedpca.html)). So, could you give some suggestions about how to compute the PVE on the subset of the genotype matrix?

Thank you!

**Comment by privefl** [comment]
This is the purpose of `ind.keep` in the code here.

**Comment by xsun1229** [comment]
Thank you privefl! Do you mean the genotype matrix used to compute total variance is already just contain the variants after clumping because of the `ind.keep`?

**Comment by privefl** [comment]
This corresponds to the subset of variants that were used in the PCA.

**Comment by xsun1229** [comment]
I see! Great thanks!
