### ISSUE TITLE
Convert data.frame to FBM.code256

### ISSUE THREAD

**Issue by ahereil** [privefl/bigsnpr#54]
Hi Florian,
I have some difficulties with your bigsnpr package. I would like to transform an SNP matrix (https://github.com/ahereil/Test-Data/blob/master/geno_test.txt) to FBM.code256 format in order to use the snp_clumping() function. 

Thanks

**Comment by privefl** [comment]
You need to transform your data to 0, 1, 2, and 3 (for missing values):
```
geno <- bigreadr::fread2(
  "https://raw.githubusercontent.com/ahereil/Test-Data/master/geno_test.txt",
  dec = ",")
geno <- data.frame(lapply(geno[-1], function(x) {
  ifelse(is.na(x), 3, 2 * x)
}))
library(bigsnpr)
G <- FBM.code256(nrow(geno), ncol(geno), code = CODE_012)
G[] <- geno
```
Note that `snp_clumping()` does not handle missing values.
You can write to bed file and use `bed_clumping()` instead, or impute.

**Comment by ahereil** [comment]
Thank you, it works well.
