### ISSUE TITLE
ind.row, ind.col do not work in snp_readBed2

### ISSUE THREAD

**Issue by msesia** [privefl/bigsnpr#59]
If the number of rows or columns is large, calling
`snp_readBed2(bed.file, backingfile = rds.basename, ind.row=ind.row, ind.col=ind.col)
`
gives the following error message:

    Error in if (file.size(.self$backingfile) != (size * .self$type_size)) stop2("Inconsistency between size of backingfile and dimensions.") :
    missing value where TRUE/FALSE needed
    In addition: Warning message:
    In .self$nrow * .self$ncol : NAs produced by integer overflow

Also, calling
snp_readBed2(bed.file, backingfile = rds.basename, ind.row=ind.row)
throws:

    Error in ncol(x) : object 'obj.bed' not found

**Comment by privefl** [comment]
Thanks for reporting!

This should be fixed now if you get both latest {bigstatsr} and {bigsnpr}.
