### ISSUE TITLE
Installation issue: OS X "-lgfortran" and "-lquadmath" errors

### ISSUE THREAD

**Issue by DrK-Lo** [privefl/bigsnpr#6]
Hi Florian, 
I've been using your bigsnpr package in a class I teach, and some of the students were having issues installing. One of the errors was this:

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bigstatsr.so] Error 1
ERROR: compilation failed for package ‘bigstatsr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/bigstatsr’
Installation failed: Command failed (1)

**Comment by privefl** [comment]
Hello Katie, 

Are you sure they all have the command line tools installed on their Mac?
They just need to run `xcode-select --install`.

**Comment by DrK-Lo** [comment]
Command line tools are installed, but from the post sounds like the problem is deeper. Thanks!

**Comment by privefl** [comment]
If you manage to solve these installation problems, please report your solution(s) there. 
It will help others, thanks.

**Comment by biojiangke** [comment]
I could confirm that following the directions in the aforementioned Blog post would solve this problem with MacOS Sierra.

**Comment by privefl** [comment]
Look also at https://github.com/fxcoudert/gfortran-for-macOS/releases (e.g. for Mac Mojave).
