### ISSUE TITLE
snp_plinkKINGQC() - version check for PLINK v2 fails when using older PLINK v2 builds

### ISSUE THREAD

**Issue by kristjanmoore** [privefl/bigsnpr#63]
(I've never reported an issue on Github before -- hope this is well described and replicable)

Running the following command:

`snp_plinkKINGQC(plink2_path, in_stem, out_stem)`

gives the following error message:

`Error: This requires PLINK v2; got 'PLINK v2.00a2LM 64-bit Intel (4 Mar 2019)' instead.`

The additional warning message tells us why:

```
In addition: Warning message:
In system(paste(plink2.path, "--version"), intern = T) :
  running command '[redacted path to my org's PLINK2 version] --version' had status 9
```

The `!identical(substr(v, 1, 8)) == "PLINK v2"` check in `snp_plinkKINGQC()` fails because the `v` object (and its `substr()` output) has `attr(,"status") [1] 9`, unlike the string "PLINK v2".

However, the more recent PLINK v2.00a2.3LM does not display the behaviour of returning a non-zero exit status when `--version` is run, so I don't get the error when I point `plink2_path` to that build.

**Comment by privefl** [comment]
Thanks for reporting.

Do you know what status 9 means?
Should it be considered as an issue or should I let it pass?

**Comment by kristjanmoore** [comment]
No worries! So the "status 9" attribute means the system call made by R's system() gave a non-zero exit code (9). I presume that exit code 9 is (that build of) PLINK v2 saying "no input file loaded" or something similar. 

I guess this would be an issue for people who are stuck using whatever versions that their organisation's IT department have decided to make available (like myself! Although it turned out that we had a more recent build too).

**Comment by privefl** [comment]
Should be fixed now.

**Comment by fmadani** [comment]
I am running PLINK2 that is downloaded after running download_plink2(). Its version is 'PLINK v2.00a3LM AVX2 Intel (3 May 2022)'

When I run this command 

rel <- snp_plinkKINGQC(plink2, "EUR.QC.bed",
                       thr.king = 2^-4.5, make.bed = FALSE, ncores = nb_cores())


I get this error:
Error in system(paste(plink2.path, "--version"), intern = TRUE): error in running command
Traceback:

1. snp_plinkKINGQC(plink2, "EUR.QC.bed", thr.king = 2^-4.5, make.bed = FALSE, 
 .     ncores = nb_cores())
2. system(paste(plink2.path, "--version"), intern = TRUE)



I checked in Linux command line and figured out that plink2.path doesn't exist but, if we remove '.path' this command (plink2 --version) works.

**Comment by fmadani** [comment]
Interestingly, when I created "tmp-data" folder and copied my bed file in it, and applied "tmp-data" to address the bed file like this: 

rel <- snp_plinkKINGQC(plink2, "tmp-data/EUR.QC.bed",
                       thr.king = 2^-4.5, make.bed = FALSE, ncores = nb_cores())

this command works without any error. It seems using "tmp-data" is mandatory?! Is it?

**Comment by privefl** [comment]
I am not sure I understand what is exactly your problem.

I am able to run 
```r
library(bigsnpr)

bedfile <- system.file("extdata", "example.bed", package = "bigsnpr")

plink2 <- download_plink2("tmp-data", overwrite = TRUE)
# plink2_win_avx2_20220503.zip

rel <- snp_plinkKINGQC(
  plink2.path = plink2,
  bedfile.in = bedfile,
  thr.king = 2^-4.5,
  make.bed = FALSE,
  ncores = nb_cores()
)
```

Are you?

**Comment by fmadani** [comment]
Yes, worked. The bim and fam files were missing. Thanks.

**Comment by privefl** [comment]
Where were you downloading it before? 
Are you sure you have appropriate rights there?
