### ISSUE TITLE
Question: is it possible to OADP project samples onto existing smartpca output?

### ISSUE THREAD

**Issue by kristjanmoore** [privefl/bigsnpr#64]
I've tested out OADP and I'm quite happy with the results. It's not absolutely perfect, but it looks to be the best projection method I've tried, aside from smartpca's computationally insane `shrinkmode: YES`.

I've been trying to apply OADP to existing smartpca output. I can generate projected coordinates, but they're not scaled correctly: PC1 values are x \~850 what they should be, PC2 are x \~400,  PC3 are x \~-150, etc. Moreover, the overall appearance of a plot of all projected PCs changes depending on how many PCs I attempt to project on.

Attempted implementation below (hopefully without elementary errors):

``` R
library(dplyr)
library(bigsnpr)

# bed file that was used as smartpca input
pca_bed <- bed(pca_bed_file)
# bed file of GTs on exact same loci as above, but for individuals we want to project
project_bed <- bed(project_bed_file)

# as I understand, when creating "scaled" GT values for the individuals we want to 
# project, we should use the "scale" (per-loci means + sds) from the fileset used to 
# calculate the PCA
pca_bed_scale <- bed_scaleBinom(pca_bed)

# using the above, read in scaled GT values for the individuals to project
project_bed_scaled <- project_bed %>%
    bigsnpr:::read_bed_scaled(1:.$nrow, 1:.$ncol, pca_bed_scale$center, pca_bed_scale$scale) 

# read in smartpca SNP loadings for 10 PCs, dropping 1st 3 cols w/ rsid chr pos:
snpweight <- paste0(result_stem, '.snpweight') %>% 
    read.table() %>%
    select(-(1:3)) %>%
    as.matrix()

# and read in smartpca's eigenvalue file:
evals <- paste0(result_stem, '.eval') %>% 
    scan(nmax = 10)

# I think we now have the ingredients for OADP.
# follow pca_OADP_proj helppage by sqrting evals to get singular values
proj <- bigutilsr::pca_OADP_proj(project_bed_scaled, snpweight, sqrt(evals))

```

I've tried to modulate how I calculate the singular values (e.g. `sqrt(evals * (length(evals) - 1))`, where the length of `evals` is the same as the number of samples used to generate the original PCA), but this doesn't seem to work; the overall appearance of the plots changing based on the number of PCs I attempt to project onto seems to be an important clue.

Anyway, I'm not mathematically sophisticated enough to figure this out. If you could point me in the right direction, I would really appreciate it. I'm probably not the only person who has some "legacy" PCA output that would be annoying to run again or can't be run again in bigsnpr due to it being dependent on functionality that doesn't (yet!) exist in the package. Thanks.

**Comment by privefl** [comment]
I guess the easiest and most efficient way would be to use `bigsnpr::bed_projectSelfPCA()` with a fake `obj.svd` (just a list basically). But then you would need to make sure that the alleles are in the same order.

I'm not very familiar with SmartPCA (just used it quickly 2y ago), but make sure that `crossprod(snpweight)` is identity.

What do you mean by "can't be run again in bigsnpr due to it being dependent on functionality that doesn't (yet!) exist in the package."?

**Comment by kristjanmoore** [comment]
Okay, so I got pretty close. Apologies for the long post below:

`crossprod(snpweight)` was distinctly *not* an identity matrix, but telling me that it should be was a great clue. By renormalising each column I was able to get the cross product strangely close to an identity matrix. (see code below)

``` R
source('/odinn/groups/ant/scripts/R/pca_kristjan.R')
library(bigsnpr)
library(dplyr)

prj_dir <- '/odinn/users/kristjanm/resources/reference_panels/decode_europe_gsa/'
setwd(prj_dir)

### map bed files

pca_and_project_bed <- bed(pca_and_project_bed_file)
pca_bed <- bed(pca_bed_file)

# calculate "scale" (per-locus means + sds) for pca_bed
pca_bed_scale <- bed_scaleBinom(pca_bed)

# find which inds are to be projected
projected_inds <- pca_and_project_bed$fam %>%
  select(1:2) %>%
  mutate(row_i = 1:nrow(.)) %>%
  anti_join(pca_bed$fam[, 1:2], by = names(.)[1:2])

### read in smartpca output

# remove first population col
evec <- paste0(result_stem, '.evec') %>%
  read_evec() %>%
  select(-1) %>%
  as.matrix()

snpweight_df <- paste0(result_stem, '.snpweight') %>% 
  read.table(stringsAsFactors = F)

# rm chr,pos,id cols from snpweights + rescale [un-normalise?]
# note: sum(x ^ 2) for each row = to 6 sig fig n_snps in data used to calc PCA
snpweight_rescaled <- snpweight_df %>%
  select(-c(1:3)) %>%
  sapply(function(x) x / sqrt(sum(x ^ 2)))

# crossprod(snpweight_rescaled)
# close to identity -- diag is 1s, other vals up to 0.07 off:
#                V4            V5            V6            V7            V8 
# V4   1.0000000000  0.0629886216 -0.0551280009  0.0342755900 -3.184831e-02 ...
# V5   0.0629886216  1.0000000000 -0.0754935467  0.0663489089 -3.037471e-02 ...
# V6  -0.0551280009 -0.0754935467  1.0000000000 -0.0308700444  1.562871e-02 ...
# V7   0.0342755900  0.0663489089 -0.0308700444  1.0000000000  1.967471e-03 ...
# V8  -0.0318483056 -0.0303747146  0.0156287070  0.0019674706  1.000000e+00 ...
# V9   0.0015981099 -0.0198431477 -0.0225956002 -0.0077647879 -1.527105e-02 ...
# V10  0.0029581338  0.0164261311  0.0014516901 -0.0007959342 -3.126125e-05 ...
# V11  0.0006888677 -0.0002119814 -0.0070838543  0.0003065091  1.261866e-03 ...
# V12  0.0008047758 -0.0009930216 -0.0016761682  0.0006491613 -2.979100e-03 ...
# V13 -0.0005483224  0.0015044037 -0.0008509219  0.0047795698  4.093559e-04 ...

# calculate singular values from eigenvalues
evals <- paste0(result_stem, '.eval') %>% 
  scan()

svs_from_evals <- sqrt(evals * (length(evals) - 1))


### create "fake" svd and then project

fake_svd <- list(
  d = svs_from_evals[1:10],
  u = evec,
  v = snpweight_rescaled,
  niter = 'who cares',
  nops = 'whatever pal', 
  center = pca_bed_scale$center,
  scale = pca_bed_scale$scale
)

proj <- bed_projectSelfPCA(
  fake_svd, pca_and_project_bed, 
  projected_inds$row_i, 1:ncol(pca_bed),
  ncores = 3
)

# to get to the same coord space as smartpca output, I think we have to divide
# each PC value by the maximum attainable value for that PC multiplied by 10
max_pc_vals <- snpweight_rescaled %>%
  as.data.frame() %>%
  sapply(function(x) sum(pmax(x, 0)) * 10)

# plot 
plot(evec[, 2:3], cex = 0.1)
points(sweep(proj$simple_proj, 2, max_pc_vals, `/`), col = 'red')
points(sweep(proj$OADP_proj, 2, max_pc_vals, `/`), col = 'blue')

```

![proj](https://user-images.githubusercontent.com/3399732/73566937-17ca4280-445d-11ea-88da-ee19cc4a73e8.png)

So the points land exactly where I expect them to, but strangely the simple + OADP projected points land on the exact same spot to 3 significant figures. Until, that is, we get to the lower PCs. Running a quick linear regression of each of the simple and OADP projected PCs against each other:

``` R

mapply(
  function(x, y) lm(x ~ y),
  as.data.frame(proj$simple_proj), as.data.frame(proj$OADP_proj),
  SIMPLIFY = F
)

# $V1 [Ed: pc1]
# (Intercept)      y
# -6.532e-05    9.999e-01
#
# $V2 [Ed: pc2]
# (Intercept)      y
# -0.00508    0.99976
# 
# ...
# 
# $V9 [Ed: pc9]
# (Intercept)      y
# -0.01667    0.86995
# 
# $V10 [Ed: pc10]
# (Intercept)      y
# -0.362778    0.002305

```

I'm really glad I managed to figure out how to transform "simple" projection coordinates to get to the smartpca's weird coordinates, but the OADP itself isn't quite working... I'm frustratingly close! If you spot anything obvious again it would be great to know.

**Comment by kristjanmoore** [comment]
OK --- I really have to leave my desk and get home, but this last issue with the OADP not changing the projected coordinates seems to have something to do with the singular values I supply. When I multiply each one by an arbitrarily large number the simple + OADP projected coords are the same all the way down to pc10.

**Comment by privefl** [comment]
Loadings should be orthonormal. It really can't be otherwise.
And I think I use this assumption somewhere in the method.

**Comment by kristjanmoore** [comment]
You're right, it is pretty strange that the loading matrix isn't orthogonal.

The reason apparently goes back to the "functionality that doesn't yet exist in the package" I mentioned but failed to elaborate on earlier. Said functionality is the `ldregress: k` mode in smartpca, where each column of the genotype count matrix is 'converted' to the residuals of a linear regression of that column on the `k` previous columns. (It's mentioned way back in Patterson's 2006 PLOS Genetics paper.) It's a way of accounting for LD without killing loci, and it's worked quite well for me -- it seems that I'm able to pick up on subtler structure when I use it.

When I turn it on, the loading matrix output by smartpca isn't orthogonal; when it's off, it is. The example I'm talking about in this issue was made with `ldregress` on. To my amateur's eye there doesn't seem to be any reason why SVD applied to such a matrix *shouldn't* create an orthogonal matrix. Maybe a bug? I might pester Nick about it -- he was a good sport when I emailed him once a year ago. Thanks again.

**Comment by privefl** [comment]
Yes, you can have values for every variants by regressing variants onto PC scores. This is what we use in package pcadapt. But it is not loadings per se.

**Comment by kristjanmoore** [comment]
OK, it seems like it wasn't that non-orthogonal matrix columns was messing with OADP, rather that I'd just calculated the singular values incorrectly (when multiplying by `n - 1` I set "n" as the number of samples rather than the number of variants). PC9 + PC10 still seem to be too "shrunk" even with OADP but this is of course not unexpected and I can live with it. Thanks for your patience!
