### ISSUE TITLE
Regression coefficients for confounding variables

### ISSUE THREAD

**Issue by BoxiLin** [privefl/bigsnpr#65]
Thanks for this wonderful package. 

For **big_univLogReg** and **big_univLinReg**, is it possible to return the regression coefficients for confounding variables?

**Comment by privefl** [comment]
They are calculated indeed, but not returned.
It would be a different set of coefficients for each of every column, right?

**Comment by privefl** [comment]
Actually, they are calculated only in `big_univLogReg()`, but I'm not sure for `big_univLinReg()` as I'm using some algebra trick to do faster computations.

**Comment by BoxiLin** [comment]
Yes it would be a different set of coefficients for each of every column.

**Comment by privefl** [comment]
Why do you need them for?

**Comment by privefl** [comment]
Any update on this?

**Comment by BoxiLin** [comment]
Sorry for the late reply! I am interested to see if specific phenotypic features are indeed the source of confounding and their interactions with SNPs. 

On the other hand, I am working on X-chromosome association test, where test statistic is the joint distribution of parameters for SNP on X-chromosome and sex.

**Comment by privefl** [comment]
This seems to be very specific, so I'm not sure it would fit in this package.

But I would be happy to collaborate with you on this if you want.

**Comment by BoxiLin** [comment]
I see. Thank you very much! Let me try first if I can figure out by myself.

**Comment by privefl** [comment]
Any update on this?
