### ISSUE TITLE
Add temporary subsetting of individuals for faster clumping

### ISSUE THREAD

**Issue by privefl** [privefl/bigsnpr#68]
Clumping should be fast enough.

What can be slow in e.g. `snp_grid_clumping()` is accessing the data.
If you parallelize over 22 chromosomes, then you basically need to access all data into memory at once.
If you don't have enough memory (RAM), then the OS will start to swap between disk and memory, which will make computations very slow.

Unfortunately, asking to use only a subset of individuals won't make this any faster as data is accessed by blocks by the OS, meaning that if you access the genotypes for a few individuals and one variant, you will access all genotypes for this variant.

One solution would be to write a new file with only this subset of individuals, and performing the clumping on this one instead. 
Another solution would be to compute LD more sequentially. Indeed, clumping use some ranking and can access variants that are very far from each other. A more sequential clumping would be access less memory at once, but would require unnecessarily computing LD between some variants.

I'll think about implementing a solution to this problem.

**Comment by privefl** [comment]
Or I can try again to parallelize the code inside each chromosome, to access only one chromosome at once.

**Comment by wongck-kevin** [comment]
> Or I can try again to parallelize the code inside each chromosome, to access only one chromosome at once.
This implementation would be very helpful. 

For the current version, can you please give me a rough idea about how to calculate the memory I need for clumping (to prevent very slow computations)?

**Comment by privefl** [comment]
I'm trying to do that right now in branch `newparclump` using {RcppParallel}.
But there is a crash in C++ code (memory not mapped) and I don't manage to find what is the problem.
You don't happen to know {RcppParallel}, do you?

For your question, try this:
```r
perc_size <- cumsum(sort(table(CHR), decreasing = FALSE)) / ncol(G)
setNames(round(2 * perc_size * file.size(G$bk) / 1024**3, 1), seq_along(perc_size))
```
I think it should give you the max RAM size you need depending on the number of cores you use.

Otherwise, you can make a subset of your `G` (e.g. sampling only 5K individuals) using `big_copy()` and use that for clumping.

Anyway, I'm working on this issue and hope I come up with a better solution by the end of the week?

**Comment by wongck-kevin** [comment]
Hi Florian, sorry I don't happen to know RcppParallel. 
Thanks very much for the code. So if I got:
|           |          |           |          |           |
|-------|-------|-------|-------|-------|
|18       |19      | 20      | 21     | 22      |
| 249.6 | 273.6 | 298.3 | 326.8 | 355.3 |

It means I need 300GB RAM to run `snp_grid_clumping()` with 22 cores, right?

**Comment by privefl** [comment]
Yes, I think so, but not 100% sure.

What you can (should) do is look at some system monitor (e.g. top in the terminal) to make sure that everything is running smoothly.

**Comment by privefl** [comment]
You can try installing new dev version with
`remotes::install_github("privefl/bigsnpr@newparclump")`
and test the new implementations of `snp_clumping()` and `bed_clumping()`.

Note that `snp_grid_clumping()` is not reimplemented yet.

**Comment by privefl** [comment]
You can now try `snp_grid_clumping()` as well.

**Comment by privefl** [comment]
Close in #71.

**Comment by wongck-kevin** [comment]
Thanks so much Florian.

**Comment by privefl** [comment]
Is this working well for you?
I've tested on 70K individuals and 1M variants and it seemed to work just fine.

**Comment by wongck-kevin** [comment]
Sorry for my late response. 
The new `snp_grid_clumping()` worked fine for me too.
