### ISSUE TITLE
Error in bigutilsr::rollmean(S.col[ind], roll.size): Parameter 'size' is too large.

### ISSUE THREAD

**Issue by tshalev** [privefl/bigsnpr#74]
I am getting this error when running bed_autoSVD() on a bed object:

bedfile <- "some_bedfile"
plink2 <- download_plink2("data_location")

rel <- snp_plinkKINGQC(
  plink2.path = plink2,
  bedfile.in = bedfile,
  thr.king = 2^-4.5,
  make.bed = FALSE,
  ncores = nb_cores(),
  extra.options = "--allow-extra-chr"
)

(obj.bed <- bed(bedfile))
ind.rel <- match(c(rel$IID1, rel$IID2), obj.bed$fam$sample.ID)
ind.norel <- rows_along(obj.bed)[-ind.rel]

obj.svd <- bed_autoSVD(obj.bed, ind.row = ind.norel, k = 20, 
                       ncores = nb_cores())

Phase of clumping (on MAC) at r^2 > 0.2.. keep 15861 variants.
Discarding 3884 variants with MAC < 10.

Iteration 1:
Computing SVD..
Error in bigutilsr::rollmean(S.col[ind], roll.size) : 
  Parameter 'size' is too large.

I've dug through the code, and the only explanation I might have is that I have some scaffolds with only one SNP on them (non-model organism)... But removing those scaffolds doesn't seem to work, so maybe it's not that. I do have some missing data, but shouldn't that work when using bedfiles?

**Comment by privefl** [comment]
It means that you have some chromosomes with less than 2 * `roll.size` variants.

**Comment by tshalev** [comment]
I see. So the minimum possible variants per scaffold would be 2? Can roll.size be set to 0? Doesn't seem to work for me.

**Comment by privefl** [comment]
What are you calling a scaffold?
The computations are split along `obj.bed$map$chromosome`.
Setting `roll.size` to 0 should work.

**Comment by tshalev** [comment]
By scaffold I mean a contiguous genomic sequence. I don't have any full chromosomes in my organism. I have at least one SNP on each of about 4000 scaffolds. Setting roll.size to 0 doesn't seem to work either. Perhaps I'm doing something else wrong... I'll dig into my outputs. Thanks for the quick response, by the way!

**Comment by privefl** [comment]
What do you mean by `doesn't seem to work either`?
You shouldn't have the same error if setting roll.size to 0.

**Comment by tshalev** [comment]
I still get the same error with `roll.size` set to 0.

**Comment by privefl** [comment]
Can you use `debugonce(bed_autoSVD)` and rerun the function?
You will be able to run it line by line inside the function.

**Comment by tshalev** [comment]
OK. So, unsurprisingly, this is the line it fails on:
`bigutilsr::rollmean(S.col[ind], roll.size)`
Even manually changing this value in the function fails.

If you would like, I can send you a subset of my dataset where the failure still occurs.

**Comment by privefl** [comment]
OK

**Comment by tshalev** [comment]
I sent you an e-mail with the file.

**Comment by privefl** [comment]
Did not get any.

**Comment by tshalev** [comment]
Hmm. I sent it to florian.prive.21@gmail.com. Maybe in the junk folder?

**Comment by privefl** [comment]
I did not allow for `roll.size = 0` with a vector of length 1, and it seems that you have "chromosomes" with only one value.

Anyway, it should work now if you install the latest version of {bigutilsr} with `remotes::install_github("privefl/bigutilsr")`.

**Comment by tshalev** [comment]
OK it works now! Thanks very much. Out of curiosity, what do you mean by one value? One variant on the chromosome?

**Comment by privefl** [comment]
Yes

**Comment by tshalev** [comment]
OK makes sense! Thanks again!
