### ISSUE TITLE
when reading bgen file using snp_readBGEN [Error: Incompatibility between dimensions.]

### ISSUE THREAD

**Issue by gaochengPRC** [privefl/bigsnpr#75]
When I used the code below to read in bgen file, error reported is **"Incompatibility between dimensions."** However, I have checked that the numbers of SNPs in list_snp_id and bgen file are the same. So, I feel very confused about the error. Can you give me some hints? Thank you in advance!
**Code:**
`library(bigsnpr)`
`chr21_v3_sum <- read.table("ukb_mfi_chr21_v3.txt")`
`fun <- function(x){paste(unlist(strsplit(as.character(x), "[:]")), sep = '_', collapse = '_')}`
`list_snp_id <- apply(as.matrix(chr21_v3_sum[,1]),1,fun)`
`rds <- bigsnpr::snp_readBGEN(
  bgenfiles = "ukb_imp_chr21_v3.bgen",
  list_snp_id = as.list(list_snp_id),
  backingfile = "ukb_imp_chr21_v3",
  ncores = nb_cores())`

**Comment by privefl** [comment]
First thing I can think of: `list_snp_id` needs to be a list of the same length as `bgenfiles`.

**Comment by gaochengPRC** [comment]
Thank you!
In the code 
`rds <- bigsnpr::snp_readBGEN( bgenfiles = "ukb_imp_chr21_v3.bgen", list_snp_id = as.list(list_snp_id), backingfile = "ukb_imp_chr21_v3", ncores = nb_cores())`, 
`list_snp_id = as.list(list_snp_id)`, `list_snp_id` is a list, the length of `list_snp_id` is the number of SNPs which is the same as that in bgen file.
So, I feel some confused.

**Comment by privefl** [comment]
Here, you have only file in `bgenfiles`.
Meaning **`list_snp_id` must be a list of length 1** containing the vector of ids you want to access (you don't need to access them all).

BTW, for now, I parallelize over `bgenfiles`, meaning that you won't see any parallelization here.
If you really want the parallelization, you have two solutions: either you split your list in a list of `ncores` elements (and replicate the bgenfile), or you install the dev version which parallelize directly inside each bgenfile (branch @ldpred2).

**Comment by privefl** [comment]
Any update on this?

**Comment by gaochengPRC** [comment]
Thank you for your answer! It works. You can close this issue.

**Comment by williambrandler** [comment]
the solution will be to convert: 
`list_snp_id = as.list(list_snp_id)`
to
`list_snp_id = list(as.list(list_snp_id))`

**Comment by privefl** [comment]
If `list_snp_id` is the vector of IDs you want to read in one file, then you just need to use `list(list_snp_id)`.

Also, note that the parallelization is now over the variants (since v1.3.1), so that you can rely on a very efficient parallelization even if using only one BGEN file.
