### ISSUE TITLE
Is bigsnpr suitable to use for only individual level data? 

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [privefl/bigsnpr#78]
1. I would like to know whether the bigsnpr package is can be used to generate PRS using individual-level data?

2. Is there any tutorial to generate PRS using bigsnpr?

Thanks in advance
M

**Comment by privefl** [comment]
Yes, polygenic scores are one of the main focus of this package. There are 3 main methods currently available:

- Penalized regressions with individual-level data (see [paper](https://doi.org/10.1534/genetics.119.302019) and [tutorial](https://privefl.github.io/bigstatsr/articles/penalized-regressions.html))

- Clumping and Thresholding (C+T) and Stacked C+T (SCT) with summary statistics and individual level data (see [paper](https://doi.org/10.1016/j.ajhg.2019.11.001) and [tutorial](https://privefl.github.io/bigsnpr/articles/SCT.html)).

- LDpred2 with summary statistics (see preprint coming soon and [tutorial](https://privefl.github.io/bigsnpr/articles/LDpred2.html))

It would probably be a good idea to add this information to the README.
