### ISSUE TITLE
Individual level PRS

### ISSUE THREAD

**Issue by dheerajbobbili1988** [privefl/bigsnpr#79]
Hi,

I have two questions, could you please let me know how to proceed:

1) How can I get the PRS for each sample from both SCT and LDpred2 tutorials?
2) For LDpred2, how can I use it in case I have only the odds ratios for the summary statistics? I see from the tutorial we need to have betas and standard errors. Do I have to convert them manually?

Regards,
Dheeraj.

**Comment by privefl** [comment]
1. What do you mean by "get the PRS for each sample"?

2. You can get betas by taking the log(odds ratios), but you should also have a standard error available.

**Comment by dheerajbobbili1988** [comment]
Thanks

1) What I mean is for example to see the PRS for individual sample in this file "public-data.fam" from your example data. The idea is to check the difference in PRS distribution between the group of individuals belonging to different percentiles.

2) Unfortunately I don't have the standard errors, that's why I was wondering if there is any alternative way.

**Comment by privefl** [comment]
1. In .fam, there is no PRS. You need to derive the PRS using the methods.

2. You can go from p-values to z-scores (= beta / beta_se).

**Comment by dheerajbobbili1988** [comment]
1) Sorry for the confusion. Yes, I'm aware of the ".fam" file, I just referred to it. What I mean is in the tutorial here (https://privefl.github.io/bigsnpr/articles/SCT.html), which variable gives me the PRS for all the samples in the study.

2) I will try thanks.

**Comment by privefl** [comment]
The final PRS (for the test set) is `pred`.

**Comment by dheerajbobbili1988** [comment]
Ok, thanks. Also which variable stores the final list of SNPs used for calculating the AUC?

**Comment by privefl** [comment]
You should run the tutorial and explore a bit more the data.

**Comment by dheerajbobbili1988** [comment]
Thanks for your help!!
