### ISSUE TITLE
Core dumped with snp_grid_clumping() function

### ISSUE THREAD

**Issue by YingMa1993** [privefl/bigsnpr#82]
Hi, 
There was an error after I used the function snp_grid_clumping which says: terminate called after throwing an instance of 'std::bad_alloc'.
It seems that it reaches the memory limit on the server. Then I just reduced the sample size of the G file, i.e. 500 individuals and just input the summary statistics of chromosome 22. It still generates the same error. 
Here is the code for the snp_clumping after I read the genotype data and summary statistics

all_keep <- snp_grid_clumping(G,
                              infos.chr = CHR,
                              infos.pos = POS,
                              lpS = lpval,
                              grid.thr.r2 = c(0.01, 0.05),
                              grid.base.size = c(100),
                              ncores = 2)

**Comment by privefl** [comment]
That's very small data with very small grid.
How much memory do you have/ask for?

What is the version of the package that you're using?

**Comment by YingMa1993** [comment]
Hi, 

The total memory on the cluster is 500G+, and the version of the package is 1.3.0. 
I  just tried to give the input of the G matrix with only the common SNP IDs between the genotype file and summary statistics, there is no core dumped happening for the small dataset.

**Comment by privefl** [comment]
With version 1.3, on a node with 128 GB, I'm able to run `snp_grid_clumping()` on a `G` of 500 GB without any problem.

Let's try to understand why you have this issue. Could you give more details?

**Comment by privefl** [comment]
Any update on this?

**Comment by YingMa1993** [comment]
Hi, Florian,

Thank you so much for reaching out, really appreciated it! I can run it with a subset of 500 individuals when I extract the common SNPs in both the summary statistics and genotype data, otherwise it will get core dumped (Before core dumped, the memory usage is about over 200G). However, the whole data consists 50k samples. When I use the genotype data of 50k, there is still memory error like, 
error: arma::memory::acquire(): out of memory
terminate called without an active exception.
Here, there are some details about the G data. 
$ fam      :'data.frame':	50000 obs. of  6 variables:
$ map      :'data.frame':	302627 obs. of  6 variables:
And the summary statistics of chromosome 22 contain 141095 SNPs and they are from external sources. The version of the package that I use is 1.4.5 and the version of bigsparser is 0.2.3.
Should I filter the number of SNPs, i.e. keep SNPs < 0.5? 
Sorry that I did not run it recently since the memory issue for this big data , but I'd love to try it again if the problem can be solved. Thanks again!

**Comment by privefl** [comment]
It is probably computing and storing too many pairwise SNP correlations.
What are the parameters of `grid.thr.r2` and `grid.base.size` are you using?
How much memory do you have?

**Comment by YingMa1993** [comment]
I just use the default parameters, grid.thr.r2 = c(0.01, 0.05, 0.1, 0.2, 0.5, 0.8, 0.95), grid.base.size = c(50, 100, 200, 500)
I have 500 G on local but normally each person might be allowed to run the code locally within 200G. And I also try to submit the job on the server that I can access more than 200G, the memory error is still there. Thanks!

**Comment by privefl** [comment]
I guess you need to subset the number of variants you're using then.
