### ISSUE TITLE
Question about LD.wiki34

### ISSUE THREAD

**Issue by PeiJenWang** [privefl/bigsnpr#84]
Hi, I have a question about LD regions in the "LD.wiki34".

The description is...
#' 34 long-range Linkage Disequilibrium (LD) regions for the human genome
#' based on some [wiki table](https://goo.gl/0Ou7uI).

The wiki table annotated that the positions are for GRCH build 36 ( it should be NCBI36 ).
Is there a list of long-range Linkage Disequilibrium (LD) regions for genome Build 38 (GRCH38)?

Thank you!

**Comment by privefl** [comment]
Yes, you are right.
Honestly, I'm using this table for the build 37 as well.
I guess the differences between builds are minimal compared to how large these regions are. And it should not matter if the limits are a few kb from what they should be.

You can always use `bigsnpr::snp_modifyBuild()` that uses LiftOver (not available for Windows) to transform these in the build you want.

**Comment by PeiJenWang** [comment]
Thanks a lot for your detailed response.
