### ISSUE TITLE
Computational time and memory

### ISSUE THREAD

**Issue by MehreenSoomro** [privefl/bigsnpr#87]
Hi,
I have been trying to use LDpred2 without any success. Every time I try to calculate snp_cor either R crashes or give error like cannot allocate memory. In other instance, I tried to generate svd plot for mean and standard deviation, it is running since two days without any outcome.  I have dataset from UK biobank for Psa with 1200 individuals, using 4 cores on 500000 variants. Also, as mentioned in the tutorial the analysis is parallelized per chromosome, so far I have not been able to get results out of first chromosome. Initially, I was using university cluster icsf which had RAM of 256GB allocated to it and after the memory issues, I shifted my analysis to csf3 but receiving similar problems. I will be extremely grateful, if you can help in pointing out any solution to this problem or is there something wrong in my analysis.

Best Regards,
Mehreen

**Comment by privefl** [comment]
I can help you but I will need more information.

Let's start with:
1. Which versions (bigstatsr/bigsnpr) are you using?
2. Are you able to run the LDpred2 vignette using the data provided there?

**Comment by MehreenSoomro** [comment]
Thanks for your timely reply...

I am using bigsnpr 1.4.0...everything else runs smoothly all the background checks...structure of data...until it comes to the point where snp_cor is used and it shows memory issue there. I dont think I can use data provided in vignettes on my university server. I was unable to install bigsnpr version 1.4.0 on my home PC due memory issue again...[Image]
[Image]



Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by privefl** [comment]
Memory issue when installing the package?!

Why wouldn't you be able to download the data there?

**Comment by MehreenSoomro** [comment]
It's a secure environment...nothing external can be stored in those directories apart from the university provided data...

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by privefl** [comment]
I recommend that you ask to get the data there and try with this data.
How were you able to install the package if you can't get things in the cluster?

**Comment by MehreenSoomro** [comment]
Ok I will try it with this data and let you know if it shows the similar issue on it as well. Thanks a lot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MehreenSoomro** [comment]
Still the same issue.

Best Regards,
Mehreen

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by privefl** [comment]
This can't be a memory issue..
How do you install the package? Are you using conda?
Can you try a clean install?

**Comment by MehreenSoomro** [comment]
Hi Florian,
Thanks for your reply. Today, I managed to run the algorithm on public data and worked absolutely fine. I will be extremely grateful, if you can guide me through what is missing from my dataset which is causing the memory issue.

Best Regards,
Mehreen

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MehreenSoomro** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: mehreen soomro <mahatyab@hotmail.com>
Sent: Wednesday, June 3, 2020 12:29:47 PM
To: mehreen soomro <mahatyab@hotmail.com>
Subject: RE: [privefl/bigsnpr] Computational time and memory (#87)


Sorry to bother you a lot, but I am also receiving this error.





Sent from Mail<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D550986&data=02%7C01%7C%7Cefca7b66e5c44038f6d408d807b16d8f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637267805935826988&sdata=RMa%2FjS4glUSN%2FOeKNq3rRmbqnfZhkTDhuK7N38l%2B65w%3D&reserved=0> for Windows 10



From: mehreen soomro<mailto:mahatyab@hotmail.com>
Sent: 03 June 2020 12:16
To: privefl/bigsnpr<mailto:reply@reply.github.com>
Subject: RE: [privefl/bigsnpr] Computational time and memory (#87)



Hi Florian,

Thanks for your reply. Today, I managed to run the algorithm on public data and worked absolutely fine. I will be extremely grateful, if you can guide me through what is missing from my dataset which is causing the memory issue.



Best Regards,

Mehreen



Sent from Mail<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkId%3D550986&data=02%7C01%7C%7Cefca7b66e5c44038f6d408d807b16d8f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637267805935837033&sdata=29Tr0qjJWzR%2FX01ns%2BUkW7dODQUCWhGApQWcIner%2B10%3D&reserved=0> for Windows 10

**Comment by privefl** [comment]
Hard to help you without more information.

Have you tried to run `snp_cor()` on chromosome 22? 
How many variants is this corresponding to?

**Comment by privefl** [comment]
Any update on this?

**Comment by MehreenSoomro** [comment]
Hi Florian,

I hope you are doing well. Yes, we were able to run Ldpred2 algorithm on all the chromosomes after reducing the number of SNPs from 400,000 to 20,000 or less. Performance is poor overall and heratability for some of the chromosomes is greater than 1. Also couldnt sum the result from all 22 chromosomes.

Best Regards,
Mehreen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by privefl** [comment]
What are the sumstats? Linear, logistic?
Have you checked the supp note on qualifying control of sumstats?

**Comment by MehreenSoomro** [comment]
Hi Florian,

Yes, we have checked the quality control note provided and followed all the instructions. But as soon as the number of variants reduce the algorithm was working fine. With higher number of variants it keeps on crashing or showing issue like cannot allocate memory. Summary statistics are logistic regression.

Best Regards,
Mehreen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by privefl** [comment]
What do you mean by performance is poor then?

And that you cannot sum results from all 22 chromosomes?

**Comment by MehreenSoomro** [comment]
I meant I have results from all 22 Chromosomes each chromosome separately and mean AUC from each is not more than 55 but I havent sum the results to get overall genome-wide performance. As I am still not sure how to correctly sum the results.

Best Regards,
Mehreen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by privefl** [comment]
It should be fine to just sum the predictions from all 22 chromosomes.

**Comment by MehreenSoomro** [comment]
Hi Florian,

I would be extremely grateful if you can provide an example code from any one model of Ldpred2 for combining the results. I still cant figure out how to do that in correct way. Thank you so much for your prompt responses and help.

Best Regards,
Mehreen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MehreenSoomro** [comment]
Hi Florian,

Thanks for your reply.

I just wanted to ask, after summing up the result from all chromosome we get one PRS. So can you check for performance through AUC from this and if no how would you interpret it?

Best Regards,
Mehreen
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by privefl** [comment]
Yes, this is the final PRS.

**Comment by MehreenSoomro** [comment]
How would you interpret that one PRS?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by privefl** [comment]
I don't understand what you mean by "interpret".
It is just a PRS that you use for anything you want, e.g. prediction.
