### ISSUE TITLE
Porblem of snp_ldpred2_grid

### ISSUE THREAD

**Issue by biostat0903** [privefl/bigsnpr#88]
Hi, 
We are very excited that LDpred has the version 2, which can estimate the effect size chromosome by chromosome. When I use the function `snp_ldpred2_grid`, I the estimated beta is all zero, which does not has in `snp_ldpred2_inf` and `snp_ldpred2_auto`. I will show you some output for my data. 
The code of `snp_ldpred2_grid`:
````R
p_len <- 17
p_seq <- signif(seq_log(1e-4, 1, length.out = p_len), 2)
params <- expand.grid(p = p_seq, h2 = h2_est, sparse = c(FALSE, TRUE))
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = 2)
````
The summary of data
````R
dim(corr) ##104957 104957
````
````R
params
         p          h2 sparse
1  0.00010 0.009615639  FALSE
2  0.00018 0.009615639  FALSE
3  0.00032 0.009615639  FALSE
4  0.00056 0.009615639  FALSE
5  0.00100 0.009615639  FALSE
6  0.00180 0.009615639  FALSE
7  0.00320 0.009615639  FALSE
8  0.00560 0.009615639  FALSE
9  0.01000 0.009615639  FALSE
10 0.01800 0.009615639  FALSE
11 0.03200 0.009615639  FALSE
12 0.05600 0.009615639  FALSE
13 0.10000 0.009615639  FALSE
14 0.18000 0.009615639  FALSE
15 0.32000 0.009615639  FALSE
16 0.56000 0.009615639  FALSE
17 1.00000 0.009615639  FALSE
18 0.00010 0.009615639   TRUE
19 0.00018 0.009615639   TRUE
20 0.00032 0.009615639   TRUE
21 0.00056 0.009615639   TRUE
22 0.00100 0.009615639   TRUE
23 0.00180 0.009615639   TRUE
24 0.00320 0.009615639   TRUE
25 0.00560 0.009615639   TRUE
26 0.01000 0.009615639   TRUE
27 0.01800 0.009615639   TRUE
28 0.03200 0.009615639   TRUE
29 0.05600 0.009615639   TRUE
30 0.10000 0.009615639   TRUE
31 0.18000 0.009615639   TRUE
32 0.32000 0.009615639   TRUE
33 0.56000 0.009615639   TRUE
34 1.00000 0.009615639   TRUE
````
````R
head(df_beta)
          beta     beta_se  n_eff
1  0.005067986 0.005180057 263687
2  0.003134671 0.005069876 269004
3  0.003134671 0.005069876 269004
4  0.001893125 0.005447923 263320
5  0.001286959 0.002983204 264826
6 -0.014879790 0.006367861 265616
dim(df_beta) ## 104957      3
````
````R
summary(beta_inf)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-2.131e-03 -4.883e-05  4.081e-07  8.000e-09  5.040e-05  1.041e-03 
summary(beta_auto)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-1.682e-03 -3.762e-05  6.943e-07  3.180e-08  3.874e-05  7.665e-04 
````
Best, 
Sheng

**Comment by privefl** [comment]
Thanks for reporting.

0s were returned when the model diverged. Note that this feature has been removed in the latest version of the code.
This happens when the model is not appropriate for the data (e.g. totally wrong p).
I've never seen the case where all of them are 0 though.

I would recommend that you perform some quality control on the summary statistics.
Make sure not to have too rare variants, no duplicate variants (multiallelic ones), and to filter on the standard deviations according to [this note](https://github.com/privefl/paper-ldpred2/blob/master/paper/paper-ldpred2-supp.pdf). Also, did you use `snp_match()` for flipping and direction of variants?

This note will be part of the next preprint version, hopefully available soon.

Can you try this QC and tell me if it improves model specification?

**Comment by biostat0903** [comment]
Hi, 
I follow you suggestion. But the function still not work. I added the filtering code: 
````R
## select snp
cnd1 <- info_snp$sgenosd < 0.5*info_snp$genosd
cnd2 <- info_snp$sgenosd > 0.1 + info_snp$genosd
cnd3 <- info_snp$sgenosd < 0.1
cnd4 <- info_snp$genosd < 0.05
info_sel <- info_snp[!(cnd1|cnd2|cnd3|cnd4), ]
df_beta <- info_sel[, c("beta", "beta_se", "n_eff")]
info_chr <- info_sel$`_NUM_ID_`
````
The output is: 
````R
beta_grid[1:10,]
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]          [,9]        [,10] [,11]
 [1,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.733817e+53 1.060472e-04   NaN
 [2,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  6.160805e+53 5.984179e-05   NaN
 [3,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  6.640284e+53 5.987234e-05   NaN
 [4,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  4.328175e+54 3.915753e-05   NaN
 [5,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.801975e+54 2.704889e-05   NaN
 [6,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.740511e+54 2.331595e-05   NaN
 [7,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.135730e+53 2.917798e-05   NaN
 [8,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN -4.715120e+53 2.970664e-05   NaN
 [9,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN -4.825880e+53 3.116590e-05   NaN
[10,]  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN -9.554191e+53 2.782687e-05   NaN
      [,12] [,13] [,14] [,15] [,16] [,17] [,18]         [,19]        [,20]
 [1,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -2.258866e+47 1.120564e-04
 [2,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -2.433562e+48 6.871839e-05
 [3,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -2.606043e+48 6.461590e-05
 [4,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -2.130943e+49 4.507529e-05
 [5,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -8.586865e+48 3.685976e-05
 [6,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -8.623384e+48 3.533233e-05
 [7,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN -1.781646e+48 3.820250e-05
 [8,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN  9.903908e+47 4.160976e-05
 [9,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN  1.062651e+48 4.081140e-05
[10,]   NaN   NaN   NaN   NaN   NaN   NaN   NaN  3.399304e+48 3.895068e-05
````
````R
summary(beta_grid[, 10])
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-2.206e+18  0.000e+00  0.000e+00  8.251e+14  0.000e+00  1.229e+18
````
Best, 
Sheng

**Comment by privefl** [comment]
Which trait is this? Can you point me to the sumstats you're using? 
I can probably try it myself on UKBB data tomorrow.

**Comment by biostat0903** [comment]
Hi, 
Thanks for your fast reply. My trait is standing height in chromosome 22. I randomly select 1000 individuals to be the validation data.  All MAFs of SNPs in the validation data are larger than 0.01. You can follows my steps. If there is any problem, please feel free to tell me. Thanks again!
Best, 
Sheng

**Comment by biostat0903** [comment]
Hi, 
I will try to use the HapMap3 to map the SNP in validation data. If there is any result, I will show you. 

Best, 
Sheng

**Comment by privefl** [comment]
Are you getting the sumstats internally from a subset of UKBB, another subset of 1K indiv for validation, and other individuals for the test set?

**Comment by privefl** [comment]
I've just tried running GWAS for height in 300K individuals and in chr22.
The results from LDpred2-grid looks just fine, even if I'm using only 1000 individuals to compute the LD matrix.
Can you tell me more about what you did?

**Comment by biostat0903** [comment]
Sure. I used about 140000 SNPs. Is the number problem?

**Comment by privefl** [comment]
From chromosome 22 only?
Are you sure you don't have duplicate variants or low-frequency variants?

**Comment by biostat0903** [comment]
Hi, 
If I use the Hapmap3 to map the UKB data (~15,000 SNPs for chromosome 22), the result makes sense. I delete all duplicate and low-frequency variants (~70,000 SNPs), LDpred does not converge. 
Thanks for your help 
Best, 
Sheng

**Comment by privefl** [comment]
Could you plot `sgenosd`  vs `genosd`?

BTW, you can't really use the QC from above because they don't have a ratio of 1 (only the case for binary phenotypes with logistic regression).

**Comment by biostat0903** [comment]
Sure, Pearson correlation coefficient is 0.9987055.

**Comment by privefl** [comment]
Yes, but they are not on the same scale, right?

**Comment by biostat0903** [comment]
I have send you an e-mail. Please check!

**Comment by biostat0903** [comment]
I have use LDpred version 1 to analyze the data. It is also not converge. Like you SCT paper, LDpred might be diverge, when the snp number is large. 
Best, 
Sheng

**Comment by privefl** [comment]
OK it seems fine; have you standardized the phenotype beforehand?

15,000 variants is not very much, it should be fine. 
I'm using approximately the same set as you do.

Could you plot the betas from LDpred2-inf vs the betas from the GWAS?
Can you also show the plots from the auto version? (you can post the plots here, you don't have to email them to me)

**Comment by privefl** [comment]
Any update on this?

**Comment by biostat0903** [comment]
No. Thanks!

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
