### ISSUE TITLE
How to merge LDpred2 results from different chromosomes?

### ISSUE THREAD

**Issue by MehreenSoomro** [privefl/bigsnpr#91]
Hi,

Can you please provide or guide on how to combine the results from chromosomes? 

Best Regards,
Mehreen

**Comment by privefl** [comment]
In which context?

**Comment by MehreenSoomro** [comment]
After I finished my analysis for LDpred2-inf,grid,or auto model chromosome by chromosome, how should I combine results from all the chromosomes?

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by privefl** [comment]
Normally, you could just sum the results scores, or equivalently, append the effect sizes.

I'll add this information in the tuto.

**Comment by MehreenSoomro** [comment]
Thankyou so much. Extremely grateful for your timely reply and help.

Best Regards,
Mehreen

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by privefl** [comment]
Thanks for giving it a try.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.

**Comment by MehreenSoomro** [comment]
Thanks Florian...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
