### ISSUE TITLE
LDpred2 merging of chromosome results

### ISSUE THREAD

**Issue by wyoungj** [privefl/bigsnpr#93]
I have had a good read of your LDpred2 paper on biorxiv and successfully run an analysis using a single chromosome. This looks like a great tool, thank you for developing. 

I have a query about merging results across different chromosomes. I can not see a tutorial on this and wondered whether there were any specific aspects to consider when doing this? Are we able to simply extract the variants in the best model for one chromosome, and combine with those identified for another chromosome and use this in the PRS?

I would be grateful for your thoughts/experience of this. 

Best wishes, 

Will

**Comment by privefl** [comment]
Please see https://github.com/privefl/bigsnpr/issues/91.

Someone also told me that it may be beneficial to choose the best parameters after combining all chromosome scores, but I have not investigated it further yet. I guess it would work if the architecture of all chromosomes is about the same. But it also means it requires saving all LDpred2 models, and doing this combining and choosing once all chromosomes have been processed.

**Comment by wyoungj** [comment]
Thanks for the prompt reply - and for highlighting #91 - I had missed this as had a filter on when searching for previous issues/queries reported. 

OK I'll give it a go.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
