### ISSUE TITLE
snp_ldpred2_inf() infinite loop

### ISSUE THREAD

**Issue by Minta821** [privefl/bigsnpr#95]
When I started running with different LD matrices,  I observed few strange behaviors. Our summary statistics is based on European populations, for colorectal cancer.  Initially I tried LD reference computed using the 1000 Genomes samples (which is publicly available, containing ~500 samples) and  obtained h2 estimate 0.232769 for Chr1,, but don't have any  phenotype. Instead, we used our individual data sets  as a LD reference. Then  the calculated h2 estimate is very big, always more than 1. When we run the snp_ldpred2_inf() or snp_ldpred2_grid(), it looks like an infinite loop.  I undesrtand that, it is basically depends on the LD reference bed file which is converted from vcf files.Do you have any suggestion to create the bed files or any other insights for this problem?

**Comment by privefl** [comment]
You get an estimate of h2 larger than 1 in chromosome 1 only for colorectal cancer?
I'm even more surprised that these GWAS results (http://pheweb.sph.umich.edu/pheno/153) do not really show anything on chromosome 1.
Are the summary statistics available somewhere for me to try?

**Comment by Minta821** [comment]
The summary statistics is not available publicly. But there are almost 13 known loci which is already published from Chromosome 1 as per my knowledge. In addition, the summary statistics from a large sample size ~120K , almost equal cases and controls.

**Comment by Minta821** [comment]
It was basically the problem in matching ref and alt allele in summary statistics and reference file; when I flipped them as names(map) <- c("chr", "pos", "a1", "a0"),  the problem is resolved. Thank you for the quick responses.

**Comment by privefl** [comment]
Switching the alleles should not have any impact on the h2 estimate from LDSC regression, because you use chi2 stats (z-scores squared), so the sign should not matter (but it would matter for LDpred2).

**Comment by Minta821** [comment]
I continue working on it and will update about it.

**Comment by privefl** [comment]
Any update on this?

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
