### ISSUE TITLE
LDpred2 'memory not mapped'

### ISSUE THREAD

**Issue by makarasmarius** [privefl/bigsnpr#96]
Good day Florian,
I am using LDpred2 auto (bigsnpr ‘1.4.2’) to compute betas for 1000 individuals using summary statistics with over 2M SNPs. Here I am analysing chromosomes separately. While running LDpred2 I get this error:

*** caught segfault ***
address 0x7f77d6c10000, cause 'memory not mapped'

Traceback:
 1: sp_solve_sym_eigen(A, b, add_to_diag, tol, maxiter)
 2: bigsparser::sp_solve_sym(corr, beta_hat, add_to_diag = ncol(corr)/(h2_init *     N))
 3: snp_ldpred2_auto(corr, df_beta_train, h2_init = h2_est, vec_p_init = p_seq,     ncores = NCORES)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)

What could cause this?
Here I am following the steps shown in the latest tutorial version (May 25, 2020):

corr0 <- snp_cor(G_train, ind.col = ind.chr2, ncores = NCORES, infos.pos = POS2[ind.chr2], size = 3 / 1000)
corr <- bigsparser::as_SFBM(as(corr0, "dgCMatrix"))
(ldsc <- snp_ldsc2(corr0, df_beta_train, ncores = NCORES))
h2_est <- ldsc[["h2"]]
multi_auto <- snp_ldpred2_auto(corr, df_beta_train, h2_init = h2_est,
                                 vec_p_init = p_seq,
                                 ncores = NCORES)

Previously I was getting betas without bigsparser::as_SFBM() as it was shown in the previous version of the tutorial. Then I had no such problems.
Thank you for the help.

**Comment by privefl** [comment]
There might be two reasons.

I think I add one similar issues. What version of {bigsparser} do you have?

**Comment by privefl** [comment]
Could you try installing the GitHub version with `remotes::install_github("privefl/bigsparser")`?
And maybe reinstall {bigsnpr} afterwards.
And tell me if it fixed this issue.

**Comment by makarasmarius** [comment]
Unfortunately, the issue remains.

**Comment by privefl** [comment]
How do you install packages?
Some have reported similar issues when installing packages with conda.

**Comment by makarasmarius** [comment]
For bigsnpr I used:
devtools::install_github("privefl/bigsnpr")

And as you recomended, for bigsparser:
remotes::install_github("privefl/bigsparser")

**Comment by privefl** [comment]
This is on your personal computer, right? Which OS?

Have you reinstalled {bigsnpr} after {bigsparser}?

**Comment by makarasmarius** [comment]
Yes, I did both.

I working on a remote Red Hat Linux Server.

**Comment by privefl** [comment]
Please try reinstalling them now.
You should now have {bigsparser} v0.2.2 and {bigsnpr} v1.4.3.

**Comment by makarasmarius** [comment]
I have reinstalled both packages. They are of the version that you mentioned.
I have ran it again and have a bit different error:

 *** caught segfault ***
address 0x7f3b44f25000, cause 'invalid permissions'

Traceback:
 1: sp_solve_sym_eigen(A, b, add_to_diag, tol, maxiter)
 2: bigsparser::sp_solve_sym(corr, beta_hat, add_to_diag = ncol(corr)/(h2_init *     N))
 3: snp_ldpred2_auto(corr, df_beta_train, h2_init = h2_est, vec_p_init = p_seq,     ncores = NCORES)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)

**Comment by privefl** [comment]
Have you made the matrix again?

**Comment by makarasmarius** [comment]
Yes.

**Comment by privefl** [comment]
I have no idea what's going on. It is a memory-mapping issue, but I don't know why.
The only time I experienced this issue is on Solaris (cf. https://stackoverflow.com/q/59275888/6103040).

What is the size of the matrix you're using already?

**Comment by makarasmarius** [comment]
I iterate through chromosomes and generate corr matrices for different chromosomes. The size of the corr matrix is 128628 x 128628 from the chromosome that it crashes. I get betas from previous chromosomes just fine with corr matrices a bit larger than this.

**Comment by privefl** [comment]
Any update on this?

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
