### ISSUE TITLE
snp_readBGEN() unable to find variants

### ISSUE THREAD

**Issue by Sabor117** [privefl/bigsnpr#97]
I have been trying to use the snp_readBGEN() function on one of the genotype datasets in our lab for use with LDpred2. Currently though I have repeatedly been getting the error:

Error in { : 
  task 1 failed - "Some variants have not been found (stored in './tmp_data_not_found.rds')."

I have tried to solve this in a few ways. I have taken my list of SNPs and then used bgenix to extract the SNPs present within our data, using the output list from _that_ to create the alternate IDs for snp_readBGEN(). I even tried to use bgenix to trim our bgens down to only the SNPs in that list of SNPs. In both cases getting the same error.

So, there are a couple of questions I have here:

1. Has this function been tested on any datasets other than UKBB? I suspect I may have contacted you before with a similar issue, but as our data is the same version of bgen (v1.2) then I don't see why it wouldn't work.

2. Assuming that it should work on other data, I must be doing something wrong with my usage, but just cannot see it, so would appreciate any help.

**Comment by privefl** [comment]
It has primarily been tested on UKBB data, and some small data provided at https://bitbucket.org/gavinband/bgen/.

Can you show the variants in `./tmp_data_not_found.rds`?
Also, you can try `snp_readBGI()` directly. I recommend running it in debug mode to run it line by line and show all internal variables (you can do that if you use `debugonce(snp_readBGI)` beforehand.

**Comment by Sabor117** [comment]
So this is an example of the SNPs in the .rds:

  [1] "01_100133974_A_G" "01_100135336_G_T" "01_100147287_A_G"
  [4] "01_100181379_A_C" "01_100185458_T_C" "01_100286774_A_C"
  [7] "01_100290752_C_T" "01_100297396_G_A" "01_100303796_T_C"
 [10] "01_100308030_C_G" "01_100310975_G_A" "01_100313692_G_A"

For this particular output I was trying to see whether it made a difference inputing the alternate ids as 01_pos_a1_a2 (instead of "1_pos_a1_a2"). Although it seems to make no difference either way.

Using snp_readBGI() seems to work on individual SNPs, but not on a full list. I will, however, make an effort at debugging this as suggested.

Since making this post though I believe I may have discovered what might be the issue... When using SNPs on chr20 snp_readBGEN() seemed to work, however not on chr1. So I am investigating whether this is caused by the chromosome column in our data being in the format of "1", "2", "20" instead of "01", "02", "20". I shall report back.

**Comment by privefl** [comment]
This might be the issue indeed.

**Comment by Sabor117** [comment]
Okay, I have now confirmed this. The issue was because of the missing "0" in front of the single digit chromosome numbers. Cheers Florian.

**Comment by privefl** [comment]
Are you able to modify your part for it to work or should we make an addition to the code?

**Comment by Sabor117** [comment]
So, I was able to modify our files it to work and I can't really say if this was an usual quirk in our own data rather than a general thing.

**Comment by privefl** [comment]
Ok, if others have the same problem, then they can report it here and we'll work on making the code more general.

Thanks for your investigation.

**Comment by variani** [comment]
Hi Florian,

I also had a similar issue with exactly the same error message and I needed to switch to another PRS package:(

```
Error in { :
task 1 failed - "Some variants have not been found (stored in './tmp_data_not_found.rds')."
```

It is good to know that it is due to chromosome names, but I wonder whether it can be fixed in your package. It would be very helpful.

Best,
Andrey

**Comment by May-Ibrahim** [comment]
Hi, I have the same issue and I know it is because of the missing 0 for one digit chromosomes. The default setting of exporting bgen files in plink is to save chr as 1,2,3 not 01,02. It would be really helpful if you can fix this in the package.

**Comment by May-Ibrahim** [comment]
> So, I was able to modify our files it to work and I can't really say if this was an usual quirk in our own data rather than a general thing.

Hi,
Can I ask which tool/command you used to change 1,2,3 to 01,02,03 in the bgen files?

Thanks,
May

**Comment by Sabor117** [comment]
> Can I ask which tool/command you used to change 1,2,3 to 01,02,03 in the bgen files?

I used qctool, specifically I used the `-map-id-data` argument from qctool which allows you modify chromosome/ID/position etc of any SNP within your bgens based on a provided map. You can fin the documentation for that here: https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/alphabetical_options.html

It's worth saying, this might not be the best solution because there is a qctool option for just changing chromosome number, but for whatever reason, that wasn't working for me.

**Comment by privefl** [comment]
This should be fixed in the latest version.
Please confirm as the example data provided in the BGEN repo do use `01`, not `1`.

**Comment by May-Ibrahim** [comment]
> > Can I ask which tool/command you used to change 1,2,3 to 01,02,03 in the bgen files?
> 
> I used qctool, specifically I used the `-map-id-data` argument from qctool which allows you modify chromosome/ID/position etc of any SNP within your bgens based on a provided map. You can fin the documentation for that here: https://www.well.ox.ac.uk/~gav/qctool_v2/documentation/alphabetical_options.html
> 
> It's worth saying, this might not be the best solution because there is a qctool option for just changing chromosome number, but for whatever reason, that wasn't working for me.

Thank you

**Comment by Yemch** [comment]
Hi,

I also have the same problem that says

Error in { : 
  task 1 failed - "Some variants have not been found (stored in './ukb_imp_chr8_v3_not_found.rds')."

I used bigsnpr v 1.4.4. I tried both list_snp_id = list("08_76941945_A_G") and list_snp_id = list("8_76941945_A_G"), that is, chr as 8 and 08. They both did not work. Should I modify anything?

Thanks,
Mingchen

**Comment by umakann-db** [comment]
I am trying to use the snp_readBGEN() function to read BGEN files. I see the below errors for different SNP lists.  

**Error1:** RserveException: eval failed

Code snippet used for Error1
```
list_snp_id <- list("21_10460657_A_G")

rds <- bigsnpr::snp_readBGEN(
    bgenfiles   = "/databricks/driver/simulate_50000_samples_1000_simulated.bgen",
    list_snp_id = list_snp_id,
    backingfile = "/databricks/driver/test1"
  )
```

**Error2 :** Some variants have not been found (stored in '/databricks/driver/simulate_50000_samples_1000_simulated_not_found.rds').
Some(<code style = 'font-size:10p'> Error: Some variants have not been found (stored in '/databricks/driver/simulate_50000_samples_1000_simulated_not_found.rds'). </code>)
Error: Some variants have not been found (stored in '/databricks/driver/simulate_50000_samples_1000_simulated_not_found.rds').

```
list_snp_id <- list("21_39870309_G_A")

rds <- bigsnpr::snp_readBGEN(
    bgenfiles   = "/databricks/driver/simulate_50000_samples_1000_simulated.bgen",
    list_snp_id = list_snp_id,
    backingfile = "/databricks/driver/test1"
  )
```

**Some variants from bgen file.**
```
Welcome to bgenix
(version: 1.1.7, revision )

(C) 2009-2017 University of Oxford


Building query                                              :  (0/?,0.0s,0.0/s)
Building query                                              :  (467/?,0.0s,572765.1/s)
# bgenix: started 2021-12-16 04:14:53
alternate_ids	rsid	chromosome	position	number_of_alleles	first_allele	alternative_alleles
rs75434219	.	21	9671019	2	T	C
rs4117812	.	21	10460657	2	A	G
rs111709978	.	21	10794845	2	AGAGTG	A
rs28972678	.	21	10813206	2	C	G
rs28970553	.	21	10828213	2	T	C
rs28972302	.	21	10841966	2	C	G
rs71326366	.	21	10966804	2	A	ATGTG
rs2479471	.	21	11033803	2	G	A
rs57224481	.	21	11045982	2	CA	C
```

Any advice on this issue?
Thank you very much.
