### ISSUE TITLE
ldpred2 - scaling when running per-chromosome?

### ISSUE THREAD

**Issue by carbocation** [privefl/bigsnpr#98]
In the original version of the ldpred2 preprint, the **New strategy for running LDpred2** section ends with:

> Combining results from all chromosomes requires using some appropriate scaling (see tutorial).

The tutorial shows, e.g.:

```R
# Make sure the scale is okay (by comparing to LDpred2-inf and others auto)
c(mad(pred_inf), apply(pred_auto, 2, mad))
```

I gather that when we run ldpred2 separately per chromosome, we need to think about how to scale the per-chromosome results, but I'm not sure from the tutorial how that is suggested to be done. Any pointers?

**Comment by privefl** [comment]
Yes, sorry about that.
Prior to using some appropriate quality control on summary statistics, some LDpred2 models could go crazy for some chromosomes, and I needed to use some scaling to put these back to normal.
Actually, now it is not needed anymore it seems. So you can just sum the predictions from all chromosomes without any scaling.

For LDpred2-auto, I run it 30 times, check the standard deviation of the resulting predictions, and keep the ones that are on the same scale (to avoid including some Gibbs chains going crazy). See the end of method subsection "New LDpred2 models".

**Comment by carbocation** [comment]
Wonderful - thank you. 

> So you can just sum the predictions from all chromosomes without any scaling.

Will give it a shot! I can close this issue if you want.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
